// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 2  (Tue Mar 17, 2026)
// COF-C03 Mock Exam · 60 questions
// Distribution: D1 31% (19q) | D2 20% (12q) | D3 18% (11q) | D4 21% (13q) | D5 10% (5q)
// Difficulty mix: ~30% Easy, ~50% Medium, ~20% Hard
//
// DAILY GENERATION RULE:
//   Each new day of questions must share ≤ 30% overlap with the previous day.
//   Before writing a new day, list the question IDs from the previous file and
//   ensure fewer than 18 of the 60 questions are repeated verbatim.
//   Rotate topics, scenarios, and SQL examples each day.
//
// DAY 2 vs DAY 1 OVERLAP CHECK:
//   Intentional repeats (same topic, fresh angle/scenario): ~12 questions
//   Fully new topics not covered in Day 1: Horizon Catalog, Snowflake Editions (VPS),
//   Snowpark-optimized WH, Fail-safe, Transient tables, Iceberg, SCIM, Privacy Policies,
//   Row-Level Security, Alerts, Notifications, Resource Monitors, INFORMATION_SCHEMA vs
//   ACCOUNT_USAGE, Unloading (COPY INTO location), GET_STAGE_LOCATION, Streams on views,
//   Task trees/DAGs, Data Clean Rooms, Native Apps, Listings, Query Profile deep-dive,
//   Spilling to disk, Search Optimization cost, JOIN optimizations, Dynamic Tables.
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 2,
  date: '2026-03-17',
  label: 'Day 2 — Deep Dive',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (19 questions) ─────────────────────

  {
    id: 'd1_d2_01',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'What is the key architectural advantage of Snowflake\'s separation of storage and compute?',
    options: [
      'It eliminates the need for any indexing or clustering',
      'Multiple virtual warehouses can run simultaneously against the same data without contention',
      'Data is automatically replicated across all regions for free',
      'Compute costs are included in the storage price',
    ],
    answer: 'Multiple virtual warehouses can run simultaneously against the same data without contention',
    exp: 'Because storage is centralized and compute is independent, unlimited virtual warehouses can read the same data concurrently. A DW loading VW and a BI reporting VW never compete for the same resources.',
  },
  {
    id: 'd1_d2_02',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'Snowflake is classified as which type of database architecture?',
    options: [
      'Shared-disk (all nodes share storage and compute)',
      'Shared-nothing (each node has its own dedicated storage)',
      'Multi-cluster shared data (separate storage and compute layers)',
      'Master-slave replication architecture',
    ],
    answer: 'Multi-cluster shared data (separate storage and compute layers)',
    exp: 'Snowflake is a multi-cluster shared data architecture: a single centralized storage layer (cloud object store) is shared across many independent compute clusters (virtual warehouses).',
  },
  {
    id: 'd1_d2_03',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'Which Snowflake edition provides a completely dedicated, isolated deployment of the Snowflake infrastructure — no shared hardware or services with any other customer?',
    options: ['Standard', 'Enterprise', 'Business Critical', 'Virtual Private Snowflake (VPS)'],
    answer: 'Virtual Private Snowflake (VPS)',
    exp: 'VPS is the highest Snowflake edition — a fully isolated, dedicated environment with its own Cloud Services layer and no shared resources. Suitable for organizations with strict data isolation requirements.',
  },
  {
    id: 'd1_d2_04',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'hard',
    q: 'Which components are included in Snowflake\'s Cloud Services Layer? (Select the BEST answer)',
    options: [
      'Virtual warehouse nodes, local SSD cache, and query execution',
      'Authentication, metadata management, query optimization, and transaction management',
      'Columnar storage, data encryption, and micro-partition management',
      'Auto-scaling, auto-suspend, and billing management only',
    ],
    answer: 'Authentication, metadata management, query optimization, and transaction management',
    exp: 'Cloud Services coordinates: authentication & authorization, infrastructure management, metadata & statistics, query parsing & optimization, and transaction management. It runs on Snowflake-managed compute — always on.',
  },
  {
    id: 'd1_d2_05',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'Apache Iceberg tables in Snowflake allow data to be stored in which location?',
    options: [
      'Only in Snowflake-managed internal stages',
      'In external cloud object storage (S3, GCS, Azure Blob) in open Iceberg format',
      'Only in Snowflake-managed micro-partitions',
      'In external databases like Redshift or BigQuery',
    ],
    answer: 'In external cloud object storage (S3, GCS, Azure Blob) in open Iceberg format',
    exp: 'Snowflake Iceberg tables store data in open Apache Iceberg format in customer-managed cloud storage. This enables interoperability with other engines (Spark, Flink, Trino) while using Snowflake for query and governance.',
  },
  {
    id: 'd1_d2_06',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'A developer wants to browse Snowflake objects, run SQL with autocomplete, and execute Snowflake Git-integrated stored procedures without leaving VS Code. Which tool enables this?',
    options: ['Snowflake SQL API', 'SnowSQL CLI', 'Snowflake VS Code Extension', 'Snowflake JDBC driver'],
    answer: 'Snowflake VS Code Extension',
    exp: 'The Snowflake VS Code Extension brings SQL IntelliSense, object browsing, query execution, and Snowpark Python support directly into VS Code — no separate app needed.',
  },
  {
    id: 'd1_d2_07',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'A serverless REST application needs to submit SQL queries to Snowflake over HTTPS without installing any client driver. Which interface should it use?',
    options: ['JDBC driver', 'Snowflake SQL API', 'Python connector', 'SnowSQL'],
    answer: 'Snowflake SQL API',
    exp: 'The Snowflake SQL API is a REST API that accepts SQL statements over HTTPS — perfect for serverless functions, browsers, and any environment where driver installation is not practical.',
  },
  {
    id: 'd1_d2_08',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'Which Snowflake object type is created automatically for every table in a schema — requires no CREATE statement and cannot be dropped?',
    options: ['User stage', 'Table stage', 'Named internal stage', 'External table'],
    answer: 'Table stage',
    exp: 'Every Snowflake table has an automatically created table stage (referenced as @%<table_name>). It cannot be explicitly dropped or altered — it is tied to the table lifecycle.',
  },
  {
    id: 'd1_d2_09',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'A stored procedure in Snowflake needs to call another stored procedure within the same schema. What type of ownership model does Snowflake stored procedures use by default?',
    options: [
      'Caller\'s rights — executes with the privileges of the calling user',
      'Owner\'s rights — executes with the privileges of the procedure owner',
      'ACCOUNTADMIN rights — all procedures run as ACCOUNTADMIN',
      'PUBLIC role rights — all procedures share the PUBLIC role',
    ],
    answer: 'Owner\'s rights — executes with the privileges of the procedure owner',
    exp: 'By default, stored procedures run with EXECUTE AS OWNER — they use the owner\'s role privileges, not the caller\'s. You can override with EXECUTE AS CALLER for caller\'s rights.',
  },
  {
    id: 'd1_d2_10',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A Python machine learning training job running inside Snowflake (via Snowpark) crashes with out-of-memory errors on a Standard XL warehouse. What is the best solution?',
    options: [
      'Switch to a multi-cluster warehouse',
      'Use a Snowpark-optimized warehouse',
      'Increase AUTO_SUSPEND to keep memory warm',
      'Split the job into smaller Tasks',
    ],
    answer: 'Use a Snowpark-optimized warehouse',
    exp: 'Snowpark-optimized warehouses provide 16× more memory per node than standard warehouses — specifically designed for memory-intensive ML training, large in-memory DataFrames, and Snowpark workloads.',
  },
  {
    id: 'd1_d2_11',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'What happens to currently executing queries when you resize a running warehouse from Large to X-Large?',
    options: [
      'Running queries are immediately cancelled and resubmitted at the new size',
      'Running queries continue to completion; new size applies only to queued/new queries',
      'The warehouse suspends and resumes at the new size before accepting queries',
      'Resize is not allowed while queries are running',
    ],
    answer: 'Running queries continue to completion; new size applies only to queued/new queries',
    exp: 'Resizing a running warehouse never interrupts in-flight queries. The new compute cluster is provisioned alongside the running one; once current queries finish, new queries use the larger size.',
  },
  {
    id: 'd1_d2_12',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'hard',
    q: 'The ECONOMY scaling policy on a multi-cluster warehouse starts a new cluster only when:',
    options: [
      'Any query is queued for more than 5 seconds',
      'The estimated workload would keep the new cluster busy for at least 6 minutes',
      'Warehouse utilization exceeds 75%',
      'The active cluster has been running for more than 10 minutes',
    ],
    answer: 'The estimated workload would keep the new cluster busy for at least 6 minutes',
    exp: 'ECONOMY scaling is conservative — it only starts a new cluster when there\'s enough queued work to justify it (≥6 min of estimated load). STANDARD policy starts a cluster as soon as any query queues.',
  },
  {
    id: 'd1_d2_13',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'Which warehouse privilege allows a role to MODIFY, MONITOR, and OPERATE on ALL virtual warehouses in the account, including ones it does not own?',
    options: ['OPERATE', 'USAGE', 'MODIFY', 'MANAGE WAREHOUSES (account-level privilege)'],
    answer: 'MANAGE WAREHOUSES (account-level privilege)',
    exp: 'MANAGE WAREHOUSES is an account-level privilege (granted on ACCOUNT, not on a specific warehouse). It effectively grants MODIFY + MONITOR + OPERATE on all warehouses — used to delegate warehouse management.',
  },
  {
    id: 'd1_d2_14',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'Which table type has NO Fail-safe period and a maximum Time Travel of 1 day — making it ideal for staging tables in ETL pipelines to reduce storage costs?',
    options: ['Permanent table', 'Temporary table', 'Transient table', 'External table'],
    answer: 'Transient table',
    exp: 'Transient tables have 0-day Fail-safe and up to 1 day Time Travel. They exist across sessions (unlike temp tables) but avoid the 7-day Fail-safe storage overhead — ideal for ETL staging.',
  },
  {
    id: 'd1_d2_15',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'easy',
    q: 'Fail-safe in Snowflake provides how many days of data recovery after the Time Travel period ends, and who can access it?',
    options: [
      '7 days, accessible by any user via SQL',
      '7 days, accessible only by Snowflake Support',
      '30 days, accessible by ACCOUNTADMIN',
      '1 day, accessible by SYSADMIN',
    ],
    answer: '7 days, accessible only by Snowflake Support',
    exp: 'Fail-safe provides a 7-day disaster recovery window after Time Travel expires. It is NOT accessible via SQL — only Snowflake Support can recover data from Fail-safe, as a last resort.',
  },
  {
    id: 'd1_d2_16',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'What is the approximate size range of a Snowflake micro-partition (uncompressed)?',
    options: [
      '1 KB – 10 KB',
      '50 MB – 500 MB',
      '1 GB – 10 GB',
      '100 MB – 1 GB',
    ],
    answer: '50 MB – 500 MB',
    exp: 'Snowflake micro-partitions are contiguous units of storage containing 50–500 MB of uncompressed data. They are stored compressed on disk. This size balances pruning granularity with I/O efficiency.',
  },
  {
    id: 'd1_d2_17',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'hard',
    q: 'An external table in Snowflake reads data from files in an S3 stage. What is a key limitation compared to native Snowflake tables?',
    options: [
      'External tables cannot be queried using SQL',
      'External tables do not support DML (INSERT, UPDATE, DELETE)',
      'External tables cannot be used in JOINs',
      'External tables are not accessible from Snowsight',
    ],
    answer: 'External tables do not support DML (INSERT, UPDATE, DELETE)',
    exp: 'External tables are read-only — they reference files in cloud storage and do not store data in Snowflake. DML is not supported. They also do not have micro-partition pruning beyond partition columns defined in the DDL.',
  },
  {
    id: 'd1_d2_18',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'What is Snowflake Cortex Search designed for?',
    options: [
      'Generating SQL from natural language questions about tabular data',
      'Full-text semantic search over unstructured and semi-structured text data',
      'Training custom ML classification models',
      'Searching for objects in the Snowflake Marketplace',
    ],
    answer: 'Full-text semantic search over unstructured and semi-structured text data',
    exp: 'Cortex Search provides full-text, semantic (vector-based) search over text data — great for document search, RAG pipelines, and building AI apps. Cortex Analyst is for structured data Q&A.',
  },
  {
    id: 'd1_d2_19',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'Snowflake Notebooks run interactively in a browser with Python and SQL cells. Which compute type do they use by default?',
    options: [
      'The user\'s assigned virtual warehouse',
      'A shared system warehouse called SYSTEM$STREAMLIT_NOTEBOOK_WH',
      'Snowflake-managed serverless compute only',
      'A dedicated Notebook warehouse that must be created first',
    ],
    answer: 'A shared system warehouse called SYSTEM$STREAMLIT_NOTEBOOK_WH',
    exp: 'Snowflake Notebooks default to SYSTEM$STREAMLIT_NOTEBOOK_WH — an auto-provisioned multi-cluster X-Small warehouse. The PUBLIC role has USAGE on it by default, so notebooks work immediately.',
  },

  // ── DOMAIN 2: Account Management & Governance (12 questions) ─────────────

  {
    id: 'd2_d2_01',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'What is the purpose of the SYSADMIN role in Snowflake?',
    options: [
      'Managing users, roles, and account-level security settings',
      'Creating and managing databases, schemas, warehouses, and data objects',
      'Billing and organizational account management',
      'Granting the ACCOUNTADMIN role to other users',
    ],
    answer: 'Creating and managing databases, schemas, warehouses, and data objects',
    exp: 'SYSADMIN is the system role for creating and managing compute and data objects (warehouses, databases, schemas, tables). It does NOT manage users/roles (that\'s SECURITYADMIN/USERADMIN) or billing.',
  },
  {
    id: 'd2_d2_02',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'hard',
    q: 'Custom roles should always be granted to which role in the recommended Snowflake RBAC hierarchy, to ensure SYSADMIN can manage all objects?',
    options: ['ACCOUNTADMIN', 'SECURITYADMIN', 'SYSADMIN', 'PUBLIC'],
    answer: 'SYSADMIN',
    exp: 'Best practice: always grant all custom roles up to SYSADMIN. This allows SYSADMIN (and ACCOUNTADMIN above it) to manage all objects owned by those custom roles. Orphaned custom roles create unmanaged objects.',
  },
  {
    id: 'd2_d2_03',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'The OWNERSHIP privilege on an object can be transferred using which command?',
    options: [
      'GRANT OWNERSHIP ON TABLE t TO ROLE new_owner;',
      'ALTER TABLE t OWNER = new_role;',
      'GRANT OWNERSHIP ON TABLE t TO ROLE new_owner REVOKE CURRENT GRANTS;',
      'TRANSFER OWNERSHIP OF TABLE t TO ROLE new_owner;',
    ],
    answer: 'GRANT OWNERSHIP ON TABLE t TO ROLE new_owner REVOKE CURRENT GRANTS;',
    exp: 'To transfer ownership, use GRANT OWNERSHIP … REVOKE CURRENT GRANTS (removes old owner\'s grants) or COPY CURRENT GRANTS (preserves them). The REVOKE CURRENT GRANTS form is safest for full ownership transfer.',
  },
  {
    id: 'd2_d2_04',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'An organization uses Azure Active Directory and wants to automatically provision and de-provision Snowflake users when employees join or leave. Which protocol handles this?',
    options: ['SAML 2.0', 'OAuth 2.0', 'SCIM (System for Cross-domain Identity Management)', 'OpenID Connect'],
    answer: 'SCIM (System for Cross-domain Identity Management)',
    exp: 'SCIM automates user/group lifecycle management (provisioning, de-provisioning, attribute sync) between an IdP (Okta, Azure AD) and Snowflake — distinct from SAML which only handles authentication.',
  },
  {
    id: 'd2_d2_05',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'MFA in Snowflake is powered by which service, and at what level is it enforced?',
    options: [
      'Snowflake\'s own OTP engine, enforced per account by ACCOUNTADMIN',
      'Duo Security, optionally enrolled per user (or enforced via policy)',
      'Google Authenticator, enforced at the network policy level',
      'Microsoft Authenticator, automatically required for all Enterprise accounts',
    ],
    answer: 'Duo Security, optionally enrolled per user (or enforced via policy)',
    exp: 'Snowflake MFA uses Duo Security. Users can self-enroll, or admins can enforce it with authentication policies (MFA enforcement). It adds a second factor (push/passcode) after username/password.',
  },
  {
    id: 'd2_d2_06',
    domain: 2,
    topic: 'Data Masking',
    difficulty: 'hard',
    q: 'A Row Access Policy is attached to the ORDERS table. The policy filters rows so users only see orders from their own region. If a user runs SELECT * FROM ORDERS, what is true?',
    options: [
      'The user receives all rows but with sensitive columns masked',
      'The user receives only rows where the region matches their session context',
      'The user receives an error: Row Access Policy violation',
      'The policy is evaluated only when running SHOW commands, not SELECT',
    ],
    answer: 'The user receives only rows where the region matches their session context',
    exp: 'Row Access Policies filter rows transparently at query time — the user sees only rows the policy allows. No error is thrown. The filter is applied by the Cloud Services layer before returning results.',
  },
  {
    id: 'd2_d2_07',
    domain: 2,
    topic: 'Object Tagging',
    difficulty: 'medium',
    q: 'Which system function returns all objects that have a specific tag key-value combination assigned?',
    options: [
      'SYSTEM$GET_TAG()',
      'TAG_REFERENCES()',
      'SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES',
      'SYSTEM$SNOWFLAKE_INFORMATION()',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES',
    exp: 'TAG_REFERENCES view in ACCOUNT_USAGE shows all objects tagged with a specific tag value. You can also use the TAG_REFERENCES() table function in INFORMATION_SCHEMA for near-real-time results.',
  },
  {
    id: 'd2_d2_08',
    domain: 2,
    topic: 'Privacy Policies',
    difficulty: 'medium',
    q: 'What does a Snowflake Privacy Policy (Aggregation Policy) enforce?',
    options: [
      'Masks column values based on the querying role',
      'Requires query results to be aggregated with a minimum group size — preventing individual-level data exposure',
      'Encrypts data at rest using customer-managed keys',
      'Blocks access to tables for non-privileged roles',
    ],
    answer: 'Requires query results to be aggregated with a minimum group size — preventing individual-level data exposure',
    exp: 'Aggregation Policies (part of Privacy Policies) enforce that results contain at minimum N distinct entity values — preventing re-identification of individuals when exposing aggregated analytics.',
  },
  {
    id: 'd2_d2_09',
    domain: 2,
    topic: 'Encryption',
    difficulty: 'medium',
    q: 'What is the default encryption standard Snowflake uses for all data at rest?',
    options: ['AES-128-bit', 'AES-256-bit', 'RSA-2048', 'TLS 1.3'],
    answer: 'AES-256-bit',
    exp: 'All Snowflake data at rest is encrypted with AES-256-bit encryption by default — no configuration needed. Data in transit is encrypted with TLS 1.2+. These protections apply to all editions.',
  },
  {
    id: 'd2_d2_10',
    domain: 2,
    topic: 'Alerts',
    difficulty: 'medium',
    q: 'A newly created Snowflake Alert will not execute unless which action is taken?',
    options: [
      'ACCOUNTADMIN must approve it',
      'The alert must be explicitly resumed with ALTER ALERT … RESUME',
      'The notification integration must be tested first',
      'The warehouse assigned to the alert must be running',
    ],
    answer: 'The alert must be explicitly resumed with ALTER ALERT … RESUME',
    exp: 'Like Tasks, Snowflake Alerts are created in SUSPENDED state. You must run ALTER ALERT <name> RESUME before the alert evaluates its condition on schedule.',
  },
  {
    id: 'd2_d2_11',
    domain: 2,
    topic: 'Notifications',
    difficulty: 'medium',
    q: 'Which Snowflake object must be created to enable sending email notifications from Snowflake (e.g., from an Alert or stored procedure)?',
    options: [
      'EMAIL INTEGRATION',
      'NOTIFICATION INTEGRATION with TYPE = EMAIL',
      'EXTERNAL FUNCTION with email endpoint',
      'ALERT with ACTION TYPE = EMAIL',
    ],
    answer: 'NOTIFICATION INTEGRATION with TYPE = EMAIL',
    exp: 'A NOTIFICATION INTEGRATION (TYPE = EMAIL) defines the allowed email recipients. It is then referenced in SYSTEM$SEND_EMAIL() calls from alerts, tasks, or stored procedures.',
  },
  {
    id: 'd2_d2_12',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'hard',
    q: 'A security auditor needs to see all login attempts (including failed ones) for the past 6 months. Which view should they query?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY',
      'INFORMATION_SCHEMA.LOGIN_HISTORY()',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY',
    exp: 'LOGIN_HISTORY in ACCOUNT_USAGE records all login events (successful and failed) with user, timestamp, IP, client type, and error message. Retention is 1 year. INFORMATION_SCHEMA has a 7-day retention.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ────────

  {
    id: 'd3_d2_01',
    domain: 3,
    topic: 'Stages',
    difficulty: 'easy',
    q: 'Which SQL command is used to upload a local file to a Snowflake internal stage?',
    options: ['COPY INTO @mystage FROM local_file', 'PUT file://path/to/file @mystage', 'UPLOAD file://path/to/file TO @mystage', 'INSERT INTO @mystage FROM \'file://path\''],
    answer: 'PUT file://path/to/file @mystage',
    exp: 'The PUT command (available in SnowSQL and JDBC/ODBC drivers) uploads files from the local filesystem to a Snowflake internal stage. It compresses the file by default (gzip).',
  },
  {
    id: 'd3_d2_02',
    domain: 3,
    topic: 'Stages',
    difficulty: 'medium',
    q: 'After uploading files to a Snowflake internal stage with PUT, which command downloads the file back to a local path?',
    options: ['DOWNLOAD @stage/file TO local/', 'GET @stage/file file://local/path/', 'COPY INTO local/path FROM @stage', 'EXPORT @stage TO file://local/'],
    answer: 'GET @stage/file file://local/path/',
    exp: 'GET is the counterpart to PUT — it downloads files from an internal stage to a local path. Like PUT, it is available in SnowSQL and driver connections, not in the Snowsight web UI.',
  },
  {
    id: 'd3_d2_03',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'medium',
    q: 'You want to unload a Snowflake query result to an external S3 stage as compressed CSV files. Which syntax is correct?',
    options: [
      'EXPORT TABLE orders TO @ext_stage FILE_FORMAT = (TYPE = CSV)',
      'COPY INTO @ext_stage FROM (SELECT * FROM orders) FILE_FORMAT = (TYPE = CSV COMPRESSION = GZIP)',
      'INSERT INTO @ext_stage SELECT * FROM orders',
      'UNLOAD TABLE orders TO @ext_stage FORMAT CSV GZIP',
    ],
    answer: 'COPY INTO @ext_stage FROM (SELECT * FROM orders) FILE_FORMAT = (TYPE = CSV COMPRESSION = GZIP)',
    exp: 'COPY INTO <stage> … FROM (<query>) is the Snowflake unloading syntax. You can specify FILE_FORMAT inline or reference a named file format object.',
  },
  {
    id: 'd3_d2_04',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'medium',
    q: 'What does the PURGE = TRUE option do in a COPY INTO statement?',
    options: [
      'Deletes all rows in the target table before loading',
      'Removes source files from the stage after a successful load',
      'Clears the load history for those files',
      'Truncates the stage directory',
    ],
    answer: 'Removes source files from the stage after a successful load',
    exp: 'PURGE = TRUE automatically removes the source files from the stage after a successful COPY INTO. Useful for keeping staging areas clean without separate cleanup scripts.',
  },
  {
    id: 'd3_d2_05',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'hard',
    q: 'Which ACCOUNT_USAGE view can you query to see the history of files that were loaded via Snowpipe?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.SNOWPIPE_HISTORY',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY',
    exp: 'PIPE_USAGE_HISTORY shows credit consumption per pipe. For file load history, use COPY_HISTORY (which includes Snowpipe loads). Both are in ACCOUNT_USAGE with up to 1-year retention.',
  },
  {
    id: 'd3_d2_06',
    domain: 3,
    topic: 'Streams',
    difficulty: 'hard',
    q: 'A Snowflake stream\'s offset advances (moves forward) only when:',
    options: [
      'SHOW STREAMS is executed',
      'The stream is queried with a SELECT statement',
      'The stream data is consumed inside a DML transaction that commits successfully',
      'A new file is loaded into the stage',
    ],
    answer: 'The stream data is consumed inside a DML transaction that commits successfully',
    exp: 'A stream\'s offset only advances after the change data is consumed in a committed DML statement (INSERT INTO … SELECT FROM stream, MERGE using stream, etc.). A SELECT alone does not advance the offset.',
  },
  {
    id: 'd3_d2_07',
    domain: 3,
    topic: 'Streams',
    difficulty: 'medium',
    q: 'What is the difference between a standard stream and an append-only stream on a table?',
    options: [
      'Append-only streams only capture INSERT and UPDATE operations; standard streams capture all three (INSERT, UPDATE, DELETE)',
      'Append-only streams only capture INSERT operations; standard streams capture INSERT, UPDATE, and DELETE',
      'Standard streams only capture DELETEs; append-only captures INSERTs and UPDATEs',
      'There is no difference — both capture all DML changes',
    ],
    answer: 'Append-only streams only capture INSERT operations; standard streams capture INSERT, UPDATE, and DELETE',
    exp: 'Append-only streams are more efficient for insert-heavy tables (like event logs) — they skip UPDATE/DELETE tracking overhead. Standard (delta) streams capture all DML including updates and deletes.',
  },
  {
    id: 'd3_d2_08',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'medium',
    q: 'A root task has 3 child tasks configured as a DAG. The root runs every 5 minutes. What is required for the child tasks?',
    options: [
      'Child tasks must also have their own SCHEDULE configured',
      'Child tasks must be RESUMED but have no SCHEDULE — they are triggered by the root',
      'Child tasks must be SUSPENDED — only the root task needs to be active',
      'All tasks in a DAG share a single SCHEDULE defined on the root',
    ],
    answer: 'Child tasks must be RESUMED but have no SCHEDULE — they are triggered by the root',
    exp: 'In a task DAG: the root task has the SCHEDULE; child tasks have no schedule but must be RESUMED. The root triggers child tasks after it completes. Only child tasks\' RESUME state matters.',
  },
  {
    id: 'd3_d2_09',
    domain: 3,
    topic: 'File Formats',
    difficulty: 'medium',
    q: 'Which file format must be used when loading Parquet files into a Snowflake VARIANT column?',
    options: [
      'A CSV file format with FIELD_OPTIONALLY_ENCLOSED_BY',
      'A Parquet file format object — Parquet is a semi-structured binary format',
      'Parquet files can only be loaded via Snowpipe, not COPY INTO',
      'Parquet files are automatically detected — no file format needed',
    ],
    answer: 'A Parquet file format object — Parquet is a semi-structured binary format',
    exp: 'Parquet is a binary columnar format. You must define a FILE FORMAT with TYPE = PARQUET and use COPY INTO with a VARIANT target column (or use MATCH_BY_COLUMN_NAME for schema-matched loading).',
  },
  {
    id: 'd3_d2_10',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'easy',
    q: 'Which Snowflake connector is purpose-built for streaming Kafka topic messages directly into Snowflake tables?',
    options: [
      'Snowflake Python Connector',
      'Snowflake Kafka Connector',
      'Snowpipe Streaming REST API',
      'Snowflake JDBC Driver',
    ],
    answer: 'Snowflake Kafka Connector',
    exp: 'The Kafka Connector (a Kafka Connect plugin) reads from Kafka topics and loads into Snowflake tables — using Snowpipe or Snowpipe Streaming under the hood. It handles offsets and error handling automatically.',
  },
  {
    id: 'd3_d2_11',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'medium',
    q: 'What tool should an admin use if they suspect network connectivity issues preventing Snowflake connections from a client machine?',
    options: ['SnowSQL with --debug flag', 'SnowCD (Snowflake Connectivity Diagnostic)', 'SHOW NETWORK POLICIES in Snowsight', 'Snowflake VS Code Extension network test'],
    answer: 'SnowCD (Snowflake Connectivity Diagnostic)',
    exp: 'SnowCD is a standalone diagnostic tool that tests network connectivity to Snowflake — DNS resolution, firewall/proxy, TLS handshake, allowlisted IPs. It reports which checks pass or fail.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (13 questions) ────────

  {
    id: 'd4_d2_01',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'Two different users run the exact same query against the same unchanged table. User A runs first, User B runs 2 hours later. Does User B benefit from the result cache?',
    options: [
      'No — the result cache is per-user and not shared',
      'Yes — the result cache is shared across all users and persists for 24 hours',
      'Yes — but only if they use the same virtual warehouse',
      'No — the 24-hour clock resets when a different user runs the query',
    ],
    answer: 'Yes — the result cache is shared across all users and persists for 24 hours',
    exp: 'The result cache is account-wide (not per-user or per-warehouse). Any user running the identical SQL against unchanged data within 24 hours gets the cached result — no compute needed.',
  },
  {
    id: 'd4_d2_02',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'A query uses WHERE YEAR(order_date) = 2023. Despite a clustering key on order_date, pruning is poor. Why?',
    options: [
      'Clustering keys do not work on DATE columns',
      'Wrapping a column in a function prevents partition pruning',
      'YEAR() is not a valid Snowflake function',
      'The clustering depth is too high for date columns',
    ],
    answer: 'Wrapping a column in a function prevents partition pruning',
    exp: 'When a filter wraps the clustering column in a function (YEAR(order_date)), Snowflake cannot use the min/max metadata to prune micro-partitions. Use range predicates instead: WHERE order_date BETWEEN \'2023-01-01\' AND \'2023-12-31\'.',
  },
  {
    id: 'd4_d2_03',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'hard',
    q: 'In Snowflake Query Profile, what does the "Bytes spilled to local storage" metric indicate?',
    options: [
      'Data was written to Time Travel storage',
      'The warehouse ran out of memory and wrote intermediate results to local SSD',
      'Data was unloaded to an external stage during query execution',
      'The query used the local disk cache for result caching',
    ],
    answer: 'The warehouse ran out of memory and wrote intermediate results to local SSD',
    exp: 'Spilling to local storage means the warehouse virtual memory was exhausted and query intermediates (e.g. sort/join buffers) were written to local SSD — significantly slowing the query. Fix: resize up or rewrite query.',
  },
  {
    id: 'd4_d2_04',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'Which join type in Snowflake is most efficiently handled because Snowflake\'s optimizer can broadcast the smaller table to all compute nodes?',
    options: [
      'CROSS JOIN between two large tables',
      'Hash join on two very large tables of equal size',
      'Broadcast join where one table is significantly smaller than the other',
      'Sort-merge join on two sorted tables',
    ],
    answer: 'Broadcast join where one table is significantly smaller than the other',
    exp: 'When one side of a join is small enough to fit in memory, Snowflake broadcasts it to all nodes — each node can join its local micro-partitions against the full small table. This avoids expensive data shuffling.',
  },
  {
    id: 'd4_d2_05',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'medium',
    q: 'Automatic clustering in Snowflake uses which type of compute to re-cluster table data in the background?',
    options: [
      'The warehouse specified in the ALTER TABLE … CLUSTER BY statement',
      'Serverless compute managed by Snowflake',
      'A dedicated system warehouse called RECLUSTERING_WH',
      'The ACCOUNTADMIN\'s default warehouse',
    ],
    answer: 'Serverless compute managed by Snowflake',
    exp: 'Automatic clustering (re-clustering) uses Snowflake-managed serverless compute running in the background. It is billed as compute-hours, not virtual warehouse credits, and is not affected by resource monitors.',
  },
  {
    id: 'd4_d2_06',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'hard',
    q: 'What does a high "average_depth" value in SYSTEM$CLUSTERING_INFORMATION indicate?',
    options: [
      'The table is well-clustered and pruning will be very effective',
      'The table is poorly clustered — many micro-partitions overlap on the clustering key values',
      'The clustering key has too many distinct values to be useful',
      'Automatic clustering is running and depth will decrease soon',
    ],
    answer: 'The table is poorly clustered — many micro-partitions overlap on the clustering key values',
    exp: 'A high average_depth means many micro-partitions contain overlapping ranges of the clustering key — so the optimizer cannot prune effectively. Ideal depth is 1 (no overlap). Values >2-3 suggest re-clustering is needed.',
  },
  {
    id: 'd4_d2_07',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'hard',
    q: 'Which of the following SQL constructs CANNOT be used in the definition of a Snowflake Materialized View?',
    options: [
      'WHERE clause filters',
      'GROUP BY with aggregate functions',
      'Joins across multiple tables',
      'Non-deterministic functions like CURRENT_TIMESTAMP()',
    ],
    answer: 'Non-deterministic functions like CURRENT_TIMESTAMP()',
    exp: 'Materialized Views cannot use non-deterministic functions (CURRENT_TIMESTAMP, RANDOM, etc.) because the stored result would immediately be stale. They also cannot use subqueries, HAVING, LIMIT, or UDFs (JS).',
  },
  {
    id: 'd4_d2_08',
    domain: 4,
    topic: 'Search Optimization',
    difficulty: 'medium',
    q: 'The Search Optimization Service stores its access path structures in which location, and how is it billed?',
    options: [
      'In the virtual warehouse local SSD — no additional billing',
      'In dedicated Snowflake-managed storage, billed as additional storage + serverless compute',
      'In Cloud Services metadata — included in the 10% daily adjustment',
      'In the external stage — no Snowflake billing',
    ],
    answer: 'In dedicated Snowflake-managed storage, billed as additional storage + serverless compute',
    exp: 'Search Optimization creates and maintains access path structures (similar to inverted indexes) in dedicated storage. You are billed for both the storage consumed and the serverless compute used to maintain them.',
  },
  {
    id: 'd4_d2_09',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'medium',
    q: 'Which function is used to cast a VARIANT value to a specific Snowflake SQL type?',
    options: [
      'CAST(variant_col AS VARCHAR)',
      'CONVERT(variant_col, \'VARCHAR\')',
      'variant_col::VARCHAR (double-colon cast / :: operator)',
      'TO_TYPE(variant_col, \'VARCHAR\')',
    ],
    answer: 'variant_col::VARCHAR (double-colon cast / :: operator)',
    exp: 'The :: (double-colon) cast operator is the Snowflake/PostgreSQL syntax for explicit type conversion. For VARIANT: data:field::VARCHAR extracts and casts in one step. CAST() also works but :: is idiomatic.',
  },
  {
    id: 'd4_d2_10',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'hard',
    q: 'What does Snowflake\'s automatic schema detection (INFER_SCHEMA) do?',
    options: [
      'Automatically adds columns to a table when new JSON fields are loaded',
      'Detects the column names and data types from staged semi-structured files before loading',
      'Converts VARIANT columns into typed relational columns',
      'Generates a CREATE TABLE statement from the ACCOUNT_USAGE schema',
    ],
    answer: 'Detects the column names and data types from staged semi-structured files before loading',
    exp: 'INFER_SCHEMA is a table function that inspects staged files (Parquet, Avro, ORC, JSON) and returns the inferred column names and SQL types. Useful for auto-generating CREATE TABLE or COPY INTO statements.',
  },
  {
    id: 'd4_d2_11',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'Which Snowflake feature lets you define a TARGET_LAG (e.g., "1 minute") so that a derived table is automatically kept within that freshness window from its source tables?',
    options: [
      'Materialized View with REFRESH_MODE = AUTO',
      'Dynamic Table with TARGET_LAG',
      'Task with SCHEDULE = \'1 MINUTE\'',
      'Snowpipe Streaming with latency SLA',
    ],
    answer: 'Dynamic Table with TARGET_LAG',
    exp: 'Dynamic Tables declare a SQL transformation and a TARGET_LAG. Snowflake automatically and incrementally refreshes the table to keep it within the lag window — simpler than building a Streams + Tasks pipeline.',
  },
  {
    id: 'd4_d2_12',
    domain: 4,
    topic: 'Query Profile',
    difficulty: 'medium',
    q: 'In Snowflake\'s Query Profile, the "Bytes spilled to remote storage" metric indicates a more serious issue than spilling to local storage. Why?',
    options: [
      'Remote storage spills write to another cloud region, causing cross-region data transfer fees',
      'Remote storage (S3/Blob/GCS) is much slower than local SSD — spilling there dramatically degrades performance',
      'Remote storage spills permanently delete the spilled data after query completion',
      'Remote storage spills cause the warehouse to automatically resize',
    ],
    answer: 'Remote storage (S3/Blob/GCS) is much slower than local SSD — spilling there dramatically degrades performance',
    exp: 'Spill hierarchy: memory → local SSD → remote object storage (S3/Blob/GCS). Remote storage is orders of magnitude slower than SSD. If spilling to remote, the query needs a much larger warehouse or query rewrite.',
  },
  {
    id: 'd4_d2_13',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'hard',
    q: 'What is the key difference between a Stored Procedure and a User-Defined Function (UDF) in Snowflake?',
    options: [
      'Stored procedures can only be written in Python; UDFs support all languages',
      'Stored procedures can execute DDL and transaction control; UDFs can only return a value and cannot execute DDL',
      'UDFs can call stored procedures but stored procedures cannot call UDFs',
      'Stored procedures are serverless; UDFs require a virtual warehouse',
    ],
    answer: 'Stored procedures can execute DDL and transaction control; UDFs can only return a value and cannot execute DDL',
    exp: 'Stored procedures can run DDL (CREATE, DROP, ALTER), DML, and transaction control (COMMIT, ROLLBACK). UDFs are scalar/tabular functions that return a value — they cannot issue DDL or contain transaction logic.',
  },

  // ── DOMAIN 5: Data Collaboration (5 questions) ───────────────────────────

  {
    id: 'd5_d2_01',
    domain: 5,
    topic: 'Time Travel',
    difficulty: 'medium',
    q: 'Which syntax queries a table as it existed 1 hour ago using Snowflake Time Travel?',
    options: [
      'SELECT * FROM orders AT (TIMESTAMP => DATEADD(hour, -1, CURRENT_TIMESTAMP()))',
      'SELECT * FROM orders BEFORE (HOURS => 1)',
      'SELECT * FROM orders AS OF 1 HOUR AGO',
      'SELECT * FROM orders TRAVEL_TO (MINUS_HOURS => 1)',
    ],
    answer: 'SELECT * FROM orders AT (TIMESTAMP => DATEADD(hour, -1, CURRENT_TIMESTAMP()))',
    exp: 'Time Travel syntax uses AT or BEFORE with a TIMESTAMP, OFFSET (seconds), or STATEMENT (query ID). AT (TIMESTAMP => …) selects the table state at the given point in time.',
  },
  {
    id: 'd5_d2_02',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'Can a Snowflake Standard edition account act as a data sharing CONSUMER?',
    options: [
      'No — only Enterprise edition can receive shares',
      'Yes — any Snowflake account (any edition) can be a consumer of a share',
      'Yes — but only if the provider is also Standard edition',
      'No — consumers must be on the same edition as the provider',
    ],
    answer: 'Yes — any Snowflake account (any edition) can be a consumer of a share',
    exp: 'Data Sharing requires no special edition on the consumer side. Any Snowflake account — including Standard — can create a database from a share and query the provider\'s data.',
  },
  {
    id: 'd5_d2_03',
    domain: 5,
    topic: 'Cloning',
    difficulty: 'hard',
    q: 'A developer clones a production database (CREATE DATABASE dev CLONE prod). The clone includes a table with a Row Access Policy. What happens to the policy in the clone?',
    options: [
      'The Row Access Policy is not copied — the cloned table has no policy',
      'The Row Access Policy is cloned and attached to the cloned table, referencing the same policy object',
      'The policy is deep-copied as a new independent policy in the dev database',
      'Cloning fails — databases with Row Access Policies cannot be cloned',
    ],
    answer: 'The Row Access Policy is cloned and attached to the cloned table, referencing the same policy object',
    exp: 'When cloning, the cloned table retains the reference to the same Row Access Policy (and masking policies). The policies are NOT deep-copied — the clone references the original policy objects (dangling reference risk if cross-DB).',
  },
  {
    id: 'd5_d2_04',
    domain: 5,
    topic: 'Data Clean Rooms',
    difficulty: 'medium',
    q: 'What is the primary purpose of a Snowflake Data Clean Room?',
    options: [
      'Automatically removing PII data from tables after a defined retention period',
      'Enabling two parties to run joint analyses on their combined data without either party seeing the other\'s raw data',
      'Encrypting shared data before publishing to the Marketplace',
      'Providing a sandboxed environment for testing new SQL before production deployment',
    ],
    answer: 'Enabling two parties to run joint analyses on their combined data without either party seeing the other\'s raw data',
    exp: 'Data Clean Rooms allow privacy-preserving collaboration — two organizations join their datasets inside a controlled environment and query the overlap without exposing each other\'s underlying records.',
  },
  {
    id: 'd5_d2_05',
    domain: 5,
    topic: 'Native Apps',
    difficulty: 'medium',
    q: 'What is a Snowflake Native App (Snowflake Native Application Framework)?',
    options: [
      'A mobile app that connects to Snowflake using JDBC',
      'A packaged application (code + data + UI) that runs inside the consumer\'s Snowflake account, distributed via the Marketplace',
      'A Snowsight dashboard that is shared read-only with external users',
      'A serverless function deployed to the consumer\'s cloud provider from Snowflake',
    ],
    answer: 'A packaged application (code + data + UI) that runs inside the consumer\'s Snowflake account, distributed via the Marketplace',
    exp: 'Native Apps bundle stored procedures, UDFs, Streamlit UI, and data logic into an installable package. The consumer installs it into their own Snowflake account — the provider\'s code runs there with controlled privileges.',
  },
];
