// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 8  (2026-03-16)
// COF-C03 Mock Exam · 60 questions
// Difficulty mix: ~30% Easy (18q) · ~50% Medium (30q) · ~20% Hard (12q)
//
// SOURCE: Adapted from Cortex-generated question set.
// NOTE: Distribution deviates from the standard 19/12/11/13/5 split because
//       the source material used a different sectioning. Actual counts:
//       D1 12q | D2 11q | D3 11q | D4 17q | D5 9q  (total 60)
//
// FIXES APPLIED vs source:
//   • Answer positions shuffled — original had ~45/60 answers at position B.
//     Options were reordered per question so correct answers are spread across
//     A/B/C/D (~15 each).
//   • Q3 numbers corrected — original math implied CS exceeded 10%, but answer
//     said it didn't. Replaced with 0.08 / 1.0 = 8% scenario (below threshold).
//   • Q9, Q17, Q24 (Choose-TWO) — restructured to single-answer format by
//     combining the two correct concepts into one option.
//   • Q43, Q45, Q50 (5-option "Both A and D/E") — restructured to 4-option
//     single-answer with the combined correct concept as one option.
//   • Explanations expanded for all questions.
//
// OVERLAP RULE:
//   Day 7 (N-1): ≤ 30% overlap (≤ 18 questions)
//   Day 6 (N-2): ≤ 20% overlap (≤ 12 questions)
//   Day 5 (N-3): ≤ 10% overlap (≤  6 questions)
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 8,
  date: '2026-03-16',
  label: 'Day 8 — Comprehensive Review',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (12 questions) ─────────────────────

  {
    id: 'd1_d8_01',
    domain: 1,
    topic: 'Multi-cluster Warehouses',
    difficulty: 'medium',
    q: 'A company uses a multi-cluster warehouse with SCALING_POLICY = ECONOMY. During a query spike, users report increased queuing. What is the MOST likely explanation?',
    options: [
      'ECONOMY mode disables auto-scaling; clusters must be started manually during spikes',
      'ECONOMY mode limits the warehouse to a maximum of two clusters regardless of MAX_CLUSTER_COUNT',
      'ECONOMY mode only adds a new cluster when the system estimates it will be busy for at least 6 continuous minutes — it intentionally tolerates more queuing to avoid wasting credits on short-lived bursts',
      'The warehouse suspended automatically due to AUTO_SUSPEND and needs time to warm up',
    ],
    answer: 'ECONOMY mode only adds a new cluster when the system estimates it will be busy for at least 6 continuous minutes — it intentionally tolerates more queuing to avoid wasting credits on short-lived bursts',
    exp: 'ECONOMY scaling optimizes for cost: it waits until queued work justifies a full cluster lifetime before spinning one up. STANDARD mode starts a cluster the moment any query is queued. For latency-sensitive workloads (BI dashboards, interactive queries) use STANDARD; for batchable workloads where a bit of queue time is acceptable, ECONOMY saves credits.',
  },
  {
    id: 'd1_d8_02',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'Snowflake separates its architecture into three layers. Which layer is responsible for query optimization, authentication, access control, and metadata management?',
    options: [
      'Virtual Warehouse (Compute) layer — processes SQL and manages execution',
      'Cloud Services layer — the brain of Snowflake, handling optimization, auth, and metadata',
      'Storage layer — manages data files and coordinates partition metadata',
      'Result Cache layer — a sub-layer of Cloud Services dedicated solely to caching',
    ],
    answer: 'Cloud Services layer — the brain of Snowflake, handling optimization, auth, and metadata',
    exp: 'The Cloud Services layer is a globally shared, multi-tenant service running 24/7. It handles query parsing and optimization, credential validation, access control enforcement, transaction coordination, and metadata (table/schema/partition definitions). It runs even when no virtual warehouses are active, which is why it has its own credit billing model (billed when exceeding 10% of daily warehouse credits).',
  },
  {
    id: 'd1_d8_03',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'For a given UTC day, an account\'s virtual warehouses consumed 1.0 credits and Cloud Services consumed 0.08 credits. Will there be an additional Cloud Services charge on that day\'s bill?',
    options: [
      'No — Cloud Services (0.08 credits) represent 8% of daily warehouse credits (1.0), which is below the 10% free threshold. Only the excess above 10% is billed, so no additional CS charge applies.',
      'Yes — Cloud Services are always billed on top of warehouse credits, regardless of usage level',
      'No — Cloud Services are fully bundled into the warehouse credit cost at all Snowflake editions',
      'Yes — the billing threshold is 5%, not 10%; any Cloud Services above 5% of warehouse credits triggers an additional charge',
    ],
    answer: 'No — Cloud Services (0.08 credits) represent 8% of daily warehouse credits (1.0), which is below the 10% free threshold. Only the excess above 10% is billed, so no additional CS charge applies.',
    exp: 'Snowflake calculates the Cloud Services adjustment once per UTC calendar day: if CS credits ≤ 10% of that day\'s warehouse credits, the CS usage is effectively free (the daily warehouse spend covers it). Only CS usage above the 10% mark generates an additional charge. Heavy use of SHOW commands, metadata queries, or serverless features can push CS above the threshold.',
  },
  {
    id: 'd1_d8_04',
    domain: 1,
    topic: 'Table Types',
    difficulty: 'easy',
    q: 'A developer creates a TRANSIENT table and then runs CREATE TABLE archive CLONE source_transient. What is the resulting type of the archive table?',
    options: [
      'A PERMANENT table — cloning always promotes the object to permanent for safety',
      'A TEMPORARY table — clones of transient tables default to temporary scope',
      'A TRANSIENT table — zero-copy clones inherit the source object\'s table type',
      'The clone operation fails because transient tables cannot be cloned',
    ],
    answer: 'A TRANSIENT table — zero-copy clones inherit the source object\'s table type',
    exp: 'This is an important exam trap. When you clone a transient table, the clone is also transient — it inherits the No Fail-safe, max 1-day Time Travel characteristics of the source. Similarly, cloning a temporary table produces another temporary table (session-scoped). To create a permanent backup from a transient source, use CREATE TABLE ... AS SELECT instead of CLONE.',
  },
  {
    id: 'd1_d8_05',
    domain: 1,
    topic: 'Micro-partitions',
    difficulty: 'easy',
    q: 'Which statement about Snowflake\'s micro-partitions is TRUE?',
    options: [
      'Users can manually define micro-partition boundaries by specifying partition key ranges',
      'Micro-partitions are stored uncompressed on local SSD for faster full scans',
      'Each micro-partition contains data from exactly one column to enable columnar compression',
      'Micro-partitions are immutable, automatically managed columnar storage files of 50–500 MB (before compression), encrypted with AES-256',
    ],
    answer: 'Micro-partitions are immutable, automatically managed columnar storage files of 50–500 MB (before compression), encrypted with AES-256',
    exp: 'Snowflake\'s micro-partition system is fully automatic — users never define or manage partition boundaries (unlike Hive-style partitioning). Each micro-partition stores all columns for a contiguous range of rows, organized columnar internally. They are immutable: any DML on a row creates new micro-partition files rather than modifying existing ones, which enables Time Travel and zero-copy cloning.',
  },
  {
    id: 'd1_d8_06',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A virtual warehouse is resized from X-Large to Medium while several queries are actively running. What happens to those running queries?',
    options: [
      'All running queries are immediately cancelled and must be resubmitted',
      'Running queries continue executing on the current X-Large resources; only new queries arriving after the resize use the Medium resources',
      'The resize is queued and does not take effect until all currently running queries complete',
      'The warehouse is briefly suspended during the resize, causing a momentary interruption to running queries',
    ],
    answer: 'Running queries continue executing on the current X-Large resources; only new queries arriving after the resize use the Medium resources',
    exp: 'Snowflake handles warehouse resizes gracefully with zero interruption to in-flight queries. The old nodes are drained (complete their current work) while new nodes at the target size become available for incoming queries. This "graceful resize" ensures production workloads are not disrupted. The tradeoff is that cost reduction from a downsize takes effect only after the running queries drain.',
  },
  {
    id: 'd1_d8_07',
    domain: 1,
    topic: 'Multi-cluster Warehouses',
    difficulty: 'easy',
    q: 'In a multi-cluster warehouse configuration, what does the MAX_CLUSTER_COUNT parameter control?',
    options: [
      'The maximum number of concurrent queries allowed per cluster node',
      'The maximum number of warehouses that can be created in the account',
      'The upper limit on how many clusters the warehouse can scale out to during peak load',
      'The maximum number of nodes within a single cluster tier',
    ],
    answer: 'The upper limit on how many clusters the warehouse can scale out to during peak load',
    exp: 'MAX_CLUSTER_COUNT is the hard ceiling for auto-scaling. During peak demand, Snowflake adds clusters one by one up to this maximum — it will never exceed it. MIN_CLUSTER_COUNT sets the baseline (always-running) clusters. Setting MAX = MIN = 1 effectively disables multi-cluster behavior and gives you a single standard warehouse.',
  },
  {
    id: 'd1_d8_08',
    domain: 1,
    topic: 'Editions',
    difficulty: 'easy',
    q: 'A company wants to use multi-cluster virtual warehouses for workload isolation. What is the MINIMUM Snowflake edition that supports this feature?',
    options: [
      'Standard — multi-cluster warehouses are available on all editions',
      'Business Critical — workload isolation features require advanced security tiers',
      'Virtual Private Snowflake — multi-cluster requires fully isolated infrastructure',
      'Enterprise — multi-cluster virtual warehouses are an Enterprise edition feature',
    ],
    answer: 'Enterprise — multi-cluster virtual warehouses are an Enterprise edition feature',
    exp: 'Multi-cluster warehouses, along with 90-day Time Travel, materialized views, and Search Optimization Service, are Enterprise-tier features. Standard edition customers are limited to single-cluster warehouses. Business Critical and VPS also include multi-cluster (they build on Enterprise). This is a frequently tested edition gate on the COF-C03 exam.',
  },
  {
    id: 'd1_d8_09',
    domain: 1,
    topic: 'Zero-copy Cloning',
    difficulty: 'easy',
    q: 'A developer clones a 2 TB production table with CREATE TABLE orders_clone CLONE orders. How much additional storage does Snowflake consume immediately after the clone is created?',
    options: [
      '2 TB — the clone creates a full physical copy of all micro-partitions',
      'Approximately 1 TB — Snowflake stores a 50% compressed copy of the data',
      'Zero bytes of additional data storage — the clone shares all existing micro-partitions with the source until data is modified (copy-on-write)',
      'Only metadata storage — plus the full 2 TB reserved for future modifications',
    ],
    answer: 'Zero bytes of additional data storage — the clone shares all existing micro-partitions with the source until data is modified (copy-on-write)',
    exp: 'Zero-copy cloning is one of Snowflake\'s flagship features. At clone creation, only metadata is written — both the source and clone point to the same underlying micro-partition files. Additional storage is only consumed when DML modifies data in either the source or clone, creating new micro-partition files (copy-on-write). This makes cloning entire databases instantaneous and free, regardless of data size.',
  },
  {
    id: 'd1_d8_10',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A DBA sets STATEMENT_TIMEOUT_IN_SECONDS = 300 on a virtual warehouse. What is the effect?',
    options: [
      'Queries waiting in the warehouse queue for more than 300 seconds are cancelled before starting',
      'Any query still executing after 300 seconds is automatically cancelled — this enforces a hard time limit per query execution',
      'The warehouse itself suspends after 300 seconds without activity (equivalent to AUTO_SUSPEND = 300)',
      'Query compilation must complete within 300 seconds; execution time is unlimited',
    ],
    answer: 'Any query still executing after 300 seconds is automatically cancelled — this enforces a hard time limit per query execution',
    exp: 'STATEMENT_TIMEOUT_IN_SECONDS controls how long a single statement can run on that warehouse. Exceeding the limit terminates the query with a timeout error. This protects against runaway queries that could occupy compute for hours. It is different from STATEMENT_QUEUED_TIMEOUT_IN_SECONDS (which limits how long a query can wait in the queue before being cancelled) and AUTO_SUSPEND (which suspends the whole warehouse on inactivity).',
  },
  {
    id: 'd1_d8_11',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A warehouse has AUTO_SUSPEND = 60 and AUTO_RESUME = TRUE. The last query finished 90 seconds ago. A new query is now submitted. What happens?',
    options: [
      'Snowflake auto-resumes the warehouse and executes the query after a brief startup delay — AUTO_RESUME = TRUE handles this transparently',
      'The query fails — the warehouse is suspended and manual intervention is required',
      'The query is served from the result cache without resuming the warehouse',
      'The query waits in queue until an admin manually resumes the warehouse',
    ],
    answer: 'Snowflake auto-resumes the warehouse and executes the query after a brief startup delay — AUTO_RESUME = TRUE handles this transparently',
    exp: 'With AUTO_RESUME = TRUE, submitting a query to a suspended warehouse automatically triggers a resume. The warehouse was suspended after 60 seconds of inactivity (AUTO_SUSPEND = 60). At 90 seconds after the last query, it is now suspended. The new query triggers auto-resume, incurring the 60-second billing minimum for the new session. The user experiences a few seconds of startup delay before results are returned.',
  },
  {
    id: 'd1_d8_12',
    domain: 1,
    topic: 'Multi-cluster Warehouses',
    difficulty: 'hard',
    q: 'A company has 500 BI users who run short, concurrent queries throughout the business day. Which virtual warehouse strategy BEST handles this workload?',
    options: [
      'One very large single warehouse (4XL) — a single large warehouse has enough resources for all concurrent users',
      'A dedicated X-Small warehouse per user — each user gets guaranteed dedicated resources',
      'A single Medium warehouse — the result cache absorbs most concurrent BI queries without scaling',
      'A multi-cluster warehouse with auto-scaling (STANDARD or ECONOMY) — adds clusters during peaks, removes them during lulls, distributing the concurrent query load across multiple warehouses',
    ],
    answer: 'A multi-cluster warehouse with auto-scaling (STANDARD or ECONOMY) — adds clusters during peaks, removes them during lulls, distributing the concurrent query load across multiple warehouses',
    exp: 'For concurrency problems (many simultaneous short queries), scale OUT — not UP. Scaling up (larger warehouse) helps with single-query throughput (faster scans, more memory for complex joins). Scaling out (multi-cluster) reduces queue depth by spreading concurrent users across multiple warehouses. For 500 BI users, a multi-cluster warehouse with STANDARD policy is the textbook answer. ECONOMY can work for less latency-sensitive teams.',
  },

  // ── DOMAIN 2: Account Management & Governance (11 questions) ─────────────

  {
    id: 'd2_d8_01',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'easy',
    q: 'A security admin wants Role_A to be able to CREATE tables in a specific schema but NOT drop or alter them. Which grant(s) satisfy this requirement at minimum privilege?',
    options: [
      'GRANT ALL PRIVILEGES ON SCHEMA to Role_A',
      'GRANT USAGE ON SCHEMA and GRANT CREATE TABLE ON SCHEMA to Role_A',
      'GRANT OWNERSHIP ON SCHEMA to Role_A',
      'GRANT MODIFY ON SCHEMA to Role_A',
    ],
    answer: 'GRANT USAGE ON SCHEMA and GRANT CREATE TABLE ON SCHEMA to Role_A',
    exp: 'USAGE on the schema allows Role_A to see and access objects within it. CREATE TABLE on the schema specifically grants the right to create new tables — no more. MODIFY allows altering existing schema properties. OWNERSHIP grants all DDL rights (create, alter, drop). ALL PRIVILEGES is far beyond minimum. This two-grant combination precisely satisfies least-privilege for table creation only.',
  },
  {
    id: 'd2_d8_02',
    domain: 2,
    topic: 'Network Policies',
    difficulty: 'medium',
    q: 'Which statement about Snowflake network policies is TRUE?',
    options: [
      'Network policies can be applied at the database or schema level to restrict object access',
      'Network policies use deny-list logic only — you specify IPs to block, and all others are allowed',
      'Network policies are exclusively available on the Business Critical edition',
      'A network policy set at the account level can be overridden for a specific user by assigning a user-level network policy to that user',
    ],
    answer: 'A network policy set at the account level can be overridden for a specific user by assigning a user-level network policy to that user',
    exp: 'Network policies in Snowflake use an ALLOWED_IP_LIST (whitelist logic, not deny-list). They can be set at the account level or user level. When a user has a user-level policy, it takes precedence over the account-level policy for that specific user. This allows targeted exceptions — e.g., a remote worker can be individually whitelisted without changing the broader account policy. Network policies apply to authentication, not database/schema object access.',
  },
  {
    id: 'd2_d8_03',
    domain: 2,
    topic: 'Encryption',
    difficulty: 'medium',
    q: 'A company needs Snowflake to use customer-managed encryption keys (Tri-Secret Secure) so that Snowflake cannot decrypt data without the customer\'s participation. What is the MINIMUM edition required?',
    options: [
      'Business Critical — Tri-Secret Secure (customer-managed keys via cloud KMS + Snowflake key) requires Business Critical edition',
      'Standard — key management is available at all editions via AWS KMS',
      'Enterprise — Tri-Secret Secure is an Enterprise-tier encryption option',
      'Virtual Private Snowflake — customer key management requires fully isolated infrastructure',
    ],
    answer: 'Business Critical — Tri-Secret Secure (customer-managed keys via cloud KMS + Snowflake key) requires Business Critical edition',
    exp: 'Tri-Secret Secure is a Business Critical (formerly "Enterprise for Sensitive Data") feature where data encryption requires BOTH a Snowflake-managed key AND a customer-managed key from their cloud KMS (AWS KMS, Azure Key Vault, or GCP Cloud KMS). If the customer revokes their key, Snowflake cannot decrypt data. Enterprise edition provides standard AES-256 Snowflake-managed encryption — not customer-managed. Standard has no enhanced encryption options.',
  },
  {
    id: 'd2_d8_04',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'Role ANALYST has SELECT on VIEW_A. VIEW_A was created with a SELECT from TABLE_B. Role ANALYST has no privileges on TABLE_B. Can ANALYST query VIEW_A successfully?',
    options: [
      'No — ANALYST must have direct SELECT on TABLE_B to read through VIEW_A',
      'No — VIEW_A would need to be a Materialized View for privilege inheritance to work',
      'Yes — standard (non-secure) views execute with the owner\'s privileges on underlying objects. ANALYST needs only SELECT on the view, not on TABLE_B.',
      'Only if TABLE_B resides in the same schema as VIEW_A',
    ],
    answer: 'Yes — standard (non-secure) views execute with the owner\'s privileges on underlying objects. ANALYST needs only SELECT on the view, not on TABLE_B.',
    exp: 'This is called "owner\'s rights" for views. When a role queries a view, Snowflake checks that role\'s privilege on the VIEW object, then checks the view OWNER\'s privileges on the underlying tables. ANALYST doesn\'t need access to TABLE_B — the view\'s owner does. This allows controlled exposure of data without granting direct table access. SECURE VIEWS behave differently: they hide the underlying definition and restrict certain pushdown optimizations.',
  },
  {
    id: 'd2_d8_05',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'hard',
    q: 'Which statement MOST accurately describes Snowflake\'s Role-Based Access Control model?',
    options: [
      'Each user can have only one role active per session; role hierarchies are not supported in Snowflake',
      'Roles form a hierarchy (roles can be granted to other roles), and ACCOUNTADMIN sits at the top inheriting all privileges from every role below it in the hierarchy',
      'Privileges granted to a custom role are automatically inherited by all users in the account without needing an explicit role assignment',
      'Only USERADMIN can grant roles to users; SECURITYADMIN cannot perform role assignments',
    ],
    answer: 'Roles form a hierarchy (roles can be granted to other roles), and ACCOUNTADMIN sits at the top inheriting all privileges from every role below it in the hierarchy',
    exp: 'Snowflake RBAC key principles: (1) Roles ARE hierarchical — you GRANT ROLE child TO ROLE parent, and the parent inherits all of child\'s privileges. (2) ACCOUNTADMIN is the apex role — all custom roles and system roles ultimately grant up to it (or should, by best practice). (3) A user CAN have multiple roles simultaneously via USE SECONDARY ROLES ALL. (4) Both USERADMIN and SECURITYADMIN (which includes USERADMIN privileges) can manage users and role assignments.',
  },
  {
    id: 'd2_d8_06',
    domain: 2,
    topic: 'Dynamic Data Masking',
    difficulty: 'easy',
    q: 'A data engineer creates a policy that shows the full SSN value to role HR_ADMIN and returns \'***-**-****\' to all other roles. Which Snowflake governance feature is being used?',
    options: [
      'Row Access Policy — filters entire rows based on role',
      'Secure View — hides the underlying SQL definition from unauthorized users',
      'External Tokenization — replaces PII with tokens before storage',
      'Dynamic Data Masking — applies column-level masking at query time based on the querying role',
    ],
    answer: 'Dynamic Data Masking — applies column-level masking at query time based on the querying role',
    exp: 'Dynamic Data Masking (DDM) is a column-level security feature that rewrites column values in query results based on a policy function. The data is stored unmasked; the masking is applied dynamically at query runtime. HR_ADMIN gets the real SSN; all others see a masked string. This is fundamentally different from Row Access Policy (which filters rows, not columns) and Secure Views (which hide view definitions, not data values).',
  },
  {
    id: 'd2_d8_07',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'hard',
    q: 'In Snowflake, who has the authority to transfer the OWNERSHIP privilege on an object to another role?',
    options: [
      'Only the current owner of the object OR a role with the MANAGE GRANTS global privilege',
      'Any role that has USAGE on the object can transfer ownership to itself',
      'Only ACCOUNTADMIN — ownership transfers must be performed at the highest privilege level',
      'Any role with CREATE privilege on the schema containing the object',
    ],
    answer: 'Only the current owner of the object OR a role with the MANAGE GRANTS global privilege',
    exp: 'GRANT OWNERSHIP is the most powerful DDL operation for an object — it transfers full control. Only the current owner can give it away, OR a role with MANAGE GRANTS (which ACCOUNTADMIN and SECURITYADMIN hold). This prevents privilege escalation attacks where a role with USAGE tries to "steal" ownership. Note: the original owner loses ownership when it is transferred — you cannot have two owners simultaneously.',
  },
  {
    id: 'd2_d8_08',
    domain: 2,
    topic: 'Network Policies',
    difficulty: 'medium',
    q: 'A company\'s security policy requires all Snowflake traffic to flow through AWS private infrastructure — no traffic over the public internet. Which Snowflake feature enables this?',
    options: [
      'A corporate VPN gateway with IP whitelisting in a Snowflake network policy',
      'Snowflake Virtual Private Cloud peering between the company VPC and Snowflake',
      'AWS PrivateLink integration with Snowflake — creates a private VPC endpoint so traffic stays within the AWS network and never traverses the public internet',
      'IP whitelisting via a Snowflake network policy alone fulfills the private connectivity requirement',
    ],
    answer: 'AWS PrivateLink integration with Snowflake — creates a private VPC endpoint so traffic stays within the AWS network and never traverses the public internet',
    exp: 'AWS PrivateLink (Business Critical edition) creates a private endpoint in your VPC that routes Snowflake traffic entirely through the AWS backbone — no internet gateway, no NAT, no public IPs involved. Network policies use IP allowlisting but don\'t prevent internet routing. VPC peering could work but PrivateLink is the Snowflake-recommended and supported mechanism. Azure has Private Link; GCP has Private Service Connect for equivalent functionality.',
  },
  {
    id: 'd2_d8_09',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'easy',
    q: 'When Multi-Factor Authentication (MFA) is configured in Snowflake, which authenticator service powers the MFA push notifications and one-time passcodes?',
    options: [
      'Google Authenticator — Snowflake exclusively supports Google\'s TOTP standard for MFA',
      'Duo Security — Snowflake\'s native MFA uses Duo for push approvals and TOTP codes',
      'Microsoft Authenticator — Snowflake uses Entra ID for push-based MFA',
      'MFA is only available through SAML 2.0 SSO; standalone MFA is not supported natively',
    ],
    answer: 'Duo Security — Snowflake\'s native MFA uses Duo for push approvals and TOTP codes',
    exp: 'Snowflake\'s built-in MFA is powered by Duo Security. Users install Duo Mobile and enroll their device; subsequent logins prompt a Duo push approval or TOTP code. MFA can be enforced account-wide via a Session Policy or enabled per user with ALTER USER ... SET MINS_TO_BYPASS_MFA. When using SAML 2.0 SSO, the IdP handles MFA separately — Duo is for Snowflake-native authentication.',
  },
  {
    id: 'd2_d8_10',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'hard',
    q: 'A compliance team must audit which roles accessed which specific TABLE COLUMNS over the past 90 days. Which ACCOUNT_USAGE view provides this granularity?',
    options: [
      'ACCESS_HISTORY — records every query\'s base objects and columns accessed, with user identity, role, and timestamp — the correct view for column-level data access auditing',
      'QUERY_HISTORY — the SQL text can be parsed to infer column access patterns',
      'OBJECT_DEPENDENCIES — shows compile-time column references in views and stored procedures',
      'LOGIN_HISTORY — records access events including column-level permission checks',
    ],
    answer: 'ACCESS_HISTORY — records every query\'s base objects and columns accessed, with user identity, role, and timestamp — the correct view for column-level data access auditing',
    exp: 'ACCESS_HISTORY (Enterprise+) is purpose-built for compliance use cases. Each row represents a query and contains DIRECT_OBJECTS_ACCESSED (explicitly named tables/views) and BASE_OBJECTS_ACCESSED (underlying tables resolved through views) including COLUMNS_ACCESSED — which specific columns were read. This is far more reliable than parsing QUERY_HISTORY SQL text and is the authoritative data access audit trail for regulatory compliance.',
  },
  {
    id: 'd2_d8_11',
    domain: 2,
    topic: 'Object Tagging',
    difficulty: 'medium',
    q: 'A governance team attaches a Snowflake TAG (e.g., PII = \'SSN\') to a table column. They also associate a masking policy with that TAG object. What happens automatically?',
    options: [
      'The tag attachment deletes existing masking policies on the column and replaces them',
      'Nothing — tags and masking policies are unrelated; the policy must be set on each column individually',
      'Any column tagged with that tag automatically inherits the associated masking policy — this is tag-based masking, a centralized way to apply policies across many columns simultaneously',
      'The tag-to-policy association only works for ACCOUNTADMIN users; other roles still see unmasked data',
    ],
    answer: 'Any column tagged with that tag automatically inherits the associated masking policy — this is tag-based masking, a centralized way to apply policies across many columns simultaneously',
    exp: 'Tag-based masking (ALTER TAG pii_tag SET MASKING POLICY ssn_mask) creates a binding between the tag and the masking policy. Any column tagged with pii_tag automatically gets the masking policy applied — without needing ALTER TABLE ... COLUMN SET MASKING POLICY on each column individually. This is extremely powerful for large environments where hundreds of SSN columns across many tables need consistent masking: tag them all, one policy, one binding.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ───────

  {
    id: 'd3_d8_01',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'medium',
    q: 'A Snowpipe is configured on an S3 bucket with AUTO_INGEST = TRUE. New files arrive in S3 but are NOT being loaded. What are the MOST likely causes?',
    options: [
      'The Snowpipe\'s virtual warehouse is suspended and not consuming the event queue',
      'Snowpipe is blocked because the account credit limit was reached',
      'Snowpipe is not enabled on the Business Critical edition used by the account',
      'Either the S3 SQS event notification is misconfigured (events not reaching Snowflake) OR the file format definition in the pipe\'s COPY INTO does not match the actual files — both are common silent failure modes',
    ],
    answer: 'Either the S3 SQS event notification is misconfigured (events not reaching Snowflake) OR the file format definition in the pipe\'s COPY INTO does not match the actual files — both are common silent failure modes',
    exp: 'Snowpipe uses serverless compute (no warehouse to suspend), so answer A is a common distractor. The two most frequent root causes for AUTO_INGEST Snowpipes not loading are: (1) SQS/SNS event notification not configured, wrong bucket, or filtered — Snowflake never receives the trigger; (2) File format mismatch (wrong delimiter, missing SKIP_HEADER, wrong type) — the pipe triggers but COPY INTO rejects the file. Check COPY_HISTORY in ACCOUNT_USAGE to diagnose which failure mode you have.',
  },
  {
    id: 'd3_d8_02',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'What is the recommended individual file size when loading data into Snowflake for optimal parallel processing performance?',
    options: [
      '1–5 MB — very small files maximize the number of parallel load threads',
      '10–50 MB compressed — a common middle ground for most file systems',
      '100–250 MB compressed — the Snowflake-recommended sweet spot for parallel loading efficiency',
      '1 GB or larger — fewer, larger files reduce metadata overhead',
    ],
    answer: '100–250 MB compressed — the Snowflake-recommended sweet spot for parallel loading efficiency',
    exp: 'Snowflake\'s parallel loading architecture assigns one file per worker thread. Files smaller than ~100 MB compressed create too many threads with overhead exceeding benefit (the "small file problem"). Files larger than ~500 MB cannot be split and limit parallelism. The 100–250 MB compressed range (equivalent to ~500 MB–1 GB uncompressed for typical text data) gives optimal throughput. If you have large files, pre-split them before staging.',
  },
  {
    id: 'd3_d8_03',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'A COPY INTO targets 10 staged files. ON_ERROR = \'CONTINUE\'. Five files have parsing errors on some rows. What is the outcome?',
    options: [
      'All rows from all 10 files are loaded; rows with errors have their bad columns replaced with NULL',
      'All 10 files are entirely rejected — any error in a batch causes a complete abort under CONTINUE mode',
      'The 5 clean files load completely; from the 5 error files, valid rows are loaded and only the erroneous rows are skipped. The load continues past errors.',
      'The command pauses and prompts the user to resolve errors before continuing',
    ],
    answer: 'The 5 clean files load completely; from the 5 error files, valid rows are loaded and only the erroneous rows are skipped. The load continues past errors.',
    exp: 'ON_ERROR = CONTINUE tells Snowflake to skip individual bad rows and keep loading. The default ABORT_STATEMENT rolls back everything on the first error. SKIP_FILE skips entire files that have errors. SKIP_FILE_n% skips files where the error rate exceeds n%. After a CONTINUE load, check COPY_HISTORY or run COPY INTO ... VALIDATION_MODE = \'RETURN_ALL_ERRORS\' to see which rows were skipped.',
  },
  {
    id: 'd3_d8_04',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'easy',
    q: 'Which statement about how Snowpipe processes data loads is TRUE?',
    options: [
      'Snowpipe uses a dedicated user-defined virtual warehouse specified in the pipe definition',
      'Snowpipe uses Snowflake-managed serverless compute — no virtual warehouse is required or consumed by the customer',
      'Snowpipe can only load from Snowflake internal stages, not external cloud storage stages',
      'Snowpipe supports direct loading from on-premises file servers via SFTP',
    ],
    answer: 'Snowpipe uses Snowflake-managed serverless compute — no virtual warehouse is required or consumed by the customer',
    exp: 'Snowpipe is fully serverless. Snowflake manages the compute infrastructure for pipe execution — customers are billed for serverless compute credits (not warehouse credits) based on the data loaded. This makes Snowpipe cost-efficient for sporadic or continuous event-driven loading: you only pay when files are actually processed. Snowpipe works with both internal and external stages (S3, Azure Blob, GCS).',
  },
  {
    id: 'd3_d8_05',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'hard',
    q: 'A data engineer wants to export query results to Parquet format on an external S3 stage. Which command achieves this?',
    options: [
      'PUT (SELECT ...) INTO @my_ext_stage FILE_FORMAT = (TYPE = PARQUET)',
      'INSERT INTO @my_ext_stage SELECT ... FILE_FORMAT = PARQUET',
      'EXPORT DATA INTO @my_ext_stage FORMAT PARQUET FROM (SELECT ...)',
      'COPY INTO @my_ext_stage FROM (SELECT ...) FILE_FORMAT = (TYPE = PARQUET)',
    ],
    answer: 'COPY INTO @my_ext_stage FROM (SELECT ...) FILE_FORMAT = (TYPE = PARQUET)',
    exp: 'COPY INTO is used for both loading (FROM stage INTO table) and unloading (FROM table/query INTO stage). The unload syntax reverses the direction: COPY INTO @stage FROM (SELECT ...). PUT only uploads local files to stages — it cannot execute queries. INSERT INTO stages is not valid SQL in Snowflake. EXPORT DATA is not a Snowflake command. For Parquet output, specify FILE_FORMAT = (TYPE = PARQUET) — no HEADER option for Parquet (the schema is embedded).',
  },
  {
    id: 'd3_d8_06',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'hard',
    q: 'File data_20250101.csv was successfully loaded 3 hours ago via COPY INTO. The same unchanged file is now placed in the stage again and COPY INTO is run without any additional options. What happens?',
    options: [
      'The file loads again, creating duplicate rows — COPY INTO has no built-in deduplication',
      'The file always reloads if it appears in the stage — deduplication must be done by the application',
      'Both of these are true: (1) Snowflake skips the file because it tracks load history by file path + ETag for 64 days; AND (2) adding FORCE = TRUE to the COPY INTO command bypasses deduplication and forces a reload',
      'The file is reloaded but Snowflake automatically detects and removes the duplicate rows using a primary key check',
    ],
    answer: 'Both of these are true: (1) Snowflake skips the file because it tracks load history by file path + ETag for 64 days; AND (2) adding FORCE = TRUE to the COPY INTO command bypasses deduplication and forces a reload',
    exp: 'COPY INTO maintains a 64-day load deduplication window keyed on file path + ETag (content hash). This prevents accidental reloads when a file remains in the stage after loading. The deduplication is NOT based on data content — a file with a different name or modified content (new ETag) IS treated as a new file. FORCE = TRUE bypasses this check when you intentionally want to reload (e.g., after fixing a data issue). Use FORCE carefully — it can create duplicates.',
  },
  {
    id: 'd3_d8_07',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'easy',
    q: 'Which file format is NOT natively supported by Snowflake for direct data loading via COPY INTO?',
    options: [
      'Microsoft Excel (.xlsx) — not a natively supported Snowflake load format',
      'Apache Avro (.avro) — a supported binary format for Snowflake loading',
      'JSON (.json / .ndjson) — natively supported including nested structure flattening',
      'CSV (.csv / .tsv) — the most commonly used Snowflake load format',
    ],
    answer: 'Microsoft Excel (.xlsx) — not a natively supported Snowflake load format',
    exp: 'Snowflake natively supports: CSV, JSON, Avro, ORC, Parquet, and XML. Microsoft Excel (.xlsx) is a proprietary binary format and is NOT supported. To load Excel data into Snowflake, export it to CSV first. This is a straightforward exam question — just remember the 6 supported formats. XML has limited support (load only, querying XML requires XMLGET/xpath functions).',
  },
  {
    id: 'd3_d8_08',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'easy',
    q: 'A developer runs PUT file:///data/sales.csv @my_internal_stage without any additional options. What transformation is automatically applied to the file?',
    options: [
      'The file is uploaded as-is in plain text — PUT performs no transformation by default',
      'The file is automatically compressed with GZIP before uploading to the stage',
      'The file is encrypted client-side before upload, but NOT compressed',
      'The file is split into 10 MB chunks for parallel upload efficiency',
    ],
    answer: 'The file is automatically compressed with GZIP before uploading to the stage',
    exp: 'PUT defaults to AUTO_COMPRESS = TRUE, which GZIP-compresses the file before uploading. The staged file gets a .gz extension. This reduces upload time, storage costs on the stage, and load time. To skip compression use AUTO_COMPRESS = FALSE, or specify SOURCE_COMPRESSION = NONE. COPY INTO automatically handles the .gz decompression during loading when FILE_FORMAT specifies COMPRESSION = AUTO (default).',
  },
  {
    id: 'd3_d8_09',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'A data team needs to continuously load streaming data from Apache Kafka topics into Snowflake with minimal custom code. What is the recommended approach?',
    options: [
      'Write a custom Python script using the Snowflake Python Connector to poll Kafka and insert rows',
      'Use Snowpipe REST API (insertFiles) to push Kafka messages as individual files',
      'Use an External Function to call a Kafka consumer API from SQL',
      'Use the Snowflake Connector for Kafka (Kafka Connect plugin) — purpose-built for reliable, scalable Kafka-to-Snowflake ingestion with exactly-once semantics and automatic topic-to-table mapping',
    ],
    answer: 'Use the Snowflake Connector for Kafka (Kafka Connect plugin) — purpose-built for reliable, scalable Kafka-to-Snowflake ingestion with exactly-once semantics and automatic topic-to-table mapping',
    exp: 'The Snowflake Kafka Connector is a Kafka Connect sink connector. It runs inside your Kafka Connect cluster, reads from Kafka topics, stages micro-batches to Snowflake internal stages, and uses Snowpipe to load them — all automatically. It handles offset management, schema evolution, and exactly-once delivery. Custom Python scripts and REST API approaches are DIY alternatives that lack the operational robustness of the native connector.',
  },
  {
    id: 'd3_d8_10',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'What is the key structural difference between a NAMED INTERNAL STAGE and a TABLE STAGE?',
    options: [
      'There is no functional difference — they are just different syntax for the same staging mechanism',
      'A named internal stage is a standalone schema-level object (CREATE STAGE) that can be managed and shared independently; a table stage (@%table_name) is automatically created with every table and is only accessible to roles with INSERT or OWNERSHIP on that table',
      'A table stage supports directory tables and auto-refresh; a named stage does not have directory table capability',
      'A named internal stage can hold only one file at a time; a table stage has no file count limit',
    ],
    answer: 'A named internal stage is a standalone schema-level object (CREATE STAGE) that can be managed and shared independently; a table stage (@%table_name) is automatically created with every table and is only accessible to roles with INSERT or OWNERSHIP on that table',
    exp: 'Named internal stages are first-class schema objects: CREATE STAGE, GRANT READ/WRITE ON STAGE, LIST @named_stage — they can be shared with multiple roles and teams. Table stages are implicitly created with each table and are private to that table\'s privilege holders. There is also the user stage (@~) — private to each user. For team-based ingestion workflows, always use named stages.',
  },
  {
    id: 'd3_d8_11',
    domain: 3,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'When loading a JSON file with COPY INTO, what does the FILE_FORMAT option STRIP_OUTER_ARRAY = TRUE do?',
    options: [
      'It removes all nested arrays from the JSON document before loading, flattening the structure',
      'It converts any array values in the JSON to comma-separated strings for relational compatibility',
      'It removes the outer array brackets so each element within the array is loaded as a separate row — useful when the JSON file contains a top-level array of objects',
      'It strips whitespace and empty strings from all array elements before loading',
    ],
    answer: 'It removes the outer array brackets so each element within the array is loaded as a separate row — useful when the JSON file contains a top-level array of objects',
    exp: 'A common JSON file pattern is an array of records: [{...},{...},{...}]. Without STRIP_OUTER_ARRAY, Snowflake loads the entire array as a single VARIANT row. With STRIP_OUTER_ARRAY = TRUE, Snowflake strips the outer [ ] and loads each element as a separate row — which is almost always the desired behavior for loading JSON record arrays. This is different from FLATTEN, which works at query time in SQL.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (17 questions) ───────

  {
    id: 'd4_d8_01',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'A Query Profile shows a "Spilling to Remote Storage" node consuming significant time. What should the analyst do FIRST?',
    options: [
      'Convert the query\'s target table to a transient table to reduce I/O overhead',
      'Increase the warehouse size — spilling to remote storage means local SSD and memory are exhausted; a larger warehouse provides more memory and local SSD for intermediate results',
      'Enable the result cache to avoid the query running again',
      'Add a clustering key to improve partition pruning and reduce the data scanned',
    ],
    answer: 'Increase the warehouse size — spilling to remote storage means local SSD and memory are exhausted; a larger warehouse provides more memory and local SSD for intermediate results',
    exp: '"Spilling to Remote Storage" is a critical performance signal — it means the warehouse ran out of local SSD AND in-memory space for intermediate data (e.g., during sort, aggregate, or hash join). Remote storage spill is much slower than local SSD spill, which itself is slower than in-memory. First response: scale up the warehouse. Secondary: investigate the query for optimization opportunities (reduce row counts earlier, add filters, rewrite joins) to reduce intermediate data size.',
  },
  {
    id: 'd4_d8_02',
    domain: 4,
    topic: 'Micro-partitions',
    difficulty: 'hard',
    q: 'Which combination of metadata does Snowflake automatically store per column in EVERY micro-partition\'s header for query optimization?',
    options: [
      'Row count and approximate byte size per micro-partition — used for cost estimation',
      'User-defined column tags and encryption key references per column',
      'Average value and standard deviation per column — used by the cost-based optimizer',
      'MIN value, MAX value, and NULL count per column — used by the query optimizer for partition pruning and cardinality estimation',
    ],
    answer: 'MIN value, MAX value, and NULL count per column — used by the query optimizer for partition pruning and cardinality estimation',
    exp: 'Snowflake stores per-column statistics in each micro-partition\'s metadata header: MIN, MAX, NULL_COUNT, and an approximate DISTINCT_COUNT. The MIN/MAX values are the foundation of partition pruning — if a WHERE clause value falls outside a partition\'s [MIN, MAX] range, that partition is pruned without scanning. NULL_COUNT helps with IS NULL / IS NOT NULL filter estimation. This "automatic zone map" system eliminates the need for user-managed indexes.',
  },
  {
    id: 'd4_d8_03',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'hard',
    q: 'A table is clustered by ORDER_DATE. A query filters heavily on CUSTOMER_ID with 90% of partitions being scanned. What is the BEST course of action?',
    options: [
      'Increase the warehouse size — more nodes means faster full scans',
      'Drop and recreate the table without any clustering key',
      'Either add CUSTOMER_ID to the clustering key (or as a separate clustering key) to enable pruning on that column, OR create a Materialized View pre-filtered/clustered on CUSTOMER_ID — both are valid depending on whether the query is ad-hoc or highly repetitive',
      'Enable the Search Optimization Service — it covers all filter column types',
    ],
    answer: 'Either add CUSTOMER_ID to the clustering key (or as a separate clustering key) to enable pruning on that column, OR create a Materialized View pre-filtered/clustered on CUSTOMER_ID — both are valid depending on whether the query is ad-hoc or highly repetitive',
    exp: 'When a clustering key doesn\'t match the query\'s filter column, pruning is ineffective. Option 1 (add CUSTOMER_ID to clustering): fast partition pruning but reclustering cost applies. Option 2 (MV with clustering on CUSTOMER_ID): great for repetitive dashboard queries; the MV can cluster differently from the base table. For equality/range lookups on high-cardinality columns, Search Optimization Service (option D) is also valid — but the question asks about the clustering mismatch specifically.',
  },
  {
    id: 'd4_d8_04',
    domain: 4,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'Which TWO factors are the primary determinants of virtual warehouse credit consumption?',
    options: [
      'The warehouse size (X-Small = 1 cr/hr, Small = 2, Medium = 4, etc.) AND the total active running time (per-second billing, 60-second minimum per start)',
      'The number of databases accessed per query and the total data volume scanned in bytes',
      'The total rows returned to the client and the Snowflake region where the account is hosted',
      'The number of concurrent users connected to the warehouse and SQL query complexity',
    ],
    answer: 'The warehouse size (X-Small = 1 cr/hr, Small = 2, Medium = 4, etc.) AND the total active running time (per-second billing, 60-second minimum per start)',
    exp: 'Virtual warehouse credits = (credit rate for size) × (seconds running, minimum 60 seconds per start). A Medium warehouse at 4 credits/hour running for 2 minutes = 4 × (120/3600) = 0.133 credits. Data scanned, rows returned, number of users, and region do NOT directly affect warehouse credit consumption. The 60-second minimum means a 5-second query on a freshly resumed warehouse is billed as if it ran for 60 seconds.',
  },
  {
    id: 'd4_d8_05',
    domain: 4,
    topic: 'Caching',
    difficulty: 'easy',
    q: 'A query is re-executed and results are returned in under 200 milliseconds — faster than any warehouse scan could produce. The warehouse was already active. Which caching layer served this result?',
    options: [
      'Local disk (SSD) cache on warehouse nodes — frequently accessed micro-partitions cached on SSD',
      'Result cache in the Cloud Services layer — identical SQL with unchanged underlying data returns the cached result without engaging the warehouse compute at all',
      'Metadata cache — SHOW commands and schema queries use this layer',
      'Remote storage cache — a CDN-style cache in cloud object storage for hot data',
    ],
    answer: 'Result cache in the Cloud Services layer — identical SQL with unchanged underlying data returns the cached result without engaging the warehouse compute at all',
    exp: 'The result cache is stored in the Cloud Services layer and returns results for identical SQL queries (same role, same session parameters, same SQL text, unchanged table data) within the 24-hour TTL. Crucially, the warehouse does NOT need to be running or even active — result cache hits are served entirely by Cloud Services. This is why you can see sub-second responses without any warehouse resume. The local disk cache accelerates scans but still requires warehouse compute.',
  },
  {
    id: 'd4_d8_06',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'medium',
    q: 'A table with a clustering key is receiving 500 million inserts per day via continuous loading. An engineer notices automatic clustering is consuming a significant portion of the account\'s credits. What should they consider?',
    options: [
      'Disable clustering entirely — Snowflake\'s natural micro-partition ordering from inserts is always optimal',
      'Evaluate whether the clustering key matches actual query patterns; load data in pre-sorted order to reduce re-clustering needs; and consider whether the query performance benefit justifies the ongoing reclustering cost',
      'Switch to a larger warehouse for loading to reduce the credit overhead of clustering',
      'Convert the table to an external table to offload clustering costs',
    ],
    answer: 'Evaluate whether the clustering key matches actual query patterns; load data in pre-sorted order to reduce re-clustering needs; and consider whether the query performance benefit justifies the ongoing reclustering cost',
    exp: 'High-volume append workloads can cause expensive automatic reclustering if incoming data is not naturally sorted by the clustering key (e.g., appending by transaction time into a date-clustered table maintains order; appending randomly across region clusters everything constantly). Options: (1) pre-sort data before loading, (2) reconsider whether the clustering key is correct, (3) use SUSPEND RECLUSTER during off-peak to control costs, (4) evaluate whether query savings exceed clustering costs.',
  },
  {
    id: 'd4_d8_07',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'hard',
    q: 'A Query Profile shows high "Bytes Sent Over Network" between two TableScan nodes in a join operation. What is the MOST likely cause?',
    options: [
      'The warehouse size is too small — network bytes indicate insufficient local memory',
      'The result cache has expired and the data must be re-transferred from cloud storage',
      'The table lacks a clustering key, causing all partitions to be scanned',
      'An inefficient JOIN is causing large-scale data redistribution (shuffle) across compute nodes — the data from one table is being sent to nodes holding the matching rows from the other table',
    ],
    answer: 'An inefficient JOIN is causing large-scale data redistribution (shuffle) across compute nodes — the data from one table is being sent to nodes holding the matching rows from the other table',
    exp: 'High network bytes between join nodes in the Query Profile indicates a hash join shuffle — rows from one table are being repartitioned across the network to co-locate with their join partners. This is expensive. Optimizations: (1) Ensure the smaller join side fits in memory for a broadcast join; (2) Pre-aggregate before joining to reduce row counts; (3) Deduplicate join keys to avoid many-to-many explosions; (4) Check for Cartesian products (missing join conditions).',
  },
  {
    id: 'd4_d8_08',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'easy',
    q: 'Which scenario would NOT benefit significantly from a Materialized View?',
    options: [
      'A complex aggregation (GROUP BY + SUM + COUNT) run hourly by 50 dashboard users on a 10 TB table',
      'A query that always filters on the clustering key with high partition pruning — already fast',
      'A SELECT * query run once per month on a 100 GB table with no filtering or aggregation',
      'A multi-table join with heavy aggregation powering an executive dashboard refreshed every 5 minutes',
    ],
    answer: 'A SELECT * query run once per month on a 100 GB table with no filtering or aggregation',
    exp: 'Materialized Views are most valuable when: the query is (1) expensive, (2) run frequently, and (3) based on slowly-changing data. A monthly SELECT * with no aggregation fails criteria (1) and (2) — the MV incurs continuous refresh cost that FAR exceeds the once-monthly query cost. For a rarely-run full scan, using the result cache after the first run is more appropriate. MVs shine for frequently-run expensive aggregations.',
  },
  {
    id: 'd4_d8_09',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'hard',
    q: 'SYSTEM$CLUSTERING_INFORMATION(\'orders\') returns average_overlap = 3.2 and average_depth = 4.5. What does this indicate?',
    options: [
      'The table is very well-clustered; depth near 4–5 is the optimal target range',
      'The table is poorly clustered — an average_depth of 4.5 means each micro-partition value range overlaps with 4.5 other partitions on average, making pruning ineffective. Reclustering would improve query performance.',
      'The table has too many micro-partitions and should be compacted using RECLUSTER',
      'The clustering key should be removed; these numbers indicate the key is adding overhead',
    ],
    answer: 'The table is poorly clustered — an average_depth of 4.5 means each micro-partition value range overlaps with 4.5 other partitions on average, making pruning ineffective. Reclustering would improve query performance.',
    exp: 'average_depth measures how many micro-partitions a given column value appears in on average. Ideal is 1.0 (each value in exactly one partition — perfect pruning). A depth of 4.5 means the query optimizer must scan 4.5× more partitions than necessary for a given filter value. average_overlap shows how many partitions share the same value range. High values for both indicate poor clustering that would benefit from enabling or adjusting the automatic clustering key.',
  },
  {
    id: 'd4_d8_10',
    domain: 4,
    topic: 'Search Optimization Service',
    difficulty: 'medium',
    q: 'When is the Search Optimization Service MOST appropriate to add to a table?',
    options: [
      'For queries that join two large tables — SOS accelerates join operations',
      'For full table scans with GROUP BY aggregations — SOS speeds up analytical aggregations',
      'For queries that always use the existing clustering key in the WHERE clause — SOS adds value on top of clustering',
      'For point lookup queries (equality and IN predicate lookups) on high-cardinality columns where clustering cannot help — SOS builds a specialized search access path for these patterns',
    ],
    answer: 'For point lookup queries (equality and IN predicate lookups) on high-cardinality columns where clustering cannot help — SOS builds a specialized search access path for these patterns',
    exp: 'Search Optimization Service creates a persistent search access path (extra storage) optimized for: equality predicates (WHERE id = \'X\'), IN lists (WHERE id IN (\'X\',\'Y\')), SUBSTRING predicates (LIKE \'%term%\', CONTAINS), and geospatial lookups. It is NOT useful for range scans (use clustering), aggregations (use MVs or clustering), or joins. It is most valuable when you have ad-hoc lookups on columns like user_id, email, or UUIDs with no clustering benefit.',
  },
  {
    id: 'd4_d8_11',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A VARIANT column data contains {"customer":{"address":{"city":"Denver"}}}. Which expression(s) correctly extract the city value as a VARCHAR in Snowflake SQL?',
    options: [
      'Only data.customer.address.city — dot notation is the standard VARIANT path syntax in Snowflake',
      'Only JSON_EXTRACT(data, \'$.customer.address.city\') — the standard ANSI JSON extraction function',
      'Both colon-path notation (data:customer:address:city::VARCHAR) and bracket notation (data[\'customer\'][\'address\'][\'city\']::VARCHAR) are valid — Snowflake supports both syntaxes for nested VARIANT access',
      'data::"customer"::"address"::"city" — double-colon quoting is required for nested paths',
    ],
    answer: 'Both colon-path notation (data:customer:address:city::VARCHAR) and bracket notation (data[\'customer\'][\'address\'][\'city\']::VARCHAR) are valid — Snowflake supports both syntaxes for nested VARIANT access',
    exp: 'Snowflake supports two VARIANT path syntaxes: (1) colon notation (data:key1:key2::type) — concise and idiomatic Snowflake; (2) bracket notation with string keys (data[\'key1\'][\'key2\']::type) — familiar to JavaScript/Python developers. Both produce identical results. The ::VARCHAR cast converts the VARIANT result to a SQL string. Note: JSON_EXTRACT is NOT a Snowflake function. Dot notation is for SQL column names, not VARIANT paths.',
  },
  {
    id: 'd4_d8_12',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'easy',
    q: 'What is the primary purpose of the FLATTEN table function in Snowflake?',
    options: [
      'To compress semi-structured VARIANT data for more efficient storage',
      'To merge multiple VARIANT rows into a single consolidated JSON object',
      'To convert VARIANT data into a permanently flattened relational table (like a DDL transformation)',
      'To explode (unnest) arrays or objects within semi-structured VARIANT data into separate rows, enabling lateral joins with relational data',
    ],
    answer: 'To explode (unnest) arrays or objects within semi-structured VARIANT data into separate rows, enabling lateral joins with relational data',
    exp: 'FLATTEN is a Snowflake table function used with LATERAL: SELECT f.value FROM my_table, LATERAL FLATTEN(INPUT => json_col:items) f. It takes an ARRAY or OBJECT and returns one row per element, producing columns: SEQ, KEY, PATH, INDEX, VALUE, THIS. It is the standard way to "unpack" nested JSON arrays into relational rows. It does not modify storage — it is a runtime transformation at query time.',
  },
  {
    id: 'd4_d8_13',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A VARIANT column status is frequently filtered with data:status::VARCHAR = \'ACTIVE\'. The query is slow due to full scans. Which approach(es) can improve performance?',
    options: [
      'Nothing can be done — VARIANT column predicates fundamentally cannot be optimized in Snowflake',
      'Either (a) define a virtual computed column using an expression over the VARIANT path and cluster the table by that expression, OR (b) add Search Optimization Service — both are valid methods to accelerate VARIANT predicate lookups',
      'Cast the entire VARIANT column to VARCHAR using ALTER TABLE ... ALTER COLUMN',
      'Only full-text indexing can accelerate VARIANT column filtering',
    ],
    answer: 'Either (a) define a virtual computed column using an expression over the VARIANT path and cluster the table by that expression, OR (b) add Search Optimization Service — both are valid methods to accelerate VARIANT predicate lookups',
    exp: 'Two approaches: (1) Clustering on a VARIANT expression: CLUSTER BY (data:status::VARCHAR) — Snowflake allows clustering expressions including VARIANT paths. New inserts are clustered by this virtual value, enabling partition pruning. (2) Search Optimization Service — supports equality predicates on VARIANT paths, building a search access path. For high-cardinality string columns, SOS is especially effective. A third option is extracting the column into a regular VARCHAR column if schema allows.',
  },
  {
    id: 'd4_d8_14',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'easy',
    q: 'A developer needs to store arbitrary JSON, Avro schema objects, or Parquet row data in a single flexible column. Which Snowflake data type is designed for this purpose?',
    options: [
      'OBJECT — stores fixed-schema key-value pairs with defined key types',
      'ARRAY — stores ordered lists of same-type values',
      'VARIANT — a flexible type that stores any semi-structured value (JSON, XML, arrays, objects, scalar) up to 16 MB',
      'STRING — store serialized JSON as plain text and parse at query time',
    ],
    answer: 'VARIANT — a flexible type that stores any semi-structured value (JSON, XML, arrays, objects, scalar) up to 16 MB',
    exp: 'VARIANT is Snowflake\'s universal semi-structured type. It can hold JSON objects, arrays, scalars, BOOLEAN, null — up to 16 MB per value. OBJECT and ARRAY are subtypes of VARIANT (created with OBJECT_CONSTRUCT and ARRAY_CONSTRUCT respectively, or inferred during parse). For loading arbitrary JSON documents where the schema varies per row, VARIANT is the correct choice. STRING could store JSON text but loses all native path access (colons/brackets, FLATTEN, PARSE_JSON operators).',
  },
  {
    id: 'd4_d8_15',
    domain: 4,
    topic: 'SQL Transformations',
    difficulty: 'medium',
    q: 'A developer writes a recursive CTE to traverse a deep employee hierarchy table. Snowflake returns an error about hitting the maximum recursion depth. What should they investigate?',
    options: [
      'Recursive CTEs are not supported in Snowflake — use a stored procedure with a WHILE loop instead',
      'The base table exceeds the maximum size for CTE processing — use a temporary table instead',
      'Recursive CTEs require a RECURSIVE keyword that the developer may have omitted from the WITH clause',
      'The hierarchy data may contain a cycle (A → B → C → A) causing infinite recursion; add a cycle-detection condition or LIMIT clause, and verify the data does not have circular references',
    ],
    answer: 'The hierarchy data may contain a cycle (A → B → C → A) causing infinite recursion; add a cycle-detection condition or LIMIT clause, and verify the data does not have circular references',
    exp: 'Snowflake DOES support recursive CTEs (WITH RECURSIVE ... UNION ALL). The maximum depth is configurable but finite. Two common issues: (1) Data cycles — circular foreign key references cause infinite recursion; detect with a path-tracking array or depth counter. (2) Runaway recursion — add AND depth < 100 or similar guard. Recursive CTEs in Snowflake require the RECURSIVE keyword and a UNION ALL between the anchor and recursive members.',
  },
  {
    id: 'd4_d8_16',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A query uses LATERAL FLATTEN on a VARIANT array column. Some rows have NULL as their array value. What is the default behavior for those NULL-array rows?',
    options: [
      'Rows with NULL array values are excluded from the FLATTEN output — OUTER = FALSE (default) skips NULLs',
      'Rows with NULL arrays produce a single output row with NULL for all FLATTEN columns',
      'FLATTEN raises an error when it encounters a NULL input value',
      'NULL arrays are treated identically to empty arrays, producing zero output rows but not excluded',
    ],
    answer: 'Rows with NULL array values are excluded from the FLATTEN output — OUTER = FALSE (default) skips NULLs',
    exp: 'FLATTEN by default uses OUTER = FALSE, which means rows where the INPUT expression is NULL produce no output rows — they are silently dropped from the result. To preserve the source rows even when the array is NULL (like a LEFT JOIN), use LATERAL FLATTEN(INPUT => ..., OUTER => TRUE). With OUTER = TRUE, NULL arrays generate a single output row with NULL for VALUE, KEY, PATH, etc. This is an important distinction for data completeness in ETL pipelines.',
  },
  {
    id: 'd4_d8_17',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A developer needs to aggregate multiple rows per group into a single VARIANT value — sometimes as a key-value map, sometimes as an ordered list. Which function(s) can achieve this?',
    options: [
      'Only PARSE_JSON() combined with LISTAGG() — the standard approach for JSON aggregation',
      'Both OBJECT_AGG(key_col, value_col) and ARRAY_AGG(value_col) — OBJECT_AGG produces a VARIANT OBJECT (key→value map) per group; ARRAY_AGG produces a VARIANT ARRAY (ordered list) per group. The right choice depends on the desired output structure.',
      'Only TO_VARIANT() — Snowflake\'s dedicated row-to-VARIANT aggregation function',
      'Only COLLECT_SET() — Snowflake\'s distinct-value aggregation function for VARIANT types',
    ],
    answer: 'Both OBJECT_AGG(key_col, value_col) and ARRAY_AGG(value_col) — OBJECT_AGG produces a VARIANT OBJECT (key→value map) per group; ARRAY_AGG produces a VARIANT ARRAY (ordered list) per group. The right choice depends on the desired output structure.',
    exp: 'OBJECT_AGG(key_col, value_col) creates {key1: val1, key2: val2} per group — ideal when each row contributes a named key. ARRAY_AGG(value_col) creates [val1, val2, val3] per group — ideal when you want an ordered list. Both return VARIANT. COLLECT_SET is a Spark/Hive function, not Snowflake. TO_VARIANT() converts a single scalar to VARIANT — not an aggregation. LISTAGG returns a STRING, not VARIANT.',
  },

  // ── DOMAIN 5: Data Collaboration (9 questions) ────────────────────────────

  {
    id: 'd5_d8_01',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'easy',
    q: 'A data provider wants to share data with a partner company that does NOT have a Snowflake account. Which Snowflake feature should the provider use?',
    options: [
      'Standard Direct Share — available to all Snowflake accounts without any account requirement',
      'Snowflake Marketplace private listing — the partner can access it through a web portal without an account',
      'A Reader Account provisioned and managed by the provider — gives the partner a Snowflake login, paid for by the provider',
      'Database replication to the partner\'s cloud region — replicates data into a separate account',
    ],
    answer: 'A Reader Account provisioned and managed by the provider — gives the partner a Snowflake login, paid for by the provider',
    exp: 'Reader Accounts are lightweight Snowflake accounts that providers create and manage for consumers who don\'t have (or don\'t want) their own Snowflake accounts. The provider controls the Reader Account, creates users, and pays for all compute. The consumer gets a login to query shared data. Direct Share and Marketplace listings require the consumer to have their own Snowflake account. For no-account consumers, Reader Account is the answer.',
  },
  {
    id: 'd5_d8_02',
    domain: 5,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'easy',
    q: 'A permanent table with DATA_RETENTION_TIME_IN_DAYS = 7 was accidentally dropped 5 days ago. Which command recovers it?',
    options: [
      'UNDROP TABLE my_table — restores the table and its data from Time Travel history within the retention window',
      'UNDELETE TABLE my_table — Snowflake\'s rollback command for accidentally dropped tables',
      'The table cannot be recovered — once a table is dropped it is permanently gone',
      'RESTORE TABLE my_table FROM BACKUP — triggers a Fail-safe restore via Snowflake Support',
    ],
    answer: 'UNDROP TABLE my_table — restores the table and its data from Time Travel history within the retention window',
    exp: 'UNDROP TABLE is the Time Travel recovery mechanism for dropped objects. Since the table\'s DATA_RETENTION_TIME_IN_DAYS = 7 and only 5 days have passed, the Time Travel history is still available. UNDROP also works for schemas (UNDROP SCHEMA) and databases (UNDROP DATABASE). After the retention period expires, recovery requires Fail-safe via Snowflake Support. UNDELETE and RESTORE are not valid Snowflake commands.',
  },
  {
    id: 'd5_d8_03',
    domain: 5,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'medium',
    q: 'A company needs to set DATA_RETENTION_TIME_IN_DAYS = 90 on a critical audit table. What is the MINIMUM Snowflake edition that allows this setting?',
    options: [
      'Standard — Standard edition supports up to 90 days for all table types',
      'Business Critical — 90-day retention requires the highest security tier',
      'Virtual Private Snowflake — maximum Time Travel requires fully isolated infrastructure',
      'Enterprise — 90-day Time Travel retention is an Enterprise-edition feature; Standard is capped at 1 day',
    ],
    answer: 'Enterprise — 90-day Time Travel retention is an Enterprise-edition feature; Standard is capped at 1 day',
    exp: 'Standard edition supports up to 1 day of Time Travel retention for all permanent tables. Enterprise edition unlocks up to 90 days. Time Travel storage costs scale with retention — keeping 90 days of change history on a large, frequently modified table can be significant. Configure retention at the table or schema level to balance recovery capability vs. storage cost. Transient tables are always capped at 1 day regardless of edition.',
  },
  {
    id: 'd5_d8_04',
    domain: 5,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'easy',
    q: 'What is the Fail-safe period for a permanent table in Snowflake, and can a customer query data directly during this period?',
    options: [
      '30 days — customers can query Fail-safe data using a special FAILSAFE() Time Travel modifier',
      'Fail-safe exists only on Business Critical edition — Standard tables have no Fail-safe',
      'No Fail-safe exists for permanent tables — only temporary tables have a Fail-safe extension period',
      '7 days — no customer SQL access is possible during Fail-safe; only Snowflake Support can attempt data recovery upon a formal request',
    ],
    answer: '7 days — no customer SQL access is possible during Fail-safe; only Snowflake Support can attempt data recovery upon a formal request',
    exp: 'Fail-safe is Snowflake\'s last-resort disaster recovery backstop. After Time Travel expires, permanent table data enters a 7-day Fail-safe window. During this period, there is NO SQL command, API, or UI that lets customers access the data — it is exclusively recoverable by Snowflake Support and only for qualifying catastrophic data loss scenarios. Transient tables have 0 days of Fail-safe. Temporary tables have 0 days of Fail-safe.',
  },
  {
    id: 'd5_d8_05',
    domain: 5,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'medium',
    q: 'A team converts a permanent production table to transient using CREATE OR REPLACE TRANSIENT TABLE prod AS SELECT * FROM prod_orig. How does this affect data protection?',
    options: [
      'No effect — Fail-safe and Time Travel settings are preserved from the original permanent table',
      'The new transient table has the same Time Travel retention as prod_orig but loses the 7-day Fail-safe',
      'Transient tables have NO Fail-safe period (0 days) and Time Travel is limited to a maximum of 1 day — significantly reducing recovery options compared to a permanent table',
      'Transient tables have a 1-day Fail-safe period on Business Critical edition only',
    ],
    answer: 'Transient tables have NO Fail-safe period (0 days) and Time Travel is limited to a maximum of 1 day — significantly reducing recovery options compared to a permanent table',
    exp: 'Transient tables trade data protection for reduced storage cost. They have: (1) 0 days Fail-safe — no emergency recovery backstop. (2) Max 1 day Time Travel. (3) Lower storage cost because Snowflake doesn\'t need to retain historical versions as long. Use transient tables for truly ephemeral data: staging tables, intermediate ETL results, scratch data. Never use transient for production fact tables or data that requires recovery beyond 1 day.',
  },
  {
    id: 'd5_d8_06',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'hard',
    q: 'A provider shares a complex SECURE VIEW. The consumer reports poor query performance and the Query Profile shows no explicit partition pruning information. What is the MOST likely explanation?',
    options: [
      'Sharing always disables partition pruning — shared objects cannot use micro-partition metadata',
      'The consumer\'s warehouse is undersized for queries against shared data',
      'The consumer needs to cluster the shared table on their side to enable pruning',
      'Secure views intentionally hide their query definition and optimizer details from the consumer\'s Query Profile — the optimizer may still perform internal pruning, but the profile does not expose it to protect the provider\'s schema',
    ],
    answer: 'Secure views intentionally hide their query definition and optimizer details from the consumer\'s Query Profile — the optimizer may still perform internal pruning, but the profile does not expose it to protect the provider\'s schema',
    exp: 'Secure views (CREATE SECURE VIEW) protect the underlying SQL definition from being visible to unauthorized roles, including in Query Profile details. This means consumers cannot see which tables are joined, what columns exist, or what filter pushdowns are applied. The optimizer can still prune micro-partitions internally — but the consumer\'s profile won\'t show it. This is by design, not a bug. If performance is truly poor (not just hidden info), the provider should optimize the underlying view or add clustering.',
  },
  {
    id: 'd5_d8_07',
    domain: 5,
    topic: 'Replication',
    difficulty: 'medium',
    q: 'An organization has accounts in AWS us-east-1 and Azure westeurope. They need a table synchronized across both accounts in near real-time. Which feature should they use?',
    options: [
      'Database Replication with Replication/Failover Groups — designed to synchronize databases across Snowflake accounts in different regions and cloud providers',
      'Direct Share — shares data read-only to other accounts without copying it',
      'External Tables in both regions pointing to the same cross-cloud shared storage bucket',
      'Snowpipe configured in both regions to independently ingest from a shared S3 bucket',
    ],
    answer: 'Database Replication with Replication/Failover Groups — designed to synchronize databases across Snowflake accounts in different regions and cloud providers',
    exp: 'Database Replication (and Failover Groups for DR scenarios) enables synchronizing databases across different Snowflake accounts — including cross-cloud (AWS to Azure). You define a primary account and one or more secondary accounts; Snowflake handles the replication asynchronously with configurable RPO. Direct Share is read-only with zero-copy (no physical copy to the consumer). External Tables can share cloud storage within a cloud provider but not cross-cloud natively.',
  },
  {
    id: 'd5_d8_08',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'hard',
    q: 'A consumer on a Reader Account wants to create their own analysis tables to join with shared provider data. Is this possible?',
    options: [
      'No — Reader Accounts are query-only environments; no objects can be created by consumers',
      'Yes — consumers in a Reader Account can create temporary tables within sessions using a warehouse provisioned in the Reader Account, but permanent table creation depends on the grants the provider has configured',
      'Yes — but only if the provider explicitly upgrades the Reader Account to a full Snowflake account',
      'No — Reader Account users cannot execute any DDL; only SELECT statements are permitted',
    ],
    answer: 'Yes — consumers in a Reader Account can create temporary tables within sessions using a warehouse provisioned in the Reader Account, but permanent table creation depends on the grants the provider has configured',
    exp: 'Reader Accounts are stripped-down Snowflake accounts managed by the provider. By default, they provide query access to shared data. The provider can grant additional privileges — including CREATE TABLE rights on a non-shared database — allowing consumers to create their own objects for analysis. Temporary tables are generally available for session-scoped work. The provider pays for all compute in a Reader Account. For heavy analytical workloads, upgrading to a full account is usually recommended.',
  },
  {
    id: 'd5_d8_09',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'easy',
    q: 'A provider adds a new table to an existing Secure Share. The consumer previously created a database from this share. What does the consumer need to do to access the new table?',
    options: [
      'Re-execute CREATE DATABASE FROM SHARE to get a fresh copy with the new table',
      'Run ALTER DATABASE ... REFRESH to pull the latest share definition',
      'Nothing — the new table is automatically visible to the consumer in the already-created database. Secure Share databases are live pointers to the provider\'s objects.',
      'Contact Snowflake Support to refresh the share metadata on the consumer side',
    ],
    answer: 'Nothing — the new table is automatically visible to the consumer in the already-created database. Secure Share databases are live pointers to the provider\'s objects.',
    exp: 'This is a key benefit of Snowflake\'s zero-copy sharing model. The consumer\'s database is a live metadata pointer to the provider\'s objects — not a physical copy. When the provider adds a table to the share, the consumer sees it immediately in their shared database without any action required. Conversely, if the provider removes an object from the share, it disappears from the consumer\'s view instantly.',
  },
];
