// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 4  (2026-03-23)
// COF-C03 Mock Exam · 60 questions
// Distribution: D1 31% (19q) | D2 20% (12q) | D3 18% (11q) | D4 21% (13q) | D5 10% (5q)
// Difficulty mix: ~30% Easy, ~50% Medium, ~20% Hard
//
// DAILY GENERATION RULE:
//   Each new day of questions must share ≤ 30% overlap with the previous day.
//   Before writing a new day, list the question IDs from the previous file and
//   ensure fewer than 18 of the 60 questions are repeated verbatim.
//   Rotate topics, scenarios, and SQL examples each day.
//
// DAY 4 vs DAY 3 OVERLAP CHECK:
//   Day 3 covered: cloud platforms, Horizon Catalog interoperability/business-continuity,
//   Standard edition, Git Integration, Snow CLI vs SnowSQL, Sequences, UDF as schema object,
//   AUTO_SUSPEND/RESUME behavior, STATEMENT_TIMEOUT, Temp vs Transient table, expression
//   clustering key, MV auto-refresh description, SiS, Cortex COMPLETE, org-based account
//   identifiers, JDBC/ODBC, Cortex Guard, VWH USAGE privilege, USERADMIN, PUBLIC role,
//   ORGADMIN, session policies, network policy blocked-wins, masking policy DDL CASE,
//   ALLOWED_VALUES tag, annual key rotation, Failover vs Replication Group, ACCESS_HISTORY,
//   GOVERNANCE_VIEWER, INFORMATION_SCHEMA vs ACCOUNT_USAGE, LIST stage, VALIDATION_MODE
//   dry-run, COPY INTO column mapping, FORCE=TRUE, Snowpipe Streaming rows vs files, stream
//   staleness, serverless task billing, STRIP_OUTER_ARRAY, stream on view insert-only,
//   ON_ERROR=CONTINUE, metadata cache/SHOW commands, partition scanned ratio, result cache +
//   Row Access Policy nuance, SUSPEND RECLUSTER, Secure MV for sharing, ALTER TABLE ADD SEARCH
//   OPTIMIZATION, OBJECT_CONSTRUCT, QUALIFY, MERGE non-deterministic, resize for spill,
//   COPY GRANTS, Aggregate query profile node, Snowpark lazy collect(), UNDROP TT expired,
//   CREATE SHARE DDL, Reader Account, clone AT timestamp, Marketplace zero-copy.
//
//   Day 4 fresh angles (~0 verbatim repeats): Apache Iceberg tables (Snowflake-managed vs
//   external catalog), multi-cluster shared data concept, Business Critical (PrivateLink,
//   PHI), VPS differentiator, SQL API, Terraform Provider, external tables refresh,
//   Snowpark-optimized warehouse, OPERATE privilege, MAXIMIZED multi-cluster mode, 90-day TT
//   Enterprise, micro-partition AES-256, Document AI, Cortex Analyst, Snowflake Notebooks,
//   account-level objects, MODIFY privilege, 60-second billing minimum, Secure view for
//   sharing, DAC definition, GRANT OWNERSHIP, OAuth 2.0, key-pair service accounts,
//   SECURITYADMIN, Aggregation Policy, GET_LINEAGE, Resource Monitor SUSPEND_IMMEDIATE,
//   QUERY_HISTORY, COPY_HISTORY, Trust Center CIS, Tri-Secret Secure, user stage limits,
//   Storage Integration, COPY INTO unload, Snowpipe AUTO_INGEST SQS, Dynamic Tables,
//   Kafka Connector, External Functions, SnowCD, PURGE option, Parquet native, REMOVE command,
//   local SSD cache eviction, result cache DML invalidation, broadcast joins, compound
//   clustering key, MV vs result cache difference, Search Opt billing components, FLATTEN,
//   tabular UDF (UDTF), SP EXECUTE AS, Dynamic Table INITIALIZE, Snowpark groupBy/agg,
//   Exchange node Query Profile, GROUPING SETS, UNDROP DATABASE, Fail-safe storage cost,
//   database-level clone, database roles in sharing, Private Data Exchange.
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 4,
  date: '2026-03-23',
  label: 'Day 4 — Deep Dives',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (19 questions) ─────────────────────

  {
    id: 'd1_d4_01',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'What fundamentally differentiates Snowflake\'s multi-cluster shared data architecture from a traditional shared-disk MPP database?',
    options: [
      'Snowflake stores data in a shared disk layer and all compute nodes write to it simultaneously',
      'Snowflake separates storage (cloud object store) from compute (virtual warehouses) — multiple independent compute clusters can read the same storage without contention',
      'Snowflake uses shared memory across all virtual warehouses to reduce storage costs',
      'Snowflake requires all warehouses to be the same size to enable shared data access',
    ],
    answer: 'Snowflake separates storage (cloud object store) from compute (virtual warehouses) — multiple independent compute clusters can read the same storage without contention',
    exp: 'Snowflake\'s architecture stores data in cloud object storage (S3/GCS/Blob) decoupled from compute. Many virtual warehouses can query the same data simultaneously — each warehouse has its own compute, so they don\'t contend for resources.',
  },
  {
    id: 'd1_d4_02',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'A company needs Snowflake to store data that is classified as Protected Health Information (PHI) under HIPAA. Which Snowflake edition is required as a MINIMUM?',
    options: ['Standard', 'Enterprise', 'Business Critical', 'Virtual Private Snowflake'],
    answer: 'Business Critical',
    exp: 'Business Critical edition provides the compliance certifications and security features required for PHI/HIPAA: customer-managed key support (Tri-Secret Secure), end-to-end encryption, BAA agreements, HITRUST, FedRAMP Ready, and PrivateLink connectivity.',
  },
  {
    id: 'd1_d4_03',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'hard',
    q: 'What is the key differentiator of Virtual Private Snowflake (VPS) compared to Business Critical edition?',
    options: [
      'VPS supports larger warehouse sizes (up to 6XL)',
      'VPS provides completely dedicated, isolated infrastructure — including a separate Cloud Services layer not shared with other Snowflake customers',
      'VPS adds support for a fourth cloud provider not available in Business Critical',
      'VPS eliminates the 60-second billing minimum for virtual warehouses',
    ],
    answer: 'VPS provides completely dedicated, isolated infrastructure — including a separate Cloud Services layer not shared with other Snowflake customers',
    exp: 'VPS is the highest tier — dedicated hardware for ALL layers including Cloud Services (metadata, optimizer). All other editions share Snowflake\'s multi-tenant Cloud Services layer. VPS eliminates any potential cross-customer metadata co-location.',
  },
  {
    id: 'd1_d4_04',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'The Snowflake SQL API allows external applications to submit SQL statements and retrieve results. Which authentication method is REQUIRED (not optional) for the SQL API?',
    options: [
      'Username and password only',
      'OAuth token or key-pair JWT — username/password is not supported',
      'SAML 2.0 SSO token',
      'IP allowlisting replaces authentication for the SQL API',
    ],
    answer: 'OAuth token or key-pair JWT — username/password is not supported',
    exp: 'The Snowflake SQL API requires OAuth 2.0 access tokens or key-pair JWT tokens for authentication. Username/password is NOT supported. This enforces secure, token-based auth for API integrations.',
  },
  {
    id: 'd1_d4_05',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'A DevOps team uses Terraform to manage Snowflake alongside AWS infrastructure (S3 buckets, IAM roles). What does the Snowflake Terraform Provider enable?',
    options: [
      'It deploys Snowflake query compute nodes inside AWS VPCs',
      'It allows Snowflake databases, warehouses, roles, grants, and integrations to be declared in HCL and managed alongside cloud infrastructure as code',
      'It automatically generates Snowflake schemas from AWS Glue catalogs',
      'It synchronizes IAM policies to Snowflake network policies',
    ],
    answer: 'It allows Snowflake databases, warehouses, roles, grants, and integrations to be declared in HCL and managed alongside cloud infrastructure as code',
    exp: 'The Snowflake Terraform Provider exposes Snowflake resources (warehouses, databases, roles, grants, integrations, network policies) as Terraform resources in HCL. Enables GitOps: plan/apply Snowflake config changes through CI/CD pipelines.',
  },
  {
    id: 'd1_d4_06',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'hard',
    q: 'What is a Snowflake External Table, and what is a key performance limitation compared to native Snowflake tables?',
    options: [
      'An External Table is a read-only object querying data in cloud object storage. It lacks partition pruning metadata cache and is generally slower than native tables.',
      'An External Table stores data outside Snowflake but supports full DML operations',
      'An External Table is the same as an External Stage — both just reference S3 paths',
      'External Tables support all micro-partition metadata features automatically',
    ],
    answer: 'An External Table is a read-only object querying data in cloud object storage. It lacks partition pruning metadata cache and is generally slower than native tables.',
    exp: 'External Tables reference files in an external stage (S3/GCS/Blob). They are read-only and must be refreshed (ALTER TABLE … REFRESH) to update the file list. Without native micro-partition pruning metadata, query performance is lower than native tables.',
  },
  {
    id: 'd1_d4_07',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A data scientist runs large ML training jobs in Python via Snowpark. Snowflake recommends using a Snowpark-optimized warehouse instead of a standard warehouse. What is the key difference?',
    options: [
      'Snowpark-optimized warehouses run on GPU hardware',
      'Snowpark-optimized warehouses have more memory per compute node (16× more than standard) for memory-intensive ML workloads',
      'Snowpark-optimized warehouses are 10× cheaper than standard warehouses',
      'Snowpark-optimized warehouses automatically scale from XS to 4XL based on ML job size',
    ],
    answer: 'Snowpark-optimized warehouses have more memory per compute node (16× more than standard) for memory-intensive ML workloads',
    exp: 'Snowpark-optimized warehouses provide significantly larger per-node memory (16× more than standard M size) and 10× local SSD cache. Ideal for memory-intensive Python/ML workloads using Snowpark, pandas on Snowflake, or ML training functions.',
  },
  {
    id: 'd1_d4_08',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'easy',
    q: 'Which warehouse privilege allows a role to suspend and resume a virtual warehouse — but NOT to resize it or change its properties?',
    options: ['USAGE', 'MODIFY', 'OPERATE', 'MONITOR'],
    answer: 'OPERATE',
    exp: 'OPERATE on a warehouse allows the role to suspend and resume it (ALTER WAREHOUSE … SUSPEND/RESUME) and also abort queries. MODIFY allows resizing and changing warehouse parameters. USAGE only allows running queries on it.',
  },
  {
    id: 'd1_d4_09',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A multi-cluster warehouse is set to MAX_CLUSTER_COUNT = 4, MIN_CLUSTER_COUNT = 4. What mode is this, and what is the behavior?',
    options: [
      'Auto-scale mode — additional clusters start as needed up to 4',
      'Maximized mode — all 4 clusters are always running, regardless of load',
      'Reserved mode — credits are pre-purchased for 4 clusters',
      'Economy mode — clusters are shared with other warehouses in the account',
    ],
    answer: 'Maximized mode — all 4 clusters are always running, regardless of load',
    exp: 'When MAX = MIN, the warehouse runs in Maximized mode: all clusters start immediately when the warehouse is resumed and stay running until the warehouse is suspended. No auto-scaling. Best for predictably high, steady concurrency.',
  },
  {
    id: 'd1_d4_10',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'easy',
    q: 'A virtual warehouse runs a 45-second query, then immediately runs another 20-second query. AUTO_SUSPEND = 300. What is the TOTAL credits billed for this session (warehouse size = XS = 1 credit/hour)?',
    options: [
      '65 seconds worth of credits (45 + 20)',
      '120 seconds worth of credits (two 60-second minimums)',
      '300 + 65 seconds worth of credits',
      '60 seconds worth of credits (single 60-second minimum for the whole session)',
    ],
    answer: '65 seconds worth of credits (45 + 20)',
    exp: 'With AUTO_SUSPEND = 300, the warehouse stays running between the two consecutive queries (it won\'t suspend after only 45 seconds). This is ONE continuous billing period of 65 seconds — already above the 60-second minimum, so 65 seconds of actual runtime is billed. Two minimums only apply if the warehouse suspends and RESTARTS between queries.',
  },
  {
    id: 'd1_d4_11',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'What is the maximum Time Travel data retention period for a permanent table on Enterprise edition?',
    options: ['1 day', '7 days', '30 days', '90 days'],
    answer: '90 days',
    exp: 'Enterprise edition supports DATA_RETENTION_TIME_IN_DAYS from 0 to 90 for permanent tables. Standard edition supports 0–1 day only. Transient and Temporary tables max out at 1 day on any edition. The default is typically 1 day.',
  },
  {
    id: 'd1_d4_12',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'Snowflake micro-partitions are stored in what format and protected by what encryption algorithm at rest?',
    options: [
      'Row-based format, RSA-2048 encryption',
      'Columnar compressed format, AES-256 encryption',
      'Columnar uncompressed format, TLS 1.2 encryption',
      'Parquet file format, AES-128 encryption',
    ],
    answer: 'Columnar compressed format, AES-256 encryption',
    exp: 'Micro-partitions store data columnar (like Parquet) with per-column compression. They are automatically encrypted at rest using AES-256 by Snowflake\'s hierarchical key management. In transit, data is protected by TLS 1.2+.',
  },
  {
    id: 'd1_d4_13',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'A business user wants to ask questions like "What were the top 10 customers by revenue last quarter?" in plain English and get a SQL query and results back. Which Snowflake Cortex feature is designed for this?',
    options: [
      'Cortex Search',
      'Cortex Complete',
      'Cortex Analyst',
      'Snowflake Notebooks',
    ],
    answer: 'Cortex Analyst',
    exp: 'Cortex Analyst translates natural language questions into SQL queries against structured (tabular) data, executes them, and returns results. It uses semantic metadata about tables and columns to generate accurate SQL — no SQL knowledge required from the user.',
  },
  {
    id: 'd1_d4_14',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'What is Snowflake Document AI used for?',
    options: [
      'Generating SQL documentation from stored procedures automatically',
      'Extracting structured information from unstructured documents (PDFs, images) using a fine-tuned LLM',
      'Translating Snowflake DDL into human-readable documentation',
      'Converting Snowflake schemas to OpenAPI specifications',
    ],
    answer: 'Extracting structured information from unstructured documents (PDFs, images) using a fine-tuned LLM',
    exp: 'Document AI processes unstructured documents (PDFs, invoices, contracts) and extracts structured fields using a fine-tuned LLM via a BUILD_SCOPED_FILE_URL + SNOWFLAKE.CORTEX.TRY_COMPLETE workflow. The results are stored in Snowflake tables.',
  },
  {
    id: 'd1_d4_15',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'easy',
    q: 'What are Snowflake Notebooks, and where do they run?',
    options: [
      'External Jupyter notebooks connected to Snowflake via JDBC',
      'Interactive Python/SQL development environments that run directly inside Snowflake, with access to Snowflake data and Snowpark',
      'A markdown documentation tool for Snowflake stored procedures',
      'External VS Code notebooks connected to Snowflake via the VS Code Extension',
    ],
    answer: 'Interactive Python/SQL development environments that run directly inside Snowflake, with access to Snowflake data and Snowpark',
    exp: 'Snowflake Notebooks are cell-based development environments (Python, SQL, Markdown) hosted inside Snowflake. They run on a compute pool or virtual warehouse and have direct access to Snowflake data and Snowpark — no external Jupyter server needed.',
  },
  {
    id: 'd1_d4_16',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'easy',
    q: 'Which of the following is an ACCOUNT-LEVEL object in Snowflake (not scoped to a database or schema)?',
    options: [
      'Table, View, Stage',
      'Virtual Warehouse, Resource Monitor, User, Role, Integration',
      'Stream, Task, Sequence, Pipe',
      'UDF, Stored Procedure, File Format',
    ],
    answer: 'Virtual Warehouse, Resource Monitor, User, Role, Integration',
    exp: 'Account-level objects exist at the account level, outside any database: Virtual Warehouses, Resource Monitors, Users, Roles, Integrations (storage, notification, API, security), Network Policies, and Share objects. Database, Schema, Table, View, etc. are database or schema objects.',
  },
  {
    id: 'd1_d4_17',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'Which warehouse privilege allows a role to change the size of the warehouse (e.g., resize from Medium to Large)?',
    options: ['USAGE', 'OPERATE', 'MONITOR', 'MODIFY'],
    answer: 'MODIFY',
    exp: 'MODIFY on a warehouse allows ALTER WAREHOUSE commands that change warehouse properties: size, auto-suspend, auto-resume, max/min cluster count. OPERATE allows suspend/resume. USAGE allows running queries.',
  },
  {
    id: 'd1_d4_18',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'What is a Snowflake Apache Iceberg table (Snowflake-managed), and how does it differ from a standard Snowflake table?',
    options: [
      'An Iceberg table stores data inside Snowflake micro-partitions but exports Parquet files for external access — uses open Iceberg metadata format for interoperability',
      'An Iceberg table is identical to a standard Snowflake table but stored on a separate cold storage tier',
      'An Iceberg table has no Time Travel support but supports full DML',
      'An Iceberg table requires Enterprise edition and stores data exclusively in S3',
    ],
    answer: 'An Iceberg table stores data inside Snowflake micro-partitions but exports Parquet files for external access — uses open Iceberg metadata format for interoperability',
    exp: 'A Snowflake-managed Iceberg table uses the open Apache Iceberg table format (Parquet files + Iceberg metadata in your object store). This enables other engines (Spark, Trino) to read the same data. It supports DML, Time Travel, and governance just like native tables.',
  },
  {
    id: 'd1_d4_19',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'hard',
    q: 'Which of these view types hides the SQL definition from users who query SHOW VIEWS or GET_DDL(), and is REQUIRED when including the view in a Data Share?',
    options: ['Standard view', 'Materialized view', 'Secure view', 'External view'],
    answer: 'Secure view',
    exp: 'Secure views hide the view definition from non-owner users (SHOW VIEWS shows no DDL, GET_DDL() returns redacted output). Secure views are REQUIRED to add a view to a Data Share — prevents consumers from inferring provider data structure. Both standard and materialized views have a SECURE variant.',
  },

  // ── DOMAIN 2: Account Management & Governance (12 questions) ─────────────

  {
    id: 'd2_d4_01',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'What is Discretionary Access Control (DAC) in Snowflake, and how does it complement RBAC?',
    options: [
      'DAC is a Snowflake-specific term for multi-cluster access control — separate from role-based access',
      'DAC allows object owners to grant privileges on their objects to other roles at their own discretion, complementing the top-down RBAC role hierarchy',
      'DAC means only ACCOUNTADMIN can grant privileges — all other grants are discretionary and need approval',
      'DAC replaces RBAC in Business Critical edition for stricter access controls',
    ],
    answer: 'DAC allows object owners to grant privileges on their objects to other roles at their own discretion, complementing the top-down RBAC role hierarchy',
    exp: 'In Snowflake\'s hybrid model, RBAC defines the role hierarchy and privilege inheritance, while DAC allows the owner of an object (role that created it) to grant its own privileges to other roles. The two models work together.',
  },
  {
    id: 'd2_d4_02',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'A table\'s ownership is currently with the ANALYST role. After running GRANT OWNERSHIP ON TABLE orders TO ROLE etl_role, what happens to ANALYST\'s existing privileges?',
    options: [
      'ANALYST retains all its privileges; ETL_ROLE simply gains additional owner rights',
      'Ownership transfers to ETL_ROLE; ANALYST loses its ownership privilege. Existing ANALYST grants on the table may be revoked unless COPY CURRENT GRANTS is specified.',
      'The command fails — ownership can only be transferred by ACCOUNTADMIN',
      'ANALYST is automatically added as a co-owner alongside ETL_ROLE',
    ],
    answer: 'Ownership transfers to ETL_ROLE; ANALYST loses its ownership privilege. Existing ANALYST grants on the table may be revoked unless COPY CURRENT GRANTS is specified.',
    exp: 'GRANT OWNERSHIP transfers ownership to the new role — the previous owner loses the OWNERSHIP privilege. By default, existing grants made by the old owner are revoked. Add COPY CURRENT GRANTS to preserve them: GRANT OWNERSHIP … TO ROLE etl_role COPY CURRENT GRANTS.',
  },
  {
    id: 'd2_d4_03',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'easy',
    q: 'Which system role can manage grants on existing roles — for example, granting a custom role to another role — but cannot create databases or warehouses?',
    options: ['SYSADMIN', 'USERADMIN', 'SECURITYADMIN', 'PUBLIC'],
    answer: 'SECURITYADMIN',
    exp: 'SECURITYADMIN can manage grants on ALL objects (GRANT ROLE TO ROLE, GRANT PRIVILEGE TO ROLE) and has MANAGE GRANTS privilege. USERADMIN only creates users and roles. SYSADMIN creates databases and warehouses. SECURITYADMIN bridges security management.',
  },
  {
    id: 'd2_d4_04',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'A CI/CD pipeline needs to connect to Snowflake with no human interaction. Which authentication method is RECOMMENDED for service accounts and automated pipelines?',
    options: [
      'Username and password stored in environment variables',
      'Key-pair authentication using an RSA private key (2048 or 4096 bit)',
      'OAuth 2.0 with a user-consent flow',
      'MFA with Duo Security push notifications',
    ],
    answer: 'Key-pair authentication using an RSA private key (2048 or 4096 bit)',
    exp: 'Key-pair authentication is recommended for service accounts: a private RSA key is used to sign a JWT token for authentication — no password stored. The public key is registered with the Snowflake user. Supports rotation with a second key pair.',
  },
  {
    id: 'd2_d4_05',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'A BI tool like Tableau connects to Snowflake and authenticates as the end user through the tool without the user entering Snowflake credentials. Which authentication protocol enables this?',
    options: [
      'SAML 2.0 (SSO/Federated Authentication)',
      'OAuth 2.0 — the tool uses delegated access tokens on behalf of the user',
      'SCIM — for just-in-time user provisioning',
      'Key-pair JWT — the tool holds a private key for all users',
    ],
    answer: 'OAuth 2.0 — the tool uses delegated access tokens on behalf of the user',
    exp: 'OAuth 2.0 allows a third-party tool (e.g., Tableau, Power BI) to obtain an access token that represents the user and connect to Snowflake on their behalf — without the tool ever seeing the user\'s Snowflake credentials. SAML is for SSO login flows.',
  },
  {
    id: 'd2_d4_06',
    domain: 2,
    topic: 'Data Masking',
    difficulty: 'hard',
    q: 'What is an Aggregation Policy in Snowflake, and what problem does it solve?',
    options: [
      'A policy that groups masking policies together for easier management',
      'A privacy policy that prevents queries from returning results unless a minimum number of rows are aggregated — protects against re-identification through small group queries',
      'A policy that limits the number of rows any single query can return',
      'A policy that enforces GROUP BY clauses on all queries against a table',
    ],
    answer: 'A privacy policy that prevents queries from returning results unless a minimum number of rows are aggregated — protects against re-identification through small group queries',
    exp: 'Aggregation Policies set a minimum GROUP SIZE — if a query\'s GROUP BY produces a group with fewer rows than the minimum, the result for that group is suppressed. Prevents re-identification when demographic data could uniquely identify individuals in small cohorts.',
  },
  {
    id: 'd2_d4_07',
    domain: 2,
    topic: 'Encryption',
    difficulty: 'hard',
    q: 'What is Tri-Secret Secure and what edition requires it?',
    options: [
      'A Snowflake feature that encrypts data three times (at rest, in transit, in compute) — available on Standard edition',
      'A key management scheme requiring three factors: Snowflake\'s key + customer-managed key (CMK) from AWS KMS/Azure Key Vault/GCP KMS + a composite master key — requires Business Critical',
      'A feature that requires three separate ACCOUNTADMIN approvals to decrypt sensitive data — available on Enterprise',
      'Triple-layer TLS for data in transit — available on all editions',
    ],
    answer: 'A key management scheme requiring three factors: Snowflake\'s key + customer-managed key (CMK) from AWS KMS/Azure Key Vault/GCP KMS + a composite master key — requires Business Critical',
    exp: 'Tri-Secret Secure combines Snowflake\'s encryption key with a customer-managed key (CMK) from the customer\'s own KMS. Without the customer\'s CMK, even Snowflake Support cannot decrypt the data. Requires Business Critical edition and a supported cloud KMS.',
  },
  {
    id: 'd2_d4_08',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'Which ACCOUNT_USAGE view contains a row for every query executed in the account, including query text, execution time, bytes scanned, and credits consumed?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY',
    exp: 'QUERY_HISTORY records every executed query: query text, status, execution time, bytes scanned, rows produced, credits used, warehouse name, user, role, and more. Has 1-year retention. Central view for query performance auditing.',
  },
  {
    id: 'd2_d4_09',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'A data engineer wants to audit every file loaded into Snowflake in the last 6 months — file name, status (loaded/failed), row count. Which ACCOUNT_USAGE view should they query?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.STAGE_STORAGE_USAGE_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.LOAD_HISTORY',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY',
    exp: 'COPY_HISTORY records every COPY INTO execution: table name, file name, rows loaded, rows with errors, bytes loaded, status (loaded/load_failed/partially_loaded), and more. 1-year retention. Includes both COPY INTO and Snowpipe loads.',
  },
  {
    id: 'd2_d4_10',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'What does the Trust Center in Snowflake do?',
    options: [
      'Encrypts inter-service communication between Snowflake\'s Cloud Services components',
      'Continuously scans the account configuration against security benchmarks (e.g., CIS Snowflake Benchmark) and surfaces posture risks like users without MFA, public roles with excessive privileges',
      'Provides a customer-managed key vault for Tri-Secret Secure deployments',
      'Manages cross-account trust relationships for Snowflake Data Sharing',
    ],
    answer: 'Continuously scans the account configuration against security benchmarks (e.g., CIS Snowflake Benchmark) and surfaces posture risks like users without MFA, public roles with excessive privileges',
    exp: 'Trust Center is a security posture management tool built into Snowsight. It runs automated scans against the CIS Snowflake Benchmark and other frameworks, flagging misconfigurations such as no MFA enforcement, weak network policies, over-privileged roles, and more.',
  },
  {
    id: 'd2_d4_11',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'hard',
    q: 'What is data lineage in Snowflake, and which function returns the upstream/downstream dependencies of a specific object?',
    options: [
      'Data lineage tracks row-level changes — accessed via SYSTEM$GET_ROW_HISTORY()',
      'Data lineage shows the history of schema changes — accessed via INFORMATION_SCHEMA.SCHEMA_EVOLUTION_HISTORY',
      'Data lineage maps upstream sources and downstream consumers of a Snowflake object (table, view, stage) — accessed via SYSTEM$GET_LINEAGE() or the OBJECT_DEPENDENCIES view',
      'Data lineage tracks credit usage per object — accessed via ACCOUNT_USAGE.OBJECT_COST_HISTORY',
    ],
    answer: 'Data lineage maps upstream sources and downstream consumers of a Snowflake object (table, view, stage) — accessed via SYSTEM$GET_LINEAGE() or the OBJECT_DEPENDENCIES view',
    exp: 'Snowflake\'s data lineage feature tracks how data flows between objects. SYSTEM$GET_LINEAGE(\'domain.name\', depth, direction) returns lineage in a specified direction. SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES also shows compile-time dependencies.',
  },
  {
    id: 'd2_d4_12',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'A resource monitor has CREDIT_QUOTA = 100, and a TRIGGER at 90% with action SUSPEND_IMMEDIATE. The warehouse has consumed 91 credits. What happens?',
    options: [
      'A notification email is sent but the warehouse keeps running',
      'The warehouse is suspended immediately — all running queries are aborted',
      'The warehouse is suspended after the current queries finish',
      'The account is locked until the next billing period',
    ],
    answer: 'The warehouse is suspended immediately — all running queries are aborted',
    exp: 'SUSPEND_IMMEDIATE is the most aggressive trigger action — it suspends the warehouse immediately when the threshold is crossed AND aborts any currently running queries. SUSPEND waits for running queries to complete before suspending. NOTIFY only sends an alert.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ────────

  {
    id: 'd3_d4_01',
    domain: 3,
    topic: 'Stages',
    difficulty: 'easy',
    q: 'Which internal stage type is private to a single user, cannot be shared with other users or roles, and does not require a CREATE STAGE command?',
    options: ['Table stage (@%)', 'Named internal stage', 'User stage (@~)', 'External stage'],
    answer: 'User stage (@~)',
    exp: 'Every Snowflake user automatically has a personal user stage (@~). It is private — only that user can access it. It requires no CREATE STAGE DDL. Cannot be shared or accessed by other users, even with ACCOUNTADMIN.',
  },
  {
    id: 'd3_d4_02',
    domain: 3,
    topic: 'Stages',
    difficulty: 'medium',
    q: 'A storage integration is created to connect an external stage to an S3 bucket. What is the main security advantage over specifying AWS_KEY_ID and AWS_SECRET_KEY directly in the stage definition?',
    options: [
      'Storage integrations use Snowflake-owned S3 buckets — no customer S3 access is needed',
      'Storage integrations use an IAM role with cross-account trust — no long-lived AWS credentials are stored in Snowflake',
      'Storage integrations automatically rotate access keys every 24 hours',
      'Storage integrations encrypt data with customer-managed keys before writing to S3',
    ],
    answer: 'Storage integrations use an IAM role with cross-account trust — no long-lived AWS credentials are stored in Snowflake',
    exp: 'A storage integration creates an IAM role trust relationship — Snowflake assumes the role via cross-account trust (STS). No AWS access key ID or secret is stored in Snowflake. This follows IAM best practices and allows centralized IAM policy management.',
  },
  {
    id: 'd3_d4_03',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'medium',
    q: 'Which COPY INTO syntax unloads data FROM a Snowflake table TO an external stage as CSV files?',
    options: [
      'COPY INTO @my_ext_stage FROM my_table FILE_FORMAT = (TYPE = CSV);',
      'EXPORT TABLE my_table TO STAGE my_ext_stage AS CSV;',
      'UNLOAD FROM my_table INTO @my_ext_stage USING CSV;',
      'COPY FROM my_table INTO EXTERNAL @my_ext_stage FORMAT CSV;',
    ],
    answer: 'COPY INTO @my_ext_stage FROM my_table FILE_FORMAT = (TYPE = CSV);',
    exp: 'COPY INTO can both load (stage → table) and unload (table → stage). Unload syntax: COPY INTO @stage FROM table FILE_FORMAT = (TYPE = …). Options like SINGLE, HEADER, MAX_FILE_SIZE, and OVERWRITE control the output format.',
  },
  {
    id: 'd3_d4_04',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'easy',
    q: 'What does PURGE = TRUE do in a COPY INTO command?',
    options: [
      'Deletes rows from the source table that were successfully loaded',
      'Removes the staged files from the stage after a successful COPY INTO load',
      'Truncates the target table before loading new data',
      'Marks the load history entries for deletion after 64 days',
    ],
    answer: 'Removes the staged files from the stage after a successful COPY INTO load',
    exp: 'PURGE = TRUE automatically deletes the source files from the stage after they are successfully loaded. Default is FALSE — files remain in the stage. Useful for managing stage storage costs and preventing re-processing.',
  },
  {
    id: 'd3_d4_05',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'medium',
    q: 'How does classic Snowpipe AUTO_INGEST work on AWS?',
    options: [
      'Snowflake polls the S3 bucket every 60 seconds for new files',
      'An S3 Event Notification triggers an SQS message; Snowpipe reads the SQS queue and automatically loads new files',
      'A Lambda function calls the Snowpipe REST API whenever a new file arrives in S3',
      'Snowpipe uses S3 Replication to mirror files to a Snowflake-owned bucket before loading',
    ],
    answer: 'An S3 Event Notification triggers an SQS message; Snowpipe reads the SQS queue and automatically loads new files',
    exp: 'AUTO_INGEST on AWS: S3 sends an event notification to an SQS queue when files are uploaded. Snowpipe monitors the SQS queue and automatically triggers a load when a new file notification arrives. Near-real-time, serverless, no manual trigger.',
  },
  {
    id: 'd3_d4_06',
    domain: 3,
    topic: 'Stages',
    difficulty: 'easy',
    q: 'Which stage command removes a specific file from a Snowflake internal stage?',
    options: ['DROP FILE @stage/path', 'DELETE FROM @stage WHERE name = \'path\'', 'REMOVE @stage/path', 'PURGE @stage/path'],
    answer: 'REMOVE @stage/path',
    exp: 'REMOVE @<stage_name>/<path> deletes one or more files from a Snowflake stage. Supports wildcard patterns: REMOVE @mystage/data/ removes all files in that path prefix. Works on all stage types (user, table, named, external).',
  },
  {
    id: 'd3_d4_07',
    domain: 3,
    topic: 'File Formats',
    difficulty: 'medium',
    q: 'A Parquet file is loaded into Snowflake. Which VARIANT column is used to store the entire Parquet record, and which function infers the schema from the file?',
    options: [
      '$1 holds the record; DETECT_SCHEMA() infers the structure',
      '$1 holds the record in VARIANT; INFER_SCHEMA() returns columns and types from the Parquet metadata',
      'A column named "DATA" is auto-created; PARSE_PARQUET() infers the schema',
      'Each Parquet field becomes a separate column automatically; no schema inference needed',
    ],
    answer: '$1 holds the record in VARIANT; INFER_SCHEMA() returns columns and types from the Parquet metadata',
    exp: 'When loading Parquet into Snowflake (SELECT $1 FROM @stage), the entire record lands in the $1 VARIANT column. INFER_SCHEMA(LOCATION => \'@stage\', FILE_FORMAT => \'parquet_ff\') reads the Parquet file metadata and returns column names and types for CREATE TABLE.',
  },
  {
    id: 'd3_d4_08',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'medium',
    q: 'What is SnowCD, and when would you use it?',
    options: [
      'A Snowflake CD/CD pipeline tool for deploying schema migrations',
      'A connectivity diagnostic tool that validates network, DNS, and proxy settings to verify a client can reach Snowflake',
      'A Snowflake-managed Change Data Capture tool that replaces Streams',
      'A Cloud Deployment tool for provisioning Snowflake accounts',
    ],
    answer: 'A connectivity diagnostic tool that validates network, DNS, and proxy settings to verify a client can reach Snowflake',
    exp: 'SnowCD (Snowflake Connectivity Diagnostic tool) tests whether a client machine can reach Snowflake endpoints — checking DNS resolution, TCP connectivity, proxy settings, and TLS certificate validation. Used to troubleshoot connection failures.',
  },
  {
    id: 'd3_d4_09',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'medium',
    q: 'Which Snowflake integration type is required to call an external REST API from a Snowflake SQL query using an External Function?',
    options: [
      'Storage Integration',
      'Notification Integration',
      'API Integration',
      'Git Integration',
    ],
    answer: 'API Integration',
    exp: 'An API Integration defines the external HTTP endpoint (e.g., AWS API Gateway, Azure API Management, GCP API Gateway) and authentication settings. The External Function then wraps the API call as a callable SQL function using this integration.',
  },
  {
    id: 'd3_d4_10',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'medium',
    q: 'Which connector enables streaming data from Apache Kafka topics directly into Snowflake tables in near real-time?',
    options: [
      'Snowflake Python Connector with Kafka client library',
      'Snowflake Kafka Connector (based on Kafka Connect)',
      'Snowpipe REST API called from a Kafka Consumer Group',
      'Snowflake Spark Connector with Kafka integration',
    ],
    answer: 'Snowflake Kafka Connector (based on Kafka Connect)',
    exp: 'The Snowflake Kafka Connector is a Kafka Connect plugin that reads messages from Kafka topics and loads them into Snowflake tables using Snowpipe (serverless compute). Easy to deploy as a Kafka Connect worker — no custom coding required.',
  },
  {
    id: 'd3_d4_11',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'hard',
    q: 'A Dynamic Table is defined with TARGET_LAG = \'1 hour\' and INITIALIZE = \'ON_CREATE\'. What does INITIALIZE = \'ON_CREATE\' mean?',
    options: [
      'The Dynamic Table will start refreshing only after the first manual trigger',
      'Snowflake performs a full initial backfill of the Dynamic Table immediately when it is created',
      'The Dynamic Table is created empty and populated only after the first scheduled refresh cycle',
      'INITIALIZE = \'ON_CREATE\' is the default and has no special behavior',
    ],
    answer: 'Snowflake performs a full initial backfill of the Dynamic Table immediately when it is created',
    exp: 'INITIALIZE = \'ON_CREATE\' (the default) causes Snowflake to fully materialize the Dynamic Table immediately upon creation using a full table scan. INITIALIZE = \'ON_SCHEDULE\' skips the initial load and waits for the first scheduled refresh window.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (13 questions) ────────

  {
    id: 'd4_d4_01',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'A virtual warehouse\'s local SSD disk cache contains warm data from recent queries. What event causes this cache to be COMPLETELY LOST?',
    options: [
      'The connected user logs out',
      'The warehouse is suspended (powered off)',
      'A new warehouse size is requested via ALTER WAREHOUSE … SET WAREHOUSE_SIZE',
      'Both B and C — suspending or resizing the warehouse clears the local cache',
    ],
    answer: 'Both B and C — suspending or resizing the warehouse clears the local cache',
    exp: 'The local SSD cache lives on the warehouse compute nodes. Suspending destroys the nodes — cache is lost. Resizing also replaces the nodes — cache lost. To preserve cache, avoid unnecessary suspends and keep the warehouse running for hot workloads.',
  },
  {
    id: 'd4_d4_02',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'A user runs a SELECT query that hits the result cache. A few seconds later, someone runs INSERT INTO orders VALUES (...) on the source table. The first user then re-runs the same SELECT. What happens?',
    options: [
      'The result cache is still used — the INSERT has not been committed yet',
      'The result cache is invalidated by the INSERT — Snowflake re-executes the query against fresh data',
      'The result cache is used — DML does not invalidate the result cache until 24 hours pass',
      'The result cache is partially used — only new rows are fetched and merged with cached results',
    ],
    answer: 'The result cache is invalidated by the INSERT — Snowflake re-executes the query against fresh data',
    exp: 'DML changes (INSERT, UPDATE, DELETE, MERGE, COPY INTO) to any table the query references immediately invalidate the result cache for that query. The 24-hour TTL only applies when no data changes occur.',
  },
  {
    id: 'd4_d4_03',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'In Snowflake Query Profile, what does an "Exchange" node represent?',
    options: [
      'A data exchange between Snowflake and an external table in cloud storage',
      'A redistribution of data between worker nodes in the warehouse — typically occurs during joins and aggregations when data must be reshuffled',
      'An exchange of compressed micro-partition data between the Cloud Services layer and the warehouse',
      'A cached result being exchanged from the result cache to the warehouse',
    ],
    answer: 'A redistribution of data between worker nodes in the warehouse — typically occurs during joins and aggregations when data must be reshuffled',
    exp: 'Exchange nodes represent network shuffles between warehouse worker nodes. During hash joins and GROUP BY operations, rows must be distributed to the node responsible for each partition key. High Exchange time suggests large data redistribution — consider pre-joining or filtering earlier.',
  },
  {
    id: 'd4_d4_04',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'When does Snowflake choose to broadcast a small table in a join rather than performing a hash join?',
    options: [
      'When both tables are larger than 1 GB',
      'When one table is small enough to fit in each node\'s memory — Snowflake sends (broadcasts) the small table to all nodes to avoid expensive data redistribution',
      'When the join column has high cardinality on both sides',
      'Only when BROADCAST JOIN hint is explicitly specified in the query',
    ],
    answer: 'When one table is small enough to fit in each node\'s memory — Snowflake sends (broadcasts) the small table to all nodes to avoid expensive data redistribution',
    exp: 'Broadcast joins send the smaller table to every compute node so each node can join its portion of the large table locally — eliminating network shuffles. The query optimizer chooses this automatically when it detects a significant size asymmetry between the two join inputs.',
  },
  {
    id: 'd4_d4_05',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'medium',
    q: 'A table is defined with CLUSTER BY (region, transaction_date). What is this called, and how many columns does the clustering key contain?',
    options: [
      'A single-column clustering key (only region is used)',
      'A compound clustering key with 2 columns — clusters by region first, then transaction_date within each region',
      'An expression clustering key — region and transaction_date are expressions',
      'A multi-partition clustering key — each column creates its own partition set',
    ],
    answer: 'A compound clustering key with 2 columns — clusters by region first, then transaction_date within each region',
    exp: 'CLUSTER BY (col1, col2) creates a compound clustering key. The first column is the primary clustering dimension, the second is secondary within each first-column group. Improves pruning on queries filtering by region AND/OR transaction_date.',
  },
  {
    id: 'd4_d4_06',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'hard',
    q: 'What is the key difference between a Materialized View and the result cache in Snowflake?',
    options: [
      'The result cache is stored on the Cloud Services layer; the MV is stored in warehouse local SSD',
      'A Materialized View is a permanent, named schema object with its own storage that persists indefinitely; the result cache is temporary (24h), query-specific, and invisible to users',
      'A Materialized View and result cache are functionally identical — just different names',
      'The result cache serves all users; MVs can only be accessed by the role that created them',
    ],
    answer: 'A Materialized View is a permanent, named schema object with its own storage that persists indefinitely; the result cache is temporary (24h), query-specific, and invisible to users',
    exp: 'MV: explicitly created, named, has DDL, stores results permanently, kept fresh by background compute, shows in SHOW VIEWS. Result cache: automatic, anonymous, 24h TTL, shared across users, transparent. Both improve query performance but work very differently.',
  },
  {
    id: 'd4_d4_07',
    domain: 4,
    topic: 'Search Optimization',
    difficulty: 'hard',
    q: 'Search Optimization Service on a table has two cost components. What are they?',
    options: [
      'Warehouse credits for building the index + storage for the search results cache',
      'Serverless compute credits for building/maintaining the search access paths + additional storage for the search access path data structures',
      'A flat monthly subscription fee + per-query compute credits',
      'Serverless compute for rebuilding on DML + INFORMATION_SCHEMA query credits',
    ],
    answer: 'Serverless compute credits for building/maintaining the search access paths + additional storage for the search access path data structures',
    exp: 'Search Optimization costs: (1) Serverless compute to build and maintain search access paths when data changes, (2) Storage for the access path data structures (typically ~1–2× the table\'s compressed data size). No virtual warehouse is needed.',
  },
  {
    id: 'd4_d4_08',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'medium',
    q: 'A VARIANT column contains arrays like [{"item":"a"},{"item":"b"}]. Which function explodes the array so each element becomes a separate row?',
    options: ['UNPIVOT()', 'EXPLODE()', 'FLATTEN()', 'LATERAL ARRAY_UNNEST()'],
    answer: 'FLATTEN()',
    exp: 'FLATTEN(INPUT => col:array_field) laterally joins the array and produces one row per element. Used in: SELECT f.value:item::VARCHAR FROM my_table, LATERAL FLATTEN(INPUT => data) f. This is the standard Snowflake function for exploding nested arrays.',
  },
  {
    id: 'd4_d4_09',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'What is a Tabular User-Defined Function (UDTF) in Snowflake?',
    options: [
      'A UDF that returns a single scalar value of any data type including ARRAY',
      'A UDF that returns a TABLE (multiple rows and columns) and is called inside a FROM clause using TABLE()',
      'A UDF defined using a TABLE statement instead of a CREATE FUNCTION statement',
      'A UDF that operates on VARIANT columns and returns structured table metadata',
    ],
    answer: 'A UDF that returns a TABLE (multiple rows and columns) and is called inside a FROM clause using TABLE()',
    exp: 'A UDTF (Table Function) returns a set of rows instead of a single value. Called as: SELECT * FROM TABLE(my_udtf(arg1)). Supported in Python, Java, and JavaScript. Useful for complex transformations that need to produce multiple output rows per input row.',
  },
  {
    id: 'd4_d4_10',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'hard',
    q: 'A stored procedure is called by USER_A using the ANALYST role. The procedure is created with EXECUTE AS OWNER. Under which role does the procedure execute?',
    options: [
      'ANALYST — the role of the calling user',
      'The role that owns the stored procedure (the creator\'s role at procedure creation time)',
      'ACCOUNTADMIN — stored procedures always execute with maximum privilege',
      'PUBLIC — for security, procedures are always demoted to the lowest role',
    ],
    answer: 'The role that owns the stored procedure (the creator\'s role at procedure creation time)',
    exp: 'EXECUTE AS OWNER means the procedure runs with the privileges of the role that created/owns it — regardless of who calls it. EXECUTE AS CALLER runs with the caller\'s role. Owner rights enable procedures to access objects the caller can\'t (e.g., privileged tables).',
  },
  {
    id: 'd4_d4_11',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'Which SQL extension allows you to aggregate data at multiple levels of granularity in a single query — for example, subtotals by region, by year, and a grand total?',
    options: [
      'PIVOT',
      'QUALIFY',
      'GROUPING SETS (or ROLLUP / CUBE)',
      'LATERAL FLATTEN',
    ],
    answer: 'GROUPING SETS (or ROLLUP / CUBE)',
    exp: 'GROUPING SETS lets you define multiple GROUP BY groupings in one query. ROLLUP generates hierarchical subtotals (e.g., region → year → grand total). CUBE generates all combinations. All three avoid multiple UNION ALL queries.',
  },
  {
    id: 'd4_d4_12',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'easy',
    q: 'What is the effect of wrapping a filter column in a function — for example, WHERE YEAR(transaction_date) = 2025 instead of WHERE transaction_date BETWEEN \'2025-01-01\' AND \'2025-12-31\'?',
    options: [
      'No difference — Snowflake automatically unwraps function calls for pruning',
      'The function-wrapped filter prevents micro-partition pruning because min/max metadata is based on the raw column, not computed expressions',
      'The function-wrapped filter is faster because Snowflake evaluates it in the Cloud Services layer',
      'Function wrapping only affects pruning for string columns, not date columns',
    ],
    answer: 'The function-wrapped filter prevents micro-partition pruning because min/max metadata is based on the raw column, not computed expressions',
    exp: 'Snowflake\'s pruning uses min/max metadata stored per column in each micro-partition. YEAR(transaction_date) is a derived expression — Snowflake can\'t match it against raw date min/max values, so ALL partitions are scanned. Use range predicates on the raw column instead.',
  },
  {
    id: 'd4_d4_13',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'In Snowpark, a developer writes: df.groupBy("region").agg(sum("sales").alias("total_sales")). When does this actually run against Snowflake data?',
    options: [
      'Immediately when groupBy() is called',
      'When agg() is called, since it is a terminal operation',
      'Only when an action like .collect(), .show(), or .write.saveAsTable() is invoked',
      'When the Snowpark session object is garbage collected',
    ],
    answer: 'Only when an action like .collect(), .show(), or .write.saveAsTable() is invoked',
    exp: 'Snowpark uses lazy evaluation — groupBy, agg, filter, select are transformations that build a query plan but don\'t execute. Execution only happens when an action is triggered. This allows chaining multiple operations into one optimized SQL execution.',
  },

  // ── DOMAIN 5: Data Collaboration (5 questions) ───────────────────────────

  {
    id: 'd5_d4_01',
    domain: 5,
    topic: 'Time Travel',
    difficulty: 'medium',
    q: 'An entire database was accidentally dropped. No backup exists outside Snowflake. The drop happened 6 hours ago. DATA_RETENTION_TIME_IN_DAYS = 7. Can the database be recovered, and how?',
    options: [
      'No — dropped databases cannot be recovered regardless of retention settings',
      'Yes — UNDROP DATABASE <name> recovers the entire database including all schemas and tables within the Time Travel window',
      'Yes — but only individual tables can be undropped, not entire databases',
      'Only Snowflake Support can recover a dropped database, regardless of Time Travel',
    ],
    answer: 'Yes — UNDROP DATABASE <name> recovers the entire database including all schemas and tables within the Time Travel window',
    exp: 'UNDROP works at the database, schema, and table level. UNDROP DATABASE restores the entire database with all its schemas and tables as they existed at the moment of the DROP — provided the Time Travel window has not expired.',
  },
  {
    id: 'd5_d4_02',
    domain: 5,
    topic: 'Time Travel',
    difficulty: 'hard',
    q: 'Increasing a table\'s DATA_RETENTION_TIME_IN_DAYS from 1 to 30 days has what storage cost implication?',
    options: [
      'No additional storage cost — Time Travel data shares the same micro-partitions as active data',
      'Additional storage cost for the Time Travel data that accumulates over 30 days of changes — you pay for changed/deleted data that must be retained for the longer window',
      'A flat fee per day of retention is charged separately from storage',
      'Storage doubles for each additional day added to retention',
    ],
    answer: 'Additional storage cost for the Time Travel data that accumulates over 30 days of changes — you pay for changed/deleted data that must be retained for the longer window',
    exp: 'Time Travel retains historical versions of changed or deleted micro-partitions for the retention window. Longer retention = more historical data stored = higher storage costs. Very active tables with frequent DML will see significant Time Travel storage costs with long retention.',
  },
  {
    id: 'd5_d4_03',
    domain: 5,
    topic: 'Cloning',
    difficulty: 'medium',
    q: 'You run: CREATE DATABASE dev_db CLONE prod_db. How much additional storage is immediately consumed for dev_db at clone time?',
    options: [
      'Exactly the same as prod_db — a full copy is made',
      'Zero — the clone shares all micro-partitions with prod_db via copy-on-write',
      '50% of prod_db — Snowflake creates a half-size replica',
      'Only metadata is stored (a few KB) — no data is stored at all, including shared references',
    ],
    answer: 'Zero — the clone shares all micro-partitions with prod_db via copy-on-write',
    exp: 'Zero-copy cloning at the database level creates dev_db instantly with zero additional storage — all schemas, tables, and micro-partitions are shared references. Storage is only consumed when either the clone or the source is modified (copy-on-write semantics).',
  },
  {
    id: 'd5_d4_04',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'hard',
    q: 'A data provider wants to grant a consumer access to a specific view in a Data Share, but wants to apply fine-grained role-based access within the share. Which Snowflake object allows RBAC to work within a shared database on the consumer side?',
    options: [
      'Account roles — the provider grants account roles to the share',
      'Database roles — the provider defines and grants database roles within the shared database, and consumers can then be granted those database roles',
      'Session policies — attached to the share to restrict which consumer roles can use it',
      'Masking policies — can be attached to the share objects to enforce role-based column access',
    ],
    answer: 'Database roles — the provider defines and grants database roles within the shared database, and consumers can then be granted those database roles',
    exp: 'Database roles are scoped to a single database and can be included in a Data Share. The provider creates database roles (e.g., BRONZE, GOLD), grants object privileges to them, and shares them. Consumers assign the database roles to their local account roles for fine-grained access.',
  },
  {
    id: 'd5_d4_05',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'What is a Snowflake Private Data Exchange, and how does it differ from the public Snowflake Marketplace?',
    options: [
      'A Private Data Exchange is an encrypted version of a public Data Share — the encryption key is private',
      'A Private Data Exchange is a curated, invitation-only data sharing hub where a company can share data with specific partner organizations without it being publicly discoverable on the Marketplace',
      'A Private Data Exchange stores data in the consumer\'s own cloud account instead of the provider\'s account',
      'A Private Data Exchange is the Snowflake-internal name for a Reader Account',
    ],
    answer: 'A Private Data Exchange is a curated, invitation-only data sharing hub where a company can share data with specific partner organizations without it being publicly discoverable on the Marketplace',
    exp: 'A Private Data Exchange (Private Hub) lets companies create their own branded data exchange — inviting specific partners to access listings. Unlike the public Snowflake Marketplace (open to all Snowflake customers), a Private Exchange is invite-only and not publicly visible.',
  },
];
