// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 6  (2026-03-16)
// COF-C03 Mock Exam · 60 questions
// Distribution: D1 31% (19q) | D2 20% (12q) | D3 18% (11q) | D4 21% (13q) | D5 10% (5q)
//
// *** CHALLENGE DAY (day divisible by 3) ***
// Difficulty mix: ~10% Easy (6q) · ~40% Medium (24q) · ~50% Hard (30q)
//
// OVERLAP RULE (decreasing by recency):
//   Day 5 (N-1): ≤ 30% overlap (≤ 18 questions) — ~8 topics shared
//   Day 4 (N-2): ≤ 20% overlap (≤ 12 questions) — ~5 topics shared
//   Day 3 (N-3): ≤ 10% overlap (≤  6 questions) — ~3 topics shared
//   Day 2 (N-4): ≤  5% overlap (≤  3 questions)
//
// DAY 6 vs DAY 5 OVERLAP CHECK:
//   Day 5 covered: Cloud Services billing UTC rule, Standard TT max, VS Code Extension,
//   Horizon Discovery/Security/Governance pillars, MANAGE WAREHOUSES, Cortex ML Functions,
//   STANDARD auto-scale policy, SiS governance, External Table REFRESH, Cortex SUMMARIZE,
//   OR-predicate pruning, CREATE SCHEMA privilege, auto schemas PUBLIC+INFO_SCHEMA, @% stage,
//   USE SECONDARY ROLES, ACCOUNTADMIN unique tasks, MFA Session Policy, RAP DDL,
//   TAG_REFERENCES, WAREHOUSE_METERING_HISTORY, CREATE ALERT + SUSPEND, webhook notification,
//   network policy user-level, SECURITY_VIEWER, Replication Group objects, custom role
//   orphan, SKIP_HEADER CSV, load history 64-day, Snowpipe REST API insertFiles, Stream
//   offset advancement (SELECT doesn't advance), Task CRON, dbt+Snowflake, GET command,
//   Avro, STORAGE_ALLOWED_LOCATIONS, METADATA$ACTION, result cache exact SQL, SHOW + metadata
//   cache, Sort node, spill to remote severity, average_depth, MV+CURRENT_DATE restriction,
//   PARSE_JSON colon, scalar Python UDF, DT incremental vs full refresh, QUALIFY+ROW_NUMBER,
//   COPY GRANTS, CTE lifetime, MERGE+stream offset, AT(BEFORE STATEMENT), CREATE DB FROM SHARE,
//   Native Apps, Marketplace free listing billing, clone + stream objects.
//
//   Day 6 fresh angles (Challenge Day — harder, deeper): micro-partition immutability (UPDATE),
//   AT(STATEMENT) vs BEFORE(STATEMENT) undo scenario, multi-cluster MAX + STANDARD queue
//   behaviour, Iceberg external catalog DML limitation, Business Critical for BAA/HIPAA,
//   MONITOR warehouse privilege (what it allows), Org-level objects, micro-partition metadata
//   fields, Snowpark Container Services compute pool, GEOGRAPHY vs GEOMETRY, SCIM lifecycle,
//   MFA Duo integration detail, OBJECT_DEPENDENCIES compile-time, Resource Monitor serverless
//   blind spot, Alerts serverless compute, masking policy admin workflow, key hierarchy 4-level,
//   External OAuth SECURITY INTEGRATION, RAP + result cache cross-role, SYSTEM$CLASSIFY output,
//   OpenLineage external lineage, ACCOUNTADMIN vs RAP, Snowpipe serverless detail, PUT GZIP
//   default, FLATTEN VALUE column, INFER_SCHEMA result set, SYSTEM$STREAM_HAS_DATA skip logic,
//   MATCH_BY_COLUMN_NAME CASE_INSENSITIVE, COPY_HISTORY error audit, METADATA$ROW_ID identity,
//   DT source restrictions (no Streams), SSE vs CSE external stage, Snowpipe Streaming vs
//   classic architecture, USE_CACHED_RESULT=FALSE scope, JS UDF sandbox limitations, ARRAY_AGG,
//   TableScan partition scan ratio, STRIP_NULL_VALUES, PIVOT, ROWS vs RANGE frame ties,
//   SUSPEND RECLUSTER vs DROP CLUSTERING KEY, BEHIND_BY staleness, SOS SUBSTRING predicates,
//   SP COMMIT inside outer transaction, DT joining two DTs lag, QAS outlier queries, Reader
//   Account compute billing, UNDROP SCHEMA restores all contained objects, Marketplace provider
//   publish sequence, provider drops shared table, clone of transient table (no Fail-safe).
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 6,
  date: '2026-03-16',
  label: 'Day 6 — Challenge',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (19 questions) ─────────────────────
  // 2 easy · 7 medium · 10 hard

  {
    id: 'd1_d6_01',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'Snowflake supports deployment on three major cloud platforms. Which set is correct?',
    options: [
      'AWS, Azure, and Google Cloud Platform',
      'AWS and Azure only — GCP support is a roadmap item',
      'AWS, Azure, and IBM Cloud',
      'GCP and AWS only — Azure uses a different architecture',
    ],
    answer: 'AWS, Azure, and Google Cloud Platform',
    exp: 'Snowflake is available on AWS, Azure, and GCP. The deployment region determines which cloud provider hosts the account, but the Snowflake architecture is identical across all three.',
  },
  {
    id: 'd1_d6_02',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'easy',
    q: 'A user is granted the MONITOR privilege on a virtual warehouse but no other warehouse privilege. What can they do?',
    options: [
      'Start and stop the warehouse on demand',
      'Resize the warehouse to a larger size',
      'Modify the AUTO_SUSPEND setting of the warehouse',
      'View the warehouse\'s query history, credit usage, and performance statistics — but cannot start, stop, or modify it',
    ],
    answer: 'View the warehouse\'s query history, credit usage, and performance statistics — but cannot start, stop, or modify it',
    exp: 'MONITOR grants read-only observability on the warehouse (see query history, credit consumption, load stats). OPERATE is needed to start/stop; MODIFY is needed to resize or change settings.',
  },

  {
    id: 'd1_d6_03',
    domain: 1,
    topic: 'Data Types',
    difficulty: 'medium',
    q: 'A developer stores meeting timestamps that must always preserve the original timezone offset (e.g., 14:00:00+02:00 should never display in UTC). Which Snowflake type is correct?',
    options: [
      'TIMESTAMP_NTZ — no timezone information stored',
      'TIMESTAMP_TZ — stores the timestamp WITH the original timezone offset embedded in the value',
      'TIMESTAMP_LTZ — converts to the session\'s local timezone automatically',
      'DATETIME — Snowflake\'s timezone-preserving alias',
    ],
    answer: 'TIMESTAMP_TZ — stores the timestamp WITH the original timezone offset embedded in the value',
    exp: 'TIMESTAMP_TZ retains the offset (e.g., +02:00) in the stored value. TIMESTAMP_LTZ stores in UTC and displays in the session timezone. TIMESTAMP_NTZ has no timezone at all. DATETIME is an alias for TIMESTAMP_NTZ.',
  },
  {
    id: 'd1_d6_04',
    domain: 1,
    topic: 'Snowflake Horizon',
    difficulty: 'medium',
    q: 'Which Snowflake Horizon Catalog pillar encompasses features like Aggregation Policies, Projection Policies, and Privacy-preserving joins (Data Clean Rooms)?',
    options: [
      'Discovery — cataloguing and tagging data assets',
      'Security & Governance — managing access controls and authentication',
      'Privacy — controlling what aggregate-level or column-level data can be seen by external parties',
      'Collaboration — enabling data sharing across accounts and cloud regions',
    ],
    answer: 'Privacy — controlling what aggregate-level or column-level data can be seen by external parties',
    exp: 'The Privacy pillar includes Aggregation Policies (minimum group size), Projection Policies (prevent SELECT * exposure), and Data Clean Rooms. Discovery handles tagging/classification; Security & Governance covers RBAC and masking; Collaboration covers Secure Data Sharing and Marketplace.',
  },
  {
    id: 'd1_d6_05',
    domain: 1,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'medium',
    q: 'Fail-safe extends protection for 7 days after the Time Travel window expires on permanent tables. Who can access data during the Fail-safe period?',
    options: [
      'Any user with the ACCOUNTADMIN role can query Fail-safe data using AT(OFFSET => -90days)',
      'SYSADMIN and ACCOUNTADMIN can both access Fail-safe data using special SQL syntax',
      'No SQL access is possible — only Snowflake Support can recover Fail-safe data upon request',
      'Fail-safe data is exposed through the SNOWFLAKE.ACCOUNT_USAGE.FAILSAFE_OBJECTS view',
    ],
    answer: 'No SQL access is possible — only Snowflake Support can recover Fail-safe data upon request',
    exp: 'Fail-safe is a disaster-recovery backstop managed entirely by Snowflake. There is NO SQL command to query Fail-safe data. If needed, you must open a Snowflake Support case. Time Travel (accessible via SQL) expires before Fail-safe begins.',
  },
  {
    id: 'd1_d6_06',
    domain: 1,
    topic: 'Snowpark Container Services',
    difficulty: 'medium',
    q: 'What does Snowpark Container Services enable that standard Snowpark DataFrames alone cannot do?',
    options: [
      'Running Python-based Snowpark transformations on a larger virtual warehouse',
      'Connecting to external S3 buckets from inside a Snowflake function',
      'Executing Snowflake SQL queries from a Jupyter Notebook',
      'Running arbitrary Docker containerized workloads (any language, any library) inside the Snowflake infrastructure boundary',
    ],
    answer: 'Running arbitrary Docker containerized workloads (any language, any library) inside the Snowflake infrastructure boundary',
    exp: 'Snowpark Container Services lets you bring fully custom Docker images (e.g., GPU-accelerated ML, specialized frameworks) and run them on Compute Pools inside Snowflake. Standard Snowpark is limited to supported languages and libraries via the Anaconda allowlist.',
  },
  {
    id: 'd1_d6_07',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'A developer needs to create a new schema inside an existing database. Their current role has only USAGE on the database (not ownership). Which additional privilege do they need on the DATABASE?',
    options: [
      'USAGE on the database is sufficient to also create schemas inside it',
      'CREATE SCHEMA privilege on the database is required to create new schemas when the role does not own the database',
      'CREATE DATABASE privilege at the account level implicitly allows schema creation in any database',
      'No additional privilege is needed — USAGE always implies all DDL rights within the object',
    ],
    answer: 'CREATE SCHEMA privilege on the database is required to create new schemas when the role does not own the database',
    exp: 'USAGE on a database lets a role access its existing schemas and objects, but does NOT grant the right to create new schemas. CREATE SCHEMA must be explicitly granted on the database. If a role OWNED the database, ownership already includes all DDL rights (including CREATE SCHEMA) and no additional grant would be needed.',
  },
  {
    id: 'd1_d6_08',
    domain: 1,
    topic: 'AI / ML Features',
    difficulty: 'medium',
    q: 'Cortex Guard is enabled in a Snowflake Cortex LLM function call. What does Cortex Guard specifically do?',
    options: [
      'Validates that the user\'s SQL syntax is correct before sending to the LLM',
      'Caches LLM responses to reduce repeated credit consumption',
      'Screens both the input prompt and LLM response for harmful, offensive, or policy-violating content — blocking unsafe outputs before they reach the caller',
      'Limits LLM token consumption to a configurable budget per query',
    ],
    answer: 'Screens both the input prompt and LLM response for harmful, offensive, or policy-violating content — blocking unsafe outputs before they reach the caller',
    exp: 'Cortex Guard is a safety layer that applies content filtering on both input and output of Cortex LLM functions. It helps enterprises prevent prompt injection, jailbreaks, and harmful content from appearing in LLM-powered applications.',
  },
  {
    id: 'd1_d6_09',
    domain: 1,
    topic: 'Interfaces & Connectivity',
    difficulty: 'medium',
    q: 'A developer wants to tag all queries from a specific application with a tracking string for later analysis in QUERY_HISTORY. Which mechanism achieves this without changing application SQL?',
    options: [
      'ALTER SESSION SET QUERY_TAG = \'app-name\' — all subsequent queries in the session carry this tag in QUERY_HISTORY.QUERY_TAG',
      'Add a -- QUERY_TAG: app-name SQL comment prefix to each query',
      'Create a row-level tag using SYSTEM$ADD_QUERY_TAG(\'app-name\') before each statement',
      'Set ACCOUNT_QUERY_TAG in the network policy to tag all account traffic',
    ],
    answer: 'ALTER SESSION SET QUERY_TAG = \'app-name\' — all subsequent queries in the session carry this tag in QUERY_HISTORY.QUERY_TAG',
    exp: 'ALTER SESSION SET QUERY_TAG sets a free-text tag that appears in QUERY_HISTORY.QUERY_TAG for every query run in that session. It\'s a lightweight way to attribute queries to applications, teams, or workflows without modifying the SQL text itself.',
  },

  {
    id: 'd1_d6_10',
    domain: 1,
    topic: 'Micro-partitions',
    difficulty: 'hard',
    q: 'An UPDATE modifies 100 rows spread across 5 different micro-partitions. What physically happens to those micro-partitions?',
    options: [
      'The 100 affected rows are updated in-place — Snowflake only rewrites the changed bytes within each micro-partition',
      'All rows across the 5 partitions are merged into a single new micro-partition to reduce fragmentation',
      'The 5 original micro-partitions are marked deleted (retained for Time Travel), and up to 5 new micro-partitions are written with the updated data — micro-partitions are immutable',
      'Snowflake acquires row-level locks on the 5 partitions, applies the delta in-memory, and commits — no new files are written',
    ],
    answer: 'The 5 original micro-partitions are marked deleted (retained for Time Travel), and up to 5 new micro-partitions are written with the updated data — micro-partitions are immutable',
    exp: 'Snowflake micro-partitions are immutable. Any DML that changes a row causes new micro-partition files to be written. The old files are marked logically deleted but physically retained to support Time Travel queries. This is how Snowflake achieves zero-copy clones and Time Travel without traditional write-ahead logs.',
  },
  {
    id: 'd1_d6_11',
    domain: 1,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'hard',
    q: 'A developer accidentally ran DELETE FROM orders WHERE status = \'PENDING\' (query_id = \'XYZ789\'). They want to see the rows as they existed JUST BEFORE that DELETE ran. Which expression is correct?',
    options: [
      'SELECT * FROM orders BEFORE(STATEMENT => \'XYZ789\') — returns state immediately before statement XYZ789 started executing',
      'SELECT * FROM orders AT(STATEMENT => \'XYZ789\') — AT always returns the pre-statement state',
      'SELECT * FROM orders AT(OFFSET => -60) — the only reliable rollback mechanism is offset-based',
      'SELECT * FROM orders BEFORE(OFFSET => -1) — offset of -1 second always captures the pre-DELETE state',
    ],
    answer: 'SELECT * FROM orders BEFORE(STATEMENT => \'XYZ789\') — returns state immediately before statement XYZ789 started executing',
    exp: 'AT(STATEMENT => id) returns the state at the END of that statement\'s execution (inclusive — the DELETE has already run). BEFORE(STATEMENT => id) returns the state JUST BEFORE that statement started — exactly what you need to recover accidentally deleted rows.',
  },
  {
    id: 'd1_d6_12',
    domain: 1,
    topic: 'Multi-cluster Warehouses',
    difficulty: 'hard',
    q: 'A multi-cluster warehouse is configured with MAX_CLUSTER_COUNT = 4, SCALING_POLICY = STANDARD. All 4 clusters are active and new queries continue to arrive. What happens to those queued queries?',
    options: [
      'Snowflake silently drops the excess queries — STANDARD policy enforces a hard concurrency cap',
      'Queries queue and wait for a cluster slot to free up — STANDARD policy does not exceed MAX_CLUSTER_COUNT, so new queries wait rather than start a 5th cluster',
      'A temporary 5th "overflow" cluster starts automatically and is billed at a 20% premium',
      'The warehouse automatically switches from STANDARD to ECONOMY policy to reduce cluster spin-up',
    ],
    answer: 'Queries queue and wait for a cluster slot to free up — STANDARD policy does not exceed MAX_CLUSTER_COUNT, so new queries wait rather than start a 5th cluster',
    exp: 'MAX_CLUSTER_COUNT is a hard ceiling. Once all clusters are fully loaded under STANDARD policy, additional queries queue. Increasing MAX_CLUSTER_COUNT or switching to a larger warehouse are the solutions. No automatic overflow beyond the configured maximum occurs.',
  },
  {
    id: 'd1_d6_13',
    domain: 1,
    topic: 'Apache Iceberg Tables',
    difficulty: 'hard',
    q: 'A team registers an Apache Iceberg table in Snowflake that is cataloged externally in AWS Glue (not Snowflake-managed). They try to run INSERT INTO that table. What happens?',
    options: [
      'Snowflake can only read externally-cataloged Iceberg tables — DML (INSERT/UPDATE/DELETE/MERGE) is not supported; the table is effectively read-only',
      'INSERT works but triggers a full table rewrite since Iceberg on Glue does not support incremental writes from Snowflake',
      'INSERT requires an explicit ALTER TABLE SET CATALOG = SNOWFLAKE command first to promote it to a writable Snowflake-managed Iceberg table',
      'INSERT fails only for UPDATE and DELETE; INSERT INTO (append) is supported on externally-cataloged Iceberg tables',
    ],
    answer: 'Snowflake can only read externally-cataloged Iceberg tables — DML (INSERT/UPDATE/DELETE/MERGE) is not supported; the table is effectively read-only',
    exp: 'Iceberg tables with an external catalog (e.g., AWS Glue, open catalog) are read-only in Snowflake. Snowflake does not own the catalog, so it cannot commit DML writes. Snowflake-managed Iceberg tables (where Snowflake acts as the catalog) DO support full DML.',
  },
  {
    id: 'd1_d6_14',
    domain: 1,
    topic: 'Editions',
    difficulty: 'hard',
    q: 'A US healthcare company must sign a BAA (Business Associate Agreement) with Snowflake to legally store PHI under HIPAA. Which minimum Snowflake edition supports BAA signing and HIPAA-eligible configurations?',
    options: [
      'Standard — HIPAA is available on all editions with proper configuration',
      'Enterprise — HIPAA compliance features and BAA eligibility begin at Enterprise',
      'Virtual Private Snowflake (VPS) — HIPAA requires a fully isolated single-tenant deployment',
      'Business Critical — BAA signing and HIPAA-eligible infrastructure (including PrivateLink, enhanced encryption, and dedicated metadata) require Business Critical',
    ],
    answer: 'Business Critical — BAA signing and HIPAA-eligible infrastructure (including PrivateLink, enhanced encryption, and dedicated metadata) require Business Critical',
    exp: 'Business Critical (formerly Enterprise for Sensitive Data) is the minimum edition that supports BAA agreements, HIPAA/HITRUST compliance, and the additional security features (customer-managed key options, PrivateLink support, enhanced audit) required for regulated healthcare data.',
  },
  {
    id: 'd1_d6_15',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'hard',
    q: 'An operations team member needs to see per-query execution times and credit consumption for a specific warehouse but should NOT be able to start, stop, or resize it. Which warehouse privilege satisfies the least-privilege requirement?',
    options: [
      'USAGE — grants ability to use the warehouse for queries and view basic metadata',
      'OPERATE — allows starting, stopping, and monitoring the warehouse',
      'MONITOR — grants read-only visibility into query history, load, and credit stats WITHOUT operational control',
      'MANAGE WAREHOUSES — required to view any warehouse statistics on an account',
    ],
    answer: 'MONITOR — grants read-only visibility into query history, load, and credit stats WITHOUT operational control',
    exp: 'MONITOR is the observability privilege. It allows viewing WAREHOUSE_METERING_HISTORY and query stats for the warehouse without granting OPERATE (start/stop/resume) or MODIFY (resize, settings change). It follows the least-privilege principle for read-only operators.',
  },
  {
    id: 'd1_d6_16',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'hard',
    q: 'An organization administrator manages a Snowflake Organization. Which objects exist at the ORGANIZATION level (above all accounts)?',
    options: [
      'Databases and schemas — the org level owns all databases across accounts',
      'Users and roles — all user identities are defined at the org level and federated down',
      'Security policies and network policies — org-level policies override account settings',
      'Accounts themselves, Replication/Failover Groups, and Snowflake Marketplace listings — the org is the container for accounts and cross-account replication constructs',
    ],
    answer: 'Accounts themselves, Replication/Failover Groups, and Snowflake Marketplace listings — the org is the container for accounts and cross-account replication constructs',
    exp: 'The Organization is the top-level container that holds multiple Snowflake accounts. Account-level objects (databases, warehouses, roles) are scoped within an account. Cross-account constructs like Replication Groups and Failover Groups are managed via ORGADMIN at the org level.',
  },
  {
    id: 'd1_d6_17',
    domain: 1,
    topic: 'Micro-partitions',
    difficulty: 'hard',
    q: 'Snowflake stores per-column metadata in each micro-partition\'s header. Which set of statistics is stored per column in micro-partition metadata?',
    options: [
      'Row count only — used for cardinality estimates during query planning',
      'Min value, max value, null count, and distinct count approximation per column — these are used by the query optimizer for micro-partition pruning',
      'Average value, standard deviation, and median per column — used by the cost-based optimizer',
      'Bloom filter and checksum per column — used for exact value matching without scanning',
    ],
    answer: 'Min value, max value, null count, and distinct count approximation per column — these are used by the query optimizer for micro-partition pruning',
    exp: 'Each micro-partition header records min/max per column (enabling range-based pruning), null count, and distinct value approximations. If a WHERE clause value falls outside the min/max range for a partition, that partition is pruned without being scanned. This is the core of Snowflake\'s automatic pruning — no index required.',
  },
  {
    id: 'd1_d6_18',
    domain: 1,
    topic: 'Snowpark Container Services',
    difficulty: 'hard',
    q: 'A Snowpark Container Services workload requires a GPU-enabled environment for a PyTorch model. What Snowflake object allocates the virtual machine nodes for container execution?',
    options: [
      'A Snowpark-Optimized Warehouse — the 16× memory tier supports GPU workloads',
      'A standard virtual warehouse resized to 4XL, which activates GPU acceleration',
      'A Compute Pool — a set of Snowflake-managed VM instances (separate from virtual warehouses) that host containerized services',
      'A Task with ALLOW_OVERLAPPING_EXECUTION = TRUE to distribute GPU work across nodes',
    ],
    answer: 'A Compute Pool — a set of Snowflake-managed VM instances (separate from virtual warehouses) that host containerized services',
    exp: 'Snowpark Container Services uses Compute Pools, which are pools of VMs with configurable instance families (including GPU options). They are distinct from virtual warehouses. You CREATE COMPUTE POOL with a specified instance type and size range, and containers run as Snowflake Services on those nodes.',
  },
  {
    id: 'd1_d6_19',
    domain: 1,
    topic: 'Data Types',
    difficulty: 'hard',
    q: 'A geospatial analyst needs to calculate great-circle distances between global GPS coordinates spanning multiple continents. Which Snowflake data type correctly models spherical earth geometry?',
    options: [
      'GEOGRAPHY — models objects on a spherical (WGS84) earth, giving accurate real-world distance and area calculations',
      'GEOMETRY — models objects on a Euclidean flat plane, best for real-world global distance',
      'VARIANT — store lat/lon as JSON and compute distances with custom UDFs for flexibility',
      'FLOAT PAIR — store latitude and longitude as two separate FLOAT columns for maximum compatibility',
    ],
    answer: 'GEOGRAPHY — models objects on a spherical (WGS84) earth, giving accurate real-world distance and area calculations',
    exp: 'GEOGRAPHY uses the WGS84 spherical model, making it accurate for global coordinates, distances, and area calculations. GEOMETRY uses a flat Euclidean plane — appropriate for local/projected coordinates but inaccurate for global distances where earth\'s curvature matters.',
  },

  // ── DOMAIN 2: Account Management & Governance (12 questions) ─────────────
  // 1 easy · 4 medium · 7 hard

  {
    id: 'd2_d6_01',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'easy',
    q: 'Your company uses Okta as an IdP. SAML 2.0 handles single-sign-on login. What does SCIM add on top of SAML?',
    options: [
      'SCIM adds MFA push notifications on top of SAML password authentication',
      'SCIM replaces SAML for role-based access token exchange',
      'SCIM automates user and group lifecycle management (provisioning/deprovisioning sync from the IdP) — SAML only handles authentication, not identity lifecycle',
      'SCIM enables Snowflake to issue SAML assertions back to the IdP for reverse SSO',
    ],
    answer: 'SCIM automates user and group lifecycle management (provisioning/deprovisioning sync from the IdP) — SAML only handles authentication, not identity lifecycle',
    exp: 'SAML 2.0 = who you are (authenticate). SCIM = keeping Snowflake users/roles in sync with the IdP directory (create user on hire, deactivate on termination, sync group→role mappings). They are complementary, not competing.',
  },

  {
    id: 'd2_d6_02',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'Which authentication app does Snowflake natively integrate with for MFA push notifications and TOTP codes?',
    options: [
      'Duo Security — Snowflake\'s native MFA integration uses Duo for push approvals and one-time passcodes',
      'Google Authenticator — Snowflake exclusively uses Google\'s TOTP standard',
      'Microsoft Authenticator — Snowflake uses Microsoft Entra ID for MFA',
      'Any RFC 6238 TOTP app — Snowflake is completely authenticator-agnostic',
    ],
    answer: 'Duo Security — Snowflake\'s native MFA integration uses Duo for push approvals and one-time passcodes',
    exp: 'Snowflake\'s built-in MFA is powered by Duo Security. Users can enroll via Duo Mobile for push notifications or TOTP codes. Third-party IdP flows (SAML/OAuth) can bring their own MFA, but Snowflake\'s native MFA specifically uses Duo.',
  },
  {
    id: 'd2_d6_03',
    domain: 2,
    topic: 'Data Lineage',
    difficulty: 'medium',
    q: 'A data engineer queries SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES. What type of dependencies does this view capture?',
    options: [
      'Runtime access patterns — objects that a query actually read during execution',
      'Network-level dependencies — connectivity between Snowflake VPC endpoints',
      'Physical storage dependencies — which micro-partitions are shared between zero-copy clones',
      'Compile-time (DDL) dependencies — objects referenced in view, stored procedure, and function definitions at creation time',
    ],
    answer: 'Compile-time (DDL) dependencies — objects referenced in view, stored procedure, and function definitions at creation time',
    exp: 'OBJECT_DEPENDENCIES captures static, compile-time references — for example, a view that references a table, or a stored procedure that calls a UDF. It does NOT capture runtime query access (use ACCESS_HISTORY for that). It helps you understand what breaks if you rename or drop an object.',
  },
  {
    id: 'd2_d6_04',
    domain: 2,
    topic: 'Resource Monitors',
    difficulty: 'medium',
    q: 'An account admin creates a Resource Monitor and assigns it to a virtual warehouse. Which credit usage does the monitor NOT track or control?',
    options: [
      'Query credits consumed by queries running on the assigned warehouse',
      'Serverless feature credits — automatic clustering, Snowpipe, materialized view refresh, and task execution are outside Resource Monitor scope',
      'Multi-cluster expansion credits when the warehouse spins up additional clusters',
      'Credits from queries run by any role using that warehouse',
    ],
    answer: 'Serverless feature credits — automatic clustering, Snowpipe, materialized view refresh, and task execution are outside Resource Monitor scope',
    exp: 'Resource Monitors only control virtual warehouse compute credits. Serverless compute (Snowpipe, automatic clustering, serverless tasks, MV refresh, Search Optimization) is billed separately and cannot be capped by a Resource Monitor. You need to track serverless costs via ACCOUNT_USAGE views instead.',
  },
  {
    id: 'd2_d6_05',
    domain: 2,
    topic: 'Alerts',
    difficulty: 'medium',
    q: 'You create an Alert without specifying a WAREHOUSE parameter. What compute resource powers the alert\'s condition evaluation?',
    options: [
      'The account\'s default virtual warehouse is used automatically',
      'A shared system warehouse borrowed from SYSADMIN\'s default',
      'Serverless compute — Alerts run on Snowflake-managed serverless infrastructure by default, requiring no virtual warehouse',
      'Alert creation fails if no warehouse is specified — a warehouse is mandatory',
    ],
    answer: 'Serverless compute — Alerts run on Snowflake-managed serverless infrastructure by default, requiring no virtual warehouse',
    exp: 'Alerts default to serverless compute (similar to serverless Tasks), so no virtual warehouse is required. You can optionally specify a warehouse, but most alert conditions (simple SQL queries) run efficiently as serverless. Serverless alerts are billed to the serverless credit pool, not to any warehouse.',
  },

  {
    id: 'd2_d6_06',
    domain: 2,
    topic: 'Dynamic Data Masking',
    difficulty: 'hard',
    q: 'In Snowflake\'s Dynamic Data Masking governance workflow, which roles handle policy CREATION vs policy ASSIGNMENT to a column?',
    options: [
      'A designated Policy Admin role (custom) creates the masking policy objects; any role with ALTER TABLE privilege on the target table can then SET the policy on a specific column',
      'SECURITYADMIN creates all masking policies; SYSADMIN sets them on table columns',
      'The table OWNER role can both create AND apply masking policies on tables it owns',
      'Only ACCOUNTADMIN can create masking policies; setting them on columns requires no special privilege',
    ],
    answer: 'A designated Policy Admin role (custom) creates the masking policy objects; any role with ALTER TABLE privilege on the target table can then SET the policy on a specific column',
    exp: 'Snowflake recommends a centralized POLICY_ADMIN custom role (with CREATE MASKING POLICY on the schema) to create policy objects. Setting the policy on a column requires ALTER privilege on the table. These two concerns are deliberately separated so policy authors and table admins can be different teams.',
  },
  {
    id: 'd2_d6_07',
    domain: 2,
    topic: 'Encryption',
    difficulty: 'hard',
    q: 'Snowflake uses a hierarchical key management model. Which correctly lists the four key hierarchy levels from top (root) to bottom (data)?',
    options: [
      'Account Key → Root Key → Table Key → Column Encryption Key',
      'Cloud KMS Key → Snowflake Root Key → Schema Key → Row Encryption Key',
      'Root Key → Account Key → Schema Key → Column Encryption Key',
      'Root Key → Account Key → Table Key → File Encryption Key',
    ],
    answer: 'Root Key → Account Key → Table Key → File Encryption Key',
    exp: 'Snowflake\'s key hierarchy: (1) Root Key (Snowflake-managed or customer-provided via Tri-Secret Secure) → (2) Account Key (per-account) → (3) Table Key (per-table) → (4) File Encryption Key (per micro-partition file). This layered model allows key rotation at any level without re-encrypting the underlying data.',
  },
  {
    id: 'd2_d6_08',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'hard',
    q: 'Your company uses Auth0 as an OAuth 2.0 authorization server. Users should authenticate to Snowflake using Auth0-issued JWTs. Which Snowflake DDL object must be created to enable this?',
    options: [
      'CREATE AUTHENTICATION POLICY with TYPE = EXTERNAL_JWT referencing the Auth0 JWKS endpoint',
      'CREATE SECURITY INTEGRATION with TYPE = EXTERNAL_OAUTH — this configures Snowflake to validate JWTs issued by the third-party OAuth server',
      'CREATE NETWORK POLICY with ALLOWED_IP_LIST pointing to Auth0\'s authorization server IPs',
      'CREATE API INTEGRATION to register the Auth0 token endpoint in Snowflake\'s API gateway',
    ],
    answer: 'CREATE SECURITY INTEGRATION with TYPE = EXTERNAL_OAUTH — this configures Snowflake to validate JWTs issued by the third-party OAuth server',
    exp: 'External OAuth is configured with a SECURITY INTEGRATION of type EXTERNAL_OAUTH. It tells Snowflake which IdP issues tokens (via EXTERNAL_OAUTH_ISSUER), how to validate them (JWKS URI), and which Snowflake roles to map to. AUTHENTICATION POLICY handles Snowflake-native auth methods, not external JWT validation.',
  },
  {
    id: 'd2_d6_09',
    domain: 2,
    topic: 'Row Access Policies',
    difficulty: 'hard',
    q: 'A Row Access Policy is applied to the orders table. User A (ANALYST role, sees all rows) queries it and the result is cached. User B (VIEWER role, sees only their region\'s rows per the RAP) runs the exact same SQL. What does Snowflake do?',
    options: [
      'Snowflake serves User B the same cached result as User A — the result cache is shared across all users for the same SQL',
      'Snowflake checks if User B\'s role qualifies for the cached result and serves it if the RAP returns the same rows',
      'Snowflake re-executes the query for User B — Row Access Policies prevent cross-role result cache sharing because different roles may see different rows',
      'Snowflake raises a PERMISSION DENIED error — users with restricted RAP access cannot use the result cache at all',
    ],
    answer: 'Snowflake re-executes the query for User B — Row Access Policies prevent cross-role result cache sharing because different roles may see different rows',
    exp: 'When a Row Access Policy is present, Snowflake cannot safely share cached results across roles because each role may receive a different subset of rows. The result cache key includes the active role context, so User B\'s query is re-executed to apply the correct row filter, even if the SQL is identical.',
  },
  {
    id: 'd2_d6_10',
    domain: 2,
    topic: 'Object Tagging',
    difficulty: 'hard',
    q: 'You call SYSTEM$CLASSIFY(\'MY_DB.PUBLIC.CUSTOMERS\', {}) to auto-classify a table. What does the function output?',
    options: [
      'A JSON object mapping each column name to recommended privacy category tags (e.g., NAME, EMAIL, PHONE_NUMBER) and associated sensitivity levels — which you can then apply with ALTER TABLE SET TAG',
      'A list of roles that have accessed the table in the last 90 days',
      'A list of existing masking policies already applied to the table\'s columns',
      'A boolean TRUE if the table contains PII, FALSE otherwise',
    ],
    answer: 'A JSON object mapping each column name to recommended privacy category tags (e.g., NAME, EMAIL, PHONE_NUMBER) and associated sensitivity levels — which you can then apply with ALTER TABLE SET TAG',
    exp: 'SYSTEM$CLASSIFY analyzes column names and sample data to recommend Snowflake system privacy tags (like SNOWFLAKE.CORE.EMAIL, SNOWFLAKE.CORE.PHONE_NUMBER). The output is a JSON recommendation object. You then decide which recommendations to apply using ALTER TABLE SET TAG or SYSTEM$APPLY_CLASSIFY_RESULT.',
  },
  {
    id: 'd2_d6_11',
    domain: 2,
    topic: 'Data Lineage',
    difficulty: 'hard',
    q: 'A company uses dbt for transformations on an external compute layer and wants that pipeline lineage visible in Snowflake\'s data lineage graph alongside internal Snowflake lineage. Which mechanism does Snowflake support for ingesting external lineage events?',
    options: [
      'Manual tagging via CREATE TAG with LINEAGE_SOURCE = EXTERNAL on each dbt-generated table',
      'SYSTEM$REGISTER_EXTERNAL_LINEAGE stored procedure — called after each dbt run with a JSON payload',
      'Native dbt integration — Snowflake auto-detects dbt lineage from query history without configuration',
      'The OpenLineage REST API — Snowflake exposes an OpenLineage-compatible endpoint that accepts lineage events from tools like dbt, Apache Airflow, and Spark',
    ],
    answer: 'The OpenLineage REST API — Snowflake exposes an OpenLineage-compatible endpoint that accepts lineage events from tools like dbt, Apache Airflow, and Spark',
    exp: 'Snowflake\'s external lineage feature is built on the OpenLineage open standard. Tools that emit OpenLineage events (dbt with openlineage-dbt, Airflow with OpenLineage provider) can push job/dataset events to Snowflake\'s OpenLineage API, stitching external pipeline steps into the native Snowflake lineage graph visible in Snowsight.',
  },
  {
    id: 'd2_d6_12',
    domain: 2,
    topic: 'Row Access Policies',
    difficulty: 'hard',
    q: 'A Row Access Policy on the salary table grants full row visibility only to the HR_ADMIN custom role. ACCOUNTADMIN is NOT granted the HR_ADMIN role. When ACCOUNTADMIN queries the salary table, what happens?',
    options: [
      'ACCOUNTADMIN sees all rows — it has elevated privileges that bypass data access policies',
      'ACCOUNTADMIN sees only the rows the Row Access Policy grants based on its active roles — RAPs apply to ALL roles including ACCOUNTADMIN',
      'ACCOUNTADMIN gets an insufficient privileges error and cannot query the table at all',
      'ACCOUNTADMIN must run USE SECONDARY ROLES ALL to inherit HR_ADMIN\'s row visibility',
    ],
    answer: 'ACCOUNTADMIN sees only the rows the Row Access Policy grants based on its active roles — RAPs apply to ALL roles including ACCOUNTADMIN',
    exp: 'Row Access Policies are enforced for ALL roles including ACCOUNTADMIN. There is no RAP bypass for any built-in role. If ACCOUNTADMIN is not included in the policy condition, it gets filtered results (or no rows if the default is deny). This is a common exam trap — ACCOUNTADMIN is NOT exempt from data governance policies.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ───────
  // 1 easy · 4 medium · 6 hard

  {
    id: 'd3_d6_01',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'easy',
    q: 'When a Snowpipe pipe triggers on an SQS notification (AUTO_INGEST = TRUE on AWS), which compute resource executes the COPY INTO load?',
    options: [
      'The virtual warehouse named in the pipe\'s COPY INTO statement',
      'Snowflake-managed serverless compute — Snowpipe does not require or consume a user-defined virtual warehouse',
      'The SYSADMIN role\'s default virtual warehouse',
      'A dedicated system warehouse automatically created per pipe',
    ],
    answer: 'Snowflake-managed serverless compute — Snowpipe does not require or consume a user-defined virtual warehouse',
    exp: 'Snowpipe runs on Snowflake\'s serverless compute, which means you are charged serverless compute credits rather than virtual warehouse credits. No warehouse needs to be running or specified. This makes Snowpipe cost-efficient for sporadic, event-driven loading.',
  },

  {
    id: 'd3_d6_02',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'A developer runs PUT file:///data/report.csv @my_stage with no additional options. What compression is applied to the file before upload?',
    options: [
      'None — PUT uploads files as-is with no compression by default',
      'Brotli — Snowflake uses Brotli compression for CSV files to maximize compression ratio',
      'LZ4 — the default for fast, low-CPU compression in Snowflake\'s staging layer',
      'GZIP — PUT automatically compresses the file with GZIP before uploading to the stage',
    ],
    answer: 'GZIP — PUT automatically compresses the file with GZIP before uploading to the stage',
    exp: 'PUT defaults to AUTO_COMPRESS = TRUE with GZIP compression. The resulting file gets a .gz extension in the stage. You can disable this with PUT ... AUTO_COMPRESS = FALSE or change the algorithm with SOURCE_COMPRESSION. COPY INTO handles decompression transparently.',
  },
  {
    id: 'd3_d6_03',
    domain: 3,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'In a LATERAL FLATTEN query, multiple columns are produced. Which column contains the actual value of each expanded element (e.g., each item in an array)?',
    options: [
      'VALUE — contains the actual content of each flattened element (the array item or object field\'s value)',
      'INDEX — contains the element\'s content; PATH contains the zero-based position',
      'KEY — contains the element value for both arrays and objects',
      'SEQ — a unique sequence number that also holds the element value for identification',
    ],
    answer: 'VALUE — contains the actual content of each flattened element (the array item or object field\'s value)',
    exp: 'FLATTEN produces: SEQ (sequence number per input row), KEY (object key or NULL for arrays), INDEX (zero-based position), VALUE (the element\'s value), PATH (full path string to the element), THIS (the element itself). VALUE is what you typically use to extract data from the expanded elements.',
  },
  {
    id: 'd3_d6_04',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'You run SELECT * FROM TABLE(INFER_SCHEMA(LOCATION=>\'@my_stage\', FILE_FORMAT=>\'my_parquet_fmt\')). What does this query return?',
    options: [
      'A set of COPY INTO statements pre-built and ready to execute for loading the stage files',
      'A row-sample preview of the first 10 rows from each Parquet file in the stage',
      'A result set with one row per detected column, showing the inferred column name, Snowflake data type, and nullable flag',
      'A VARIANT object containing the full Parquet schema as nested JSON',
    ],
    answer: 'A result set with one row per detected column, showing the inferred column name, Snowflake data type, and nullable flag',
    exp: 'INFER_SCHEMA inspects the staged files and returns a tabular schema: COLUMN_NAME, TYPE, NULLABLE, and EXPRESSION columns (the EXPRESSION is a SQL snippet for the COPY INTO column mapping). It is the foundation for GENERATE_COLUMN_DESCRIPTION and automating COPY INTO column lists.',
  },
  {
    id: 'd3_d6_05',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'medium',
    q: 'A Task has WHEN SYSTEM$STREAM_HAS_DATA(\'orders_stream\') defined. The stream is empty when the task\'s scheduled time arrives. What does Snowflake do?',
    options: [
      'The task runs anyway — the MERGE in the task body handles an empty stream gracefully with zero rows processed',
      'The task is skipped for this scheduled interval — the WHEN condition is evaluated first and the task only executes if the stream contains unconsumed data',
      'Snowflake raises an error because SYSTEM$STREAM_HAS_DATA cannot be used as a WHEN condition on a root task',
      'The stream is forcibly refreshed, and if still empty after refresh, the task suspends itself permanently',
    ],
    answer: 'The task is skipped for this scheduled interval — the WHEN condition is evaluated first and the task only executes if the stream contains unconsumed data',
    exp: 'WHEN SYSTEM$STREAM_HAS_DATA(\'stream_name\') acts as a guard clause. If the stream is empty at scheduled execution time, Snowflake skips the task entirely for that interval — saving compute and preventing no-op runs. The task will run at the next scheduled time and check the stream again.',
  },

  {
    id: 'd3_d6_06',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'hard',
    q: 'A Parquet file has columns [order_id, customer_id, amount] but the target table has them in a different order: [amount, order_id, customer_id]. Which COPY INTO option maps columns by name instead of position?',
    options: [
      'FILE_FORMAT = (COLUMN_MATCH = TRUE) — a file format option that enables name-based mapping',
      'COPY INTO target (order_id, customer_id, amount) FROM (SELECT order_id, customer_id, amount FROM @stage) — explicit select list reorders columns',
      'ALTER TABLE target SET COLUMN_ORDER = FILE_MATCH before running COPY INTO',
      'COPY INTO target FROM @stage FILE_FORMAT = ... MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE',
    ],
    answer: 'COPY INTO target FROM @stage FILE_FORMAT = ... MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE',
    exp: 'MATCH_BY_COLUMN_NAME (CASE_SENSITIVE or CASE_INSENSITIVE) is a COPY INTO option that maps file columns to table columns by name, ignoring positional order. This is especially useful for Parquet and ORC files that carry schema metadata. CASE_INSENSITIVE handles files where column capitalization differs from the table definition.',
  },
  {
    id: 'd3_d6_07',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'hard',
    q: 'Files were cloud-event-notified to a Snowpipe but the target table shows no new rows. Where should an engineer look FIRST to diagnose the failure?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY — records every Snowpipe and COPY INTO load with STATUS, ERROR_MESSAGE, ROWS_LOADED, and ROWS_PARSED — the primary audit trail for load failures',
      'INFORMATION_SCHEMA.PIPES — contains error logs for the last 10 pipe executions',
      'SHOW PIPES — the STATUS column shows any recent error messages',
      'The virtual warehouse query history — Snowpipe loads appear there like regular queries',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY — records every Snowpipe and COPY INTO load with STATUS, ERROR_MESSAGE, ROWS_LOADED, and ROWS_PARSED — the primary audit trail for load failures',
    exp: 'COPY_HISTORY in ACCOUNT_USAGE is the correct diagnostic for Snowpipe failures. It shows STATUS (\'Loaded\', \'Load failed\', \'Partially loaded\'), ERROR_MESSAGE, file name, rows loaded vs parsed, and timestamps. SHOW PIPES shows the pipe\'s last refresh time and state, not per-file error details. INFORMATION_SCHEMA.COPY_HISTORY exists but has shorter retention.',
  },
  {
    id: 'd3_d6_08',
    domain: 3,
    topic: 'Streams',
    difficulty: 'hard',
    q: 'A stream on the orders table includes a METADATA$ROW_ID column alongside METADATA$ACTION and METADATA$ISUPDATE. What does METADATA$ROW_ID represent?',
    options: [
      'The primary key value of the changed row — Snowflake infers this from the table\'s PRIMARY KEY constraint',
      'A sequential number indicating the DML operation order within a transaction',
      'An opaque Snowflake-internal identifier that uniquely tracks the physical row across inserts, updates, and deletes — enabling CDC correlation when there is no natural primary key',
      'The micro-partition file ID where the changed row\'s new version physically resides',
    ],
    answer: 'An opaque Snowflake-internal identifier that uniquely tracks the physical row across inserts, updates, and deletes — enabling CDC correlation when there is no natural primary key',
    exp: 'METADATA$ROW_ID is a stable, internal row identifier assigned by Snowflake. It is NOT a user-visible primary key — it is an opaque handle used to correlate the DELETE and INSERT pair that represents a single UPDATE in a standard (non-append-only) stream, enabling accurate change data capture even on tables without a defined PK.',
  },
  {
    id: 'd3_d6_09',
    domain: 3,
    topic: 'Dynamic Tables',
    difficulty: 'hard',
    q: 'Which of the following objects CANNOT serve as a direct source in a Dynamic Table\'s defining SELECT query?',
    options: [
      'A permanent Snowflake table in the same schema',
      'A standard (non-materialized, non-secure) view that joins multiple tables',
      'Another Dynamic Table from the same database',
      'A Snowflake Stream object — Streams are consumed by Tasks; they are not valid sources for Dynamic Tables',
    ],
    answer: 'A Snowflake Stream object — Streams are consumed by Tasks; they are not valid sources for Dynamic Tables',
    exp: 'Dynamic Tables support declarative incremental pipelines that can reference tables, views, and other Dynamic Tables as sources. However, Dynamic Tables do NOT consume Streams directly — Streams are paired with Tasks. If you are already using Dynamic Tables, you do not need Streams+Tasks for that pipeline.',
  },
  {
    id: 'd3_d6_10',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'hard',
    q: 'A company uploads files to an S3-backed external stage using Client-Side Encryption (CSE) with a customer-managed key. What is the defining characteristic of CSE vs Server-Side Encryption (SSE)?',
    options: [
      'SSE secures data in transit over HTTPS; CSE encrypts data after it lands in S3',
      'With CSE, the customer encrypts the file BEFORE uploading — Snowflake never receives the plaintext; with SSE, S3 applies encryption after the file arrives (Snowflake sees plaintext on ingest)',
      'Both CSE and SSE use AWS KMS — the only difference is which AWS service manages the key (S3 vs KMS)',
      'CSE requires a Snowflake Business Critical account; SSE is available on all editions',
    ],
    answer: 'With CSE, the customer encrypts the file BEFORE uploading — Snowflake never receives the plaintext; with SSE, S3 applies encryption after the file arrives (Snowflake sees plaintext on ingest)',
    exp: 'Client-Side Encryption means encryption happens on the client BEFORE the data leaves the local system. The cloud storage provider (S3) and Snowflake only ever see ciphertext. Server-Side Encryption delegates encryption to S3/Azure/GCS after upload. CSE requires the customer to manage key material and pass it to the PUT command.',
  },
  {
    id: 'd3_d6_11',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'hard',
    q: 'What is the PRIMARY architectural difference between classic Snowpipe (AUTO_INGEST) and Snowpipe Streaming (SDK-based)?',
    options: [
      'Classic Snowpipe processes file-based batches triggered by cloud storage events (no staging files needed); Snowpipe Streaming accepts continuous row-level data via the Ingest SDK with sub-second latency — no file staging required',
      'Classic Snowpipe uses virtual warehouse credits; Snowpipe Streaming uses only serverless credits',
      'Snowpipe Streaming is exclusively for Kafka; classic Snowpipe works with any file type',
      'Classic Snowpipe lands data in external stages; Snowpipe Streaming bypasses staging into internal tables',
    ],
    answer: 'Classic Snowpipe processes file-based batches triggered by cloud storage events (no staging files needed); Snowpipe Streaming accepts continuous row-level data via the Ingest SDK with sub-second latency — no file staging required',
    exp: 'Classic Snowpipe ingests staged files (event-triggered via SQS/Event Grid/Pub/Sub). Snowpipe Streaming ingests rows directly through the Ingest SDK without needing to stage a file first, enabling near-real-time (sub-second) latency. Both use serverless compute, but the ingestion model — file-based vs row-streaming — is the key architectural difference.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (13 questions) ───────
  // 1 easy · 6 medium · 6 hard

  {
    id: 'd4_d6_01',
    domain: 4,
    topic: 'Caching',
    difficulty: 'easy',
    q: 'A developer runs ALTER SESSION SET USE_CACHED_RESULT = FALSE and re-executes a recent query. What is the effect?',
    options: [
      'The cached result for all users who ran this SQL is deleted from the result cache',
      'The local SSD cache on the warehouse nodes is flushed before the query runs',
      'The result cache is bypassed for this session only — Snowflake re-executes the query against the data even if a valid cached result exists',
      'The query runs in read-only mode and cannot update any result tables',
    ],
    answer: 'The result cache is bypassed for this session only — Snowflake re-executes the query against the data even if a valid cached result exists',
    exp: 'USE_CACHED_RESULT = FALSE is a session-level parameter that disables result cache for queries in that session. Other sessions are unaffected. Useful for benchmarking or when you need fresh results regardless of cache status. The cached result itself is not deleted — other sessions can still use it.',
  },

  {
    id: 'd4_d6_02',
    domain: 4,
    topic: 'UDFs',
    difficulty: 'medium',
    q: 'A developer wants to write a UDF that makes an outbound HTTP call to enrich data from a third-party REST API. They choose JavaScript. Will this work and why?',
    options: [
      'Yes — JavaScript UDFs support the fetch() API for HTTP calls',
      'Yes — but only after registering an API Integration object first',
      'No — JavaScript UDFs run in a sandboxed environment without network access, file system access, or multi-threading; use External Functions for HTTP callouts instead',
      'No — JavaScript UDFs are deprecated; all new UDFs must be written in Python',
    ],
    answer: 'No — JavaScript UDFs run in a sandboxed environment without network access, file system access, or multi-threading; use External Functions for HTTP callouts instead',
    exp: 'JavaScript UDFs are fully sandboxed: no I/O, no network calls, no file system, no spawning threads. For external API calls from SQL, use CREATE EXTERNAL FUNCTION with an API Integration (which routes through an AWS API Gateway or Azure Function). Python UDFs can access approved packages, but direct HTTP egress also requires careful setup.',
  },
  {
    id: 'd4_d6_03',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A query must group sales records by region and collect all product SKUs sold in each region into a single ARRAY. Which SQL aggregate function achieves this?',
    options: [
      'ARRAY_AGG(sku) — collects multiple row values into an ARRAY within each GROUP BY group',
      'COLLECT_LIST(sku) — Snowflake\'s dedicated array aggregation function',
      'OBJECT_CONSTRUCT(sku, 1) — builds an OBJECT keyed by each SKU value',
      'LISTAGG(sku, \',\') — concatenates SKUs into a comma-separated string, not an ARRAY',
    ],
    answer: 'ARRAY_AGG(sku) — collects multiple row values into an ARRAY within each GROUP BY group',
    exp: 'ARRAY_AGG is Snowflake\'s aggregate function that returns a VARIANT ARRAY. LISTAGG produces a string. COLLECT_LIST is a Spark/Hive function, not native Snowflake SQL. Use ARRAY_AGG when the consumer expects a VARIANT column or when nesting in semi-structured output.',
  },
  {
    id: 'd4_d6_04',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'A Query Profile TableScan node shows Partitions Scanned = 800 out of Partitions Total = 850. What does this indicate?',
    options: [
      'Poor pruning — almost all micro-partitions are scanned, suggesting the WHERE filter is not aligned with the clustering key (or no clustering key exists)',
      'Excellent pruning — a 94% scan rate means only 6% of partitions were needlessly read',
      'The table will automatically recluster since the scan ratio exceeds 90%',
      'The 50-partition difference indicates 50 partitions were served from the result cache',
    ],
    answer: 'Poor pruning — almost all micro-partitions are scanned, suggesting the WHERE filter is not aligned with the clustering key (or no clustering key exists)',
    exp: 'Effective pruning means the ratio of partitions_scanned / partitions_total should be LOW. Scanning 800/850 = 94% means the clustering metadata offers almost no benefit for this filter — either the filter column is not the clustering key, or the data\'s natural sort order doesn\'t align with the query\'s filter. Consider adding or changing the clustering key.',
  },
  {
    id: 'd4_d6_05',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A VARIANT column profile contains {"name":"Alice","age":null,"city":"Paris"}. You call STRIP_NULL_VALUES(profile). What is returned?',
    options: [
      '{"name":"Alice","age":0,"city":"Paris"} — null values are replaced with 0',
      'An error — STRIP_NULL_VALUES only operates on ARRAY types, not OBJECT types',
      '{"name":"Alice","city":"Paris"} — key-value pairs where the value is SQL NULL are removed from the VARIANT OBJECT',
      'null — if any top-level key has a null value, the entire VARIANT is replaced with null',
    ],
    answer: '{"name":"Alice","city":"Paris"} — key-value pairs where the value is SQL NULL are removed from the VARIANT OBJECT',
    exp: 'STRIP_NULL_VALUES(variant_val) removes any object key whose value is NULL from a VARIANT OBJECT (recursively). It is the counterpart to OBJECT_CONSTRUCT_KEEP_NULL. Useful for cleaning up JSON before sharing or inserting into downstream systems that reject null-valued keys.',
  },
  {
    id: 'd4_d6_06',
    domain: 4,
    topic: 'SQL Transformations',
    difficulty: 'medium',
    q: 'A table monthly_sales has columns (product, month, revenue). You need one row per product with separate columns for each month value (Jan, Feb, Mar). Which SQL feature achieves this?',
    options: [
      'UNPIVOT — rotates column headers into rows',
      'FLATTEN — expands array elements into rows',
      'LATERAL JOIN with VALUES clause — maps month string values to column positions',
      'PIVOT — rotates the distinct values of the month column into separate output columns with aggregated revenue',
    ],
    answer: 'PIVOT — rotates the distinct values of the month column into separate output columns with aggregated revenue',
    exp: 'PIVOT transforms rows into columns by rotating unique values from a specified column into column headers. UNPIVOT does the reverse (columns → rows). FLATTEN is for arrays/objects. The Snowflake PIVOT syntax: SELECT * FROM monthly_sales PIVOT(SUM(revenue) FOR month IN (\'Jan\',\'Feb\',\'Mar\')).',
  },
  {
    id: 'd4_d6_07',
    domain: 4,
    topic: 'SQL Transformations',
    difficulty: 'medium',
    q: 'A window function uses RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW. When does this differ in behavior from ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW?',
    options: [
      'ROWS counts exact row positions one-by-one; RANGE includes ALL rows with the same ORDER BY value as the current row (peer rows / ties) — they differ only when there are duplicate ORDER BY values',
      'RANGE only applies to numeric ORDER BY columns; ROWS applies to all data types',
      'RANGE and ROWS are exact synonyms in Snowflake SQL',
      'ROWS can span multiple PARTITION BY groups; RANGE is restricted to a single partition',
    ],
    answer: 'ROWS counts exact row positions one-by-one; RANGE includes ALL rows with the same ORDER BY value as the current row (peer rows / ties) — they differ only when there are duplicate ORDER BY values',
    exp: 'With ROWS, the frame boundary is the exact physical row count. With RANGE, the frame includes all rows with values equal to the boundary value (peer/tie handling). For a running sum: if three rows share the same ORDER BY date, RANGE includes all three in the current row\'s window, while ROWS stops at the physical position of the current row.',
  },

  {
    id: 'd4_d6_08',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'hard',
    q: 'What is the operational difference between ALTER TABLE orders SUSPEND RECLUSTER and ALTER TABLE orders DROP CLUSTERING KEY?',
    options: [
      'SUSPEND RECLUSTER pauses the background automatic reclustering service but RETAINS the clustering key definition; DROP CLUSTERING KEY removes the key definition entirely, stopping all future reclustering',
      'SUSPEND RECLUSTER removes existing clustering metadata; DROP CLUSTERING KEY only pauses background maintenance',
      'They are functionally identical — SUSPEND RECLUSTER is just an alias for DROP CLUSTERING KEY',
      'DROP CLUSTERING KEY immediately re-sorts all existing micro-partitions into natural order; SUSPEND prevents only future automatic sorting',
    ],
    answer: 'SUSPEND RECLUSTER pauses the background automatic reclustering service but RETAINS the clustering key definition; DROP CLUSTERING KEY removes the key definition entirely, stopping all future reclustering',
    exp: 'SUSPEND RECLUSTER temporarily stops the background reclustering service (saves costs while the table is quiescent) but the clustering key definition stays — you can RESUME RECLUSTER later. DROP CLUSTERING KEY permanently removes the key definition. After DROP, you must CLUSTER BY again and reclustering will not restart automatically.',
  },
  {
    id: 'd4_d6_09',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'hard',
    q: 'You run SHOW MATERIALIZED VIEWS on a heavily updated table. One MV shows BEHIND_BY = \'00:04:32\'. What does this value indicate?',
    options: [
      'The MV has consumed 4 minutes 32 seconds of serverless refresh compute and is approaching its budget',
      'Four MV refresh jobs have been queued but not yet started',
      'The MV is stale — base table changes made in the last 4 minutes 32 seconds have not yet been reflected in the materialized view',
      'The MV was created 4 minutes 32 seconds ago and has not been queried yet',
    ],
    answer: 'The MV is stale — base table changes made in the last 4 minutes 32 seconds have not yet been reflected in the materialized view',
    exp: 'BEHIND_BY in SHOW MATERIALIZED VIEWS shows the lag between the MV\'s last successful refresh and the base table\'s most recent data. A non-zero BEHIND_BY means the MV is stale by that duration. Snowflake\'s serverless background refresh aims to keep MVs fresh, but under heavy DML load the refresh can lag behind.',
  },
  {
    id: 'd4_d6_10',
    domain: 4,
    topic: 'Search Optimization Service',
    difficulty: 'hard',
    q: 'A table has a STRING column description. Common queries include WHERE CONTAINS(description, \'shipment\') and WHERE description LIKE \'%invoice%\'. Which service best accelerates these substring searches?',
    options: [
      'Defining a clustering key on description — min/max metadata will prune partitions for substring patterns',
      'Creating a Materialized View pre-filtering rows containing the top 50 most searched keywords',
      'Pinning the table in the result cache with ALTER TABLE SET RESULT_CACHE_SCOPE = ALL',
      'Search Optimization Service — it supports SUBSTRING predicates (CONTAINS, LIKE with leading wildcards, ILIKE) in addition to equality point lookups',
    ],
    answer: 'Search Optimization Service — it supports SUBSTRING predicates (CONTAINS, LIKE with leading wildcards, ILIKE) in addition to equality point lookups',
    exp: 'Search Optimization Service (SOS) is specifically designed for point lookup and substring searches. Clustering keys help with range queries but cannot help with leading-wildcard LIKE patterns — because min/max metadata is useless for \'%keyword%\'. SOS builds a search access path (stored as additional storage) that enables fast substring matches without full scans.',
  },
  {
    id: 'd4_d6_11',
    domain: 4,
    topic: 'Stored Procedures',
    difficulty: 'hard',
    q: 'A stored procedure includes an explicit COMMIT statement. It is called inside an outer transaction: BEGIN TRANSACTION; CALL sp_orders(); COMMIT;. When the SP\'s COMMIT executes, what happens?',
    options: [
      'The SP\'s COMMIT commits only the rows modified inside the SP, leaving the outer transaction\'s pre-SP changes still pending',
      'The SP\'s COMMIT is silently ignored — stored procedures cannot issue a COMMIT when called within an active outer transaction',
      'The SP\'s COMMIT commits ALL pending changes in the entire active transaction — both pre-SP statements and the SP\'s own work — ending the transaction prematurely',
      'Snowflake raises an error: "COMMIT not allowed inside a stored procedure called within a transaction"',
    ],
    answer: 'The SP\'s COMMIT commits ALL pending changes in the entire active transaction — both pre-SP statements and the SP\'s own work — ending the transaction prematurely',
    exp: 'Snowflake does NOT support nested transactions (savepoints). An explicit COMMIT inside a stored procedure commits the ENTIRE active transaction — including any DML done before the CALL. After the SP returns, the outer COMMIT in the calling code finds no active transaction to commit. This is a common exam trap about transaction isolation in stored procedures.',
  },
  {
    id: 'd4_d6_12',
    domain: 4,
    topic: 'Dynamic Tables',
    difficulty: 'hard',
    q: 'Dynamic Table dt_enriched JOINs dt_base and dt_lookup — both are Dynamic Tables with TARGET_LAG = \'1 minute\'. What should dt_enriched\'s TARGET_LAG be set to in order to consistently join fresh data from both sources?',
    options: [
      'Exactly \'1 minute\' — all Dynamic Tables in a pipeline must use identical lag to stay synchronized',
      'TARGET_LAG of dt_enriched should be greater than or equal to the lag of its source DTs — setting it to \'1 minute\' or more ensures dt_base and dt_lookup have refreshed before dt_enriched computes the join',
      'Dynamic Tables cannot JOIN other Dynamic Tables — use Streams and Tasks for multi-stage pipelines instead',
      'TARGET_LAG is irrelevant when joining two Dynamic Tables — Snowflake auto-synchronizes their refresh cycles',
    ],
    answer: 'TARGET_LAG of dt_enriched should be greater than or equal to the lag of its source DTs — setting it to \'1 minute\' or more ensures dt_base and dt_lookup have refreshed before dt_enriched computes the join',
    exp: 'Snowflake automatically infers refresh dependencies in Dynamic Table pipelines. Setting dt_enriched\'s TARGET_LAG >= its sources\' lag ensures downstream tables always read freshly-refreshed upstream data. Setting it lower (e.g., \'30 seconds\') could cause dt_enriched to read stale data from dt_base or dt_lookup that haven\'t refreshed yet.',
  },
  {
    id: 'd4_d6_13',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'hard',
    q: 'Query Acceleration Service (QAS, Enterprise edition) is enabled on a warehouse. The team runs two workloads: routine 5-second OLAP queries and occasional deep-dive scans that take 8 minutes and scan 100× more data than typical. Which workload does QAS MOST benefit?',
    options: [
      'The occasional 8-minute deep-dive "outlier" scans — QAS offloads their disproportionately large partitioned scans to elastic serverless compute, reducing both execution time and impact on the shared warehouse',
      'The routine 5-second OLAP queries — QAS reduces their execution time close to zero by precomputing their results',
      'Both equally — QAS improves throughput uniformly across all query sizes on the warehouse',
      'Neither — QAS only applies to queries that are explicitly tagged with ALTER QUERY SET ACCELERATION = TRUE',
    ],
    answer: 'The occasional 8-minute deep-dive "outlier" scans — QAS offloads their disproportionately large partitioned scans to elastic serverless compute, reducing both execution time and impact on the shared warehouse',
    exp: 'Query Acceleration Service targets "outlier" queries — queries that are significantly slower and scan significantly more data than the warehouse\'s typical workload. It offloads the heavy scan portions to elastic compute, freeing the warehouse for regular queries. Routine small queries already run well on the warehouse and benefit little from QAS.',
  },

  // ── DOMAIN 5: Data Collaboration (5 questions) ────────────────────────────
  // 1 easy · 3 medium · 1 hard

  {
    id: 'd5_d6_01',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'easy',
    q: 'A data provider creates a Reader Account for a consumer who does not have a Snowflake account. The consumer runs queries against shared data. Who pays for the compute credits used by those queries?',
    options: [
      'The consumer pays based on their actual query volume',
      'The data provider pays for all compute credits consumed in the Reader Account — this cost appears in the provider\'s Snowflake bill',
      'Snowflake absorbs the cost — Reader Account compute is free for both parties',
      'Compute costs are split 50/50 between provider and Snowflake',
    ],
    answer: 'The data provider pays for all compute credits consumed in the Reader Account — this cost appears in the provider\'s Snowflake bill',
    exp: 'Reader Accounts are Snowflake accounts fully managed and billed by the data provider. The provider absorbs all compute costs when the consumer runs queries. This makes Reader Accounts suitable for scenarios where the consumer should not need their own Snowflake account or billing relationship.',
  },

  {
    id: 'd5_d6_02',
    domain: 5,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'medium',
    q: 'A developer accidentally runs DROP SCHEMA prod.reporting. The schema contained 15 tables and 5 views. They immediately run UNDROP SCHEMA prod.reporting. What is restored?',
    options: [
      'Only the schema container itself — tables and views must be individually UNDROPped afterwards',
      'The schema plus all tables but not views — views are not storage objects and cannot be recovered via UNDROP',
      'Nothing — UNDROP requires a minimum Time Travel retention of 7 days, and the schema had the account default of 1 day',
      'The schema AND all objects (tables, views, stages, etc.) that existed inside it at the time of DROP — UNDROP restores the entire container and its contents',
    ],
    answer: 'The schema AND all objects (tables, views, stages, etc.) that existed inside it at the time of DROP — UNDROP restores the entire container and its contents',
    exp: 'UNDROP SCHEMA restores the schema AND all objects it contained at the time of the DROP — including tables (with their data and Time Travel history), views, stages, and other schema-level objects. This is a key difference from UNDROP TABLE which only restores a single object.',
  },
  {
    id: 'd5_d6_03',
    domain: 5,
    topic: 'Marketplace',
    difficulty: 'medium',
    q: 'A data company wants to publish a free listing on the Snowflake Marketplace. What is the correct high-level sequence?',
    options: [
      'First publish the listing, then attach a Secure Share — listings can be created before data is ready',
      'Create a database → grant SELECT to the PUBLIC role → the database is automatically listed on the Marketplace',
      'Create a Secure Share → attach it to a Marketplace listing → add pricing, description, and sample data → submit for listing review and publication',
      'Create a Reader Account → attach to a listing — only Reader Accounts can serve as Marketplace data sources',
    ],
    answer: 'Create a Secure Share → attach it to a Marketplace listing → add pricing, description, and sample data → submit for listing review and publication',
    exp: 'A Marketplace listing requires a Secure Share as its data source. The provider creates the share (with GRANT SELECT ON TABLE TO SHARE), then creates a listing in Provider Studio, attaches the share, adds metadata (description, sample queries, data dictionary), sets pricing (free or paid), and submits for Snowflake review before it becomes publicly visible.',
  },
  {
    id: 'd5_d6_04',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'A data consumer has built daily reports against a shared table from a provider. The provider then drops that shared table from their account. What happens when the consumer next queries it?',
    options: [
      'The consumer retains a Time Travel snapshot of the table as it was when the provider dropped it — valid for 90 days',
      'The consumer receives an "object does not exist" or access denied error — the dropped shared object is immediately unavailable',
      'The consumer is automatically notified by email and given 30 days to retrieve the data',
      'The consumer\'s query runs against the Fail-safe copy of the dropped table for 7 days',
    ],
    answer: 'The consumer receives an "object does not exist" or access denied error — the dropped shared object is immediately unavailable',
    exp: 'When a provider drops a table that is part of a share, the consumer immediately loses access — there is no grace period. Since the consumer database is a live read-only pointer to the provider\'s objects, any removal on the provider side is instantly reflected on the consumer side. This is a key risk to document in data-sharing SLAs.',
  },

  {
    id: 'd5_d6_05',
    domain: 5,
    topic: 'Zero-copy Cloning',
    difficulty: 'hard',
    q: 'A developer runs CREATE TABLE orders_backup CLONE orders_transient, where orders_transient is a TRANSIENT table. What is the table type and Fail-safe status of orders_backup?',
    options: [
      'orders_backup is a PERMANENT table — cloning promotes the table type to permanent by default',
      'The clone operation fails — transient tables cannot be the source of a CLONE operation',
      'orders_backup is a TRANSIENT table (clones inherit the source\'s table type) and therefore has ZERO days of Fail-safe — only Time Travel up to 1 day maximum',
      'orders_backup has 7 days of Fail-safe because CLONE always creates a permanent copy with default account settings',
    ],
    answer: 'orders_backup is a TRANSIENT table (clones inherit the source\'s table type) and therefore has ZERO days of Fail-safe — only Time Travel up to 1 day maximum',
    exp: 'Clones inherit the source\'s table type. Cloning a TRANSIENT table creates another TRANSIENT table — no Fail-safe, Time Travel limited to 0 or 1 day. This is a common exam trap: developers assume CLONE creates a permanent backup, but if the source is transient, the clone offers no Fail-safe protection either. To get a permanent copy, use CREATE TABLE ... AS SELECT or explicitly specify the new table with no CLONE modifier.',
  },
];
