// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 5  (2026-03-26)
// COF-C03 Mock Exam · 60 questions
// Distribution: D1 31% (19q) | D2 20% (12q) | D3 18% (11q) | D4 21% (13q) | D5 10% (5q)
// Difficulty mix: ~30% Easy, ~50% Medium, ~20% Hard
//
// DAILY GENERATION RULE:
//   Each new day of questions must share ≤ 30% overlap with the previous day.
//   Before writing a new day, list the question IDs from the previous file and
//   ensure fewer than 18 of the 60 questions are repeated verbatim.
//   Rotate topics, scenarios, and SQL examples each day.
//
// ANSWER POSITION RULE (added Day 5):
//   Correct answers are deliberately spread across positions A/B/C/D (~25% each).
//   The longest option is intentionally NOT always the correct one.
//
// DAY 5 vs DAY 4 OVERLAP CHECK:
//   Day 4 covered: multi-cluster shared data concept, Business Critical (PrivateLink/PHI),
//   VPS, SQL API auth, Terraform, External Tables, Snowpark-optimized WH, OPERATE privilege,
//   MAXIMIZED mode, 90-day TT max, AES-256 micro-partition, Cortex Analyst, Document AI,
//   Notebooks, account-level objects, MODIFY privilege, billing for continuous session, Secure
//   view for sharing, Iceberg tables, DAC, GRANT OWNERSHIP + COPY CURRENT GRANTS, SECURITYADMIN,
//   key-pair, OAuth 2.0, Aggregation Policy, Tri-Secret Secure, QUERY_HISTORY, COPY_HISTORY,
//   Trust Center CIS, GET_LINEAGE, SUSPEND_IMMEDIATE, User stage privacy, Storage Integration,
//   COPY INTO unload, PURGE=TRUE, AUTO_INGEST SQS, REMOVE command, INFER_SCHEMA/Parquet,
//   SnowCD, API Integration, Kafka Connector, Dynamic Table INITIALIZE, SSD cache eviction,
//   result cache + DML invalidation, broadcast joins, compound clustering key, MV vs result
//   cache difference, Search Opt billing, FLATTEN, UDTF, SP EXECUTE AS OWNER, GROUPING SETS,
//   Exchange node, function wrapping breaks pruning, Snowpark lazy eval, UNDROP DATABASE,
//   TT storage cost, DB-level clone, database roles in sharing, Private Data Exchange.
//
//   Day 5 fresh angles (~0 verbatim repeats): Cloud Services billing daily UTC rule,
//   Standard edition Time Travel max, VS Code Extension, Horizon Data Discovery / Security &
//   Governance pillars, MANAGE WAREHOUSES privilege, Cortex ML Functions, STANDARD policy
//   trigger condition, Streamlit in Snowflake governance, External table REFRESH, Cortex
//   SUMMARIZE, micro-partition OR-predicate pruning, CREATE SCHEMA privilege, auto-created
//   schemas (PUBLIC + INFORMATION_SCHEMA), table stage @%, USE SECONDARY ROLES, ACCOUNTADMIN
//   unique tasks, MFA enforcement via Session Policy, Row Access Policy DDL, TAG_REFERENCES,
//   WAREHOUSE_METERING_HISTORY, CREATE ALERT + SUSPEND state, NOTIFICATION INTEGRATION + webhook,
//   network policy user-level override scenario, SECURITY_VIEWER, Replication Group objects,
//   custom role orphan anti-pattern, SKIP_HEADER CSV, load history 64-day expiry, Snowpipe REST
//   API insertFiles, Stream offset advancement rule (SELECT does NOT advance), Task CRON syntax,
//   dbt + Snowflake, GET command, Avro loading, STORAGE_ALLOWED_LOCATIONS, METADATA$ACTION,
//   result cache exact SQL match, SHOW + COUNT* metadata cache, Sort node in Query Profile,
//   spill to remote severity, SYSTEM$CLUSTERING_INFORMATION average_depth, MV + CURRENT_DATE
//   restriction, PARSE_JSON colon notation, scalar Python UDF, Dynamic Table incremental vs full
//   refresh, QUALIFY + ROW_NUMBER, COPY GRANTS on replaced view, CTE lifetime, MERGE + stream
//   offset advancement, AT (BEFORE STATEMENT), CREATE DATABASE FROM SHARE, Native Apps Framework,
//   Marketplace free listing billing, clone + stream objects.
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 5,
  date: '2026-03-26',
  label: 'Day 5 — Mixed Scenarios',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (19 questions) ─────────────────────

  {
    id: 'd1_d5_01',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'Snowflake calculates the Cloud Services credit adjustment once per UTC calendar day. Under what condition are Cloud Services credits actually billed to the customer?',
    options: [
      'Daily in UTC — when Cloud Services usage exceeds 10% of that day\'s virtual warehouse credits, the overage is billed',
      'Always — Cloud Services is billed at a flat rate regardless of warehouse usage',
      'Hourly — Cloud Services is billed if usage exceeds 10% of warehouse credits in any single hour',
      'Never — Cloud Services is always included in the cost of virtual warehouse credits',
    ],
    answer: 'Daily in UTC — when Cloud Services usage exceeds 10% of that day\'s virtual warehouse credits, the overage is billed',
    exp: 'Cloud Services runs continuously but Snowflake gives a daily free adjustment of 10% of VWH credits. The daily calculation window is UTC. Only the excess above 10% is charged. Heavy use of SHOW commands, metadata ops, or serverless features can trigger the charge.',
  },
  {
    id: 'd1_d5_02',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'easy',
    q: 'What is the maximum DATA_RETENTION_TIME_IN_DAYS setting allowed for a PERMANENT table on Standard edition?',
    options: [
      '7 days',
      '30 days',
      '90 days',
      '1 day',
    ],
    answer: '1 day',
    exp: 'Standard edition supports Time Travel retention of 0 or 1 day only. Enterprise+ unlocks up to 90 days for permanent tables. Transient and Temporary tables are capped at 1 day on ALL editions.',
  },
  {
    id: 'd1_d5_03',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'What is the primary purpose of the Snowflake VS Code Extension?',
    options: [
      'It deploys Snowflake databases and warehouses using Terraform directly from VS Code',
      'It replicates the full Snowsight UI inside VS Code for account management',
      'It enables developers to write, execute, and debug Snowflake SQL and Snowpark code in VS Code with native Snowflake connectivity, syntax highlighting, and IntelliSense',
      'It connects to Snowflake Git Repositories and syncs branches automatically to local projects',
    ],
    answer: 'It enables developers to write, execute, and debug Snowflake SQL and Snowpark code in VS Code with native Snowflake connectivity, syntax highlighting, and IntelliSense',
    exp: 'The Snowflake VS Code Extension integrates Snowflake directly into VS Code: connect to accounts, run SQL, write and run Snowpark Python/Java/Scala, browse object trees, and see results — all without leaving the IDE.',
  },
  {
    id: 'd1_d5_04',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'The Snowflake Horizon Catalog includes a "Data Discovery" pillar. Which capability best describes what it provides?',
    options: [
      'Automatic discovery of cloud storage buckets to create external stages without manual configuration',
      'Discovery and recommendation of Snowflake Marketplace listings based on an account\'s existing data schemas',
      'Automatic generation of ER diagrams and data dictionaries from table column names',
      'A unified catalog with AI-powered classification of sensitive data, search across all assets, and lineage tracking — helping teams find, understand, and trust data',
    ],
    answer: 'A unified catalog with AI-powered classification of sensitive data, search across all assets, and lineage tracking — helping teams find, understand, and trust data',
    exp: 'The Data Discovery pillar of Snowflake Horizon provides: Snowflake Search (across tables/columns/queries), auto-classification of PII/sensitive data types, object lineage, and data profiles — enabling a governed data catalog experience natively inside Snowflake.',
  },
  {
    id: 'd1_d5_05',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'Which GLOBAL (account-level) privilege allows a role to create, resize, suspend, and drop ANY virtual warehouse in the account — without needing per-warehouse grants?',
    options: [
      'MODIFY on each warehouse individually',
      'CREATE WAREHOUSE granted on the account',
      'MANAGE WAREHOUSES',
      'OPERATE on each warehouse individually',
    ],
    answer: 'MANAGE WAREHOUSES',
    exp: 'MANAGE WAREHOUSES is a global privilege that gives full control over all warehouses in the account without needing per-object grants. Typically granted to DBAs or ops roles. CREATE WAREHOUSE allows only creating new warehouses, not managing existing ones.',
  },
  {
    id: 'd1_d5_06',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'A data analyst wants to generate automated FORECASTS and ANOMALY DETECTION on sales data using only SQL — no Python or external ML tools. Which Snowflake feature enables this?',
    options: [
      'Cortex ML Functions (SNOWFLAKE.ML.FORECAST, SNOWFLAKE.ML.ANOMALY_DETECTION)',
      'Snowpark ML Modeling API (requires a Python Snowpark session)',
      'SNOWFLAKE.CORTEX.COMPLETE() with a time-series prompt template',
      'Snowflake Notebooks with scikit-learn installed as a package',
    ],
    answer: 'Cortex ML Functions (SNOWFLAKE.ML.FORECAST, SNOWFLAKE.ML.ANOMALY_DETECTION)',
    exp: 'Cortex ML Functions are SQL-callable, no-code ML capabilities. SNOWFLAKE.ML.FORECAST trains a time-series model and returns predictions. SNOWFLAKE.ML.ANOMALY_DETECTION finds statistical outliers. No Python, no external tools — pure SQL.',
  },
  {
    id: 'd1_d5_07',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'hard',
    q: 'A multi-cluster warehouse uses scaling policy STANDARD, MIN_CLUSTER_COUNT = 1, MAX_CLUSTER_COUNT = 5. Two clusters are already running. Under what EXACT condition does STANDARD policy start a 3rd cluster?',
    options: [
      'As soon as any query must wait in the queue because all running clusters are fully occupied',
      'When average cluster utilization across all running clusters exceeds 80%',
      'When the queue has been non-empty for at least 60 consecutive seconds',
      'When the number of queued queries exceeds 10 per running cluster',
    ],
    answer: 'As soon as any query must wait in the queue because all running clusters are fully occupied',
    exp: 'STANDARD policy is aggressive — it starts a new cluster immediately when any query is queued. ECONOMY policy waits until the estimated load justifies running the cluster for ≥6 minutes. STANDARD prioritizes speed over cost.',
  },
  {
    id: 'd1_d5_08',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'A Streamlit app is deployed using Streamlit in Snowflake (SiS). Under which identity does the app execute and access Snowflake data?',
    options: [
      'A shared service account created specifically for the Streamlit app deployment',
      'The ACCOUNTADMIN role — SiS apps require elevated privileges to access any data',
      'The Snowflake identity of the end user viewing the app — subject to that user\'s grants and active role',
      'The PUBLIC role, since Streamlit apps must be accessible to all users',
    ],
    answer: 'The Snowflake identity of the end user viewing the app — subject to that user\'s grants and active role',
    exp: 'SiS apps run with the viewer\'s own Snowflake identity and role. This means row-level security, masking policies, and role-based grants all apply normally. No shared service account or elevated privilege is needed for data access.',
  },
  {
    id: 'd1_d5_09',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'easy',
    q: 'Which DML operations (INSERT, UPDATE, DELETE) can be performed on a Snowflake External Table?',
    options: [
      'INSERT only — external tables support appending new rows to the underlying stage files',
      'All three — INSERT, UPDATE, and DELETE are fully supported via stage file modifications',
      'UPDATE only — column values can be changed without altering file structure',
      'None — external tables are read-only and no DML is permitted',
    ],
    answer: 'None — external tables are read-only and no DML is permitted',
    exp: 'External tables are read-only views over files in cloud object storage. No INSERT, UPDATE, DELETE, or MERGE is supported. To modify the data you must modify the underlying files externally. Also requires manual REFRESH to detect new or changed files.',
  },
  {
    id: 'd1_d5_10',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A warehouse (XS = 1 credit/hr) is started, runs a 5-second query, then manually suspended. This happens twice in the same hour. How many total seconds are billed?',
    options: [
      '10 seconds — only actual execution time is billed',
      '60 seconds — one 60-second minimum applies to the whole hour regardless of starts',
      '120 seconds — each warehouse START incurs a separate 60-second minimum',
      '300 seconds — Snowflake rounds up to the nearest 5-minute block per start',
    ],
    answer: '120 seconds — each warehouse START incurs a separate 60-second minimum',
    exp: 'Each time a warehouse STARTS (resumes from suspended state), a 60-second minimum billing applies. Two separate starts = two minimums = 120 seconds billed. This is why suspending and immediately restarting a warehouse frequently can be costly.',
  },
  {
    id: 'd1_d5_11',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'easy',
    q: 'How is a Snowflake table stage (e.g., @%orders) created?',
    options: [
      'It is created automatically for every Snowflake table — no CREATE STAGE DDL is needed',
      'With CREATE STAGE @%orders TYPE = TABLE in the schema',
      'By running ALTER TABLE orders ADD STAGE',
      'It is created only for tables that have a primary key defined',
    ],
    answer: 'It is created automatically for every Snowflake table — no CREATE STAGE DDL is needed',
    exp: 'Every Snowflake table gets an automatic table stage (@%table_name). No DDL required — it exists from the moment the table is created. It is private to the table and can be used to stage files for COPY INTO that table.',
  },
  {
    id: 'd1_d5_12',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'hard',
    q: 'A Snowpark DataFrame is written using df.write.mode("overwrite").saveAsTable("analytics.results"). The table "analytics.results" already exists with different data. What happens?',
    options: [
      'The existing table is dropped and recreated with the DataFrame\'s schema, then loaded with the new data',
      'Only new rows from the DataFrame are inserted; existing rows are unchanged',
      'The operation fails — OVERWRITE mode is not supported in Snowpark write operations',
      'The DataFrame data is written to a new table version, and the old table is archived automatically',
    ],
    answer: 'The existing table is dropped and recreated with the DataFrame\'s schema, then loaded with the new data',
    exp: 'mode("overwrite") in Snowpark is equivalent to CREATE OR REPLACE TABLE — it drops the existing table and creates a new one with the new data and schema. To append instead, use mode("append"). To error on existing table, use mode("errorifexists").',
  },
  {
    id: 'd1_d5_13',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'The Snowflake Horizon Catalog has a "Security & Governance" pillar. Which set of capabilities falls under it?',
    options: [
      'Only user authentication (MFA, SSO, key-pair) and network policies',
      'Only data encryption at rest (AES-256) and in transit (TLS)',
      'Snowflake Marketplace security reviews and vendor due diligence checks',
      'Dynamic Data Masking, Row Access Policies, Object Tagging, auto-classification, Privacy Policies, Trust Center, and Access History',
    ],
    answer: 'Dynamic Data Masking, Row Access Policies, Object Tagging, auto-classification, Privacy Policies, Trust Center, and Access History',
    exp: 'The Security & Governance pillar covers all the fine-grained data protection features: DDM, RAPs, tags, PII classification, aggregation policies, Trust Center security scanning, and data access audit trails via ACCESS_HISTORY.',
  },
  {
    id: 'd1_d5_14',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'When you run CREATE DATABASE mydb in Snowflake, which schemas are automatically present in mydb immediately after creation?',
    options: [
      'PUBLIC and INFORMATION_SCHEMA',
      'Only PUBLIC',
      'SYSTEM, PUBLIC, and INFORMATION_SCHEMA',
      'Only INFORMATION_SCHEMA',
    ],
    answer: 'PUBLIC and INFORMATION_SCHEMA',
    exp: 'Every new Snowflake database includes two auto-created schemas: PUBLIC (a regular, writable default schema) and INFORMATION_SCHEMA (a virtual, read-only system schema with views about the database\'s objects and metadata).',
  },
  {
    id: 'd1_d5_15',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'New files are added to the S3 location backing a Snowflake External Table. Which command makes them queryable via the external table?',
    options: [
      'REFRESH EXTERNAL TABLE my_ext_table',
      'SYNC TABLE my_ext_table FROM STAGE',
      'No command needed — external tables detect new files in real time automatically',
      'ALTER EXTERNAL TABLE my_ext_table REFRESH',
    ],
    answer: 'ALTER EXTERNAL TABLE my_ext_table REFRESH',
    exp: 'ALTER EXTERNAL TABLE … REFRESH scans the external stage and updates the external table\'s metadata to reflect new, modified, or deleted files. Without this, new files are invisible to queries. Auto-refresh can be enabled using event notifications (similar to Snowpipe).',
  },
  {
    id: 'd1_d5_16',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'easy',
    q: 'Which Snowflake Cortex function returns a concise, human-readable summary of a long text document?',
    options: [
      'SNOWFLAKE.CORTEX.SUMMARIZE(text)',
      'SNOWFLAKE.CORTEX.COMPLETE(model, text)',
      'SNOWFLAKE.CORTEX.EXTRACT_ANSWER(question, context)',
      'SNOWFLAKE.CORTEX.CLASSIFY_TEXT(text, categories)',
    ],
    answer: 'SNOWFLAKE.CORTEX.SUMMARIZE(text)',
    exp: 'CORTEX.SUMMARIZE() takes a text string and returns a concise summary. No model name needed — Snowflake picks the best hosted LLM automatically. Other specialized functions: EXTRACT_ANSWER for Q&A, CLASSIFY_TEXT for categorization, TRANSLATE for language translation.',
  },
  {
    id: 'd1_d5_17',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'hard',
    q: 'A table is clustered on region. A query filters: WHERE region = \'EU\' OR order_date > \'2025-12-31\'. A micro-partition contains ONLY region=\'US\' rows with all order_dates in 2024. Can Snowflake prune this partition?',
    options: [
      'Yes — since BOTH conditions are provably FALSE for this partition (region≠EU and all dates ≤ 2025-12-31), it can be safely skipped',
      'No — the OR operator always disables micro-partition pruning; only AND filters allow pruning',
      'Yes — the clustering key on region always skips non-EU partitions regardless of other conditions',
      'No — the second predicate (order_date) has no clustering key, so the entire scan is forced',
    ],
    answer: 'Yes — since BOTH conditions are provably FALSE for this partition (region≠EU and all dates ≤ 2025-12-31), it can be safely skipped',
    exp: 'With OR, a partition can only be pruned if EVERY branch of the OR is provably false. Since region=\'EU\' is false (partition has only \'US\') AND order_date > \'2025-12-31\' is false (all dates are in 2024), both sides of the OR are false — the partition is pruned.',
  },
  {
    id: 'd1_d5_18',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'To create a new table in schema ANALYTICS.SALES, which privileges are minimally required?',
    options: [
      'CREATE TABLE granted on the DATABASE',
      'CREATE TABLE on the SCHEMA and USAGE on the DATABASE',
      'SYSADMIN role only — no specific object-level grants are needed',
      'CREATE TABLE on the schema — USAGE on the DB is inherited automatically',
    ],
    answer: 'CREATE TABLE on the SCHEMA and USAGE on the DATABASE',
    exp: 'To create a table: USAGE on the database (to "enter" it), USAGE on the schema (to "enter" it), and CREATE TABLE on the schema. Without USAGE on the parent objects, the role cannot navigate the object hierarchy to reach the schema.',
  },
  {
    id: 'd1_d5_19',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A Snowflake external table is configured with AUTO_REFRESH = TRUE via a cloud event notification integration. What does this enable?',
    options: [
      'DML changes to the underlying files are automatically written back to Snowflake',
      'The external table automatically runs REFRESH when a cloud event (e.g., S3 PutObject) triggers — new files are immediately queryable without a manual ALTER EXTERNAL TABLE REFRESH',
      'Snowflake continuously polls the S3 bucket every 60 seconds and refreshes automatically',
      'AUTO_REFRESH = TRUE enables real-time streaming ingestion from external stage to a native table',
    ],
    answer: 'The external table automatically runs REFRESH when a cloud event (e.g., S3 PutObject) triggers — new files are immediately queryable without a manual ALTER EXTERNAL TABLE REFRESH',
    exp: 'AUTO_REFRESH uses cloud event notifications (SQS on AWS, Event Grid on Azure, Pub/Sub on GCP) to trigger automatic REFRESH when files are added. This eliminates the need for manual ALTER EXTERNAL TABLE … REFRESH commands and keeps the metadata up to date.',
  },

  // ── DOMAIN 2: Account Management & Governance (12 questions) ─────────────

  {
    id: 'd2_d5_01',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'easy',
    q: 'A user\'s primary role is ANALYST. They also have the DEVELOPER role. Which command activates DEVELOPER\'s privileges alongside ANALYST for the session without changing the primary role?',
    options: [
      'USE SECONDARY ROLES ALL;',
      'GRANT ROLE DEVELOPER TO SESSION;',
      'ALTER SESSION ADD ROLE DEVELOPER;',
      'USE ROLE ANALYST, DEVELOPER;',
    ],
    answer: 'USE SECONDARY ROLES ALL;',
    exp: 'USE SECONDARY ROLES ALL activates all granted roles as secondary roles. Privileges combine. The primary role (ANALYST) stays the same — new objects created in the session are still owned by ANALYST. USE SECONDARY ROLES NONE reverts to primary only.',
  },
  {
    id: 'd2_d5_02',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'Which task can ONLY ACCOUNTADMIN perform — not SECURITYADMIN or SYSADMIN?',
    options: [
      'Create network policies and assign them to users',
      'View account-level billing and credit usage in the Snowsight "Cost Management" tab',
      'Create and manage virtual warehouses',
      'Grant any privilege to any role',
    ],
    answer: 'View account-level billing and credit usage in the Snowsight "Cost Management" tab',
    exp: 'ACCOUNTADMIN is the only role with visibility into account billing, credit consumption, and the Cost Management section. SECURITYADMIN manages grants/roles, SYSADMIN manages data objects, neither can see billing details.',
  },
  {
    id: 'd2_d5_03',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'An admin wants ALL users in the account to be required to enroll in MFA before any Snowflake session. Which object enforces this?',
    options: [
      'Network Policy with MFA_REQUIRED = TRUE parameter',
      'ALTER ACCOUNT SET REQUIRE_MFA = TRUE (account-level parameter)',
      'A Session Policy applied at account level with MFA_ENROLLMENT = REQUIRED',
      'Resource Monitor with MFA_TRIGGER action',
    ],
    answer: 'A Session Policy applied at account level with MFA_ENROLLMENT = REQUIRED',
    exp: 'Session Policies can enforce MFA enrollment (REQUIRED, OPTIONAL) and session idle timeouts. Applying a Session Policy at the ACCOUNT level with MFA_ENROLLMENT = REQUIRED forces all users to complete MFA setup before they can log in.',
  },
  {
    id: 'd2_d5_04',
    domain: 2,
    topic: 'Data Masking',
    difficulty: 'hard',
    q: 'A Row Access Policy returns TRUE only when CURRENT_ROLE() = \'DATA_OWNER\' OR (CURRENT_ROLE() = \'ANALYST\' AND status = \'CLOSED\'). What does a user with role ANALYST see?',
    options: [
      'Only rows where status = \'CLOSED\'',
      'All rows — the OR condition means any matched clause returns all data',
      'No rows — ANALYST is not DATA_OWNER so the first clause always returns FALSE for them',
      'Only rows where status != \'CLOSED\' — the AND inverts the condition',
    ],
    answer: 'Only rows where status = \'CLOSED\'',
    exp: 'The policy returns TRUE for ANALYST rows only when status = \'CLOSED\'. All other rows return FALSE and are filtered out. Row Access Policies are transparent — no error is thrown; filtered rows simply don\'t appear in results.',
  },
  {
    id: 'd2_d5_05',
    domain: 2,
    topic: 'Object Tagging',
    difficulty: 'medium',
    q: 'Which ACCOUNT_USAGE view shows every Snowflake object that has a specific tag currently applied to it?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.OBJECT_TAGGING_HISTORY',
      'INFORMATION_SCHEMA.APPLIED_TAGS',
      'SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES',
      'SYSTEM$GET_TAG_REFERENCES(\'tag_name\')',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES',
    exp: 'TAG_REFERENCES shows every object in the account that has a tag applied (directly or via lineage). Includes object name, type, column name (for column-level tags), tag name, and value. Useful for data discovery and compliance reporting.',
  },
  {
    id: 'd2_d5_06',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'easy',
    q: 'A finance team needs to report on virtual warehouse credit consumption per day for the last 90 days. Which ACCOUNT_USAGE view should they query?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY with warehouse credits column',
      'SNOWFLAKE.ACCOUNT_USAGE.RESOURCE_MONITOR_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.CREDITS_BILLED',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY',
    exp: 'WAREHOUSE_METERING_HISTORY contains per-warehouse, per-hour credit consumption. Aggregate by DAY and warehouse to build billing reports. 1-year retention. QUERY_HISTORY shows per-query details but is not the right view for warehouse-level billing summaries.',
  },
  {
    id: 'd2_d5_07',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'An ALERT is created and configured correctly with a warehouse, condition query, and action. It never fires despite the condition being true. What is the most likely cause?',
    options: [
      'The alert requires Business Critical edition to execute',
      'ALERT objects are created in a SUSPENDED state by default and must be explicitly RESUMED with ALTER ALERT … RESUME',
      'The WAREHOUSE assigned to the alert must be a dedicated warehouse — shared warehouses are not supported',
      'Alerts only fire once per day regardless of how often the condition is met',
    ],
    answer: 'ALERT objects are created in a SUSPENDED state by default and must be explicitly RESUMED with ALTER ALERT … RESUME',
    exp: 'Like Tasks, Alerts are created in SUSPENDED state. They will not execute until you run ALTER ALERT alert_name RESUME. This is a common exam trap — created ≠ running.',
  },
  {
    id: 'd2_d5_08',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'An alert needs to POST a JSON payload to a Slack webhook URL when triggered. Which integration type supports this outbound notification?',
    options: [
      'Storage Integration — used for outbound HTTP calls to third-party services',
      'A NOTIFICATION INTEGRATION with TYPE = WEBHOOK, referencing the Slack webhook URL',
      'An API Integration pointing to the Slack API endpoint as an external function',
      'Git Integration — supports webhook-based triggers from external systems',
    ],
    answer: 'A NOTIFICATION INTEGRATION with TYPE = WEBHOOK, referencing the Slack webhook URL',
    exp: 'NOTIFICATION INTEGRATIONs support three push types: EMAIL (SMTP), QUEUE (SQS/SNS/GCS Pub/Sub/Azure Service Bus), and WEBHOOK (any HTTPS URL). Alerts call the integration via SYSTEM$SEND_SNOWFLAKE_NOTIFICATION() in their action body.',
  },
  {
    id: 'd2_d5_09',
    domain: 2,
    topic: 'Network Policies',
    difficulty: 'hard',
    q: 'Account-level network policy allows only 10.0.0.0/8. User BOB has a user-level policy allowing only 192.168.1.0/24. BOB connects from IP 10.0.0.5. Is the connection allowed?',
    options: [
      'Yes — when a user-level and account-level policy exist, Snowflake uses the UNION (most permissive) of both',
      'No — BOB\'s user-level policy overrides the account-level policy, and 10.0.0.5 is not in 192.168.1.0/24',
      'Yes — the account-level policy allows 10.0.0.0/8, and user-level policies only ADD restrictions on top',
      'No — any conflict between user-level and account-level policies results in an automatic deny',
    ],
    answer: 'No — BOB\'s user-level policy overrides the account-level policy, and 10.0.0.5 is not in 192.168.1.0/24',
    exp: 'User-level network policies OVERRIDE account-level policies for that user. BOB\'s policy allows only 192.168.1.0/24. Since 10.0.0.5 is not in that range, the connection is denied — even though the account policy would allow it.',
  },
  {
    id: 'd2_d5_10',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'A security analyst needs read access to LOGIN_HISTORY, SESSIONS, and GRANTS_TO_ROLES without being given ACCOUNTADMIN. Which SNOWFLAKE database role provides this?',
    options: [
      'GOVERNANCE_VIEWER — grants access to governance and tagging views',
      'OBJECT_VIEWER — grants access to object metadata views',
      'USAGE_VIEWER — grants access to resource usage views',
      'SECURITY_VIEWER — grants access to security and identity-related ACCOUNT_USAGE views',
    ],
    answer: 'SECURITY_VIEWER — grants access to security and identity-related ACCOUNT_USAGE views',
    exp: 'SECURITY_VIEWER grants SELECT on security-focused ACCOUNT_USAGE views: LOGIN_HISTORY, SESSIONS, GRANTS_TO_ROLES, GRANTS_TO_USERS, ROLES, USERS, POLICY_REFERENCES. Complements GOVERNANCE_VIEWER (tagging/masking) and USAGE_VIEWER (billing/compute).',
  },
  {
    id: 'd2_d5_11',
    domain: 2,
    topic: 'Replication',
    difficulty: 'medium',
    q: 'Which categories of objects can be included in a Snowflake Replication Group for cross-region replication?',
    options: [
      'Databases (tables, views, stages) and account-level objects (users, roles, warehouses, integrations, network policies)',
      'Only databases — account-level objects such as users and roles cannot be replicated',
      'Only tables and views — stages, pipes, streams, and tasks are excluded from replication',
      'All objects including active query history and ACCOUNT_USAGE view data',
    ],
    answer: 'Databases (tables, views, stages) and account-level objects (users, roles, warehouses, integrations, network policies)',
    exp: 'Replication Groups can include: databases and account-level objects. Account objects include: users, roles, warehouses, resource monitors, integrations, network policies, session policies. Query history and ACCOUNT_USAGE data are NOT replicated.',
  },
  {
    id: 'd2_d5_12',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'hard',
    q: 'A developer creates role ETL_LOADER, grants it table privileges, but forgets to grant ETL_LOADER to SYSADMIN. What is the consequence?',
    options: [
      'ETL_LOADER automatically rolls up to PUBLIC — ACCOUNTADMIN can still manage it via PUBLIC',
      'SYSADMIN and higher roles cannot manage objects owned by ETL_LOADER — they become orphaned from the standard role hierarchy',
      'Snowflake automatically links unconnected roles to SYSADMIN within 24 hours',
      'Only ACCOUNTADMIN can still access the objects — SYSADMIN is bypassed but security is not compromised',
    ],
    answer: 'SYSADMIN and higher roles cannot manage objects owned by ETL_LOADER — they become orphaned from the standard role hierarchy',
    exp: 'If a custom role is not granted up to SYSADMIN, SYSADMIN cannot inherit its privileges or manage its owned objects. This creates "orphan" objects that only ETL_LOADER (or ACCOUNTADMIN directly) can access. Best practice: always GRANT custom_role TO SYSADMIN.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ────────

  {
    id: 'd3_d5_01',
    domain: 3,
    topic: 'Stages',
    difficulty: 'easy',
    q: 'What is the correct syntax to reference the Snowflake table stage for a table named "sales"?',
    options: [
      '@%sales',
      '@~sales',
      '@sales',
      '@#sales',
    ],
    answer: '@%sales',
    exp: '@%<table_name> is the table stage. @~ is the user stage (current user). Named stages have no prefix other than @. @# is not a valid Snowflake stage syntax.',
  },
  {
    id: 'd3_d5_02',
    domain: 3,
    topic: 'File Formats',
    difficulty: 'medium',
    q: 'A CSV file has column names in the first row that must NOT be loaded as data. Which FILE FORMAT option skips the header row?',
    options: [
      'HEADER = FALSE',
      'IGNORE_HEADER_ROWS = 1',
      'SKIP_HEADER = 1',
      'FIRST_ROW_AS_HEADER = TRUE',
    ],
    answer: 'SKIP_HEADER = 1',
    exp: 'SKIP_HEADER = N skips the first N rows of a CSV file during COPY INTO. Setting it to 1 skips the header row. FIELD_OPTIONALLY_ENCLOSED_BY and TRIM_SPACE are other useful CSV options. The option is part of the FILE_FORMAT definition.',
  },
  {
    id: 'd3_d5_03',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'medium',
    q: 'A file was staged and loaded with COPY INTO 70 days ago. You want to reload it without FORCE = TRUE. Is this possible?',
    options: [
      'No — files in load history can never be re-loaded without FORCE = TRUE',
      'No — the file must be renamed first, then it can be loaded as a new file',
      'Yes — the 64-day load history window has expired; Snowflake no longer tracks this file as already loaded, so it will reload automatically',
      'Yes — but only ACCOUNTADMIN can reload files older than 60 days',
    ],
    answer: 'Yes — the 64-day load history window has expired; Snowflake no longer tracks this file as already loaded, so it will reload automatically',
    exp: 'COPY INTO tracks load history per stage/table for 64 days to prevent duplicate loads. After 64 days, the record expires — the file is treated as new and will be re-loaded on the next COPY INTO run without needing FORCE = TRUE.',
  },
  {
    id: 'd3_d5_04',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'medium',
    q: 'Instead of AUTO_INGEST event notifications, which Snowpipe mechanism lets an application programmatically trigger a load for specific files already in a stage?',
    options: [
      'EXECUTE PIPE my_pipe FOR FILES = (\'path/file.csv\');',
      'Snowpipe REST API — POST to the /v1/data/pipes/{pipeName}/insertFiles endpoint with a list of file paths',
      'ALTER PIPE my_pipe TRIGGER FILES = (\'path/file.csv\');',
      'CALL SYSTEM$PIPE_FORCE_LOAD(\'my_pipe\', \'path/file.csv\');',
    ],
    answer: 'Snowpipe REST API — POST to the /v1/data/pipes/{pipeName}/insertFiles endpoint with a list of file paths',
    exp: 'The Snowpipe REST API (insertFiles endpoint) lets applications push a list of staged file paths to Snowpipe for immediate serverless ingestion — no cloud event notification setup required. Useful when you control the file production pipeline externally.',
  },
  {
    id: 'd3_d5_05',
    domain: 3,
    topic: 'Streams',
    difficulty: 'hard',
    q: 'A stored procedure queries a stream with SELECT * FROM my_stream but never executes any DML using the results. After the procedure completes, what is the stream\'s offset?',
    options: [
      'Advanced to the latest state — any SELECT on a stream consumes and advances it',
      'Advanced only if the SELECT returned at least one row',
      'Unchanged — the stream offset only advances when DML changes are consumed in a COMMITTED transaction (INSERT, MERGE, etc.)',
      'Reset to the beginning — unconsumed streams roll back their offset automatically',
    ],
    answer: 'Unchanged — the stream offset only advances when DML changes are consumed in a COMMITTED transaction (INSERT, MERGE, etc.)',
    exp: 'A SELECT on a stream does NOT advance the offset — it just reads the current change records without consuming them. The offset only advances when a DML statement (INSERT INTO … SELECT FROM stream, MERGE … USING stream) is executed and COMMITTED.',
  },
  {
    id: 'd3_d5_06',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'medium',
    q: 'A Task must run at 6:00 AM UTC every weekday (Monday through Friday). Which SCHEDULE value is correct?',
    options: [
      'SCHEDULE = \'USING CRON 0 6 * * 1-5 UTC\'',
      'SCHEDULE = \'AT 06:00 UTC WEEKDAYS\'',
      'SCHEDULE = \'CRON(0, 6, *, *, MON-FRI, UTC)\'',
      'SCHEDULE = \'EVERY DAY AT 06:00 WHERE WEEKDAY = TRUE\'',
    ],
    answer: 'SCHEDULE = \'USING CRON 0 6 * * 1-5 UTC\'',
    exp: 'Snowflake Tasks use standard cron syntax: USING CRON minute hour day-of-month month day-of-week timezone. 0 6 * * 1-5 = minute 0, hour 6, any day of month, any month, Mon(1)–Fri(5). The timezone suffix (e.g., UTC, America/New_York) is appended after the 5 cron fields.',
  },
  {
    id: 'd3_d5_07',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'easy',
    q: 'dbt (data build tool) is used with Snowflake in a modern data stack. What does dbt primarily handle?',
    options: [
      'Raw data ingestion from external sources (APIs, databases) into Snowflake staging tables',
      'SQL-based data transformation inside Snowflake — defining models, running tests, and generating documentation and lineage',
      'Monitoring and alerting on Snowflake warehouse cost anomalies',
      'Infrastructure-as-code for provisioning Snowflake databases and warehouses',
    ],
    answer: 'SQL-based data transformation inside Snowflake — defining models, running tests, and generating documentation and lineage',
    exp: 'dbt focuses on the T in ELT — it transforms data already in Snowflake using SQL SELECT models. It handles dependency ordering, incremental models, data quality tests (not_null, unique, accepted_values), and generates interactive docs with lineage graphs.',
  },
  {
    id: 'd3_d5_08',
    domain: 3,
    topic: 'Stages',
    difficulty: 'easy',
    q: 'Which Snowflake command downloads a specific file FROM an internal stage TO the local filesystem?',
    options: [
      'GET @mystage/reports/q1.csv file:///C:/Downloads/',
      'PULL @mystage/reports/q1.csv TO file:///C:/Downloads/',
      'COPY FROM @mystage/reports/q1.csv TO file:///C:/Downloads/',
      'EXPORT @mystage/reports/q1.csv LOCAL \'/C:/Downloads/\'',
    ],
    answer: 'GET @mystage/reports/q1.csv file:///C:/Downloads/',
    exp: 'GET @<stage_path> file://<local_path> downloads files from a Snowflake internal stage to the local filesystem. Works in SnowSQL and JDBC/ODBC drivers. Not available in Snowsight. The reverse (upload) is PUT file://<local> @<stage>.',
  },
  {
    id: 'd3_d5_09',
    domain: 3,
    topic: 'File Formats',
    difficulty: 'hard',
    q: 'When loading an Avro file into a Snowflake table with a single VARIANT column, how is an individual Avro record accessed and how is a specific field extracted?',
    options: [
      'Each Avro record field is automatically mapped to a separate typed column in the target table',
      'The entire Avro record is stored in column $1 as VARIANT; field access uses colon notation: $1:field_name::TARGET_TYPE',
      'Avro must be converted to JSON or Parquet before loading — native Avro loading is not supported',
      'Avro records are stored as ARRAY elements — access uses $1[0]:field_name notation',
    ],
    answer: 'The entire Avro record is stored in column $1 as VARIANT; field access uses colon notation: $1:field_name::TARGET_TYPE',
    exp: 'Like Parquet and JSON, Avro data lands in $1 as a VARIANT. Extract fields with: SELECT $1:user_id::NUMBER, $1:name::VARCHAR FROM @stage (FILE_FORMAT => my_avro_ff). INFER_SCHEMA works on Avro to auto-detect the schema.',
  },
  {
    id: 'd3_d5_10',
    domain: 3,
    topic: 'Stages',
    difficulty: 'medium',
    q: 'A Storage Integration has STORAGE_ALLOWED_LOCATIONS = (\'s3://prod-bucket/data/\'). An external stage references this integration. Which file path can this stage successfully access?',
    options: [
      's3://prod-bucket/data/2026/march/orders.csv',
      's3://prod-bucket/archive/old_data.csv — same bucket, different prefix',
      's3://other-bucket/data/file.csv — Storage Integrations are not bucket-specific',
      's3://prod-bucket/ — allowed locations grant access to the entire bucket',
    ],
    answer: 's3://prod-bucket/data/2026/march/orders.csv',
    exp: 'STORAGE_ALLOWED_LOCATIONS is a path prefix allowlist. Any file under s3://prod-bucket/data/ (including subfolders) is accessible. Paths outside that prefix (like /archive/) or in other buckets are blocked — even if using the same integration.',
  },
  {
    id: 'd3_d5_11',
    domain: 3,
    topic: 'Streams',
    difficulty: 'easy',
    q: 'What value appears in the METADATA$ACTION column of a standard Snowflake stream for a row that was DELETED from the source table?',
    options: [
      '\'DELETE\'',
      '\'REMOVE\'',
      '\'UPDATE\' with METADATA$ISUPDATE = FALSE',
      'Two rows: \'INSERT\' (before image) and \'DELETE\' (after image)',
    ],
    answer: '\'DELETE\'',
    exp: 'METADATA$ACTION values: INSERT (new/after-image rows), DELETE (removed/before-image rows). For an UPDATE, Snowflake inserts TWO rows: a DELETE (old values) and an INSERT (new values), both with METADATA$ISUPDATE = TRUE.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (13 questions) ────────

  {
    id: 'd4_d5_01',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'User A runs: SELECT COUNT(*) FROM orders WHERE status = \'OPEN\'. User B then runs: SELECT count(*) FROM orders WHERE status = \'OPEN\' (lowercase "count"). Does User B get a result cache hit?',
    options: [
      'No — the result cache requires an exact, case-sensitive SQL text match; "SELECT COUNT" ≠ "SELECT count"',
      'Yes — Snowflake normalizes SQL to uppercase before cache lookup',
      'Yes — result cache is case-insensitive for function names',
      'It depends on whether both users have the same active role',
    ],
    answer: 'No — the result cache requires an exact, case-sensitive SQL text match; "SELECT COUNT" ≠ "SELECT count"',
    exp: 'The result cache key is the exact SQL string including all whitespace and casing. "SELECT COUNT(*)" and "SELECT count(*)" are treated as different queries and produce separate cache entries. Normalize query text in BI tools or templates to maximize cache reuse.',
  },
  {
    id: 'd4_d5_02',
    domain: 4,
    topic: 'Caching',
    difficulty: 'easy',
    q: 'Which two query types are served by the Cloud Services metadata cache WITHOUT starting or using any virtual warehouse?',
    options: [
      'SHOW commands AND simple COUNT(*) / MIN / MAX queries on NOT NULL columns',
      'SELECT * FROM table LIMIT 10 AND DESCRIBE TABLE queries',
      'All INFORMATION_SCHEMA queries AND all SHOW commands',
      'Any query against a table smaller than 1 MB AND all DDL commands',
    ],
    answer: 'SHOW commands AND simple COUNT(*) / MIN / MAX queries on NOT NULL columns',
    exp: 'SHOW commands (SHOW TABLES, SHOW WAREHOUSES, etc.) use the metadata cache — zero warehouse credits. Simple COUNT(*) with no filter, and MIN/MAX on NOT NULL columns, can also be answered from partition-level statistics metadata without a warehouse.',
  },
  {
    id: 'd4_d5_03',
    domain: 4,
    topic: 'Query Profile',
    difficulty: 'medium',
    q: 'A query with ORDER BY event_time shows a very high time in the "Sort" node in Query Profile. What is the most likely cause and fix?',
    options: [
      'The table lacks a clustering key on event_time — adding one eliminates the sort entirely',
      'The Sort is memory-bound: insufficient warehouse memory is forcing spill to disk. Resize the warehouse up to provide more memory per node.',
      'ORDER BY creates implicit indexes that must be rebuilt — disable auto-indexing with ALTER SESSION',
      'The Sort node is always the bottleneck for large tables; only partitioning can reduce it',
    ],
    answer: 'The Sort is memory-bound: insufficient warehouse memory is forcing spill to disk. Resize the warehouse up to provide more memory per node.',
    exp: 'A dominant Sort node usually indicates spilling — the sort buffer exceeded available memory and spilled to local SSD or remote storage. Upsizing the warehouse provides more memory, eliminating or reducing spill. Clustering helps pruning but doesn\'t remove the sort step.',
  },
  {
    id: 'd4_d5_04',
    domain: 4,
    topic: 'Query Profile',
    difficulty: 'hard',
    q: 'A query shows "Bytes spilled to remote storage: 800 GB" in Query Profile. What is the performance implication compared to spilling to local SSD?',
    options: [
      'Remote storage spill is roughly 2× slower than local SSD spill',
      'There is no meaningful performance difference — Snowflake optimizes both equally',
      'Remote storage spill is orders of magnitude slower (100×+) — it is the most severe query performance problem after a complete absence of pruning',
      'Remote storage spill only affects XS–M warehouse sizes; L+ warehouses never spill to remote',
    ],
    answer: 'Remote storage spill is orders of magnitude slower (100×+) — it is the most severe query performance problem after a complete absence of pruning',
    exp: 'Spilling to local SSD is bad; spilling to remote storage (S3/GCS/Blob) is catastrophic — remote I/O is orders of magnitude slower than local SSD. Fix by: upsizing the warehouse (more memory), rewriting the query to reduce intermediate result size, or adding filters earlier.',
  },
  {
    id: 'd4_d5_05',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'medium',
    q: 'SYSTEM$CLUSTERING_INFORMATION(\'orders\', \'(order_date)\') returns average_depth = 5.2. What does this indicate?',
    options: [
      'The table has exactly 5.2 micro-partitions — it is very small',
      'The clustering is poor — on average, 5.2 micro-partitions overlap for any given order_date value, meaning pruning is ineffective',
      'The clustering is excellent — depth of 5.2 means 5.2× compression efficiency was achieved',
      'average_depth ≤ 6 is always considered good; no action is needed',
    ],
    answer: 'The clustering is poor — on average, 5.2 micro-partitions overlap for any given order_date value, meaning pruning is ineffective',
    exp: 'average_depth measures micro-partition overlap on the clustering key. Ideal depth ≈ 1.0 (no overlap). Depth > 2 suggests poor clustering; depth > 4–5 means significant overlap and pruning efficiency loss. Re-clustering or an INSERT/CTAS to sort the data may be needed.',
  },
  {
    id: 'd4_d5_06',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'hard',
    q: 'Why does the following DDL fail? CREATE MATERIALIZED VIEW daily_report AS SELECT CURRENT_DATE() AS rpt_date, region, SUM(sales) AS total FROM orders GROUP BY region;',
    options: [
      'MVs do not support GROUP BY — only simple SELECT projections are allowed',
      'CURRENT_DATE() is non-deterministic — its value changes daily, which conflicts with the statically stored MV result',
      'The SELECT list must include all GROUP BY columns plus at least one aggregate',
      'MVs cannot reference permanent tables — only transient tables are supported',
    ],
    answer: 'CURRENT_DATE() is non-deterministic — its value changes daily, which conflicts with the statically stored MV result',
    exp: 'Materialized Views store pre-computed results on disk. Non-deterministic functions (CURRENT_DATE, CURRENT_TIMESTAMP, RANDOM, UUID_STRING) are forbidden because the stored result would immediately be incorrect. Also forbidden: subqueries, HAVING, LIMIT, ORDER BY, non-aggregate window functions, and JavaScript UDFs.',
  },
  {
    id: 'd4_d5_07',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'medium',
    q: 'A VARCHAR column raw_json contains the string \'{"city":"Madrid","pop":3300000}\'. What is the correct SQL to extract the city as a VARCHAR?',
    options: [
      'PARSE_JSON(raw_json):city::VARCHAR',
      'raw_json->\'city\'::VARCHAR',
      'JSON_EXTRACT(raw_json, \'$.city\')',
      'TO_VARCHAR(raw_json:city)',
    ],
    answer: 'PARSE_JSON(raw_json):city::VARCHAR',
    exp: 'PARSE_JSON converts a VARCHAR JSON string into a VARIANT. Colon notation (:city) then navigates to the "city" key. ::VARCHAR casts the VARIANT result to a string. Raw column:field notation (raw_json:city) only works if raw_json is already a VARIANT column.',
  },
  {
    id: 'd4_d5_08',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'A scalar Python UDF is created in Snowflake. Where does the Python code actually execute?',
    options: [
      'On the Cloud Services layer — Python UDFs run on Snowflake\'s metadata infrastructure',
      'Inside the virtual warehouse\'s Python runtime — the warehouse processes each row',
      'In an external Python microservice — Snowflake calls it via HTTP for each batch of rows',
      'In Snowflake Notebooks — all Python UDFs require an active Notebook session',
    ],
    answer: 'Inside the virtual warehouse\'s Python runtime — the warehouse processes each row',
    exp: 'Python UDFs run inside the warehouse compute nodes using a sandboxed Python runtime. No external service needed. They can optionally use vectorized processing (pandas UDFs) for better performance. A Snowpark-optimized warehouse is recommended for memory-intensive Python UDFs.',
  },
  {
    id: 'd4_d5_09',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'hard',
    q: 'A Dynamic Table has REFRESH_MODE = AUTO. What determines whether a specific refresh cycle runs as INCREMENTAL vs FULL?',
    options: [
      'Only the first refresh is always FULL; all subsequent refreshes are always INCREMENTAL',
      'INCREMENTAL is used when Snowflake can compute the delta from only new/changed source rows; FULL is used when the query cannot be incrementally applied (e.g., certain aggregations or joins)',
      'The mode is set permanently at creation time and never changes',
      'FULL is always used for any DT that contains a JOIN; INCREMENTAL is for single-table DTs only',
    ],
    answer: 'INCREMENTAL is used when Snowflake can compute the delta from only new/changed source rows; FULL is used when the query cannot be incrementally applied (e.g., certain aggregations or joins)',
    exp: 'Snowflake automatically selects INCREMENTAL when it can compute the change using only new/modified source rows (simple transforms, filters). It falls back to FULL when the DT query requires a complete re-evaluation (complex aggregations, windowed aggregates, certain joins). REFRESH_MODE = AUTO lets Snowflake decide dynamically.',
  },
  {
    id: 'd4_d5_10',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'medium',
    q: 'What does this query return? SELECT name, dept, salary FROM emp QUALIFY ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) = 1;',
    options: [
      'One row per department: the employee with the highest salary in each dept',
      'All employees in departments that have exactly 1 row',
      'Syntax error — ROW_NUMBER cannot be used in QUALIFY without a CTE',
      'All employees sorted by salary descending, with duplicates removed',
    ],
    answer: 'One row per department: the employee with the highest salary in each dept',
    exp: 'QUALIFY filters rows based on a window function result. ROW_NUMBER() = 1 after partitioning by dept and ordering by salary DESC gives rank 1 to the top earner per dept. QUALIFY lets you write this without wrapping in a CTE or subquery.',
  },
  {
    id: 'd4_d5_11',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'A developer runs CREATE OR REPLACE VIEW sales_summary AS SELECT … without adding COPY GRANTS. A BI team had SELECT on the old view. What happens to their access?',
    options: [
      'Access is unaffected — CREATE OR REPLACE preserves all existing grants automatically',
      'Only the owner\'s privileges are reset; other roles\' grants on the view are preserved',
      'The BI team loses SELECT — CREATE OR REPLACE drops and recreates the object, revoking all grants unless COPY GRANTS is specified',
      'The view is locked for 5 minutes during the replace; access resumes automatically after',
    ],
    answer: 'The BI team loses SELECT — CREATE OR REPLACE drops and recreates the object, revoking all grants unless COPY GRANTS is specified',
    exp: 'CREATE OR REPLACE is equivalent to DROP + CREATE. All existing privilege grants on the old object are lost. Add COPY GRANTS to transfer them to the new object: CREATE OR REPLACE VIEW … COPY GRANTS AS SELECT …',
  },
  {
    id: 'd4_d5_12',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'easy',
    q: 'A Common Table Expression (CTE) is defined using the WITH clause at the top of a query. How long does the named result set it creates persist?',
    options: [
      'For the entire session — it behaves like a session-scoped temporary view',
      'For 24 hours — result is cached in Snowflake\'s result cache',
      'Only for the duration of the single SQL statement in which it is defined',
      'Until explicitly dropped with DROP CTE <name>',
    ],
    answer: 'Only for the duration of the single SQL statement in which it is defined',
    exp: 'A CTE is not stored or cached — it is a named inline subquery that exists only within the WITH … SELECT statement. It cannot be referenced from other queries or sessions. For reusability across queries, create a view or temporary table instead.',
  },
  {
    id: 'd4_d5_13',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'A stream captures INSERT/UPDATE/DELETE changes. A MERGE statement uses the stream as source and completes successfully. After the COMMIT, what is the stream\'s offset?',
    options: [
      'Advanced to the current state — the MERGE commit consumed the changes',
      'Unchanged — only INSERT INTO … SELECT FROM stream advances the offset, not MERGE',
      'Reset to the beginning — MERGE always resets stream state',
      'Advanced only for rows that matched the WHEN MATCHED clause',
    ],
    answer: 'Advanced to the current state — the MERGE commit consumed the changes',
    exp: 'Any DML that reads from a stream and commits (INSERT, UPDATE, DELETE, MERGE) advances the stream offset to the current watermark. After the MERGE commit, the stream will show empty (no new changes) until more source DML occurs.',
  },

  // ── DOMAIN 5: Data Collaboration (5 questions) ───────────────────────────

  {
    id: 'd5_d5_01',
    domain: 5,
    topic: 'Time Travel',
    difficulty: 'medium',
    q: 'A developer accidentally deleted rows with DELETE FROM orders WHERE status = \'PENDING\'. They have the query_id of that DELETE. Which Time Travel syntax returns the table state immediately BEFORE that specific statement ran?',
    options: [
      'SELECT * FROM orders BEFORE (STATEMENT => \'<query_id>\')',
      'SELECT * FROM orders AT (TIMESTAMP => DATEADD(second, -1, CURRENT_TIMESTAMP()))',
      'SELECT * FROM orders AT (OFFSET => -60)',
      'UNDROP TABLE orders; — this restores to the pre-delete state',
    ],
    answer: 'SELECT * FROM orders BEFORE (STATEMENT => \'<query_id>\')',
    exp: 'BEFORE (STATEMENT => \'<query_id>\') returns the table state as it was immediately BEFORE that specific statement ran — the exact point-in-time recovery needed. AT (STATEMENT => id) returns the state AT the END of that statement. BEFORE is the precise recovery syntax here.',
  },
  {
    id: 'd5_d5_02',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'A provider account shares data with a consumer account. Which SQL command must the consumer run to make the shared data queryable in their account?',
    options: [
      'ACCEPT SHARE provider_account.my_share;',
      'MOUNT SHARE provider_account.my_share AS local_db;',
      'IMPORT SHARE provider_account.my_share INTO DATABASE local_db;',
      'CREATE DATABASE local_db FROM SHARE provider_account.my_share;',
    ],
    answer: 'CREATE DATABASE FROM SHARE provider_account.my_share;',
    exp: 'The consumer creates a local database object that maps to the provider\'s share: CREATE DATABASE local_db FROM SHARE <provider_account>.<share_name>. The database appears in the consumer\'s account and its objects can be queried — zero-copy, no data moved.',
  },
  {
    id: 'd5_d5_03',
    domain: 5,
    topic: 'Collaboration',
    difficulty: 'hard',
    q: 'What does the Snowflake Native Application Framework enable?',
    options: [
      'Packaging and distributing a Snowflake-powered application (Snowpark logic, Streamlit UI, and data) that consumers INSTALL directly into their own Snowflake account — without data leaving either account',
      'A Docker-based container service for running Python microservices alongside Snowflake data processing',
      'A framework for deploying Snowflake connectors to external systems such as Salesforce or SAP',
      'A way to create external Streamlit apps that read from Snowflake using OAuth tokens',
    ],
    answer: 'Packaging and distributing a Snowflake-powered application (Snowpark logic, Streamlit UI, and data) that consumers INSTALL directly into their own Snowflake account — without data leaving either account',
    exp: 'The Native Application Framework lets ISVs build and publish applications on the Snowflake Marketplace. Consumers install the app into their Snowflake account — it runs there with access to their data. No ETL, no external services, no data movement. Governed, versioned, monetizable.',
  },
  {
    id: 'd5_d5_04',
    domain: 5,
    topic: 'Marketplace',
    difficulty: 'easy',
    q: 'A Snowflake Marketplace listing is free. What cost does the consumer incur when querying data from it?',
    options: [
      'No cost at all — free listings include free Snowflake compute credits for querying',
      'The consumer pays for their own virtual warehouse credits used to run queries against the listing',
      'A nominal per-query fee is charged by Snowflake as a platform fee, even for free listings',
      'Consumers must have a Business Critical account to access Marketplace listings',
    ],
    answer: 'The consumer pays for their own virtual warehouse credits used to run queries against the listing',
    exp: 'Marketplace listings being "free" means there is no data licensing fee. However, consumer queries run on the consumer\'s virtual warehouse — warehouse credits are consumed from the consumer\'s account. No Snowflake platform fee is added for free listings.',
  },
  {
    id: 'd5_d5_05',
    domain: 5,
    topic: 'Cloning',
    difficulty: 'medium',
    q: 'A schema is cloned: CREATE SCHEMA dev CLONE prod. The prod schema contains a Stream on a table. What is the state of the Stream in the dev clone?',
    options: [
      'The dev stream is not created — streams are excluded from schema and database clones',
      'The dev stream is cloned and points to the cloned dev table, capturing new changes from the moment of cloning forward',
      'The dev stream references the original prod table — not the cloned dev table',
      'The dev stream is cloned but immediately becomes STALE and must be recreated manually',
    ],
    answer: 'The dev stream is cloned and points to the cloned dev table, capturing new changes from the moment of cloning forward',
    exp: 'Schema clones include streams. The cloned stream in dev is re-pointed to the cloned dev table (not the prod source). Its offset starts fresh at clone time — it captures only changes made to the dev table after the clone was created.',
  },
];
