// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 7  (2026-03-16)
// COF-C03 Mock Exam · 60 questions
// Distribution: D1 31% (19q) | D2 20% (12q) | D3 18% (11q) | D4 21% (13q) | D5 10% (5q)
// Difficulty mix: ~30% Easy (18q) · ~50% Medium (30q) · ~20% Hard (12q)
//
// OVERLAP RULE (decreasing by recency):
//   Day 6 (N-1): ≤ 30% overlap (≤ 18 questions) — ~8 topics shared
//   Day 5 (N-2): ≤ 20% overlap (≤ 12 questions) — ~5 topics shared
//   Day 4 (N-3): ≤ 10% overlap (≤  6 questions) — ~3 topics shared
//   Day 3 (N-4): ≤  5% overlap (≤  3 questions)
//
// DAY 7 vs DAY 6 OVERLAP CHECK:
//   Day 6 covered: cloud provider support, MONITOR privilege, TIMESTAMP_TZ, Horizon Privacy pillar,
//   Fail-safe Support-only access, SCS general concept, CREATE SCHEMA with USAGE-only, Cortex Guard,
//   Query Tag, micro-partition UPDATE immutability, AT(STATEMENT) vs BEFORE(STATEMENT) undo,
//   multi-cluster MAX+STANDARD queue, Iceberg external catalog read-only DML, BC for HIPAA/BAA,
//   MONITOR privilege detail, Org-level objects, micro-partition metadata min/max/null/distinct,
//   SCS Compute Pool GPU, GEOGRAPHY vs GEOMETRY, SCIM vs SAML lifecycle, MFA Duo, OBJECT_DEPENDENCIES
//   compile-time, Resource Monitor serverless blindspot, Alerts serverless compute, masking policy
//   admin create vs set, key hierarchy 4-level, External OAuth SECURITY INTEGRATION, RAP + result
//   cache cross-role, SYSTEM$CLASSIFY output, OpenLineage external lineage, ACCOUNTADMIN vs RAP,
//   Snowpipe serverless, PUT GZIP default, FLATTEN VALUE column, INFER_SCHEMA result set,
//   SYSTEM$STREAM_HAS_DATA task skip, MATCH_BY_COLUMN_NAME CASE_INSENSITIVE, COPY_HISTORY error
//   audit, METADATA$ROW_ID, DT cannot use Streams, SSE vs CSE, Snowpipe Streaming vs classic,
//   USE_CACHED_RESULT=FALSE session scope, JS UDF sandbox, ARRAY_AGG, TableScan partition ratio,
//   STRIP_NULL_VALUES, PIVOT, ROWS vs RANGE frame, SUSPEND RECLUSTER vs DROP CLUSTERING KEY,
//   BEHIND_BY MV staleness, SOS SUBSTRING predicates, SP COMMIT outer transaction, DT joining
//   two DTs lag, QAS outlier queries, Reader Account billing, UNDROP SCHEMA restores all,
//   Marketplace publish sequence, provider drops shared object, clone of transient no Fail-safe.
//
//   Day 7 fresh angles: storage layer independence, AUTO_RESUME behavior, SEQUENCE object,
//   INFORMATION_SCHEMA vs ACCOUNT_USAGE query history retention, temporary table scope,
//   Search Optimization edition requirement, near-real-time INFORMATION_SCHEMA use, VPS vs BC
//   isolated metadata, Horizon Collaboration pillar, warehouse scale-up cost equivalence,
//   Cortex Analyst NL→SQL, Snowpark lazy eval vs Pandas eager, external table REFRESH needed,
//   ECONOMY policy 6-min cluster threshold, table @% stage access restriction, clone TT clock
//   independence, STANDARD vs ECONOMY exact trigger, ACCOUNTADMIN blast radius risk, TT not
//   supported on external tables, USERADMIN purpose, PUBLIC auto-grant, GRANT TO SHARE syntax,
//   network policy user-level override, COPY CURRENT GRANTS with OWNERSHIP transfer,
//   database roles vs account roles, ACCESS_HISTORY column-level audit, LOGIN_HISTORY auth
//   audit, GOVERNANCE_VIEWER role, RAP ALTER TABLE DROP, session policy existing sessions,
//   GRANT OWNERSHIP without COPY CURRENT GRANTS, ON_ERROR ABORT_STATEMENT default, LIST command
//   output, named vs user stage sharing, VALIDATION_MODE RETURN_ALL_ERRORS, Snowpipe 64-day
//   deduplication, APPEND_ONLY stream INSERT-only, Task AFTER clause child link, stream staleness
//   window, Storage Integration over credentials, Task DAG sibling independence, COPY INTO
//   PURGE effect, PARTITION BY window function, result cache DML invalidation, EXPLAIN PLAN
//   no-execute, CTE optimizer equivalence, warehouse cache lost on resize, Query Profile
//   Aggregate node, broadcast join trigger, OBJECT_CONSTRUCT, VARIANT array 0-based index,
//   Snowpark collect() triggers execution, clustering ideal average_depth, MV repeated
//   aggregations, CREATE OR REPLACE VIEW drops grants, TT default 1-day retention, consumer
//   pays with own WH, UNDROP DATABASE full restore, shared data read-only, TT external tables 0.
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 7,
  date: '2026-03-16',
  label: 'Day 7 — Fundamentals Reinforced',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (19 questions) ─────────────────────
  // 6 easy · 9 medium · 4 hard

  {
    id: 'd1_d7_01',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'Snowflake\'s architecture separates storage, compute, and cloud services. What is the primary characteristic of the storage layer in this design?',
    options: [
      'Each virtual warehouse has its own dedicated, exclusive data storage — data is not shared between warehouses',
      'Storage is centralized and fully decoupled from compute — all virtual warehouses read from the same underlying data, eliminating redundant copies',
      'The storage layer uses local SSDs on warehouse nodes for both speed and durability',
      'Storage is tiered automatically — hot data stays on NVMe flash while cold data moves to object storage',
    ],
    answer: 'Storage is centralized and fully decoupled from compute — all virtual warehouses read from the same underlying data, eliminating redundant copies',
    exp: 'Snowflake\'s multi-cluster shared data architecture stores data once (in cloud object storage) and makes it available to all virtual warehouses simultaneously. This separation means any warehouse can access all data without moving it, and compute can scale independently of storage.',
  },
  {
    id: 'd1_d7_02',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'easy',
    q: 'A virtual warehouse has AUTO_RESUME = TRUE and is currently in SUSPENDED state. A user submits a query against that warehouse. What happens?',
    options: [
      'The query fails immediately — users must manually RESUME the warehouse before queries can run',
      'The query waits in a queue for up to 10 minutes, then fails if the warehouse is still suspended',
      'The query is silently rerouted to the account\'s default warehouse',
      'Snowflake automatically resumes the warehouse before executing the query — there is a brief startup delay (seconds) but no manual intervention is needed',
    ],
    answer: 'Snowflake automatically resumes the warehouse before executing the query — there is a brief startup delay (seconds) but no manual intervention is needed',
    exp: 'AUTO_RESUME = TRUE is the default and is specifically designed for this scenario. When a query arrives for a suspended warehouse, Snowflake wakes it automatically. Users and applications experience a short delay on the first query after suspension — this is the warm-up time. AUTO_RESUME = FALSE requires an explicit RESUME before queries can run.',
  },
  {
    id: 'd1_d7_03',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'easy',
    q: 'A team needs a schema-level object that generates guaranteed unique, auto-incrementing integers for use as surrogate keys across multiple concurrent sessions. Which object type is designed for this?',
    options: [
      'A SEQUENCE — CREATE SEQUENCE generates unique integer values via NEXTVAL, guaranteed to be unique even across concurrent sessions',
      'A STREAM on the table — STREAM captures inserts and provides auto-incremented IDs',
      'A TASK that reads a counter table and increments a stored value each run',
      'A DEFAULT EXPRESSION using HASH(CURRENT_TIMESTAMP) to produce unique integers',
    ],
    answer: 'A SEQUENCE — CREATE SEQUENCE generates unique integer values via NEXTVAL, guaranteed to be unique even across concurrent sessions',
    exp: 'SEQUENCE is a schema-level object that produces monotonically increasing integers. Unlike AUTOINCREMENT (which is a column property), a Sequence can be shared across multiple tables and called from multiple sessions simultaneously — Snowflake handles the concurrency safely. Use nextval(\'my_seq\') in SQL or DEFAULT SEQ.NEXTVAL as a column default.',
  },
  {
    id: 'd1_d7_04',
    domain: 1,
    topic: 'Interfaces & Connectivity',
    difficulty: 'easy',
    q: 'A security team needs to audit all queries run in the past 300 days. Why can INFORMATION_SCHEMA.QUERY_HISTORY not be used for this?',
    options: [
      'INFORMATION_SCHEMA.QUERY_HISTORY only shows queries run by the current user\'s session',
      'INFORMATION_SCHEMA requires ACCOUNTADMIN to query historical data',
      'INFORMATION_SCHEMA.QUERY_HISTORY has a rolling 7-day retention window — for long-term history up to 1 year, use SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY instead',
      'INFORMATION_SCHEMA only logs DDL queries; DML queries appear only in ACCOUNT_USAGE',
    ],
    answer: 'INFORMATION_SCHEMA.QUERY_HISTORY has a rolling 7-day retention window — for long-term history up to 1 year, use SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY instead',
    exp: 'INFORMATION_SCHEMA is a near-real-time metadata layer with short retention (up to 7 days for query history, with a 10,000-row cap per call). It is designed for recent operational views. ACCOUNT_USAGE retains data for 1 year (365 days) but has a latency of up to 3 hours — the right tool for historical auditing.',
  },
  {
    id: 'd1_d7_05',
    domain: 1,
    topic: 'Table Types',
    difficulty: 'easy',
    q: 'A developer creates a TEMPORARY TABLE scratch_data inside their session. Another user in a different session tries SELECT * FROM scratch_data. What happens?',
    options: [
      'The second user sees the table but gets zero rows — temporary tables are readable but locked from writing by other sessions',
      'The second user gets an "Object does not exist" error — temporary tables are session-scoped and completely invisible to all other sessions',
      'The second user must be granted SELECT on the temporary table by the creator first',
      'The temporary table converts to a permanent table after 24 hours and becomes universally accessible',
    ],
    answer: 'The second user gets an "Object does not exist" error — temporary tables are session-scoped and completely invisible to all other sessions',
    exp: 'Temporary tables exist only for the duration of the session that created them. They are not visible in other sessions, even if those sessions know the object name. They are automatically dropped when the session ends. This makes them safe for intermediate scratch data without polluting the schema namespace.',
  },
  {
    id: 'd1_d7_06',
    domain: 1,
    topic: 'Editions',
    difficulty: 'easy',
    q: 'A data team wants to use the Search Optimization Service on their Snowflake tables. What is the minimum Snowflake edition that supports this feature?',
    options: [
      'Standard — Search Optimization is available on all editions',
      'Business Critical — it is a security-adjacent feature requiring the highest tier',
      'Virtual Private Snowflake — only fully isolated deployments support the search index infrastructure',
      'Enterprise — Search Optimization Service requires Enterprise edition or above',
    ],
    answer: 'Enterprise — Search Optimization Service requires Enterprise edition or above',
    exp: 'Search Optimization Service is an Enterprise edition feature (along with multi-cluster warehouses, materialized views, and 90-day Time Travel). Standard edition customers cannot add search optimization to tables. Business Critical and VPS include it as well, since they build on Enterprise.',
  },

  {
    id: 'd1_d7_07',
    domain: 1,
    topic: 'Interfaces & Connectivity',
    difficulty: 'medium',
    q: 'An engineer needs to query Snowflake\'s query history for events from the last 15 minutes. Which metadata source is most appropriate and why?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY — most comprehensive history, but latency up to 3 hours makes it unsuitable for recent activity',
      'INFORMATION_SCHEMA.QUERY_HISTORY — provides near-real-time data (minutes of latency), making it the right choice for recent operational monitoring despite its 7-day retention limit',
      'SHOW QUERIES — the only zero-latency option for live in-progress query inspection',
      'Both sources are equivalent for recent queries; choose either based on column preference',
    ],
    answer: 'INFORMATION_SCHEMA.QUERY_HISTORY — provides near-real-time data (minutes of latency), making it the right choice for recent operational monitoring despite its 7-day retention limit',
    exp: 'INFORMATION_SCHEMA is updated with minimal latency (seconds to minutes), making it ideal for "what ran in the last hour?" operational questions. ACCOUNT_USAGE is better for historical reporting (weeks/months) but has a 45-minute to 3-hour latency. Use the right tool for the right time horizon.',
  },
  {
    id: 'd1_d7_08',
    domain: 1,
    topic: 'Editions',
    difficulty: 'medium',
    q: 'What is the defining architectural difference between Virtual Private Snowflake (VPS) and the Business Critical edition?',
    options: [
      'VPS supports multi-factor authentication; Business Critical does not include MFA as standard',
      'VPS uses customer-managed encryption keys exclusively; Business Critical uses Snowflake-managed keys only',
      'VPS runs on completely isolated, dedicated Snowflake infrastructure with a separate metadata store — no shared services with any other Snowflake customers. Business Critical is still on shared multi-tenant infrastructure at the metadata layer.',
      'VPS is cloud-agnostic; Business Critical is available on AWS only',
    ],
    answer: 'VPS runs on completely isolated, dedicated Snowflake infrastructure with a separate metadata store — no shared services with any other Snowflake customers. Business Critical is still on shared multi-tenant infrastructure at the metadata layer.',
    exp: 'VPS (Virtual Private Snowflake) provides complete tenant isolation — dedicated hardware, network, and metadata services. This is the highest level of isolation for customers with extreme compliance requirements (e.g., government, defense). Business Critical provides enhanced security features but runs on the standard shared multi-tenant infrastructure.',
  },
  {
    id: 'd1_d7_09',
    domain: 1,
    topic: 'Snowflake Horizon',
    difficulty: 'medium',
    q: 'Which Snowflake Horizon Catalog pillar covers Secure Data Sharing, Snowflake Marketplace, Private Data Exchange, and Data Clean Rooms?',
    options: [
      'Collaboration — encompasses features that let organizations securely share, publish, and collaborate on data across Snowflake accounts and cloud regions',
      'Discovery — focuses on cataloguing and tagging data assets for findability',
      'Privacy — controls what aggregate-level or column-level data external parties are allowed to see',
      'Security & Governance — enforces access controls including those for shared objects',
    ],
    answer: 'Collaboration — encompasses features that let organizations securely share, publish, and collaborate on data across Snowflake accounts and cloud regions',
    exp: 'The Collaboration pillar groups all cross-organizational data access features: zero-copy Secure Data Sharing, the Snowflake Marketplace (listing and discovering data products), Private Data Exchange (closed invite-only sharing), and Data Clean Rooms (privacy-preserving joint analytics). Discovery, Privacy, and Security & Governance cover the other three pillars.',
  },
  {
    id: 'd1_d7_10',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'An XS warehouse (1 credit/hour) runs a query in 4 minutes. Scaled up to Medium (4 credits/hour, roughly 4× resources), the same query finishes in ~1 minute. How does total credit cost compare between the two runs?',
    options: [
      'The Medium warehouse costs 4× more — the credit rate quadrupled for the same workload',
      'The total cost is approximately the same — more resources finish in proportionally less time, keeping total credits consumed similar. Scale-up buys speed, not cost savings.',
      'The Medium is cheaper because Snowflake bills by wall-clock time regardless of warehouse size',
      'The XS is cheaper — larger warehouses have overhead multipliers that increase cost beyond linear scaling',
    ],
    answer: 'The total cost is approximately the same — more resources finish in proportionally less time, keeping total credits consumed similar. Scale-up buys speed, not cost savings.',
    exp: 'XS at 1 cr/hr × 4 min ≈ 0.067 credits. Medium at 4 cr/hr × 1 min ≈ 0.067 credits — approximately equal. This is the principle of scale-out equivalence: doubling resources halves time, keeping cost constant. Scale up to meet SLAs or reduce queue time, NOT to save money. Actual savings come from AUTO_SUSPEND reducing idle time.',
  },
  {
    id: 'd1_d7_11',
    domain: 1,
    topic: 'AI / ML Features',
    difficulty: 'medium',
    q: 'What is Snowflake Cortex Analyst designed to enable for business users?',
    options: [
      'Automated Snowflake account administration tasks generated from natural language commands',
      'Batch ML inference pipelines on Snowpark-optimized warehouses with minimal SQL',
      'Natural language questions from business users translated into accurate SQL queries against semantic models defined on Snowflake data — enabling self-service analytics without SQL knowledge',
      'Automated anomaly detection and alerting on data quality metrics across the data warehouse',
    ],
    answer: 'Natural language questions from business users translated into accurate SQL queries against semantic models defined on Snowflake data — enabling self-service analytics without SQL knowledge',
    exp: 'Cortex Analyst lets you define a semantic model (metric definitions, join relationships, synonyms) on top of your Snowflake tables, then accepts natural language questions and converts them to SQL. It is designed for business analysts who need answers from data without writing SQL — backed by an LLM that understands the semantic context you provided.',
  },
  {
    id: 'd1_d7_12',
    domain: 1,
    topic: 'AI / ML Features',
    difficulty: 'medium',
    q: 'A Pandas user is learning Snowpark DataFrames in Python. What is the most important architectural difference to understand?',
    options: [
      'Snowpark DataFrames only support Parquet file sources; Pandas supports all file types',
      'Snowpark DataFrames execute operations eagerly on the Python client like Pandas does',
      'Pandas DataFrames support SQL-style GROUP BY natively; Snowpark DataFrames do not support aggregations',
      'Snowpark DataFrames are lazy — transformations build a query plan without executing; only action methods like .collect() or .to_pandas() send work to Snowflake, while Pandas loads all data into local memory immediately',
    ],
    answer: 'Snowpark DataFrames are lazy — transformations build a query plan without executing; only action methods like .collect() or .to_pandas() send work to Snowflake, while Pandas loads all data into local memory immediately',
    exp: 'Snowpark uses lazy evaluation (like Apache Spark): chaining filter(), select(), join() etc. builds a logical plan but does NOT move data. Calling .collect(), .to_pandas(), .show(), or write operations triggers the actual SQL execution inside Snowflake. This means you can build complex transformations on billions of rows without memory constraints on the Python client.',
  },
  {
    id: 'd1_d7_13',
    domain: 1,
    topic: 'Table Types',
    difficulty: 'medium',
    q: 'An external table is created over CSV files in an S3 bucket. New files are added directly to S3. Why won\'t a SELECT against the external table immediately show the new data?',
    options: [
      'External tables only support Parquet format — CSV files must be converted before Snowflake can detect them',
      'The external table\'s metadata cache must be refreshed — Snowflake does not automatically detect new cloud files; run ALTER EXTERNAL TABLE ... REFRESH or enable AUTO_REFRESH to pick up new files',
      'New S3 files are only visible to Snowflake after the table\'s retention period resets (once per 24 hours)',
      'A COPY INTO must be run to load the S3 files into the external table before querying',
    ],
    answer: 'The external table\'s metadata cache must be refreshed — Snowflake does not automatically detect new cloud files; run ALTER EXTERNAL TABLE ... REFRESH or enable AUTO_REFRESH to pick up new files',
    exp: 'External tables maintain a metadata cache of the file listing in cloud storage. New files added externally are not visible until this cache is refreshed. You can do this manually (ALTER EXTERNAL TABLE REFRESH) or automatically via cloud messaging (AUTO_REFRESH = TRUE with an SQS/Event Grid/Pub/Sub integration). Until refreshed, queries see the old file set.',
  },
  {
    id: 'd1_d7_14',
    domain: 1,
    topic: 'Multi-cluster Warehouses',
    difficulty: 'medium',
    q: 'A multi-cluster warehouse uses SCALING_POLICY = ECONOMY. Under what condition does Snowflake start an additional cluster?',
    options: [
      'Only when the system estimates that queued workload would keep a new cluster busy for at least 6 minutes — ECONOMY avoids spinning up clusters for short bursts to save credits',
      'As soon as any single query is queued — ECONOMY and STANDARD both respond immediately to queue formation',
      'When at least 3 queries have been waiting for more than 30 seconds each',
      'When CPU utilization across all active clusters exceeds 80% for at least 2 minutes',
    ],
    answer: 'Only when the system estimates that queued workload would keep a new cluster busy for at least 6 minutes — ECONOMY avoids spinning up clusters for short bursts to save credits',
    exp: 'ECONOMY policy prioritizes cost efficiency: it only adds a cluster if the estimated queued work justifies at least ~6 minutes of runtime on the new cluster. STANDARD policy starts a new cluster as soon as any query is queued. Use STANDARD for latency-sensitive workloads, ECONOMY for batch jobs where a little queue time is acceptable in exchange for lower credit consumption.',
  },
  {
    id: 'd1_d7_15',
    domain: 1,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'A team wants to use the table stage (@%) to let multiple external teams upload files for the orders table. What is a key restriction on using table stages for this purpose?',
    options: [
      'Table stages only support CSV format — JSON, Parquet, and ORC cannot be uploaded to a table stage',
      'Table stages have a 100 MB per-file size limit; larger files must use named external stages',
      'Only roles with OWNERSHIP or INSERT privilege on the table can PUT files to or load files from its table stage — it cannot be used as a general-purpose shared ingestion area for external teams without those grants',
      'Table stage files are automatically purged after 24 hours, requiring all loads to complete same-day',
    ],
    answer: 'Only roles with OWNERSHIP or INSERT privilege on the table can PUT files to or load files from its table stage — it cannot be used as a general-purpose shared ingestion area for external teams without those grants',
    exp: 'Table stages (@%) are tied to the table\'s access control. The stage cannot be independently shared — accessing it requires the same privilege as modifying the table (INSERT or OWNERSHIP). For a multi-team ingestion workflow, a NAMED INTERNAL STAGE is the correct tool, as it can be independently managed and granted access to multiple roles.',
  },

  {
    id: 'd1_d7_16',
    domain: 1,
    topic: 'Zero-copy Cloning',
    difficulty: 'hard',
    q: 'A production table has DATA_RETENTION_TIME_IN_DAYS = 90. A developer clones it at 3:00 PM. At 5:00 PM they run a Time Travel query on the CLONE using AT(TIMESTAMP => \'2:00 PM today\'). What happens?',
    options: [
      'The query succeeds — the clone inherits the production table\'s full TT history including pre-clone timestamps',
      'The query succeeds — the 90-day TT window on the clone covers timestamps from today',
      'The query fails — the clone\'s Time Travel clock starts at 3:00 PM (the moment of cloning); timestamps before that point are not in the clone\'s history',
      'The query works for the first 24 hours, then the clone\'s TT resets and becomes unavailable',
    ],
    answer: 'The query fails — the clone\'s Time Travel clock starts at 3:00 PM (the moment of cloning); timestamps before that point are not in the clone\'s history',
    exp: 'Zero-copy clones start their own independent Time Travel clock from the moment they are created. The clone does NOT inherit the source table\'s pre-clone change history. To see data at 2:00 PM, query the original table using Time Travel. This is a common misconception — cloning is not a form of historical backup.',
  },
  {
    id: 'd1_d7_17',
    domain: 1,
    topic: 'Multi-cluster Warehouses',
    difficulty: 'hard',
    q: 'STANDARD and ECONOMY are both scaling policies for multi-cluster warehouses. What is the precise behavioral difference in when they trigger a new cluster?',
    options: [
      'STANDARD adds a cluster as soon as any query is queued; ECONOMY adds a cluster only when the system estimates the queued load would keep a new cluster busy for at least 6 minutes — prioritizing cost efficiency over immediate responsiveness',
      'STANDARD waits 60 seconds before adding clusters; ECONOMY scales immediately on first queue',
      'STANDARD scales automatically up to MAX; ECONOMY requires a manual RESUME WAREHOUSE call for each additional cluster',
      'STANDARD and ECONOMY behave identically on scale-up; they differ only in the scale-down (cluster retirement) threshold',
    ],
    answer: 'STANDARD adds a cluster as soon as any query is queued; ECONOMY adds a cluster only when the system estimates the queued load would keep a new cluster busy for at least 6 minutes — prioritizing cost efficiency over immediate responsiveness',
    exp: 'STANDARD = optimize for speed (lowest latency — spin up immediately on any queue). ECONOMY = optimize for cost (avoid wasting credits on transient spikes). Both will eventually add clusters under sustained load. The 6-minute threshold for ECONOMY means short bursts of 1-2 queries will wait in queue rather than triggering a new cluster.',
  },
  {
    id: 'd1_d7_18',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'hard',
    q: 'Snowflake best practice recommends NOT using the ACCOUNTADMIN role for day-to-day data operations. What is the primary reason?',
    options: [
      'ACCOUNTADMIN cannot read data from tables — its purpose is account management only, not data access',
      'Any mistake made while operating as ACCOUNTADMIN — accidental DROP, misconfigured security policy, unintended grants — affects the entire account with no guardrails. Its unlimited blast radius makes it too dangerous for routine work; use purpose-built roles instead.',
      'ACCOUNTADMIN is rate-limited to 100 queries per day to prevent resource abuse',
      'ACCOUNTADMIN cannot be used with MFA or SSO, creating a security audit gap',
    ],
    answer: 'Any mistake made while operating as ACCOUNTADMIN — accidental DROP, misconfigured security policy, unintended grants — affects the entire account with no guardrails. Its unlimited blast radius makes it too dangerous for routine work; use purpose-built roles instead.',
    exp: 'ACCOUNTADMIN is omnipotent — it can drop any object, change any policy, and access any data. That power is exactly why it should be reserved for account setup and emergencies. Routine ETL, reporting, or admin tasks should use the most limited role that accomplishes the task, following the least-privilege principle. Most Snowflake best-practice frameworks recommend that ACCOUNTADMIN should have very few active users.',
  },
  {
    id: 'd1_d7_19',
    domain: 1,
    topic: 'Table Types',
    difficulty: 'hard',
    q: 'A team creates an external table pointing to Parquet files in GCS. A developer asks if they can query the external table as it was 48 hours ago using Time Travel. What is the answer?',
    options: [
      'Yes — external tables support Time Travel since the underlying GCS files are retained in cloud storage',
      'Yes — but only if GCS bucket versioning is enabled for the underlying files',
      'No — external tables do not support Time Travel. Snowflake does not manage or version the underlying external data. DATA_RETENTION_TIME_IN_DAYS must be set to 0 for external tables.',
      'Yes — use AT(OFFSET => -172800) to query the external data as it was 48 hours ago',
    ],
    answer: 'No — external tables do not support Time Travel. Snowflake does not manage or version the underlying external data. DATA_RETENTION_TIME_IN_DAYS must be set to 0 for external tables.',
    exp: 'Time Travel requires Snowflake to manage change history through its micro-partition system. Since external tables point to data Snowflake does not own or version (the files live in S3/GCS/Azure and can be changed externally without Snowflake\'s knowledge), Time Travel cannot be supported. DATA_RETENTION_TIME_IN_DAYS is fixed at 0 for external tables.',
  },

  // ── DOMAIN 2: Account Management & Governance (12 questions) ─────────────
  // 3 easy · 6 medium · 3 hard

  {
    id: 'd2_d7_01',
    domain: 2,
    topic: 'System Roles',
    difficulty: 'easy',
    q: 'What is the primary purpose of the USERADMIN system-defined role in Snowflake?',
    options: [
      'Managing virtual warehouses and assigning warehouse quotas to users',
      'Owning all databases and schemas — USERADMIN is responsible for data object creation',
      'Creating and managing users and roles — but USERADMIN itself cannot grant privileges to roles (that requires SECURITYADMIN or higher)',
      'Monitoring account-level credit usage and configuring resource monitors',
    ],
    answer: 'Creating and managing users and roles — but USERADMIN itself cannot grant privileges to roles (that requires SECURITYADMIN or higher)',
    exp: 'USERADMIN is scoped to user and role lifecycle management: CREATE USER, ALTER USER, DROP USER, CREATE ROLE, DROP ROLE. It does NOT have the MANAGE GRANTS privilege and cannot grant privileges to roles — that requires SECURITYADMIN (which includes MANAGE GRANTS) or a role with explicit GRANT OPTION. This separation is by design in Snowflake\'s role hierarchy.',
  },
  {
    id: 'd2_d7_02',
    domain: 2,
    topic: 'System Roles',
    difficulty: 'easy',
    q: 'Every Snowflake user is automatically a member of which role at account creation?',
    options: [
      'PUBLIC — every user automatically inherits PUBLIC role membership; any object granted to PUBLIC is accessible to all account users',
      'SYSADMIN — all users can create objects in SYSADMIN\'s scope by default',
      'USERADMIN — all users can self-manage their profiles and preferences',
      'VIEWER — a default read-only role granted automatically to all new users',
    ],
    answer: 'PUBLIC — every user automatically inherits PUBLIC role membership; any object granted to PUBLIC is accessible to all account users',
    exp: 'PUBLIC is the baseline role that every Snowflake user belongs to implicitly. Granting privileges to PUBLIC makes them available to everyone in the account. By default, PUBLIC has minimal privileges. Care should be taken before granting any significant access to PUBLIC, as it effectively means "accessible to all users."',
  },
  {
    id: 'd2_d7_03',
    domain: 2,
    topic: 'Data Sharing',
    difficulty: 'easy',
    q: 'To add a table to a Snowflake Secure Share and make it accessible to data consumers, which SQL syntax is used?',
    options: [
      'GRANT SELECT ON TABLE my_db.my_schema.orders TO USER consumer_user',
      'GRANT SELECT ON TABLE my_db.my_schema.orders TO ROLE data_consumer',
      'SHARE TABLE my_db.my_schema.orders WITH ACCOUNT consumer_account',
      'GRANT SELECT ON TABLE my_db.my_schema.orders TO SHARE my_share',
    ],
    answer: 'GRANT SELECT ON TABLE my_db.my_schema.orders TO SHARE my_share',
    exp: 'Data sharing uses the SHARE object as the recipient of grants — not a user or role. The syntax is GRANT <privilege> ON <object> TO SHARE <share_name>. The share also needs GRANT USAGE ON DATABASE and GRANT USAGE ON SCHEMA before granting SELECT on individual tables. Consumers then CREATE DATABASE FROM SHARE to access the data.',
  },

  {
    id: 'd2_d7_04',
    domain: 2,
    topic: 'Network Policies',
    difficulty: 'medium',
    q: 'An account-level network policy blocks all IPs outside the corporate office range. A developer has a user-level network policy that allows their home IP (which is outside the office range). Which policy governs the developer\'s connection?',
    options: [
      'The account-level policy always wins — account settings override user-level settings for security',
      'The user-level network policy takes precedence for that specific user — user-level policies override the account-level network policy for the user they are assigned to',
      'Both policies are ANDed together — the IP must appear in BOTH allowed lists to connect',
      'The most recently created policy always takes precedence',
    ],
    answer: 'The user-level network policy takes precedence for that specific user — user-level policies override the account-level network policy for the user they are assigned to',
    exp: 'Snowflake evaluates network policies in this order: if a user-level network policy exists, it takes effect for that user, overriding the account-level policy. This allows exceptions — e.g., remote developers or contractors can be individually whitelisted without opening the account-level policy. Removing the user-level policy reverts the user to account-level restrictions.',
  },
  {
    id: 'd2_d7_05',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'A role executes GRANT OWNERSHIP ON TABLE orders TO ROLE new_team COPY CURRENT GRANTS. What does the COPY CURRENT GRANTS clause do?',
    options: [
      'Copies the table\'s physical data to new_team\'s schema as part of the ownership transfer',
      'Transfers ownership AND all account-admin-level privileges to new_team simultaneously',
      'Preserves all existing access grants on the object (e.g., SELECT already granted to ANALYST) when transferring ownership — without it, all non-ownership grants are automatically revoked',
      'Creates a snapshot of the current grant configuration in INFORMATION_SCHEMA for audit purposes',
    ],
    answer: 'Preserves all existing access grants on the object (e.g., SELECT already granted to ANALYST) when transferring ownership — without it, all non-ownership grants are automatically revoked',
    exp: 'By default, GRANT OWNERSHIP revokes all non-ownership privileges on the object. COPY CURRENT GRANTS prevents this — it carries forward all existing grants (SELECT to ANALYST, INSERT to ETL_ROLE, etc.) to the new owner\'s object. This is important in production where other teams depend on access to the transferred object.',
  },
  {
    id: 'd2_d7_06',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'When is a DATABASE ROLE preferable to an ACCOUNT ROLE for managing data access in Snowflake?',
    options: [
      'Use database roles to scope access grants within a specific database — they can be granted to account roles and included in Data Shares, making them ideal for structured object-level permissions. Use account roles for cross-database patterns and account administration.',
      'Database roles and account roles are interchangeable — the distinction is cosmetic only',
      'Account roles are for read-only access; database roles are for read-write access',
      'Database roles can only be created by USERADMIN; account roles require SYSADMIN',
    ],
    answer: 'Use database roles to scope access grants within a specific database — they can be granted to account roles and included in Data Shares, making them ideal for structured object-level permissions. Use account roles for cross-database patterns and account administration.',
    exp: 'Database roles are defined within a database and can only grant privileges to objects in that database. They are especially useful in Data Sharing scenarios where providers can bundle a set of permissions as a database role for consumers. Account roles span the whole account. Best practice: use database roles for fine-grained data access and account roles for operational personas (ETL_ROLE, ANALYST, etc.).',
  },
  {
    id: 'd2_d7_07',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'A compliance team must identify exactly which users accessed specific columns in the CUSTOMERS table over the last 6 months. Which ACCOUNT_USAGE view should they use?',
    options: [
      'QUERY_HISTORY — the SQL text shows which columns were referenced in each query',
      'COPY_HISTORY — records all data movement operations involving the table',
      'OBJECT_DEPENDENCIES — shows compile-time column references in view and SP definitions',
      'ACCESS_HISTORY — records the specific base objects and columns each query actually read, with user identity and timestamp, purpose-built for data access auditing',
    ],
    answer: 'ACCESS_HISTORY — records the specific base objects and columns each query actually read, with user identity and timestamp, purpose-built for data access auditing',
    exp: 'ACCESS_HISTORY (Enterprise+) provides column-level access tracking. For each query, it shows DIRECT_OBJECTS_ACCESSED (tables/views the query explicitly named) and BASE_OBJECTS_ACCESSED (underlying tables resolved through views). It is the authoritative source for "who accessed what data, and when" — more precise than parsing QUERY_HISTORY SQL text.',
  },
  {
    id: 'd2_d7_08',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'A security engineer suspects brute-force login attempts against a service account. Which ACCOUNT_USAGE view provides authentication event data?',
    options: [
      'QUERY_HISTORY — includes failed authentication attempts as query errors',
      'LOGIN_HISTORY — records all login attempts (successful and failed) with client type, IP address, error code, and timestamp — the primary view for authentication auditing',
      'ACCESS_HISTORY — captures all access events including failed logins',
      'SESSIONS — shows only currently active sessions; failed logins are not recorded',
    ],
    answer: 'LOGIN_HISTORY — records all login attempts (successful and failed) with client type, IP address, error code, and timestamp — the primary view for authentication auditing',
    exp: 'LOGIN_HISTORY in ACCOUNT_USAGE (or INFORMATION_SCHEMA.LOGIN_HISTORY for recent data) captures every authentication attempt. Fields include USER_NAME, REPORTED_CLIENT_TYPE, CLIENT_IP, IS_SUCCESS, ERROR_CODE, and ERROR_MESSAGE. It is the go-to for detecting failed login spikes, unusual IP addresses, or disabled accounts being targeted.',
  },
  {
    id: 'd2_d7_09',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'A governance analyst needs read access to ACCOUNT_USAGE views about object tags, masking policies, and row access policies without being given ACCOUNTADMIN. Which SNOWFLAKE database role grants this?',
    options: [
      'OBJECT_VIEWER — provides metadata about all account objects and their properties',
      'USAGE_VIEWER — grants access to warehouse and compute usage metrics',
      'GOVERNANCE_VIEWER — grants SELECT on ACCOUNT_USAGE views for tags, masking policies, row access policies, and other governance metadata',
      'SECURITY_VIEWER — grants access to security-specific views like LOGIN_HISTORY and ACCESS_HISTORY',
    ],
    answer: 'GOVERNANCE_VIEWER — grants SELECT on ACCOUNT_USAGE views for tags, masking policies, row access policies, and other governance metadata',
    exp: 'Snowflake provides predefined database roles on the SNOWFLAKE database to delegate ACCOUNT_USAGE access without granting ACCOUNTADMIN. GOVERNANCE_VIEWER includes access to TAG_REFERENCES, POLICY_REFERENCES, MASKING_POLICIES, and ROW_ACCESS_POLICIES views. SECURITY_VIEWER covers LOGIN_HISTORY, GRANTS_TO_ROLES, etc. OBJECT_VIEWER covers objects/columns/tables metadata.',
  },

  {
    id: 'd2_d7_10',
    domain: 2,
    topic: 'Row Access Policies',
    difficulty: 'hard',
    q: 'A table has a Row Access Policy added via ALTER TABLE orders ADD ROW ACCESS POLICY rap_regional ON (region_col). How is this association removed?',
    options: [
      'ALTER TABLE orders DROP ROW ACCESS POLICY rap_regional — removes the policy association from the table without dropping the policy object itself',
      'DROP ROW ACCESS POLICY rap_regional — removes both the policy object and its table association',
      'ALTER TABLE orders SET ROW ACCESS POLICY = NULL — sets the policy reference to null',
      'REVOKE ROW ACCESS POLICY rap_regional FROM TABLE orders — uses REVOKE syntax for policy removal',
    ],
    answer: 'ALTER TABLE orders DROP ROW ACCESS POLICY rap_regional — removes the policy association from the table without dropping the policy object itself',
    exp: 'ALTER TABLE ... DROP ROW ACCESS POLICY is the correct DDL to detach a Row Access Policy from a table column. The policy OBJECT itself still exists in the schema and can be applied to other tables. To remove the policy object entirely, use DROP ROW ACCESS POLICY after detaching it from all tables. The policy must be detached before it can be dropped.',
  },
  {
    id: 'd2_d7_11',
    domain: 2,
    topic: 'Session Policies',
    difficulty: 'hard',
    q: 'An admin applies a new SESSION POLICY with SESSION_IDLE_TIMEOUT_MINS = 30 at the account level. Users currently have active sessions. How does the new idle timeout affect them?',
    options: [
      'Active sessions are terminated immediately — the policy applies globally and instantly to all sessions',
      'Active sessions are completely unaffected until the user ends the session and re-authenticates',
      'Active sessions get a 5-minute warning notification before being terminated',
      'The new timeout applies to existing sessions as well — their idle timer will now be enforced from the next idle period under the new policy, though in-progress queries are not interrupted mid-execution',
    ],
    answer: 'The new timeout applies to existing sessions as well — their idle timer will now be enforced from the next idle period under the new policy, though in-progress queries are not interrupted mid-execution',
    exp: 'Session policies are applied in real-time to all sessions, including active ones. However, "idle timeout" only triggers when the session becomes idle (no activity). A currently running query will complete. Once idle, the 30-minute clock starts ticking under the new policy. Sessions that were already idle for >30 minutes at policy application time may be terminated.',
  },
  {
    id: 'd2_d7_12',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'hard',
    q: 'A role runs GRANT OWNERSHIP ON TABLE sales TO ROLE new_team without the COPY CURRENT GRANTS clause. The ANALYST role previously had SELECT on this table. What is the result?',
    options: [
      'The ANALYST role retains SELECT on the table — ownership transfers automatically preserve all non-ownership grants',
      'The ANALYST role loses its SELECT grant on the table — without COPY CURRENT GRANTS, all existing non-ownership privileges on the object are revoked at the moment of ownership transfer',
      'The command fails — COPY CURRENT GRANTS is mandatory when granting OWNERSHIP',
      'The ANALYST role\'s SELECT grant is suspended but can be re-activated by new_team without re-granting',
    ],
    answer: 'The ANALYST role loses its SELECT grant on the table — without COPY CURRENT GRANTS, all existing non-ownership privileges on the object are revoked at the moment of ownership transfer',
    exp: 'This is an important production risk to understand. GRANT OWNERSHIP without COPY CURRENT GRANTS wipes all non-ownership grants (SELECT, INSERT, etc.) on the object. If downstream consumers had access, they lose it instantly and silently. Always use COPY CURRENT GRANTS when transferring ownership of production objects to avoid breaking dependent workloads.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ───────
  // 3 easy · 6 medium · 2 hard

  {
    id: 'd3_d7_01',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'easy',
    q: 'A COPY INTO command loads a 10,000-row CSV file. Row 500 contains a data type mismatch error. No ON_ERROR option is specified. What is the default behavior?',
    options: [
      'Snowflake skips the bad row and continues loading the remaining rows (CONTINUE behavior is default)',
      'Only the first 10 errors are tolerated; remaining rows after the 10th error are aborted',
      'The entire load aborts — no rows are inserted. The default ON_ERROR = ABORT_STATEMENT rolls back the entire COPY INTO on the first error encountered.',
      'Rows 1 through 499 are committed, then the operation pauses and waits for the user to fix row 500',
    ],
    answer: 'The entire load aborts — no rows are inserted. The default ON_ERROR = ABORT_STATEMENT rolls back the entire COPY INTO on the first error encountered.',
    exp: 'ON_ERROR defaults to ABORT_STATEMENT, which is the safest option — it prevents partial loads that could corrupt downstream data. The entire COPY INTO is rolled back atomically. To skip bad rows and continue, set ON_ERROR = CONTINUE. To skip only the entire file containing the error, use ON_ERROR = SKIP_FILE.',
  },
  {
    id: 'd3_d7_02',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'easy',
    q: 'A developer runs LIST @my_internal_stage. What does the output display?',
    options: [
      'The file name, size in bytes, MD5 checksum, and last-modified timestamp for each file in the stage',
      'The CREATE STAGE DDL statement used to originally define the stage',
      'The estimated row count and file format detection result for each staged file',
      'The IAM permissions and encryption settings currently configured on the stage\'s cloud storage',
    ],
    answer: 'The file name, size in bytes, MD5 checksum, and last-modified timestamp for each file in the stage',
    exp: 'LIST @stage returns a row per file with columns: name (full path), size (bytes), md5 (hash for integrity), last_modified (timestamp). This is useful for verifying files arrived, confirming sizes, and auditing staged content before COPY INTO. It works for all stage types — internal named, external, user, and table stages.',
  },
  {
    id: 'd3_d7_03',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'easy',
    q: 'What is an advantage of a NAMED INTERNAL STAGE over a USER STAGE (@~) for a team data-loading workflow?',
    options: [
      'User stages are temporary and auto-drop after 7 days; named stages are persistent',
      'Named internal stages are schema-level objects that can be independently granted to multiple roles — multiple users and teams can PUT and GET files; user stages are private to a single user and inaccessible to others',
      'Named stages support encrypted uploads; user stages store files in plaintext',
      'Named stages support files up to 5 GB; user stages are limited to 100 MB per file',
    ],
    answer: 'Named internal stages are schema-level objects that can be independently granted to multiple roles — multiple users and teams can PUT and GET files; user stages are private to a single user and inaccessible to others',
    exp: 'User stages (@~) are per-user private scratch spaces — no one else can access them. Named internal stages (CREATE STAGE) are schema objects with standard RBAC: GRANT READ, WRITE on STAGE to roles. This makes named stages the right choice for team-based loading workflows, ETL pipelines, and any scenario requiring shared file staging.',
  },

  {
    id: 'd3_d7_04',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'A developer runs COPY INTO orders FROM @my_stage VALIDATION_MODE = \'RETURN_ALL_ERRORS\'. What does Snowflake do?',
    options: [
      'Data is loaded normally and all encountered errors are written to a dedicated error table for later review',
      'The load executes but is automatically rolled back, returning only a total error count summary',
      'Only rows that pass validation are loaded; rows with errors go to a quarantine table',
      'No rows are loaded — Snowflake performs a dry-run scan of all files and returns a result set containing every validation error found, with file name, row number, and error description',
    ],
    answer: 'No rows are loaded — Snowflake performs a dry-run scan of all files and returns a result set containing every validation error found, with file name, row number, and error description',
    exp: 'VALIDATION_MODE = \'RETURN_ALL_ERRORS\' is a dry-run mode. No data is committed. Snowflake scans the staged files against the target table\'s schema and returns ALL errors it finds (unlike \'RETURN_N_ROWS\' which previews good rows). This is the best way to validate file format and schema compatibility before a production load.',
  },
  {
    id: 'd3_d7_05',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'medium',
    q: 'An SQS event fires twice for the same S3 file due to an infrastructure hiccup, triggering Snowpipe twice. Does Snowflake load the file twice?',
    options: [
      'No — Snowpipe tracks load history by file path + ETag combination. If the same file was already loaded within the 64-day deduplication window, the duplicate notification is silently ignored',
      'Yes — Snowpipe has no built-in deduplication; the application layer must handle idempotency',
      'No — Snowpipe uses only file size as the deduplication key; the same size file is never loaded twice',
      'Yes — but Snowflake\'s background deduplication task detects and deletes the duplicate rows within 1 hour',
    ],
    answer: 'No — Snowpipe tracks load history by file path + ETag combination. If the same file was already loaded within the 64-day deduplication window, the duplicate notification is silently ignored',
    exp: 'Snowpipe maintains a 64-day load history keyed on file path + ETag (object content hash). If a duplicate event arrives for a file already loaded, Snowpipe skips it without reloading. This deduplication window is the same 64 days that COPY INTO uses for load history. Files modified (different ETag) ARE treated as new files and will be reloaded.',
  },
  {
    id: 'd3_d7_06',
    domain: 3,
    topic: 'Streams',
    difficulty: 'medium',
    q: 'An APPEND_ONLY stream is created on the orders table. A developer deletes 100 rows and then inserts 50 new rows. What does the stream contain?',
    options: [
      'All 150 change records — the 100 deletes and 50 inserts',
      'Only the 50 new INSERT records — APPEND_ONLY streams capture only newly inserted rows and ignore DELETE and UPDATE operations',
      'Only the 100 DELETE records — the stream focuses on removals to track data loss',
      'Nothing — APPEND_ONLY streams require an active Task to be in STARTED state to capture changes',
    ],
    answer: 'Only the 50 new INSERT records — APPEND_ONLY streams capture only newly inserted rows and ignore DELETE and UPDATE operations',
    exp: 'APPEND_ONLY streams are optimized for insert-only workloads (event tables, log tables) where you only care about new data. They ignore DELETE, UPDATE, and MERGE delete operations. This makes them more efficient than standard streams for high-volume append patterns. Standard streams capture all DML (inserts, updates, and deletes).',
  },
  {
    id: 'd3_d7_07',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'medium',
    q: 'A DAG needs task_enrich to run AFTER task_extract completes successfully. Which DDL correctly creates this dependency?',
    options: [
      'ALTER TASK task_enrich SET DEPENDS_ON = task_extract',
      'CREATE TASK task_enrich ... AFTER task_extract AS <sql> — the AFTER clause in the child task\'s CREATE statement establishes the parent-child dependency',
      'ALTER TASK task_extract ADD CHILD task_enrich',
      'CREATE TASK task_enrich ... SCHEDULE = \'AFTER task_extract\' AS <sql>',
    ],
    answer: 'CREATE TASK task_enrich ... AFTER task_extract AS <sql> — the AFTER clause in the child task\'s CREATE statement establishes the parent-child dependency',
    exp: 'In Snowflake Task DAGs, child tasks use the AFTER clause to declare their parent. CREATE TASK child_task ... AFTER parent_task AS ... The child task MUST NOT have a SCHEDULE — it inherits the trigger from the root task. Only the root task has a SCHEDULE or CRON. Child tasks cannot be resumed independently; the whole DAG runs when the root triggers.',
  },
  {
    id: 'd3_d7_08',
    domain: 3,
    topic: 'Streams',
    difficulty: 'medium',
    q: 'A stream on the orders table has not been consumed (no MERGE or DML reading it) for an extended period. What happens to the stream?',
    options: [
      'The stream is automatically dropped after 14 days of inactivity',
      'The stream\'s accumulated data is compressed and archived — accessible via UNDROP STREAM',
      'The stream pauses automatically but resumes as soon as the next Task runs',
      'The stream becomes STALE — it can no longer provide change data. This occurs when the underlying table\'s Time Travel retention has expired for the oldest changes tracked by the stream (staleness window = retention days + 14 days)',
    ],
    answer: 'The stream becomes STALE — it can no longer provide change data. This occurs when the underlying table\'s Time Travel retention has expired for the oldest changes tracked by the stream (staleness window = retention days + 14 days)',
    exp: 'Streams depend on Time Travel to track change offsets. If a stream is not consumed and the Time Travel history for its tracked changes expires, the stream goes STALE (IS_STALE = TRUE). A stale stream cannot be read — it needs to be recreated. The staleness window is DATA_RETENTION_TIME_IN_DAYS + 14 additional days. Monitor streams regularly to prevent staleness.',
  },
  {
    id: 'd3_d7_09',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'medium',
    q: 'When creating a Snowflake external stage on S3, why is using a STORAGE INTEGRATION object preferred over storing AWS credentials (ACCESS_KEY_ID and SECRET_ACCESS_KEY) directly in the stage?',
    options: [
      'Storage Integrations support files larger than 5 GB; direct credentials cap uploads at 5 GB',
      'Storage Integrations allow cross-region S3 access; direct credentials are region-restricted',
      'Storage Integrations use IAM role delegation — no long-lived credentials are stored in Snowflake, eliminating the risk of credential exposure or rotation disruption',
      'Direct credentials only support CSV format; Storage Integrations work with all file formats',
    ],
    answer: 'Storage Integrations use IAM role delegation — no long-lived credentials are stored in Snowflake, eliminating the risk of credential exposure or rotation disruption',
    exp: 'A STORAGE INTEGRATION uses an IAM role (AWS) or Service Principal (Azure) via assume-role delegation. Snowflake\'s identity assumes the role temporarily — no static credentials are stored. This follows security best practices: no long-lived access keys to rotate, no credentials that can be stolen from Snowflake\'s DDL, and easier auditability via AWS CloudTrail IAM role assumption logs.',
  },

  {
    id: 'd3_d7_10',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'hard',
    q: 'A Task DAG: task_a (root) → {task_b, task_c, task_d} (all three are children of task_a only). task_a succeeds. task_b fails during its SQL execution. What happens to task_c and task_d?',
    options: [
      'task_c and task_d are cancelled — in Snowflake Task DAGs, any task failure stops all remaining tasks in that DAG run',
      'task_c and task_d run independently — they are siblings of task_b (children of task_a). task_b\'s failure does NOT block siblings; only task_b\'s own children would be skipped',
      'task_c retries task_b\'s SQL before running its own logic',
      'The entire DAG restarts from task_a automatically up to 3 retry attempts',
    ],
    answer: 'task_c and task_d run independently — they are siblings of task_b (children of task_a). task_b\'s failure does NOT block siblings; only task_b\'s own children would be skipped',
    exp: 'In Snowflake Task DAGs, failure propagates DOWN through descendants, not sideways to siblings. Since task_c and task_d depend only on task_a (which succeeded), they proceed normally. If task_b had its own children (task_e, task_f), THOSE would be skipped. Monitoring failed tasks requires checking TASK_HISTORY in ACCOUNT_USAGE — errors don\'t surface automatically unless you configure error notifications.',
  },
  {
    id: 'd3_d7_11',
    domain: 3,
    topic: 'Data Loading',
    difficulty: 'hard',
    q: 'A COPY INTO command uses PURGE = TRUE and completes successfully. What happens to the files in the stage?',
    options: [
      'The files are moved to a Snowflake internal backup location for 7 days before permanent deletion',
      'Files are moved from the stage into the table\'s internal storage directory, replacing the stage copy',
      'Successfully loaded files are immediately and permanently deleted from the stage — there is no recovery mechanism once purged',
      'Files are flagged for deletion but remain accessible in the stage for 24 hours as a safety window',
    ],
    answer: 'Successfully loaded files are immediately and permanently deleted from the stage — there is no recovery mechanism once purged',
    exp: 'PURGE = TRUE instructs Snowflake to delete staged files from the internal (or external) stage immediately after a successful load. This is useful for automated pipelines where you want the stage cleaned up automatically. Use with caution: if you discover a load issue after the fact, the source files are gone. Keep backups elsewhere or use PURGE = FALSE (default) if you need to reprocess.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (13 questions) ───────
  // 4 easy · 6 medium · 3 hard

  {
    id: 'd4_d7_01',
    domain: 4,
    topic: 'SQL Transformations',
    difficulty: 'easy',
    q: 'In a window function like ROW_NUMBER() OVER (PARTITION BY region ORDER BY sale_date), what is the purpose of PARTITION BY region?',
    options: [
      'PARTITION BY filters the query result to only include rows matching the region condition (like WHERE)',
      'PARTITION BY controls the size of the sliding window frame (like ROWS BETWEEN)',
      'PARTITION BY sorts the rows within each window partition for order-sensitive functions',
      'PARTITION BY divides rows into independent groups so the window function restarts its calculation for each group — like a GROUP BY that doesn\'t collapse rows into a single output row',
    ],
    answer: 'PARTITION BY divides rows into independent groups so the window function restarts its calculation for each group — like a GROUP BY that doesn\'t collapse rows into a single output row',
    exp: 'PARTITION BY creates logical groups within the window function. ROW_NUMBER() restarts at 1 for each partition. Without PARTITION BY, the window spans the entire result set. Unlike GROUP BY, PARTITION BY does NOT reduce the number of rows — every original row is present in the output, each annotated with its window function result.',
  },
  {
    id: 'd4_d7_02',
    domain: 4,
    topic: 'Caching',
    difficulty: 'easy',
    q: 'A 24-hour cached query result exists for SELECT COUNT(*) FROM orders. Under what condition is this cache invalidated BEFORE the 24 hours expire?',
    options: [
      'When a different user runs the same query under a Row Access Policy that returns fewer rows',
      'When underlying table data changes — any DML (INSERT, UPDATE, DELETE, COPY INTO, MERGE) on the orders table immediately invalidates all cached results for queries against it',
      'When the warehouse that originally ran the query is suspended and resumed',
      'When the database containing the table is cloned',
    ],
    answer: 'When underlying table data changes — any DML (INSERT, UPDATE, DELETE, COPY INTO, MERGE) on the orders table immediately invalidates all cached results for queries against it',
    exp: 'The result cache is table-aware: any DML that modifies the table\'s micro-partitions (even appending new rows via COPY INTO) triggers immediate cache invalidation for ALL queries that referenced that table. Pure metadata operations (like SHOW or DESCRIBE) do not invalidate data caches. This ensures result cache always reflects current data.',
  },
  {
    id: 'd4_d7_03',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'easy',
    q: 'A developer runs EXPLAIN SELECT * FROM orders WHERE status = \'PENDING\'. What does this return?',
    options: [
      'The logical and physical execution plan for the query — operators like TableScan, Filter, Aggregate — without executing the query or consuming warehouse credits',
      'The estimated cost in credit-seconds and estimated row count for the query',
      'A list of which micro-partitions would be pruned vs scanned for this filter',
      'Actual execution time based on cached statistics from previous runs of identical SQL',
    ],
    answer: 'The logical and physical execution plan for the query — operators like TableScan, Filter, Aggregate — without executing the query or consuming warehouse credits',
    exp: 'EXPLAIN returns the query execution plan (the operator tree Snowflake would use) without running the query. No warehouse compute is consumed — EXPLAIN runs in Cloud Services. It is useful for understanding how Snowflake would execute a query and identifying potential inefficiencies (e.g., unexpected full scans, cross joins) before paying to run them.',
  },
  {
    id: 'd4_d7_04',
    domain: 4,
    topic: 'SQL Transformations',
    difficulty: 'easy',
    q: 'Does rewriting a subquery as a CTE (WITH clause) typically improve performance in Snowflake?',
    options: [
      'Yes — CTEs are always materialized into temporary tables first, which speeds up re-use in complex queries',
      'Yes — subqueries run on warehouse compute; CTEs are pushed down to Cloud Services for free execution',
      'Yes — CTEs enable query-level result caching not available to subqueries',
      'Generally no — Snowflake\'s optimizer inlines CTEs the same way it handles subqueries. Performance is typically equivalent; use CTEs for readability, not as a performance optimization.',
    ],
    answer: 'Generally no — Snowflake\'s optimizer inlines CTEs the same way it handles subqueries. Performance is typically equivalent; use CTEs for readability, not as a performance optimization.',
    exp: 'Unlike some databases where CTEs create materialization boundaries, Snowflake\'s optimizer treats non-recursive CTEs the same as inline subqueries. The resulting execution plan is typically identical. CTEs are strongly preferred for code clarity and maintainability in complex queries, but they are not a performance tuning lever in Snowflake.',
  },

  {
    id: 'd4_d7_05',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'A large warehouse has been running queries for 2 hours, building up a warm local SSD cache. The warehouse is then resized from XL to L. What happens to the cached data?',
    options: [
      'The local SSD cache is preserved — resizing does not affect existing node caches',
      'The cache is persisted to Snowflake internal storage during resize and restored afterward',
      'Only the most recently accessed 50% of cached data is retained after resize',
      'The local SSD cache is completely lost — resizing creates new compute nodes, which start with empty caches. This is why frequent resizing can cause repeated cold-start performance degradation.',
    ],
    answer: 'The local SSD cache is completely lost — resizing creates new compute nodes, which start with empty caches. This is why frequent resizing can cause repeated cold-start performance degradation.',
    exp: 'The warehouse (local) cache is ephemeral — it lives on the node\'s local SSD and is lost when the warehouse is suspended, resized, or if a node is replaced. After a resize, the first queries will experience cold-start performance as the new nodes populate their caches from cloud storage. Avoid frequent resizes if you rely on a warm cache for performance.',
  },
  {
    id: 'd4_d7_06',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'A query runs SELECT region, COUNT(*), SUM(amount) FROM orders GROUP BY region. In the Query Profile, which node represents the grouping and aggregation work?',
    options: [
      'Aggregate — the Aggregate node handles GROUP BY computation, COUNT, SUM, MAX, MIN, and other aggregate functions',
      'Sort — aggregation requires sorting by the group key, so it appears in the Sort node',
      'Filter — GROUP BY filters duplicates, shown as a Filter node in the profile',
      'Exchange — cross-partition aggregation is always shown as an Exchange node when multiple nodes are involved',
    ],
    answer: 'Aggregate — the Aggregate node handles GROUP BY computation, COUNT, SUM, MAX, MIN, and other aggregate functions',
    exp: 'In Snowflake\'s Query Profile, Aggregate is the node for all grouping and aggregation operations. If the data must be shuffled across nodes for aggregation, you may also see an Exchange node feeding into the Aggregate. Seeing a large Aggregate node (high execution time) suggests either a high-cardinality group-by or an inefficient data distribution requiring heavy reshuffling.',
  },
  {
    id: 'd4_d7_07',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'A query joins a large orders table (10 TB) with a small country_codes lookup table (2 MB). Which join strategy does Snowflake most likely choose?',
    options: [
      'Sort-merge join — Snowflake sorts both tables by the join key before merging them',
      'Broadcast join — the small country_codes table is replicated to every compute node processing the large table, avoiding expensive data shuffling of the large table',
      'Nested loop join — every row of orders is iterated against the full country_codes scan',
      'Symmetric hash join with equal data partitioning across all nodes',
    ],
    answer: 'Broadcast join — the small country_codes table is replicated to every compute node processing the large table, avoiding expensive data shuffling of the large table',
    exp: 'When one join side is small enough to fit in each node\'s memory, Snowflake uses a broadcast join: the small table is sent to every node, and each node joins its local partition of the large table against the in-memory copy. This eliminates shuffling the large table across the network. You can see this labeled in the Query Profile as "Broadcast" on the join node.',
  },
  {
    id: 'd4_d7_08',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A developer needs to build a VARIANT OBJECT from SQL column values with specific key names. Which Snowflake function achieves this?',
    options: [
      'PARSE_JSON(\'{"col1": \' || col1 || \'}\') — concatenates column values into a JSON string then parses it',
      'JSON_OBJECT(col1, col2) — the ANSI SQL function for building JSON from column values',
      'OBJECT_CONSTRUCT(\'order_id\', order_id, \'customer\', customer_name) — builds a VARIANT OBJECT with named keys from SQL column values',
      'STRUCT(order_id, customer_name) — Snowflake\'s struct type constructor',
    ],
    answer: 'OBJECT_CONSTRUCT(\'order_id\', order_id, \'customer\', customer_name) — builds a VARIANT OBJECT with named keys from SQL column values',
    exp: 'OBJECT_CONSTRUCT takes alternating key-value pairs and returns a VARIANT OBJECT. Keys must be string literals or expressions. It is the standard Snowflake function for assembling JSON objects from SQL data. Use OBJECT_CONSTRUCT_KEEP_NULL to include null values; the default OBJECT_CONSTRUCT omits keys with NULL values.',
  },
  {
    id: 'd4_d7_09',
    domain: 4,
    topic: 'Semi-structured Data',
    difficulty: 'medium',
    q: 'A VARIANT column data holds the JSON array [10, 20, 30]. Which expression correctly retrieves the value 30 (the last element)?',
    options: [
      'data[0] — zero-based indexing; index 0 = value 10',
      'data[1] — zero-based indexing; index 1 = value 20',
      'data[-1] — negative index for last element (Python-style)',
      'data[2] — zero-based indexing; index 2 is the third and last element (value 30)',
    ],
    answer: 'data[2] — zero-based indexing; index 2 is the third and last element (value 30)',
    exp: 'Snowflake VARIANT arrays use zero-based bracket indexing: data[0] = 10, data[1] = 20, data[2] = 30. Negative indexing (data[-1]) is NOT supported in Snowflake\'s path expressions. Options A and B help reinforce 0-based indexing — a common source of off-by-one errors when coming from SQL or R which use 1-based conventions.',
  },
  {
    id: 'd4_d7_10',
    domain: 4,
    topic: 'AI / ML Features',
    difficulty: 'medium',
    q: 'A Snowpark Python script chains df.filter(), df.join(), and df.select() operations. No data has come back to Python yet. When does Snowflake actually execute these operations?',
    options: [
      'When .collect(), .to_pandas(), .show(), or any other action method is called — Snowpark is lazy: all transformation methods build a query plan but nothing executes in Snowflake until an action triggers it',
      'Immediately when each method is chained — Snowpark eagerly evaluates each transformation as it is called',
      'After a 30-second automatic batching window — Snowpark accumulates operations for efficiency',
      'When the Python script exits or the connection is closed — operations run asynchronously in the background',
    ],
    answer: 'When .collect(), .to_pandas(), .show(), or any other action method is called — Snowpark is lazy: all transformation methods build a query plan but nothing executes in Snowflake until an action triggers it',
    exp: 'Snowpark DataFrames are lazy (like Apache Spark). Calling filter(), join(), select() etc. only modifies the internal logical plan — no SQL is sent to Snowflake, no warehouse credits are consumed. The plan is compiled and executed as a single optimized SQL query when you call an action. This enables efficient query planning and avoids materializing intermediate results unnecessarily.',
  },

  {
    id: 'd4_d7_11',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'hard',
    q: 'SYSTEM$CLUSTERING_INFORMATION(\'orders\', \'(region, order_date)\') returns average_depth = 1.05 (very close to 1.0). An engineer proposes a manual full recluster to optimize performance. What should the response be?',
    options: [
      'Agree — cluster depth should always be maintained at exactly 1.00; any deviation requires immediate action',
      'Disagree — an average_depth of ~1.0 means the table is already optimally clustered; reclustering would waste credits with no performance benefit. This is the target state.',
      'Agree — but only if the table has received more than 1,000 DML operations since the last recluster',
      'Disagree — but increase the clustering key to include 3 more columns for future resilience',
    ],
    answer: 'Disagree — an average_depth of ~1.0 means the table is already optimally clustered; reclustering would waste credits with no performance benefit. This is the target state.',
    exp: 'average_depth in SYSTEM$CLUSTERING_INFORMATION measures partition overlap — depth of 1.0 means zero overlap (perfect clustering). A value near 1.0 (~1.0–1.2) indicates excellent clustering. Manually triggering recluster when depth is already near 1.0 is wasted compute. Monitor for values rising above 2.0–3.0, which suggests increasing overlap that would benefit from reclustering.',
  },
  {
    id: 'd4_d7_12',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'hard',
    q: 'Which query type is BEST suited to benefit from a Materialized View?',
    options: [
      'Ad-hoc queries with varying SQL structure each run — MVs adapt dynamically to any query pattern',
      'Single-row primary-key lookups — MVs are pre-indexed for point queries on large tables',
      'Frequently executed expensive aggregation queries (GROUP BY, SUM, COUNT) over large, slowly-changing base data — the MV pre-computes and maintains the aggregated result, avoiding repeated full scans',
      'Full table scans with no filter or aggregation — pre-materializing a full scan offers no benefit over querying the table directly',
    ],
    answer: 'Frequently executed expensive aggregation queries (GROUP BY, SUM, COUNT) over large, slowly-changing base data — the MV pre-computes and maintains the aggregated result, avoiding repeated full scans',
    exp: 'MVs shine when: (1) the underlying query is expensive (large scan + aggregation), (2) the same query runs frequently, (3) base data changes slowly (so MV refresh overhead is low). Snowflake\'s background refresh service keeps the MV up to date automatically. For ad-hoc or highly variable queries, the result cache is more appropriate. For point lookups, a clustering key or Search Optimization is better.',
  },
  {
    id: 'd4_d7_13',
    domain: 4,
    topic: 'SQL Transformations',
    difficulty: 'hard',
    q: 'A view v_customers exists with SELECT granted to the ANALYST role. A developer runs CREATE OR REPLACE VIEW v_customers AS SELECT ... (a modified version). Without COPY GRANTS, what happens to ANALYST\'s SELECT grant?',
    options: [
      'The ANALYST role\'s grant is preserved automatically — OR REPLACE always carries forward existing grants',
      'The grant is placed in "suspended" state and requires re-approval from ACCOUNTADMIN',
      'The grant is scoped down — ANALYST can only see columns present in both the old and new versions of the view',
      'The ANALYST role loses its SELECT grant — CREATE OR REPLACE recreates the object from scratch, revoking all previously granted privileges. Add COPY GRANTS to the DDL statement to preserve them.',
    ],
    answer: 'The ANALYST role loses its SELECT grant — CREATE OR REPLACE recreates the object from scratch, revoking all previously granted privileges. Add COPY GRANTS to the DDL statement to preserve them.',
    exp: 'CREATE OR REPLACE is equivalent to DROP + CREATE: the old object is removed (losing all grants) and a new object takes its place. Without COPY GRANTS, dependent roles immediately lose access — a production incident waiting to happen. Best practice: always include COPY GRANTS in CREATE OR REPLACE for views and other objects that have downstream consumers.',
  },

  // ── DOMAIN 5: Data Collaboration (5 questions) ────────────────────────────
  // 2 easy · 3 medium

  {
    id: 'd5_d7_01',
    domain: 5,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'easy',
    q: 'A permanent table is created with no explicit DATA_RETENTION_TIME_IN_DAYS setting and the account default has not been changed. How many days of Time Travel history are available?',
    options: [
      '7 days — Snowflake defaults match the Fail-safe duration',
      '0 days — Time Travel must be explicitly configured on each object',
      '1 day — the Snowflake default for DATA_RETENTION_TIME_IN_DAYS on permanent tables is 1 day',
      '90 days — the maximum is available on all editions by default',
    ],
    answer: '1 day — the Snowflake default for DATA_RETENTION_TIME_IN_DAYS on permanent tables is 1 day',
    exp: 'The account-wide default DATA_RETENTION_TIME_IN_DAYS is 1 day (unless changed). Permanent tables inherit this default. Enterprise edition customers can extend up to 90 days at the table, schema, or database level. Standard edition customers are capped at 1 day. Transient and temporary tables have a maximum of 1 day regardless of edition.',
  },
  {
    id: 'd5_d7_02',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'easy',
    q: 'A consumer has a Snowflake account and creates a database from a provider\'s Secure Share. The consumer queries the shared data using THEIR OWN virtual warehouse. Who pays for the compute credits?',
    options: [
      'The consumer — they use their own virtual warehouse, so compute credits are billed to the consumer\'s account',
      'The data provider — they own the underlying data and are responsible for all access costs',
      'Snowflake subsidizes shared data queries as a marketplace growth incentive',
      'Costs are split proportionally between provider and consumer based on query volume',
    ],
    answer: 'The consumer — they use their own virtual warehouse, so compute credits are billed to the consumer\'s account',
    exp: 'In a standard Secure Data Share, the consumer uses their own warehouse to query the shared data. The consumer pays for their own compute. The provider bears no compute cost when consumers query via standard sharing. This is different from Reader Accounts, where the provider creates the warehouse and pays for consumer compute. Zero-copy sharing also means no storage transfer costs.',
  },

  {
    id: 'd5_d7_03',
    domain: 5,
    topic: 'Time Travel & Fail-safe',
    difficulty: 'medium',
    q: 'An admin accidentally runs DROP DATABASE prod_db. The database contained 20 schemas, 500 tables, and 200 views. They run UNDROP DATABASE prod_db immediately. What is recovered?',
    options: [
      'Only the database container itself — schemas and tables must be individually UNDROPped',
      'The database AND all its schemas, tables (with their data and Time Travel history), views, and other contained objects — UNDROP DATABASE fully restores the entire hierarchy as it was at drop time',
      'The database and schemas only — table data requires a Snowflake Support request from Fail-safe',
      'Nothing — UNDROP DATABASE requires DATA_RETENTION_TIME_IN_DAYS to be set to at least 7 days on the database',
    ],
    answer: 'The database AND all its schemas, tables (with their data and Time Travel history), views, and other contained objects — UNDROP DATABASE fully restores the entire hierarchy as it was at drop time',
    exp: 'UNDROP is recursive for containers. UNDROP DATABASE restores the database and all schemas inside it. UNDROP SCHEMA restores the schema and all tables/views inside it. UNDROP TABLE restores a single table. This cascading restoration means a single UNDROP DATABASE is usually all you need after an accidental DROP DATABASE.',
  },
  {
    id: 'd5_d7_04',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'A data consumer creates a database from a provider\'s Secure Share. Can the consumer run INSERT or UPDATE statements against the shared tables?',
    options: [
      'Yes — if the provider grants MODIFY privilege on the share, consumers can write back',
      'Yes — but only if both accounts are on Business Critical edition',
      'Yes — providers can create writable shares by adding WRITE PERMISSION to the share object',
      'No — Secure Data Sharing provides zero-copy read-only access. Shared data is always read-only for consumers; they cannot INSERT, UPDATE, DELETE, or otherwise modify provider data',
    ],
    answer: 'No — Secure Data Sharing provides zero-copy read-only access. Shared data is always read-only for consumers; they cannot INSERT, UPDATE, DELETE, or otherwise modify provider data',
    exp: 'Snowflake Secure Data Sharing is fundamentally read-only from the consumer\'s perspective. The consumer\'s database is a logical pointer to the provider\'s data — no copy exists, and no write path exists back to the provider\'s tables. If bidirectional data exchange is needed, options include Data Clean Rooms (privacy-preserving) or direct data agreements outside Snowflake.',
  },
  {
    id: 'd5_d7_05',
    domain: 5,
    topic: 'Table Types',
    difficulty: 'medium',
    q: 'An external table is created over Parquet files in an Azure Blob Storage container. How many days of Time Travel history does this external table support?',
    options: [
      'The same as the account default (typically 1 day) — external tables inherit account-level Time Travel settings',
      '7 days — external tables use the Fail-safe duration since Azure Blob retains versions',
      '0 days — external tables do not support Time Travel. Snowflake does not own or version the external data, so DATA_RETENTION_TIME_IN_DAYS is fixed at 0.',
      '90 days — same as permanent tables on Enterprise edition, since the data is in cloud storage',
    ],
    answer: '0 days — external tables do not support Time Travel. Snowflake does not own or version the external data, so DATA_RETENTION_TIME_IN_DAYS is fixed at 0.',
    exp: 'External tables are metadata overlays over externally managed cloud storage. Since Snowflake doesn\'t control when files are added, modified, or deleted in S3/GCS/Azure, it cannot maintain Time Travel history for them. DATA_RETENTION_TIME_IN_DAYS = 0 is enforced. If you need time-based versioning of external data, use cloud-native versioning (e.g., S3 versioning) separately.',
  },
];
