// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 1  (Mon Mar 16, 2026)
// COF-C03 Mock Exam · 60 questions
// Distribution: D1 31% (19q) | D2 20% (12q) | D3 18% (11q) | D4 21% (13q) | D5 10% (5q)
// Difficulty mix: ~30% Easy, ~50% Medium, ~20% Hard
//
// DAILY GENERATION RULE:
//   Each new day of questions must share ≤ 30% overlap with the previous day.
//   Before writing a new day, list the question IDs from the previous file and
//   ensure fewer than 18 of the 60 questions are repeated verbatim.
//   Rotate topics, scenarios, and SQL examples each day.
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 1,
  date: '2026-03-16',
  label: 'Day 1 — Foundations',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (19 questions) ─────────────────────

  {
    id: 'd1_01',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'Which layer of the Snowflake architecture is responsible for parsing SQL queries, managing metadata, and enforcing access control?',
    options: [
      'Database Storage Layer',
      'Query Processing (Compute) Layer',
      'Cloud Services Layer',
      'Virtual Warehouse Layer',
    ],
    answer: 'Cloud Services Layer',
    exp: 'Cloud Services coordinates everything: authentication, access control, metadata, query optimization, and infrastructure management. It runs entirely on Snowflake-managed compute.',
  },
  {
    id: 'd1_02',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'What storage format does Snowflake use internally for all table data?',
    options: [
      'Row-oriented CSV files',
      'Columnar compressed micro-partitions',
      'Delta Lake Parquet files',
      'Apache ORC files',
    ],
    answer: 'Columnar compressed micro-partitions',
    exp: 'Snowflake organizes all table data into micro-partitions (50–500 MB uncompressed), stored in a columnar compressed format on cloud object storage.',
  },
  {
    id: 'd1_03',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'A company needs Multi-cluster Virtual Warehouses, Dynamic Data Masking, and Materialized Views. What is the MINIMUM Snowflake edition they require?',
    options: ['Standard', 'Enterprise', 'Business Critical', 'Virtual Private Snowflake'],
    answer: 'Enterprise',
    exp: 'Multi-cluster warehouses, Dynamic Data Masking, and Materialized Views are all Enterprise-tier features. Business Critical is not the minimum — Enterprise suffices.',
  },
  {
    id: 'd1_04',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'Which Snowflake edition is required to configure Database Failover and Failback for business continuity?',
    options: ['Standard', 'Enterprise', 'Business Critical', 'Any edition supports failover'],
    answer: 'Business Critical',
    exp: 'Database Failover/Failback (account-level DR) requires Business Critical or higher. Standard and Enterprise only support database replication, not failover.',
  },
  {
    id: 'd1_05',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'hard',
    q: 'Snowflake charges for Cloud Services usage only under what condition?',
    options: [
      'Cloud Services are always charged separately',
      'Cloud Services are charged when they exceed 10% of the daily virtual warehouse credits',
      'Cloud Services are charged only when ACCOUNTADMIN executes queries',
      'Cloud Services are charged per query optimization event',
    ],
    answer: 'Cloud Services are charged when they exceed 10% of the daily virtual warehouse credits',
    exp: 'Snowflake provides a daily credit adjustment: if Cloud Services usage is ≤ 10% of virtual warehouse credits consumed that day (calculated in UTC), there is no additional charge.',
  },
  {
    id: 'd1_06',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'easy',
    q: 'Which Snowflake interface is a fully web-based SQL editor that requires no driver installation and supports dashboards, notebooks, and data exploration?',
    options: ['SnowSQL CLI', 'Snowsight', 'Snow CLI', 'JDBC Driver'],
    answer: 'Snowsight',
    exp: 'Snowsight is Snowflake\'s browser-based UI — SQL worksheets, charts, dashboards, Snowflake Notebooks, and Data Marketplace access, all without any local install.',
  },
  {
    id: 'd1_07',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'A DevOps team wants to manage Snowflake databases, roles, and warehouses as version-controlled infrastructure-as-code alongside other cloud resources. Which tool fits best?',
    options: ['SnowSQL', 'Snowflake Terraform Provider', 'Snowflake SQL API', 'Snow CLI'],
    answer: 'Snowflake Terraform Provider',
    exp: 'The Terraform Provider for Snowflake lets teams declaratively define and version-control Snowflake resources in HCL alongside other IaC, enabling GitOps workflows.',
  },
  {
    id: 'd1_08',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'easy',
    q: 'What is the correct object hierarchy from top to bottom in Snowflake?',
    options: [
      'Account → Organization → Database → Schema → Table',
      'Organization → Account → Database → Schema → Table',
      'Organization → Account → Warehouse → Database → Table',
      'Account → Database → Schema → Table → Column',
    ],
    answer: 'Organization → Account → Database → Schema → Table',
    exp: 'The hierarchy is: Organization → Account → Database → Schema → Tables/Views/Stages/etc. An Organization can manage multiple accounts.',
  },
  {
    id: 'd1_09',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'Which Snowflake object type is schema-level and stores the metadata for an external S3 location used by COPY INTO commands?',
    options: ['Pipe', 'Stage', 'File Format', 'Task'],
    answer: 'Stage',
    exp: 'A Stage is a schema-level named object that points to a storage location (internal or external). External stages reference cloud buckets (S3, GCS, Azure Blob) for loading/unloading.',
  },
  {
    id: 'd1_10',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'easy',
    q: 'An X-Small warehouse costs 1 credit/hour. A Large warehouse costs:',
    options: ['4 credits/hour', '6 credits/hour', '8 credits/hour', '16 credits/hour'],
    answer: '8 credits/hour',
    exp: 'Credits double with each size step: XS=1, S=2, M=4, L=8, XL=16, 2XL=32, 3XL=64, 4XL=128.',
  },
  {
    id: 'd1_11',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A warehouse runs for 45 seconds and then auto-suspends. How many credits are billed for an X-Small warehouse?',
    options: [
      '0 — too short to bill',
      '0.0125 — 45 seconds of billing',
      '0.0167 — 60-second minimum applies',
      '1.0 — full hour minimum',
    ],
    answer: '0.0167 — 60-second minimum applies',
    exp: 'Snowflake bills per second but enforces a 60-second minimum per warehouse start. 1 credit/hr ÷ 3600s × 60s ≈ 0.0167 credits.',
  },
  {
    id: 'd1_12',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A production warehouse receives 200 concurrent queries every morning, causing heavy queuing. Which configuration best addresses this?',
    options: [
      'Resize the warehouse from Medium to X-Large',
      'Enable Multi-cluster warehouse with Auto-scale mode',
      'Enable the ECONOMY scaling policy',
      'Set AUTO_SUSPEND to 0',
    ],
    answer: 'Enable Multi-cluster warehouse with Auto-scale mode',
    exp: 'Queuing due to high concurrency is solved by scaling OUT (multi-cluster). Resizing (scale UP) improves query speed, not concurrency. Auto-scale starts/stops extra clusters as needed.',
  },
  {
    id: 'd1_13',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'hard',
    q: 'A multi-cluster Medium warehouse runs in Maximized mode (MIN=MAX=3) for 1 hour. What is the total credit consumption?',
    options: ['4 credits', '8 credits', '12 credits', '16 credits'],
    answer: '12 credits',
    exp: 'Maximized mode keeps all clusters running at all times. Medium = 4 credits/hr per cluster. 3 clusters × 4 credits/hr × 1 hr = 12 credits.',
  },
  {
    id: 'd1_14',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'easy',
    q: 'Which table type in Snowflake persists data until explicitly dropped and supports Time Travel?',
    options: ['Temporary table', 'Transient table', 'Permanent table', 'External table'],
    answer: 'Permanent table',
    exp: 'Permanent (standard) tables persist indefinitely, support Time Travel (0–90 days Enterprise), and have Fail-safe (7 days). Transient/Temporary tables have no Fail-safe.',
  },
  {
    id: 'd1_15',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'What is the maximum number of days that Time Travel can be configured for on a permanent table in Snowflake Enterprise edition?',
    options: ['1 day', '7 days', '14 days', '90 days'],
    answer: '90 days',
    exp: 'Enterprise edition supports Time Travel up to 90 days for permanent tables. Standard edition is limited to 1 day. The default is 1 day for both editions.',
  },
  {
    id: 'd1_16',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'A query reads only 3 of the 15 columns in a table. What storage feature of Snowflake ensures only those 3 columns are read from disk?',
    options: [
      'Row-level pruning via micro-partition metadata',
      'Columnar storage — only referenced columns are read',
      'Partition elimination via clustering keys',
      'The result cache serves the query without disk I/O',
    ],
    answer: 'Columnar storage — only referenced columns are read',
    exp: 'Snowflake stores data in columnar format inside micro-partitions. When a query references only specific columns, only those column segments are read — this is column pruning.',
  },
  {
    id: 'd1_17',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'hard',
    q: 'Which view type in Snowflake hides the underlying base table names from users who have access to the view, even when inspecting the view definition?',
    options: ['Standard view', 'Materialized view', 'Secure view', 'Lateral view'],
    answer: 'Secure view',
    exp: 'Secure views hide the view definition from unauthorized users — the underlying table names and logic are not exposed. Required when sharing views externally via Data Sharing.',
  },
  {
    id: 'd1_18',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'A data scientist wants to train an ML model using Python directly inside Snowflake without exporting data. Which Snowflake feature enables this?',
    options: ['Snowflake Cortex Analyst', 'Snowpark (Python stored procedures)', 'Snowsight Notebooks only', 'External Functions'],
    answer: 'Snowpark (Python stored procedures)',
    exp: 'Snowpark lets data engineers/scientists write Python, Java, or Scala directly in Snowflake. Python stored procedures run inside Snowflake\'s compute, eliminating the need to export data.',
  },
  {
    id: 'd1_19',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'Which Snowflake Cortex feature allows users to ask natural-language questions about structured data and get SQL-generated answers?',
    options: ['Cortex Search', 'Cortex Analyst', 'Cortex Guard', 'Snowflake Intelligence'],
    answer: 'Cortex Analyst',
    exp: 'Cortex Analyst translates natural language questions into SQL queries against structured (tabular) data — enabling business users to query data without writing SQL.',
  },

  // ── DOMAIN 2: Account Management & Governance (12 questions) ─────────────

  {
    id: 'd2_01',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'easy',
    q: 'In Snowflake\'s RBAC model, which statement correctly describes role inheritance?',
    options: [
      'A child role inherits all privileges of its parent role',
      'A parent role inherits all privileges of its child roles',
      'Roles do not inherit privileges — all must be explicitly granted',
      'Only ACCOUNTADMIN can inherit privileges from child roles',
    ],
    answer: 'A parent role inherits all privileges of its child roles',
    exp: 'In Snowflake RBAC, when role A is granted to role B, role B (parent) inherits ALL privileges that role A (child) has. This is bottom-up inheritance.',
  },
  {
    id: 'd2_02',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'A user has the primary role ANALYST but also needs the DEV_ROLE active for a specific session to access development schemas. What command activates both roles?',
    options: [
      'USE ROLE DEV_ROLE;',
      'USE SECONDARY ROLES ALL;',
      'GRANT ROLE DEV_ROLE TO USER current_user;',
      'ALTER SESSION SET ROLES = ALL;',
    ],
    answer: 'USE SECONDARY ROLES ALL;',
    exp: 'USE SECONDARY ROLES ALL activates all roles granted to the current user as secondary roles for the session — privileges from all roles combine without changing the primary role.',
  },
  {
    id: 'd2_03',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'What privilege must be granted at ALL three levels before a role can query a table in Snowflake?',
    options: [
      'SELECT on the table only',
      'USAGE on the database, USAGE on the schema, and SELECT on the table',
      'USAGE on the database and SELECT on the table',
      'OWNERSHIP on the schema and SELECT on the table',
    ],
    answer: 'USAGE on the database, USAGE on the schema, and SELECT on the table',
    exp: 'Access is hierarchical: missing any level blocks access. USAGE on database ✓ → USAGE on schema ✓ → SELECT on table ✓ — all three are required.',
  },
  {
    id: 'd2_04',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'easy',
    q: 'Which authentication method is recommended for automated service accounts and CI/CD pipelines because it avoids storing passwords?',
    options: ['MFA with Duo push', 'OAuth 2.0 browser flow', 'Key-pair authentication', 'SCIM provisioning'],
    answer: 'Key-pair authentication',
    exp: 'Key-pair authentication uses a public/private RSA key pair — no password is stored. The private key stays with the client. Ideal for scripts, pipelines, and service accounts.',
  },
  {
    id: 'd2_05',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'A company uses Okta as its identity provider and wants employees to sign into Snowflake using their Okta credentials via SSO. Which protocol does Snowflake use for this?',
    options: ['OAuth 2.0', 'SAML 2.0 (Federated Authentication)', 'OpenID Connect', 'LDAP'],
    answer: 'SAML 2.0 (Federated Authentication)',
    exp: 'Snowflake supports Federated Authentication via SAML 2.0 — integrating with IdPs like Okta, AD FS, and Azure AD for SSO. The IdP authenticates the user and sends a SAML assertion.',
  },
  {
    id: 'd2_06',
    domain: 2,
    topic: 'Network Policies',
    difficulty: 'medium',
    q: 'An account-level network policy allows only 10.0.0.0/8. A specific user has a user-level network policy that allows only 192.168.1.0/24. When that user connects from 192.168.1.100, what happens?',
    options: [
      'Connection is blocked — 192.168.1.100 is not in the account policy',
      'Connection is allowed — the user-level policy overrides the account policy',
      'Connection is allowed — the union of both policies is evaluated',
      'Connection is blocked — both policies must agree to allow the IP',
    ],
    answer: 'Connection is allowed — the user-level policy overrides the account policy',
    exp: 'User-level network policies completely override the account-level policy for that specific user. 192.168.1.100 is in the user\'s policy (192.168.1.0/24), so access is allowed.',
  },
  {
    id: 'd2_07',
    domain: 2,
    topic: 'Data Masking',
    difficulty: 'medium',
    q: 'A masking policy is applied to the EMAIL column in a table. A user with the ANALYST role queries the column. The policy returns \'*****\' for non-privileged roles. What does the analyst see?',
    options: [
      'The real email address',
      'NULL',
      '*****',
      'An error — the column is blocked entirely',
    ],
    answer: '*****',
    exp: 'Dynamic Data Masking evaluates the masking policy at query time. For the ANALYST role (non-privileged), the policy returns the masked value \'*****\' — the original data is never exposed.',
  },
  {
    id: 'd2_08',
    domain: 2,
    topic: 'Object Tagging',
    difficulty: 'medium',
    q: 'A tag "PII" is set at the table level with tag lineage enabled. Which objects automatically inherit the tag?',
    options: [
      'Only the table itself',
      'The table and all its columns',
      'The table, its columns, and any views built on it',
      'Tags are never inherited automatically',
    ],
    answer: 'The table and all its columns',
    exp: 'Tag lineage (propagation) automatically propagates a table-level tag to all columns of that table. Tags do not automatically propagate to downstream views by default.',
  },
  {
    id: 'd2_09',
    domain: 2,
    topic: 'Trust Center',
    difficulty: 'easy',
    q: 'What is the primary purpose of the Snowflake Trust Center?',
    options: [
      'Encrypting data at rest using customer-managed keys',
      'Scanning the account against security benchmarks and identifying misconfigurations',
      'Managing data sharing agreements with other accounts',
      'Auditing query history for compliance reports',
    ],
    answer: 'Scanning the account against security benchmarks and identifying misconfigurations',
    exp: 'Trust Center continuously evaluates the Snowflake account against security frameworks (like CIS benchmarks) and surfaces security risks — such as users without MFA or over-privileged roles.',
  },
  {
    id: 'd2_10',
    domain: 2,
    topic: 'Encryption',
    difficulty: 'hard',
    q: 'Which Snowflake feature allows a customer to use their own encryption key from AWS KMS, Azure Key Vault, or GCP Cloud KMS so that Snowflake cannot access data without the customer\'s key?',
    options: [
      'Column-Level Encryption',
      'Tri-Secret Secure',
      'AES-256 at-rest encryption (default)',
      'External Tokenization',
    ],
    answer: 'Tri-Secret Secure',
    exp: 'Tri-Secret Secure (Business Critical+) combines a Snowflake-managed key, a customer-managed key (CMK), and the composite master key. Without the CMK, Snowflake cannot decrypt data.',
  },
  {
    id: 'd2_11',
    domain: 2,
    topic: 'Replication',
    difficulty: 'medium',
    q: 'A secondary database created by Snowflake replication is in which state?',
    options: [
      'Writable — users can insert/update data',
      'Read-only — users can only query it',
      'Suspended — it must be manually resumed to query',
      'Invisible — only the primary account can see it',
    ],
    answer: 'Read-only — users can only query it',
    exp: 'Secondary databases are always read-only replicas. DML operations on them are not allowed. Writes must go to the primary; the secondary is refreshed via REFRESH.',
  },
  {
    id: 'd2_12',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'You need to find how many credits a specific warehouse consumed last month. Which schema and view should you query?',
    options: [
      'INFORMATION_SCHEMA.WAREHOUSE_METERING_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.CREDIT_USAGE_HISTORY',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY',
    exp: 'ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY contains per-warehouse credit consumption with 1-year retention. INFORMATION_SCHEMA has much shorter retention and is scoped to current DB.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ────────

  {
    id: 'd3_01',
    domain: 3,
    topic: 'Stages',
    difficulty: 'easy',
    q: 'Which type of Snowflake stage is automatically created for every user and does not require any DDL to create?',
    options: ['Named internal stage', 'External stage', 'User stage', 'Table stage'],
    answer: 'User stage',
    exp: 'Each Snowflake user automatically has a personal user stage (~/@~). It requires no CREATE statement and is private to that user. Table stages are auto-created per table.',
  },
  {
    id: 'd3_02',
    domain: 3,
    topic: 'Stages',
    difficulty: 'medium',
    q: 'A team needs to reference the same S3 bucket from multiple tables and schemas with centralized credentials. Which stage type is appropriate?',
    options: ['User stage', 'Table stage', 'Named external stage', 'Internal named stage'],
    answer: 'Named external stage',
    exp: 'Named external stages are schema-level objects pointing to a cloud bucket. They can be reused by multiple COPY INTO statements and support centralized credential/integration management.',
  },
  {
    id: 'd3_03',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'easy',
    q: 'What is the default behavior of COPY INTO when it encounters a row with parsing errors?',
    options: [
      'Skip the bad row and continue loading',
      'Abort the entire load and roll back all rows',
      'Load the bad row to a quarantine table',
      'Log the error and continue loading the rest',
    ],
    answer: 'Abort the entire load and roll back all rows',
    exp: 'The default ON_ERROR setting for COPY INTO is ABORT_STATEMENT — any parsing error aborts the entire copy and rolls back all loaded rows. Use ON_ERROR=CONTINUE or SKIP_FILE to change this.',
  },
  {
    id: 'd3_04',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'medium',
    q: 'After a successful COPY INTO, the same files are run again with COPY INTO. What happens?',
    options: [
      'The files are loaded again, creating duplicates',
      'The files are skipped — COPY INTO tracks loaded files for 64 days',
      'An error is thrown: files already loaded',
      'The files overwrite the existing rows',
    ],
    answer: 'The files are skipped — COPY INTO tracks loaded files for 64 days',
    exp: 'Snowflake maintains a load history per stage/table for 64 days. Files already loaded are automatically skipped unless FORCE=TRUE is specified.',
  },
  {
    id: 'd3_05',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'medium',
    q: 'Which compute type does Snowpipe use to load data, and how does this affect billing?',
    options: [
      'Virtual warehouses — billed per warehouse credit',
      'Serverless compute managed by Snowflake — billed per compute-second',
      'Cloud provider compute — no Snowflake charges',
      'Shared pool from SYSTEM warehouse — no extra billing',
    ],
    answer: 'Serverless compute managed by Snowflake — billed per compute-second',
    exp: 'Snowpipe uses Snowflake-managed serverless compute (not a virtual warehouse). It is billed as compute-hours. Resource monitors do not apply to Snowpipe consumption.',
  },
  {
    id: 'd3_06',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'medium',
    q: 'A team wants files uploaded to S3 to be automatically loaded into Snowflake within seconds. What is the recommended Snowpipe trigger?',
    options: [
      'Schedule a Task to run COPY INTO every 5 minutes',
      'Use Snowpipe with cloud event notifications (S3 SQS/SNS)',
      'Use Snowpipe REST API called from a Lambda function',
      'Use COPY INTO with AUTO_INGEST=TRUE on the stage',
    ],
    answer: 'Use Snowpipe with cloud event notifications (S3 SQS/SNS)',
    exp: 'Snowpipe\'s AUTO_INGEST=TRUE triggers loading automatically when cloud event notifications (S3 → SQS, Azure Event Grid, GCP Pub/Sub) detect new files — near-real-time ingestion.',
  },
  {
    id: 'd3_07',
    domain: 3,
    topic: 'Streams',
    difficulty: 'medium',
    q: 'What does a Snowflake Stream capture?',
    options: [
      'A point-in-time snapshot of a table',
      'The change data (inserts, updates, deletes) on a table since the last stream consumption',
      'The schema evolution history of a table',
      'Query execution plans for a table',
    ],
    answer: 'The change data (inserts, updates, deletes) on a table since the last stream consumption',
    exp: 'A Stream is a CDC (Change Data Capture) object that records DML changes (INSERTs, UPDATEs, DELETEs) on a source table. The offset advances each time the stream is consumed in a DML transaction.',
  },
  {
    id: 'd3_08',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'medium',
    q: 'A Snowflake Task is configured with SCHEDULE = \'5 MINUTE\'. What must be done before the task will actually execute on schedule?',
    options: [
      'Nothing — tasks run immediately after creation',
      'The task must be resumed with ALTER TASK … RESUME',
      'The warehouse assigned must be running',
      'ACCOUNTADMIN must approve the task schedule',
    ],
    answer: 'The task must be resumed with ALTER TASK … RESUME',
    exp: 'New tasks are created in SUSPENDED state by default. You must execute ALTER TASK <name> RESUME before it will run on schedule. This is a common exam trap.',
  },
  {
    id: 'd3_09',
    domain: 3,
    topic: 'File Formats',
    difficulty: 'easy',
    q: 'Which file format is natively semi-structured and supported by Snowflake\'s VARIANT data type for direct querying without pre-defined schemas?',
    options: ['CSV', 'Parquet', 'JSON', 'ORC'],
    answer: 'JSON',
    exp: 'JSON (along with AVRO, Parquet, ORC, XML) is a semi-structured format. Snowflake loads it into the VARIANT column type, which supports dot notation and bracket notation for querying nested fields.',
  },
  {
    id: 'd3_10',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'medium',
    q: 'An application needs to call an external payment REST API from inside a Snowflake SQL query. Which Snowflake feature enables this?',
    options: [
      'External Stage with URL parameter',
      'Storage Integration',
      'External Function via API Integration',
      'Notification Integration',
    ],
    answer: 'External Function via API Integration',
    exp: 'External Functions let Snowflake SQL call external REST APIs synchronously. The API Integration defines the endpoint and security; the External Function wraps it as a callable SQL function.',
  },
  {
    id: 'd3_11',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'hard',
    q: 'A team needs to connect an S3 external stage securely without storing AWS access keys inside Snowflake. What is the correct approach?',
    options: [
      'Embed the AWS_KEY_ID and AWS_SECRET_KEY in the CREDENTIALS clause',
      'Use a Storage Integration that leverages an IAM role with cross-account trust',
      'Use a Notification Integration to grant S3 access',
      'Store credentials in a Snowflake Secret object',
    ],
    answer: 'Use a Storage Integration that leverages an IAM role with cross-account trust',
    exp: 'Storage Integration uses an AWS IAM role (assumed via Snowflake\'s own AWS account through cross-account trust). No credentials are stored in Snowflake — only the IAM role ARN is referenced.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (13 questions) ────────

  {
    id: 'd4_01',
    domain: 4,
    topic: 'Caching',
    difficulty: 'easy',
    q: 'A user runs the same SELECT query twice in a row on the same warehouse. The second execution returns results instantly. Which cache type served the second result?',
    options: [
      'Metadata cache (Cloud Services)',
      'Remote disk cache (S3/Blob/GCS)',
      'Result cache (Cloud Services)',
      'Local SSD cache (Virtual Warehouse)',
    ],
    answer: 'Result cache (Cloud Services)',
    exp: 'The Result Cache stores the output of queries in Cloud Services for 24 hours. If the same SQL is run by any user and the underlying data has not changed, the cached result is served instantly — no warehouse needed.',
  },
  {
    id: 'd4_02',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'Which action will INVALIDATE the Snowflake result cache for a specific query?',
    options: [
      'Re-running the same query with a different user',
      'The underlying table being modified (DML)',
      'Suspending and resuming the warehouse',
      'Switching to a different role',
    ],
    answer: 'The underlying table being modified (DML)',
    exp: 'The result cache is invalidated when the underlying data changes (INSERT, UPDATE, DELETE, MERGE on source tables) or after 24 hours. Role changes or warehouse operations do not invalidate it.',
  },
  {
    id: 'd4_03',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'The local SSD cache on a Virtual Warehouse is lost when:',
    options: [
      'The result cache expires after 24 hours',
      'The warehouse is suspended',
      'A new query is submitted',
      'The table metadata is updated',
    ],
    answer: 'The warehouse is suspended',
    exp: 'The local SSD (warehouse data) cache is ephemeral — it lives on the virtual warehouse nodes. When a warehouse suspends, the nodes are released and the cache is discarded.',
  },
  {
    id: 'd4_04',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'How does Snowflake use micro-partition metadata to improve query performance?',
    options: [
      'It compresses data further at query time',
      'It prunes (skips) entire micro-partitions whose min/max values exclude the WHERE clause filter',
      'It distributes queries across multiple warehouses automatically',
      'It converts SQL to a more optimal dialect before execution',
    ],
    answer: 'It prunes (skips) entire micro-partitions whose min/max values exclude the WHERE clause filter',
    exp: 'Snowflake stores min/max, null count, and distinct count metadata for every column in every micro-partition. The query optimizer skips micro-partitions that cannot contain rows matching the WHERE clause — this is partition pruning.',
  },
  {
    id: 'd4_05',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'medium',
    q: 'A large fact table is frequently queried with WHERE ORDER_DATE BETWEEN … filters but has poor pruning. What should you do?',
    options: [
      'Increase the warehouse size to improve scan speed',
      'Define a clustering key on ORDER_DATE',
      'Partition the table by day using DDL partitioning',
      'Convert the table to a Materialized View',
    ],
    answer: 'Define a clustering key on ORDER_DATE',
    exp: 'Clustering keys co-locate rows with similar ORDER_DATE values into the same micro-partitions. This dramatically improves partition pruning (and scan efficiency) for range-based date filters.',
  },
  {
    id: 'd4_06',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'hard',
    q: 'What does the SYSTEM$CLUSTERING_INFORMATION function return?',
    options: [
      'The list of all clustering keys defined in the account',
      'Statistics about the current clustering depth and efficiency of a table',
      'The cost of re-clustering the table',
      'The list of micro-partitions that need compaction',
    ],
    answer: 'Statistics about the current clustering depth and efficiency of a table',
    exp: 'SYSTEM$CLUSTERING_INFORMATION returns metrics like average_depth, average_overlaps, and a histogram showing how well the table data is sorted by the clustering key — used to decide if re-clustering is needed.',
  },
  {
    id: 'd4_07',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'medium',
    q: 'Which statement about Materialized Views in Snowflake is TRUE?',
    options: [
      'Materialized Views must be manually refreshed with ALTER MATERIALIZED VIEW ... REFRESH',
      'Materialized Views are automatically refreshed by Snowflake serverless compute when base data changes',
      'Materialized Views require a virtual warehouse to stay synchronized',
      'Materialized Views are available in Standard edition',
    ],
    answer: 'Materialized Views are automatically refreshed by Snowflake serverless compute when base data changes',
    exp: 'Snowflake automatically maintains Materialized Views using serverless background compute — no manual refresh needed. This is billed separately from virtual warehouse credits.',
  },
  {
    id: 'd4_08',
    domain: 4,
    topic: 'Search Optimization',
    difficulty: 'medium',
    q: 'Search Optimization Service in Snowflake is designed to improve the performance of which query pattern?',
    options: [
      'Large analytical range scans on date columns',
      'Selective point lookups on high-cardinality columns (e.g., WHERE user_id = ?)',
      'Aggregation queries on low-cardinality categorical columns',
      'Joins between large fact and dimension tables',
    ],
    answer: 'Selective point lookups on high-cardinality columns (e.g., WHERE user_id = ?)',
    exp: 'Search Optimization Service builds access path structures for point lookups and equality/IN predicates on high-cardinality columns — not for full table scans or range queries.',
  },
  {
    id: 'd4_09',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'medium',
    q: 'A JSON document is stored in a VARIANT column called "data". Which syntax correctly extracts the field "user.name"?',
    options: [
      'data.user.name',
      'data["user"]["name"]',
      'data:user:name',
      'GET(data, \'user.name\')',
    ],
    answer: 'data:user:name',
    exp: 'Snowflake uses colon notation (data:user:name) to navigate VARIANT paths. Bracket notation (data["user"]["name"]) also works. The colon is the idiomatic Snowflake way.',
  },
  {
    id: 'd4_10',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'hard',
    q: 'What does the FLATTEN table function do in Snowflake?',
    options: [
      'Compresses nested objects into a single string',
      'Expands a VARIANT array or object into multiple rows — one per element',
      'Normalizes a VARIANT column into a relational table',
      'Parses a JSON string into a VARIANT value',
    ],
    answer: 'Expands a VARIANT array or object into multiple rows — one per element',
    exp: 'FLATTEN is a table function that "explodes" a VARIANT array or object into individual rows — similar to LATERAL JOIN / UNNEST in other databases. Used to process arrays embedded in JSON.',
  },
  {
    id: 'd4_11',
    domain: 4,
    topic: 'Query Profile',
    difficulty: 'medium',
    q: 'A query takes much longer than expected. In Snowsight\'s Query Profile, you see a node with the label "TableScan" consuming 98% of total time. What is the most likely root cause?',
    options: [
      'The warehouse is undersized',
      'Poor partition pruning — too many micro-partitions are being scanned',
      'The result cache was invalidated',
      'The query has too many JOINs',
    ],
    answer: 'Poor partition pruning — too many micro-partitions are being scanned',
    exp: 'When TableScan dominates Query Profile time, it usually means Snowflake cannot skip micro-partitions — often because filters are on non-clustered columns or data types mismatch.',
  },
  {
    id: 'd4_12',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'Which Snowflake object can be used to define a reusable SQL transformation that runs on a schedule or when triggered, consuming credits from a specified warehouse?',
    options: ['Stream', 'Pipe', 'Task', 'Dynamic Table'],
    answer: 'Task',
    exp: 'Tasks execute SQL statements (or stored procedure calls) on a schedule (CRON or interval) or when triggered by stream data. They use a specified warehouse (or serverless compute).',
  },
  {
    id: 'd4_13',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'hard',
    q: 'What is a Dynamic Table in Snowflake?',
    options: [
      'A table that automatically adjusts its schema based on incoming data',
      'A declarative, incrementally-refreshed materialized result of a SQL query that tracks lag',
      'A table that automatically partitions by ingestion timestamp',
      'A table that replaces all rows when its source data changes',
    ],
    answer: 'A declarative, incrementally-refreshed materialized result of a SQL query that tracks lag',
    exp: 'Dynamic Tables define a SQL transformation and a TARGET_LAG. Snowflake automatically keeps the table up to date by incrementally processing changes from source tables — a simpler alternative to Streams+Tasks pipelines.',
  },

  // ── DOMAIN 5: Data Collaboration (5 questions) ───────────────────────────

  {
    id: 'd5_01',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'easy',
    q: 'In Snowflake Secure Data Sharing, what is shared with the consumer account?',
    options: [
      'A physical copy of the data is transferred to the consumer',
      'A read-only reference to the provider\'s data — no data is copied',
      'Compressed delta files are replicated nightly',
      'SQL views that run on the consumer\'s warehouse',
    ],
    answer: 'A read-only reference to the provider\'s data — no data is copied',
    exp: 'Data Sharing is zero-copy — no data is duplicated. The consumer gets live read access to the provider\'s data via Snowflake\'s metadata. Queries run on the consumer\'s own warehouse but read provider data.',
  },
  {
    id: 'd5_02',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'A consumer Snowflake account wants to query shared data from a provider. What Snowflake object do they create from the share?',
    options: ['A Shared Table', 'A Database created FROM SHARE', 'A replica database', 'An External Table'],
    answer: 'A Database created FROM SHARE',
    exp: 'Consumers create a database from the share using CREATE DATABASE <name> FROM SHARE <provider>.<share_name>. This gives them a local reference to the shared objects without copying data.',
  },
  {
    id: 'd5_03',
    domain: 5,
    topic: 'Time Travel',
    difficulty: 'medium',
    q: 'A developer accidentally drops a table. Using Time Travel, which command restores the table?',
    options: [
      'RESTORE TABLE mydb.public.orders;',
      'UNDROP TABLE mydb.public.orders;',
      'RECOVER TABLE mydb.public.orders AT (BEFORE DROP);',
      'ALTER TABLE mydb.public.orders RESTORE;',
    ],
    answer: 'UNDROP TABLE mydb.public.orders;',
    exp: 'UNDROP TABLE restores a dropped table from Time Travel. It also works for schemas and databases. The table must still be within the Time Travel retention window.',
  },
  {
    id: 'd5_04',
    domain: 5,
    topic: 'Cloning',
    difficulty: 'medium',
    q: 'What is the storage cost of cloning a 10 TB table immediately after the clone is created?',
    options: [
      '10 TB — full copy is made',
      '20 TB — original and clone both store 10 TB',
      '0 additional storage — clone shares micro-partitions with the source until modified',
      'Storage cost depends on the warehouse size used for cloning',
    ],
    answer: '0 additional storage — clone shares micro-partitions with the source until modified',
    exp: 'Zero-copy cloning creates a clone that shares all existing micro-partitions with the source. No data is duplicated at clone time. New storage is only consumed when the clone is modified (copy-on-write).',
  },
  {
    id: 'd5_05',
    domain: 5,
    topic: 'Marketplace',
    difficulty: 'easy',
    q: 'A company wants to publish a dataset for external companies to discover and use without copying data. Which Snowflake feature supports this?',
    options: [
      'Snowflake Marketplace listing',
      'Snowflake Replication Group',
      'Snowflake External Table',
      'Snowflake Data Exchange (private)',
    ],
    answer: 'Snowflake Marketplace listing',
    exp: 'Snowflake Marketplace lets providers publish live data products (no copy) that consumers can discover and query. Listings can be free or paid. The Marketplace is the public catalog; Data Exchange is private.',
  },
];
