// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Hard Drill 1  (2026-04-17)
// COF-C03 Hard-Mode Real-Like Set · 30 questions · 60 min
// Distribution (proportional to real exam):
//   D1 30% (9q) | D2 20% (6q) | D3 20% (6q) | D4 20% (6q) | D5 10% (3q)
//
// Difficulty mix: 100% HARD — no warm-ups.
// Each question is modeled after the trickiest angles seen on COF-C03:
//   - edge-case numeric values (cache windows, retention, billing thresholds)
//   - policy interactions (masking + EXECUTE AS OWNER, secondary roles)
//   - feature-blurring (Iceberg vs native, Snowpipe vs bulk, Stream vs DT)
//   - misleading names (Reader Account, Economy scaling, AUTO_SUSPEND=0)
//   - fake-vs-real system functions and privilege boundaries
//
// Topics avoid repeating the previous Day-11 angles — this set is a standalone
// "trap drill" you run when you want to stress-test weak spots.
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 'H1',
  date: '2026-04-17',
  label: 'Hard Drill 1 — Real-Like Traps (30q)',
  totalQuestions: 30,
  timeMinutes: 60,
};

export const QUESTIONS = [
  // ── DOMAIN 1: Architecture & Features (9 questions) ────────────────────────
  {
    id: 'd1_h1_01',
    domain: 1,
    topic: 'Cloud Services Layer — Billing Threshold',
    difficulty: 'hard',
    q: 'A customer sees occasional line items for "Cloud Services" compute in their daily credit usage. Under what condition do Cloud Services credits become billable?',
    options: [
      'All Cloud Services activity is always billed per-second, independently of warehouse usage.',
      'Cloud Services activity is only billed for queries executed by reader accounts.',
      'Cloud Services activity is billed only for the portion that exceeds 10% of that day\'s warehouse credit consumption.',
      'Cloud Services activity is billed on a per-query basis, regardless of total warehouse credits.',
    ],
    answer: 'Cloud Services activity is billed only for the portion that exceeds 10% of that day\'s warehouse credit consumption.',
    exp: 'Cloud Services is "free" up to 10% of daily warehouse credits. Only the portion above the 10% threshold is billed, which is why metadata-heavy accounts (lots of SHOW/DDL) can see occasional CS charges.',
  },
  {
    id: 'd1_h1_02',
    domain: 1,
    topic: 'Virtual Private Snowflake (VPS) Edition',
    difficulty: 'hard',
    q: 'A customer in a highly regulated industry requires a dedicated metadata store and dedicated cloud-services infrastructure, physically isolated from all other Snowflake tenants. Which edition satisfies this requirement?',
    options: [
      'Enterprise',
      'Business Critical',
      'Standard (with Tri-Secret Secure add-on)',
      'Virtual Private Snowflake (VPS)',
    ],
    answer: 'Virtual Private Snowflake (VPS)',
    exp: 'VPS is the only edition that provides a completely isolated deployment including dedicated metadata store and cloud services — above Business Critical\'s security features.',
  },
  {
    id: 'd1_h1_03',
    domain: 1,
    topic: 'Multi-cluster — ECONOMY Scaling Wait',
    difficulty: 'hard',
    q: 'A multi-cluster warehouse is configured with AUTO_SCALE and SCALING_POLICY = ECONOMY (MAX_CLUSTER_COUNT = 4). Queries start queuing heavily on cluster 1. Approximately how long will the warehouse wait before starting an additional cluster?',
    options: [
      'Immediately as soon as any query queues (STANDARD behavior).',
      'After ~30 seconds of sustained queuing.',
      'After ~2 minutes of sustained queuing.',
      'After approximately 6 minutes of sustained queuing.',
    ],
    answer: 'After approximately 6 minutes of sustained queuing.',
    exp: 'ECONOMY intentionally waits ~6 min to confirm sustained load before spinning a new cluster (optimizing cost over latency). STANDARD adds clusters on first queued statement.',
  },
  {
    id: 'd1_h1_04',
    domain: 1,
    topic: 'Micro-partitions — Immutability',
    difficulty: 'hard',
    q: 'Which statement about Snowflake micro-partitions is TRUE?',
    options: [
      'Micro-partitions are immutable; any DML produces NEW micro-partitions and marks old ones as logically deleted, with physical reclamation governed by Time Travel and Fail-safe.',
      'Micro-partitions are updated in place to reduce total storage growth from frequent DML.',
      'Micro-partitions are stored row-oriented to accelerate OLTP workloads.',
      'Micro-partitions are always exactly 16 MB compressed on disk regardless of data type.',
    ],
    answer: 'Micro-partitions are immutable; any DML produces NEW micro-partitions and marks old ones as logically deleted, with physical reclamation governed by Time Travel and Fail-safe.',
    exp: 'Micro-partitions are columnar, ~50–500 MB uncompressed (≈16 MB compressed), AES-256 encrypted, and IMMUTABLE. DML never rewrites a micro-partition — it always writes new ones.',
  },
  {
    id: 'd1_h1_05',
    domain: 1,
    topic: 'Time Travel — UNDROP after CREATE with Same Name',
    difficulty: 'hard',
    q: 'A developer runs: DROP TABLE t1; CREATE TABLE t1 (...); on a permanent table with 90-day retention. She then runs UNDROP TABLE t1;. What happens?',
    options: [
      'UNDROP transparently merges the old and new versions of t1 into one table.',
      'UNDROP fails because a table named t1 already exists — the new t1 must be dropped or renamed first.',
      'UNDROP silently replaces the current t1 with the historical version, and the new t1 is discarded.',
      'UNDROP succeeds and creates a second visible object named t1 in the schema.',
    ],
    answer: 'UNDROP fails because a table named t1 already exists — the new t1 must be dropped or renamed first.',
    exp: 'UNDROP restores to the ORIGINAL name. If an object with that name already exists in the schema, the command fails. You must DROP or RENAME the conflicting object before UNDROP will succeed.',
  },
  {
    id: 'd1_h1_06',
    domain: 1,
    topic: 'Snowpark-optimized Warehouse — Minimum Size',
    difficulty: 'hard',
    q: 'A data scientist wants to create a warehouse with WAREHOUSE_TYPE = \'SNOWPARK-OPTIMIZED\' to run a memory-intensive UDF. What is the SMALLEST permitted warehouse size?',
    options: [
      'X-Small',
      'Small',
      'Medium',
      'Large',
    ],
    answer: 'Medium',
    exp: 'Snowpark-optimized warehouses require a minimum size of Medium. Compared to a standard warehouse at the same size, they provide ~16× memory per node — useful for ML workloads.',
  },
  {
    id: 'd1_h1_07',
    domain: 1,
    topic: 'Apache Iceberg — External Catalog Writability',
    difficulty: 'hard',
    q: 'A team creates an Apache Iceberg table in Snowflake using an EXTERNAL catalog (for example, AWS Glue). Which behavioral difference should they expect vs a Snowflake-managed (internal-catalog) Iceberg table?',
    options: [
      'Iceberg tables with an external catalog are READ-ONLY from Snowflake — DML must go through the engine that owns the catalog.',
      'Iceberg tables with an external catalog do not support Time Travel, but internal-catalog Iceberg tables do.',
      'Iceberg tables with an external catalog always use ~2× the storage of a native Snowflake FDN table.',
      'Iceberg tables with an external catalog cannot be queried with standard SQL and require Snowpark.',
    ],
    answer: 'Iceberg tables with an external catalog are READ-ONLY from Snowflake — DML must go through the engine that owns the catalog.',
    exp: 'With an EXTERNAL Iceberg catalog, only the owning engine (e.g. Spark, Glue) can write. Snowflake reads via the catalog. With a Snowflake-managed catalog, Snowflake can read AND write.',
  },
  {
    id: 'd1_h1_08',
    domain: 1,
    topic: 'QUERY_TAG — Session Precedence',
    difficulty: 'hard',
    q: 'A DBA runs ALTER USER jdoe SET QUERY_TAG = \'finance_team\'; and ALTER WAREHOUSE wh_a SET QUERY_TAG = \'reporting\';. User jdoe then runs ALTER SESSION SET QUERY_TAG = \'adhoc\'; and executes a query on wh_a. What QUERY_TAG value appears in QUERY_HISTORY for that query?',
    options: [
      'finance_team — user-level tag always wins for attribution.',
      'reporting — warehouse-level tag overrides session and user.',
      'A comma-separated concatenation of finance_team, reporting, and adhoc.',
      'adhoc — the session-level QUERY_TAG takes precedence for the executing query.',
    ],
    answer: 'adhoc — the session-level QUERY_TAG takes precedence for the executing query.',
    exp: 'QUERY_TAG resolution is session > user > account default. A session-level ALTER SESSION SET QUERY_TAG overrides the user default for that session. Note: warehouses do NOT have a QUERY_TAG parameter — that "ALTER WAREHOUSE" call would actually fail in reality; it\'s an exam distractor.',
  },
  {
    id: 'd1_h1_09',
    domain: 1,
    topic: 'Cortex — Feature Recognition',
    difficulty: 'hard',
    q: 'The COF-C03 exam expects you to recognize the Cortex feature surface. Which of the following is NOT an actual Snowflake Cortex feature?',
    options: [
      'Cortex Analyst — natural-language queries against a structured semantic model.',
      'Cortex Search — managed vector / hybrid search over unstructured text.',
      'Cortex Complete — invoking foundation LLMs directly from SQL.',
      'Cortex Train — a service that deploys customer-trained classical ML models from an external S3 bucket.',
    ],
    answer: 'Cortex Train — a service that deploys customer-trained classical ML models from an external S3 bucket.',
    exp: 'Cortex Train is fabricated. Real Cortex features include Analyst, Search, Complete, Summarize, Guard, plus ML Functions and Document AI. Model deployment uses Snowflake ML / Model Registry, not "Cortex Train".',
  },

  // ── DOMAIN 2: Account Management & Governance (6 questions) ────────────────
  {
    id: 'd2_h1_10',
    domain: 2,
    topic: 'Row Access Policy — Implicit NULL/Zero-rows Trap',
    difficulty: 'hard',
    q: 'A row access policy is defined as: CASE WHEN CURRENT_ROLE() = \'SALES\' THEN region = \'US\' END. When a role OTHER than SALES queries the table, what rows does it see?',
    options: [
      'All rows — the policy only restricts SALES; other roles are unaffected.',
      'Zero rows — the CASE returns NULL for non-SALES roles, and NULL is treated as FALSE in a row access policy.',
      'Only rows where region IS NULL, because the CASE returns NULL.',
      'An error is raised because the policy lacks an ELSE clause.',
    ],
    answer: 'Zero rows — the CASE returns NULL for non-SALES roles, and NULL is treated as FALSE in a row access policy.',
    exp: 'A row access policy must return BOOLEAN. A CASE with no matching WHEN and no ELSE returns NULL, and NULL is treated as FALSE by the row access policy — so the role sees nothing. ACCOUNTADMIN is NOT exempt.',
  },
  {
    id: 'd2_h1_11',
    domain: 2,
    topic: 'Masking Policy — CURRENT_ROLE vs Secondary Roles',
    difficulty: 'hard',
    q: 'A user\'s primary role is ANALYST. The user has activated all secondary roles with USE SECONDARY ROLES ALL, including role FINANCE. A masking policy uses: CASE WHEN CURRENT_ROLE() = \'FINANCE\' THEN val ELSE \'***\' END. What does the user see when querying the masked column?',
    options: [
      'Masked values — CURRENT_ROLE() returns only the primary role (ANALYST), so FINANCE never matches.',
      'Unmasked values — FINANCE is active as a secondary role.',
      'An error — masking policies are not permitted to reference CURRENT_ROLE().',
      'Unmasked values, but only for rows the FINANCE role owns.',
    ],
    answer: 'Masked values — CURRENT_ROLE() returns only the primary role (ANALYST), so FINANCE never matches.',
    exp: 'CURRENT_ROLE() returns ONLY the primary role. To make a masking policy secondary-role aware, use IS_ROLE_IN_SESSION(\'FINANCE\'), which returns TRUE for primary, secondary, or inherited roles in the session.',
  },
  {
    id: 'd2_h1_12',
    domain: 2,
    topic: 'CREATE RESOURCE MONITOR — Non-delegable',
    difficulty: 'hard',
    q: 'A Snowflake admin wants to delegate the ability to CREATE resource monitors to a custom role so that business unit leads can self-serve. What is the correct approach?',
    options: [
      'Issue GRANT CREATE RESOURCE MONITOR ON ACCOUNT TO ROLE bu_admin.',
      'Grant ROLE ORGADMIN to the custom role, which permits resource monitor creation.',
      'It cannot be delegated — only ACCOUNTADMIN may CREATE resource monitors.',
      'Issue GRANT MODIFY ON ALL RESOURCE MONITORS TO ROLE bu_admin.',
    ],
    answer: 'It cannot be delegated — only ACCOUNTADMIN may CREATE resource monitors.',
    exp: 'CREATE RESOURCE MONITOR is a non-delegable ACCOUNTADMIN-only privilege. MONITOR and MODIFY on specific resource monitors CAN be delegated to view or change existing ones, but creation cannot.',
  },
  {
    id: 'd2_h1_13',
    domain: 2,
    topic: 'Network Policy — User-level Overrides Account-level',
    difficulty: 'hard',
    q: 'An account-level network policy allows 10.0.0.0/8. A user-level network policy on user JDOE allows ONLY 192.168.1.0/24. JDOE attempts to connect from 10.0.0.50. What happens?',
    options: [
      'Connection succeeds — the account-level policy covers the IP.',
      'Connection succeeds — policies are additive, so any allowed range works.',
      'Connection succeeds — user-level policies only restrict OUTBOUND traffic.',
      'Connection is BLOCKED — user-level network policy overrides the account-level policy, and 10.0.0.50 is not in 192.168.1.0/24.',
    ],
    answer: 'Connection is BLOCKED — user-level network policy overrides the account-level policy, and 10.0.0.50 is not in 192.168.1.0/24.',
    exp: 'User-level network policy completely overrides (not supplements) the account-level policy for that user. The user is evaluated solely against their own policy.',
  },
  {
    id: 'd2_h1_14',
    domain: 2,
    topic: 'Failover Groups — Edition + Capability',
    difficulty: 'hard',
    q: 'A Business Critical account needs to replicate databases PLUS users, roles, integrations, and warehouses together, with primary/secondary failover. Which mechanism is required?',
    options: [
      'Database Replication with OAuth shadow accounts.',
      'Standard Replication Groups on Enterprise edition.',
      'Failover Groups on Business Critical or higher edition.',
      'External Tokens plus Tri-Secret Secure replication.',
    ],
    answer: 'Failover Groups on Business Critical or higher edition.',
    exp: 'Replication Groups (Enterprise) replicate account objects together but cannot failover. Failover Groups (Business Critical+) replicate account objects AND support primary promotion (failover) across regions or clouds.',
  },
  {
    id: 'd2_h1_15',
    domain: 2,
    topic: 'GRANT OWNERSHIP — COPY CURRENT GRANTS',
    difficulty: 'hard',
    q: 'A role owns a table that has multiple SELECT grants issued to other roles. An admin runs: GRANT OWNERSHIP ON TABLE t1 TO ROLE newowner COPY CURRENT GRANTS; What is the result?',
    options: [
      'Ownership transfers to newowner, and all existing grants on t1 are preserved.',
      'Ownership transfers to newowner, but all existing grants on t1 are revoked (default behavior without REVOKE CURRENT GRANTS).',
      'The statement fails — COPY CURRENT GRANTS is only valid on CREATE TABLE ... CLONE.',
      'Ownership transfers only if newowner is an ancestor of the current owner.',
    ],
    answer: 'Ownership transfers to newowner, and all existing grants on t1 are preserved.',
    exp: 'GRANT OWNERSHIP defaults to REVOKE CURRENT GRANTS. Passing COPY CURRENT GRANTS preserves existing downstream grants after the ownership transfer.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (6 questions) ─────────
  {
    id: 'd3_h1_16',
    domain: 3,
    topic: 'COPY INTO — MATCH_BY_COLUMN_NAME with Parquet',
    difficulty: 'hard',
    q: 'A team runs: COPY INTO orders FROM @stg FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE; Which statement is TRUE about this load?',
    options: [
      'MATCH_BY_COLUMN_NAME is only supported for CSV files.',
      'CASE_INSENSITIVE requires the target table to use quoted identifiers.',
      'Snowflake matches each Parquet column to a target column by name, ignoring case; columns not found are silently skipped.',
      'Column names in the Parquet file must still be specified in a COPY column list.',
    ],
    answer: 'Snowflake matches each Parquet column to a target column by name, ignoring case; columns not found are silently skipped.',
    exp: 'MATCH_BY_COLUMN_NAME is supported for Parquet, Avro, ORC, and JSON — NOT CSV. CASE_INSENSITIVE matches names regardless of case. Unmapped source columns are skipped; unmapped target columns get NULL.',
  },
  {
    id: 'd3_h1_17',
    domain: 3,
    topic: 'Snowpipe — 14-day Load History',
    difficulty: 'hard',
    q: 'A file was loaded via Snowpipe AUTO_INGEST 20 days ago. Today the same file (identical name and contents) reappears in the staged S3 bucket and triggers a notification event. What is the expected behavior?',
    options: [
      'Snowpipe skips the file because bulk-load\'s 64-day metadata window still marks it as loaded.',
      'Snowpipe reloads the file because its load-history metadata is retained for only 14 days, which has already expired.',
      'Snowpipe raises a duplicate-load error and suspends the pipe.',
      'Snowpipe reloads only the rows whose content hashes differ from the original load.',
    ],
    answer: 'Snowpipe reloads the file because its load-history metadata is retained for only 14 days, which has already expired.',
    exp: 'Snowpipe load-history metadata is kept 14 days; bulk COPY metadata is kept 64 days. After 14 days, Snowpipe has forgotten the file and will reload it.',
  },
  {
    id: 'd3_h1_18',
    domain: 3,
    topic: 'Streams — Staleness Window',
    difficulty: 'hard',
    q: 'A stream is defined on a permanent table whose DATA_RETENTION_TIME_IN_DAYS is 1 and MAX_DATA_EXTENSION_TIME_IN_DAYS is 14. No consumer reads the stream for 16 days. What is the state of the stream?',
    options: [
      'Active — Snowflake automatically resets the stream offset to the current time.',
      'STALE — the stream has exceeded (DATA_RETENTION + MAX_DATA_EXTENSION) without being consumed; it must be dropped and recreated to resume capturing changes.',
      'Active — the 14-day extension becomes rolling as long as DML occurs.',
      'STALE but still readable — it returns a full snapshot of the base table.',
    ],
    answer: 'STALE — the stream has exceeded (DATA_RETENTION + MAX_DATA_EXTENSION) without being consumed; it must be dropped and recreated to resume capturing changes.',
    exp: 'Snowflake extends retention up to MAX_DATA_EXTENSION_TIME_IN_DAYS to protect streams. Beyond that, the stream becomes STALE — its offset cannot advance, and you must DROP and recreate it.',
  },
  {
    id: 'd3_h1_19',
    domain: 3,
    topic: 'Dynamic Tables vs Streams+Tasks',
    difficulty: 'hard',
    q: 'Which statement correctly distinguishes Dynamic Tables from a Stream + Task pipeline?',
    options: [
      'Dynamic Tables require a Kafka connector; Streams+Tasks do not.',
      'Streams+Tasks can query semi-structured VARIANT data; Dynamic Tables cannot.',
      'Dynamic Tables are declarative with a TARGET_LAG and support incremental refresh where possible; Streams+Tasks are imperative and require the developer to write DML and scheduling logic.',
      'Dynamic Tables always use serverless compute; Streams+Tasks must always use a user-managed warehouse.',
    ],
    answer: 'Dynamic Tables are declarative with a TARGET_LAG and support incremental refresh where possible; Streams+Tasks are imperative and require the developer to write DML and scheduling logic.',
    exp: 'Dynamic Tables let you declare the desired result and a freshness target (TARGET_LAG); Snowflake figures out the refresh. Streams+Tasks remain the imperative alternative when you need fine-grained control over DML.',
  },
  {
    id: 'd3_h1_20',
    domain: 3,
    topic: 'Storage Integration — IAM Trust Advantage',
    difficulty: 'hard',
    q: 'What is the PRIMARY advantage of using a Snowflake Storage Integration instead of embedding AWS access keys directly in a CREATE STAGE statement?',
    options: [
      'Storage Integrations expose direct JDBC access to the cloud bucket from client apps.',
      'The secret key is never stored in Snowflake — authentication uses IAM role trust via the Snowflake-managed AWS identity.',
      'Storage Integrations are always faster than credential-based stages because they bypass the cloud provider\'s API.',
      'Storage Integrations encrypt data at rest; credential-based stages do not.',
    ],
    answer: 'The secret key is never stored in Snowflake — authentication uses IAM role trust via the Snowflake-managed AWS identity.',
    exp: 'Storage Integrations delegate auth via a trust relationship between the Snowflake-managed IAM user/role and the customer\'s IAM role. No long-lived keys live in Snowflake, and allowed locations are restricted via STORAGE_ALLOWED_LOCATIONS.',
  },
  {
    id: 'd3_h1_21',
    domain: 3,
    topic: 'COPY INTO — ON_ERROR Defaults',
    difficulty: 'hard',
    q: 'A developer runs a bulk COPY INTO without specifying ON_ERROR. A Snowpipe later uses the same file format without specifying ON_ERROR. What are the two defaults?',
    options: [
      'Both default to CONTINUE.',
      'Both default to ABORT_STATEMENT.',
      'Bulk COPY defaults to SKIP_FILE; Snowpipe defaults to ABORT_STATEMENT.',
      'Bulk COPY defaults to ABORT_STATEMENT; Snowpipe defaults to SKIP_FILE.',
    ],
    answer: 'Bulk COPY defaults to ABORT_STATEMENT; Snowpipe defaults to SKIP_FILE.',
    exp: 'The two contexts have DIFFERENT defaults — a classic exam trap. Bulk COPY fails the statement on first error by default; Snowpipe skips the offending file and keeps ingesting others.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (6 questions) ─────────
  {
    id: 'd4_h1_22',
    domain: 4,
    topic: 'Query Profile — Remote Storage Spilling',
    difficulty: 'hard',
    q: 'A slow query\'s profile shows "Bytes spilled to remote storage: 450 GB". What does this most likely imply, and what is the BEST first remediation?',
    options: [
      'The warehouse hit a storage cap — enable Time Travel compaction.',
      'The query returned too many rows — add a LIMIT clause.',
      'Micro-partition pruning failed — add a clustering key immediately.',
      'Intermediate results outgrew local SSD and are being read/written to object storage — scale UP to a larger warehouse with more memory and SSD (and/or rewrite to reduce intermediate size).',
    ],
    answer: 'Intermediate results outgrew local SSD and are being read/written to object storage — scale UP to a larger warehouse with more memory and SSD (and/or rewrite to reduce intermediate size).',
    exp: 'Remote spill is severe — intermediates are hitting object storage. First fix is usually to scale UP (more RAM + local SSD per node). Rewriting to reduce Cartesian / exploding joins is the other path.',
  },
  {
    id: 'd4_h1_23',
    domain: 4,
    topic: 'Search Optimization Service — Ideal Predicates',
    difficulty: 'hard',
    q: 'The Search Optimization Service (SOS) on a table provides the GREATEST benefit for which query pattern?',
    options: [
      'SELECT * FROM t WHERE amount > 1000 — range predicate on a numeric column.',
      'SELECT * FROM t WHERE email = \'x@y.com\' OR email IN (\'a@b.com\',\'c@d.com\') — selective equality / IN predicates on a high-cardinality column.',
      'SELECT COUNT(*) FROM t GROUP BY state — full-scan aggregation.',
      'SELECT * FROM t ORDER BY created_at DESC — full-scan ordering by timestamp.',
    ],
    answer: 'SELECT * FROM t WHERE email = \'x@y.com\' OR email IN (\'a@b.com\',\'c@d.com\') — selective equality / IN predicates on a high-cardinality column.',
    exp: 'SOS is designed for selective point lookups (equality, IN, some LIKE/SUBSTRING) on high-cardinality columns where clustering would not help. Range, ORDER BY, and wide aggregations benefit from other techniques.',
  },
  {
    id: 'd4_h1_24',
    domain: 4,
    topic: 'Clustering — When NOT to Define a Key',
    difficulty: 'hard',
    q: 'A table is 80 GB and ~95% of queries filter on order_date for the last 7 days. Incoming data is written in strict order_date order. Which recommendation is MOST appropriate?',
    options: [
      'Immediately add CLUSTER BY (order_date) to guarantee pruning on new loads.',
      'Create a materialized view clustered by order_date.',
      'Do NOT define a clustering key — natural ingestion order already aligns micro-partitions with the filter, so automatic clustering credits would be wasted.',
      'Enable Search Optimization on order_date.',
    ],
    answer: 'Do NOT define a clustering key — natural ingestion order already aligns micro-partitions with the filter, so automatic clustering credits would be wasted.',
    exp: 'If insertion order already co-locates rows by the filter column, adding a clustering key just spends serverless credits to maintain what already exists. Always check SYSTEM$CLUSTERING_INFORMATION before committing to a key.',
  },
  {
    id: 'd4_h1_25',
    domain: 4,
    topic: 'MERGE — Concurrency Behavior',
    difficulty: 'hard',
    q: 'Two concurrent MERGE statements target the same table. One mostly inserts new rows; the other mostly updates existing rows. What is the expected behavior in Snowflake?',
    options: [
      'The second MERGE always raises a deadlock error that must be retried by the client.',
      'Both MERGEs succeed without any interaction because MERGE is always purely optimistic.',
      'One MERGE blocks behind the other because Snowflake locks the whole table with a row-level X-lock.',
      'Snowflake allows both to proceed concurrently, but if they touch the same micro-partitions a conflict can occur and one statement may be automatically re-queued / retried.',
    ],
    answer: 'Snowflake allows both to proceed concurrently, but if they touch the same micro-partitions a conflict can occur and one statement may be automatically re-queued / retried.',
    exp: 'Snowflake uses multi-version concurrency; conflicts surface when two statements rewrite overlapping micro-partitions. Snowflake transparently retries the losing statement before returning an error.',
  },
  {
    id: 'd4_h1_26',
    domain: 4,
    topic: 'Warehouse Local Cache — Cleared on Resize',
    difficulty: 'hard',
    q: 'A warehouse has been running queries, warming its local SSD data cache. The DBA then resizes the warehouse from Large to X-Large. What happens to the data cache?',
    options: [
      'It is preserved because the warehouse stays online during resize.',
      'Only the metadata cache is cleared; the data cache persists across the resize.',
      'It is cleared — resizing provisions new compute nodes, so all local data cache is lost and must be re-warmed.',
      'It is preserved and automatically redistributed across the new nodes in proportion to credit rate.',
    ],
    answer: 'It is cleared — resizing provisions new compute nodes, so all local data cache is lost and must be re-warmed.',
    exp: 'The warehouse-local data cache is ephemeral: it is lost on suspend AND on resize, because new compute nodes are allocated. Only the Result Cache (24h, cloud services) and metadata cache survive.',
  },
  {
    id: 'd4_h1_27',
    domain: 4,
    topic: 'EXECUTE AS OWNER — Masking Policy Trap',
    difficulty: 'hard',
    q: 'A stored procedure is created with EXECUTE AS OWNER by role DATA_ENG. The procedure reads a table that has a masking policy: CASE WHEN CURRENT_ROLE() = \'ANALYST\' THEN val ELSE \'***\' END. Role ANALYST calls the procedure. What does ANALYST see?',
    options: [
      'Unmasked values — EXECUTE AS OWNER bypasses all masking policies.',
      'Unmasked values — the masking policy sees CURRENT_ROLE() = ANALYST, the caller.',
      'Masked values — the procedure runs as DATA_ENG, so the masking policy evaluates CURRENT_ROLE() = DATA_ENG, not ANALYST.',
      'An error — masking policies are incompatible with EXECUTE AS OWNER procedures.',
    ],
    answer: 'Masked values — the procedure runs as DATA_ENG, so the masking policy evaluates CURRENT_ROLE() = DATA_ENG, not ANALYST.',
    exp: 'Inside EXECUTE AS OWNER, the effective role IS the owner. The masking policy sees CURRENT_ROLE() = DATA_ENG, which does not match the ANALYST allow clause, so values are masked. Switch to EXECUTE AS CALLER or use IS_ROLE_IN_SESSION to fix.',
  },

  // ── DOMAIN 5: Data Collaboration (3 questions) ─────────────────────────────
  {
    id: 'd5_h1_28',
    domain: 5,
    topic: 'Reader Account — Capabilities and Limits',
    difficulty: 'hard',
    q: 'A provider creates a Reader Account for a downstream consumer who does not have a Snowflake contract. Which statement is TRUE?',
    options: [
      'The Reader Account can CREATE warehouses, databases, tables, and views for local transformations; all compute is billed to the provider.',
      'The Reader Account can CREATE SHARE to resell the provider\'s data to its own customers.',
      'The Reader Account can CREATE PIPE for continuous ingestion from its own S3 bucket.',
      'The Reader Account can INSERT rows into tables it receives through a secure share.',
    ],
    answer: 'The Reader Account can CREATE warehouses, databases, tables, and views for local transformations; all compute is billed to the provider.',
    exp: '"Reader" is misleading — Reader Accounts can create objects and run queries. They CANNOT create shares, pipes, or stages, and they cannot write to shared objects. The provider pays for all their compute.',
  },
  {
    id: 'd5_h1_29',
    domain: 5,
    topic: 'Shared Database — Clone Restriction',
    difficulty: 'hard',
    q: 'A consumer account has a shared database SHARED_DB received via secure data sharing. A developer runs CREATE DATABASE local_copy CLONE SHARED_DB;. What happens?',
    options: [
      'The clone succeeds and produces a full read-write copy of the shared data.',
      'The clone succeeds but is itself read-only.',
      'The clone succeeds but no micro-partitions are copied until a write occurs.',
      'The statement FAILS — objects in a shared database cannot be cloned because the consumer does not own the underlying storage.',
    ],
    answer: 'The statement FAILS — objects in a shared database cannot be cloned because the consumer does not own the underlying storage.',
    exp: 'Secure shares are zero-copy references. Consumers cannot CLONE, INSERT, UPDATE, DELETE, MERGE, or DROP objects they receive via a share — they lack OWNERSHIP. To get a local writable copy they must CTAS (SELECT-and-copy).',
  },
  {
    id: 'd5_h1_30',
    domain: 5,
    topic: 'Marketplace Listing vs Direct Share vs Replication',
    difficulty: 'hard',
    q: 'A provider wants to distribute a data product to consumers across multiple regions and clouds, with public discoverability and optional paid monetization. Which mechanism is DESIGNED for this use case?',
    options: [
      'Direct Secure Data Share — cross-region distribution is automatic via zero-copy.',
      'Snowflake Marketplace Listing — provides cross-region discoverability and supports free or paid listings.',
      'Database Replication — replicate the source database to every region and grant SELECT per consumer.',
      'Reader Account — set the billing contact to the consumer\'s credit card.',
    ],
    answer: 'Snowflake Marketplace Listing — provides cross-region discoverability and supports free or paid listings.',
    exp: 'Direct Shares are same-region and not discoverable. Marketplace Listings are globally discoverable, support paid products, and use auto-fulfillment across regions/clouds. Replication is for DR / geo-latency, not distribution. Reader Account has single-consumer scope.',
  },
];
