// ─────────────────────────────────────────────────────────────────────────────
// EXAM PREP — Day 3  (Wed Mar 18, 2026)
// COF-C03 Mock Exam · 60 questions
// Distribution: D1 31% (19q) | D2 20% (12q) | D3 18% (11q) | D4 21% (13q) | D5 10% (5q)
// Difficulty mix: ~30% Easy, ~50% Medium, ~20% Hard
//
// DAILY GENERATION RULE:
//   Each new day of questions must share ≤ 30% overlap with the previous day.
//   Before writing a new day, list the question IDs from the previous file and
//   ensure fewer than 18 of the 60 questions are repeated verbatim.
//   Rotate topics, scenarios, and SQL examples each day.
//
// DAY 3 vs DAY 2 OVERLAP CHECK:
//   Day 2 covered: storage/compute separation, multi-cluster shared data, VPS, Cloud Services
//   components, Iceberg, VS Code Extension, SQL API, table stage, SP owner's rights, Snowpark-
//   optimized WH, resize behavior, ECONOMY policy, MANAGE WAREHOUSES, transient table, Fail-safe,
//   micro-partition size, external table DML, Cortex Search, Notebook WH, SYSADMIN, custom role →
//   SYSADMIN, GRANT OWNERSHIP, SCIM, MFA/Duo, Row Access Policy, TAG_REFERENCES, Aggregation
//   Policy, AES-256, Alert RESUME, NOTIFICATION INTEGRATION, LOGIN_HISTORY, PUT, GET, COPY INTO
//   unload, PURGE, PIPE_USAGE_HISTORY, stream offset, append-only stream, Task DAG, Parquet format,
//   Kafka Connector, SnowCD, cross-user result cache, function wrapping pruning, spill to local,
//   broadcast joins, auto-clustering serverless, average_depth, MV restrictions, Search Opt billing,
//   :: cast, INFER_SCHEMA, Dynamic Table TARGET_LAG, spill to remote, SP vs UDF, Time Travel AT,
//   consumer edition, clone + policy, Data Clean Rooms, Native Apps.
//
//   Day 3 fresh angles (~0 verbatim repeats): Horizon Catalog pillars, cloud provider multi-cloud,
//   Standard edition features, Git Integration, Snow CLI, sequences, UDFs, AUTO_SUSPEND/RESUME,
//   STATEMENT_TIMEOUT, temp table vs transient, Streamlit in Snowflake, Cortex LLM COMPLETE,
//   ORGADMIN, USERADMIN, PUBLIC role, account identifiers, session policies, masking policy DDL,
//   CREATE TAG with ALLOWED_VALUES, Trust Center scanner, key rotation, Failover Group DDL,
//   data lineage OBJECT_DEPENDENCIES, Resource Monitor CREATE DDL, INFORMATION_SCHEMA vs
//   ACCOUNT_USAGE comparison, ACCESS_HISTORY view, GOVERNANCE_VIEWER DB role, stage LIST/REMOVE,
//   COPY INTO VALIDATION_MODE, FORCE=TRUE, COPY INTO column mapping, Snowpipe REST API, stream
//   staleness, serverless tasks, Task error handling, XML loading, Git Integration, metadata cache,
//   SHOW commands free, Query Profile partitions pruned, clustering expression keys, DROP CLUSTERING,
//   MV vs result cache, Search Opt ALTER TABLE ADD, PARSE_JSON/OBJECT_CONSTRUCT, QUALIFY/window fn,
//   MERGE statement, UNDROP schema/database, Fail-safe cost, CREATE SHARE DDL, reader accounts,
//   Marketplace provider side, Private Data Exchange.
// ─────────────────────────────────────────────────────────────────────────────

export const DAY_META = {
  day: 3,
  date: '2026-03-18',
  label: 'Day 3 — Advanced Scenarios',
  totalQuestions: 60,
  timeMinutes: 115,
};

export const QUESTIONS = [

  // ── DOMAIN 1: Architecture & Features (19 questions) ─────────────────────

  {
    id: 'd1_d3_01',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'On which cloud platforms can Snowflake accounts be deployed?',
    options: [
      'Only Amazon Web Services (AWS)',
      'AWS and Microsoft Azure only',
      'Amazon Web Services, Microsoft Azure, and Google Cloud Platform',
      'Any cloud provider or on-premises data center',
    ],
    answer: 'Amazon Web Services, Microsoft Azure, and Google Cloud Platform',
    exp: 'Snowflake is a true multi-cloud service — accounts can be created on AWS, Azure, or GCP. Each cloud and region is a separate deployment option. Snowflake does not support on-premises deployments.',
  },
  {
    id: 'd1_d3_02',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'Which of the following is a Snowflake Horizon Catalog pillar that focuses on ensuring the same governance policies and permissions apply whether data is accessed via Snowflake, Spark, or any other engine?',
    options: ['Context for AI', 'Data Discovery', 'Security & Governance', 'Interoperability'],
    answer: 'Interoperability',
    exp: 'The Interoperability pillar of Snowflake Horizon ensures consistent metadata, access controls, and governance policies across Snowflake and external compute engines (Spark, Flink, Trino) via open standards like Apache Iceberg.',
  },
  {
    id: 'd1_d3_03',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'easy',
    q: 'Which Snowflake edition includes Streams, Tasks, Snowpipe, Snowpark, and core SQL — but does NOT include Multi-cluster virtual warehouses?',
    options: ['Business Critical', 'Enterprise', 'Standard', 'Virtual Private Snowflake'],
    answer: 'Standard',
    exp: 'Standard edition includes all core Snowflake features: Streams, Tasks, Snowpipe, Snowpark, Time Travel (1 day), and all data types. Multi-cluster warehouses, Dynamic Data Masking, and Materialized Views require Enterprise+.',
  },
  {
    id: 'd1_d3_04',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'A team version-controls their Snowflake stored procedures and UDFs in a GitHub repository. Which Snowflake feature lets them deploy and execute code directly from the repo inside Snowflake?',
    options: [
      'Snowflake External Functions',
      'Snowflake Git Integration (Git Repository stage)',
      'Snowflake VS Code Extension with GitHub Actions',
      'Snowflake Terraform Provider with GitHub runner',
    ],
    answer: 'Snowflake Git Integration (Git Repository stage)',
    exp: 'Git Integration creates a special stage type (REPOSITORY) linked to a remote Git repo. Snowflake can pull branches/commits from GitHub/GitLab and execute stored procedures/UDFs directly from the repo files.',
  },
  {
    id: 'd1_d3_05',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'medium',
    q: 'What is the key difference between the Snow CLI (Snowflake CLI) and SnowSQL?',
    options: [
      'Snow CLI is the legacy tool; SnowSQL is the modern replacement',
      'SnowSQL is the SQL-only client; Snow CLI is the modern multi-feature developer CLI supporting Snowpark, Streamlit, Native Apps, and scripting',
      'Snow CLI only works on macOS; SnowSQL is cross-platform',
      'SnowSQL can deploy Snowpark apps; Snow CLI can only run SQL',
    ],
    answer: 'SnowSQL is the SQL-only client; Snow CLI is the modern multi-feature developer CLI supporting Snowpark, Streamlit, Native Apps, and scripting',
    exp: 'SnowSQL is the classic SQL client for running queries and loading data. Snow CLI is the newer tool designed for developers — it supports Snowpark projects, Streamlit apps, Native App deployment, and CI/CD scripting.',
  },
  {
    id: 'd1_d3_06',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'Which schema-level Snowflake object generates sequential unique integers — commonly used to populate surrogate keys?',
    options: ['Task', 'Stream', 'Sequence', 'File Format'],
    answer: 'Sequence',
    exp: 'Sequences are schema-level objects that produce monotonically increasing (or custom-increment) integers. Used with DEFAULT seq.NEXTVAL in table DDL or in INSERT statements for surrogate key generation.',
  },
  {
    id: 'd1_d3_07',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'A JavaScript UDF in Snowflake is called inside a SELECT statement. What type of object is a UDF in the Snowflake object hierarchy?',
    options: [
      'Account-level object — shared across all databases',
      'Database-level object — lives directly under a database',
      'Schema-level object — scoped to a specific schema',
      'Warehouse-level object — runs inside a virtual warehouse',
    ],
    answer: 'Schema-level object — scoped to a specific schema',
    exp: 'UDFs (scalar and tabular) are schema-level objects, just like tables, views, stages, streams, and tasks. They are referenced as <database>.<schema>.<function_name>().',
  },
  {
    id: 'd1_d3_08',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'easy',
    q: 'A virtual warehouse is configured with AUTO_SUSPEND = 60 and AUTO_RESUME = TRUE. A query is submitted when the warehouse is suspended. What happens?',
    options: [
      'The query fails with an error: warehouse is suspended',
      'The warehouse resumes automatically, runs the query, then suspends after 60 seconds of inactivity',
      'The query is queued and runs after a manual RESUME command',
      'AUTO_RESUME only works for multi-cluster warehouses',
    ],
    answer: 'The warehouse resumes automatically, runs the query, then suspends after 60 seconds of inactivity',
    exp: 'AUTO_RESUME = TRUE means the warehouse wakes up automatically when a query arrives — no manual RESUME needed. After the query completes, if no new queries arrive within AUTO_SUSPEND seconds, it suspends again.',
  },
  {
    id: 'd1_d3_09',
    domain: 1,
    topic: 'Virtual Warehouses',
    difficulty: 'medium',
    q: 'A query has been running on a warehouse for 10 minutes. The warehouse has STATEMENT_TIMEOUT_IN_SECONDS = 300. What happens?',
    options: [
      'Nothing — STATEMENT_TIMEOUT only applies to queued queries',
      'The query is cancelled and an error is returned to the client',
      'The warehouse suspends and the query is requeued on restart',
      'Snowflake sends a notification but lets the query finish',
    ],
    answer: 'The query is cancelled and an error is returned to the client',
    exp: 'STATEMENT_TIMEOUT_IN_SECONDS cancels any executing statement that exceeds the timeout and returns an error. 10 minutes = 600 seconds > 300 — the query is terminated. This parameter can be set at account, session, or warehouse level.',
  },
  {
    id: 'd1_d3_10',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'How does a Temporary table differ from a Transient table in Snowflake?',
    options: [
      'Temporary tables support Time Travel up to 90 days; transient tables do not support Time Travel',
      'Temporary tables are session-scoped (auto-dropped when the session ends); transient tables persist across sessions',
      'Temporary tables can be shared externally; transient tables cannot',
      'Temporary tables have a 7-day Fail-safe; transient tables do not',
    ],
    answer: 'Temporary tables are session-scoped (auto-dropped when the session ends); transient tables persist across sessions',
    exp: 'Key difference: temp tables exist ONLY for the duration of the session that created them. Transient tables persist like permanent tables but with no Fail-safe and max 1-day Time Travel — ideal for ETL staging that survives session changes.',
  },
  {
    id: 'd1_d3_11',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'hard',
    q: 'A CLUSTER BY clause uses an expression: CLUSTER BY (SUBSTR(last_name, 1, 3)). What is this called, and when is it useful?',
    options: [
      'Compound clustering key — used to cluster on multiple columns simultaneously',
      'Expression clustering key — clusters by a derived value when the raw column has too many distinct values',
      'Partial clustering key — only clusters a subset of micro-partitions',
      'Functional clustering key — only available in Enterprise edition',
    ],
    answer: 'Expression clustering key — clusters by a derived value when the raw column has too many distinct values',
    exp: 'An expression clustering key applies a function to column values before clustering (e.g., SUBSTR, CAST, DATE_TRUNC). Useful when the full column has extremely high cardinality — grouping by a prefix or truncated value improves pruning.',
  },
  {
    id: 'd1_d3_12',
    domain: 1,
    topic: 'Storage Concepts',
    difficulty: 'medium',
    q: 'Which Snowflake view type stores pre-computed results on disk and is automatically refreshed by background serverless compute when the underlying data changes?',
    options: ['Secure view', 'Standard view', 'Materialized view', 'Lateral view'],
    answer: 'Materialized view',
    exp: 'Materialized views store the query result on disk (like a cached table). Snowflake automatically keeps them fresh using serverless background compute. They improve performance for expensive, frequently-run aggregations.',
  },
  {
    id: 'd1_d3_13',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'What is Streamlit in Snowflake (SiS)?',
    options: [
      'A Snowflake CLI plugin for streaming data ingestion',
      'A feature that lets you build and host interactive Python web applications directly inside Snowflake without external infrastructure',
      'A real-time streaming integration with Apache Kafka',
      'A Snowflake-managed Jupyter Notebook environment',
    ],
    answer: 'A feature that lets you build and host interactive Python web applications directly inside Snowflake without external infrastructure',
    exp: 'Streamlit in Snowflake (SiS) hosts Streamlit apps inside your Snowflake account — no external server needed. Apps run with Snowflake identity, governance, and direct access to Snowflake data.',
  },
  {
    id: 'd1_d3_14',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'medium',
    q: 'Which Snowflake Cortex function generates text completions using an LLM (e.g., for summarizing or answering questions about unstructured text)?',
    options: ['CORTEX.ANALYST()', 'SNOWFLAKE.CORTEX.COMPLETE()', 'CORTEX.SEARCH()', 'SNOWFLAKE.ML.CLASSIFY()'],
    answer: 'SNOWFLAKE.CORTEX.COMPLETE()',
    exp: 'SNOWFLAKE.CORTEX.COMPLETE(model, prompt) calls a hosted LLM (e.g., llama3, mistral, snowflake-arctic) to generate a text response. Used for summarization, Q&A, classification, and extraction tasks on text data.',
  },
  {
    id: 'd1_d3_15',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'hard',
    q: 'An account\'s Snowflake URL follows the format: org_name-account_name.snowflakecomputing.com. What does this URL format indicate?',
    options: [
      'The account is on a Business Critical edition deployment',
      'This is the new Organization-based account identifier format (recommended for new accounts)',
      'The account uses a custom domain configuration',
      'The account is in a Virtual Private Snowflake environment',
    ],
    answer: 'This is the new Organization-based account identifier format (recommended for new accounts)',
    exp: 'Snowflake supports two account identifier formats: the legacy <account_locator>.<region>.snowflakecomputing.com and the recommended organization-based <org_name>-<account_name>.snowflakecomputing.com. The org-based format is preferred for new accounts and is required for cross-cloud features.',
  },
  {
    id: 'd1_d3_16',
    domain: 1,
    topic: 'Architecture',
    difficulty: 'medium',
    q: 'What is the Snowflake Horizon Catalog\'s "Business Continuity" pillar responsible for?',
    options: [
      'Automatic query failover when a warehouse crashes',
      'Cross-region and cross-cloud data replication and account failover capabilities',
      'Backup of data to a separate cloud provider for compliance',
      'Automatic Time Travel recovery for dropped objects',
    ],
    answer: 'Cross-region and cross-cloud data replication and account failover capabilities',
    exp: 'The Business Continuity pillar of Snowflake Horizon covers data replication across regions/clouds and Failover Groups for account-level DR. This ensures data availability even during regional cloud outages.',
  },
  {
    id: 'd1_d3_17',
    domain: 1,
    topic: 'Interfaces & Tools',
    difficulty: 'easy',
    q: 'Which Snowflake interface allows Power BI, Tableau, and other BI tools to connect using standard protocols without a Snowflake-specific connector?',
    options: ['Snowflake SQL API', 'Snowsight', 'JDBC and ODBC drivers', 'Python Connector'],
    answer: 'JDBC and ODBC drivers',
    exp: 'JDBC and ODBC are industry-standard protocols that BI tools natively support. Snowflake provides JDBC and ODBC drivers that these tools use to connect — no Snowflake-native plugin required for most BI platforms.',
  },
  {
    id: 'd1_d3_18',
    domain: 1,
    topic: 'AI/ML Features',
    difficulty: 'hard',
    q: 'Snowflake Cortex Guard is used for which purpose?',
    options: [
      'Encrypting LLM prompts before sending to external AI providers',
      'Detecting and filtering unsafe, toxic, or policy-violating content in LLM inputs and outputs',
      'Monitoring Cortex function credit consumption in real time',
      'Blocking external AI API calls from unauthorized Snowflake roles',
    ],
    answer: 'Detecting and filtering unsafe, toxic, or policy-violating content in LLM inputs and outputs',
    exp: 'Cortex Guard is a safety layer for LLM workflows — it screens prompts and responses for harmful, toxic, or inappropriate content (e.g., jailbreak attempts, PII leakage, offensive outputs) before they reach users or downstream systems.',
  },
  {
    id: 'd1_d3_19',
    domain: 1,
    topic: 'Object Hierarchy',
    difficulty: 'medium',
    q: 'Which privilege on a virtual warehouse allows a role to submit queries and use it for computation, but NOT to suspend, resume, or resize it?',
    options: ['MODIFY', 'OPERATE', 'USAGE', 'MONITOR'],
    answer: 'USAGE',
    exp: 'USAGE on a warehouse allows a role to use it for query execution. OPERATE allows suspend/resume. MODIFY allows resize and changing warehouse properties. MONITOR allows viewing query history and usage stats.',
  },

  // ── DOMAIN 2: Account Management & Governance (12 questions) ─────────────

  {
    id: 'd2_d3_01',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'easy',
    q: 'Which system role in Snowflake is specifically designed for creating users and managing roles — but does NOT have the ability to create databases or warehouses?',
    options: ['SYSADMIN', 'USERADMIN', 'SECURITYADMIN', 'ACCOUNTADMIN'],
    answer: 'USERADMIN',
    exp: 'USERADMIN can CREATE USER and CREATE ROLE only. It cannot create databases, schemas, or warehouses. For managing grants on roles (GRANT ROLE TO ROLE), SECURITYADMIN is required.',
  },
  {
    id: 'd2_d3_02',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'easy',
    q: 'What is the PUBLIC role in Snowflake, and which users have it?',
    options: [
      'A role granted to administrators for public-facing data sharing',
      'A default role automatically granted to ALL users in the account — the lowest-privilege base role',
      'A role that allows read-only access to all public schemas',
      'A role with USAGE on all public Snowflake Marketplace listings',
    ],
    answer: 'A default role automatically granted to ALL users in the account — the lowest-privilege base role',
    exp: 'PUBLIC is automatically granted to every user. It has minimal privileges by default. Objects granted to PUBLIC are accessible to all users. It sits at the bottom of the role hierarchy.',
  },
  {
    id: 'd2_d3_03',
    domain: 2,
    topic: 'RBAC',
    difficulty: 'medium',
    q: 'An ORGADMIN role exists in Snowflake. Which of the following is a task ONLY ORGADMIN can perform?',
    options: [
      'Create new databases and warehouses within an account',
      'Create new Snowflake accounts within the organization',
      'Grant the ACCOUNTADMIN role to other users',
      'Configure network policies for the account',
    ],
    answer: 'Create new Snowflake accounts within the organization',
    exp: 'ORGADMIN is an account-level role that manages the Snowflake organization — it can CREATE ACCOUNT, view cross-account usage, enable replication, and manage org-level features. Regular ACCOUNTADMIN operations stay within a single account.',
  },
  {
    id: 'd2_d3_04',
    domain: 2,
    topic: 'Authentication',
    difficulty: 'medium',
    q: 'A user connects to Snowflake using a BI tool that does not support key-pair or SSO. The admin wants to enforce an idle session timeout of 30 minutes. Which Snowflake object controls this?',
    options: [
      'Network Policy with SESSION_TIMEOUT parameter',
      'Resource Monitor with SESSION_LIMIT trigger',
      'Session Policy with SESSION_IDLE_TIMEOUT_MINS',
      'ALTER USER … SET SESSION_TIMEOUT = 30',
    ],
    answer: 'Session Policy with SESSION_IDLE_TIMEOUT_MINS',
    exp: 'Session Policies control session behavior: idle timeout, UI idle timeout, and MFA enforcement. They are created as schema-level objects and can be applied at the account or user level.',
  },
  {
    id: 'd2_d3_05',
    domain: 2,
    topic: 'Network Policies',
    difficulty: 'medium',
    q: 'A network policy has ALLOWED_IP_LIST = (\'203.0.113.0/24\') and BLOCKED_IP_LIST = (\'203.0.113.5\'). A request comes from 203.0.113.5. What happens?',
    options: [
      'Allowed — the ALLOWED_IP_LIST takes precedence over BLOCKED_IP_LIST',
      'Blocked — BLOCKED_IP_LIST entries override any overlapping ALLOWED_IP_LIST entries',
      'Allowed — only BLOCKED_IP_LIST is evaluated; ALLOWED_IP_LIST is advisory only',
      'Rejected with an error because the lists overlap',
    ],
    answer: 'Blocked — BLOCKED_IP_LIST entries override any overlapping ALLOWED_IP_LIST entries',
    exp: 'When an IP is in both lists, BLOCKED_IP_LIST wins. Snowflake evaluates the block list first — if the source IP is blocked, the connection is rejected regardless of whether it also appears in the allowed list.',
  },
  {
    id: 'd2_d3_06',
    domain: 2,
    topic: 'Data Masking',
    difficulty: 'hard',
    q: 'The following masking policy is applied to a SALARY column. Which role sees the real salary value?\n\nCREATE MASKING POLICY salary_mask AS (val NUMBER) RETURNS NUMBER ->\n  CASE WHEN CURRENT_ROLE() = \'HR_ANALYST\' THEN val ELSE -1 END;',
    options: [
      'All roles see the real value; -1 is returned for NULL salary rows',
      'Only the HR_ANALYST role sees the real value; all other roles see -1',
      'Only ACCOUNTADMIN sees the real value; HR_ANALYST sees -1',
      'No role sees the real value — the CASE has a logic error',
    ],
    answer: 'Only the HR_ANALYST role sees the real value; all other roles see -1',
    exp: 'The masking policy returns val (real value) when the querying role is HR_ANALYST. All other roles receive -1. Dynamic Data Masking evaluates CURRENT_ROLE() at query execution time.',
  },
  {
    id: 'd2_d3_07',
    domain: 2,
    topic: 'Object Tagging',
    difficulty: 'medium',
    q: 'What does the ALLOWED_VALUES clause do when creating a Snowflake tag?',
    options: [
      'Restricts which roles can apply the tag',
      'Limits the tag to specific object types (tables only, columns only, etc.)',
      'Constrains the tag value to a predefined list of valid strings',
      'Sets the maximum character length for the tag value',
    ],
    answer: 'Constrains the tag value to a predefined list of valid strings',
    exp: 'CREATE TAG sensitivity ALLOWED_VALUES \'PUBLIC\', \'INTERNAL\', \'CONFIDENTIAL\', \'RESTRICTED\' — only these strings can be used as the tag value. Attempting to set any other value raises an error.',
  },
  {
    id: 'd2_d3_08',
    domain: 2,
    topic: 'Encryption',
    difficulty: 'medium',
    q: 'By default, how often does Snowflake automatically rotate its encryption keys for data at rest?',
    options: ['Every 30 days', 'Every 90 days', 'Annually (every year)', 'Keys are never rotated automatically'],
    answer: 'Annually (every year)',
    exp: 'Snowflake automatically rotates its hierarchical encryption keys annually. New data is re-encrypted with the new key. Customers can also request more frequent rotation or use Tri-Secret Secure (BC+) with their own CMK.',
  },
  {
    id: 'd2_d3_09',
    domain: 2,
    topic: 'Replication',
    difficulty: 'hard',
    q: 'What is the difference between a Replication Group and a Failover Group in Snowflake?',
    options: [
      'Replication Groups support account-object replication; Failover Groups do not',
      'Failover Groups include all Replication Group capabilities PLUS the ability to promote a secondary to primary (failover/failback)',
      'Replication Groups require Business Critical edition; Failover Groups work on Standard',
      'Failover Groups replicate compute resources; Replication Groups replicate only data',
    ],
    answer: 'Failover Groups include all Replication Group capabilities PLUS the ability to promote a secondary to primary (failover/failback)',
    exp: 'Replication Groups replicate objects but cannot be promoted. Failover Groups are a superset — they add the ability to perform failover (promote secondary to primary) and failback. Both require Business Critical+ for account objects.',
  },
  {
    id: 'd2_d3_10',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'A compliance team needs to know which users accessed which tables and columns in the last 30 days, including which rows they touched. Which ACCOUNT_USAGE view provides this level of detail?',
    options: [
      'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY',
      'SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY',
    ],
    answer: 'SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY',
    exp: 'ACCESS_HISTORY records every query that touched data — with the specific tables, views, and columns accessed (including column projection and filtering). This is the authoritative source for data access audit trails.',
  },
  {
    id: 'd2_d3_11',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'medium',
    q: 'Which database role grants access to ACCOUNT_USAGE views related to governance — such as policy usage, tag references, and classification results — without giving full ACCOUNTADMIN?',
    options: ['OBJECT_VIEWER', 'USAGE_VIEWER', 'GOVERNANCE_VIEWER', 'SECURITY_VIEWER'],
    answer: 'GOVERNANCE_VIEWER',
    exp: 'The GOVERNANCE_VIEWER database role on the SNOWFLAKE database grants SELECT on governance-related ACCOUNT_USAGE views: masking policy references, row access policy references, tag references, classification history, etc.',
  },
  {
    id: 'd2_d3_12',
    domain: 2,
    topic: 'ACCOUNT_USAGE',
    difficulty: 'hard',
    q: 'INFORMATION_SCHEMA vs ACCOUNT_USAGE — which statement is CORRECT?',
    options: [
      'INFORMATION_SCHEMA has 1-year retention; ACCOUNT_USAGE is near-real-time',
      'ACCOUNT_USAGE has 1-year retention and up to 3-hour latency; INFORMATION_SCHEMA is near-real-time with short retention (7–14 days)',
      'Both have identical retention and latency — ACCOUNT_USAGE just has more views',
      'INFORMATION_SCHEMA covers the entire account; ACCOUNT_USAGE is scoped to one database',
    ],
    answer: 'ACCOUNT_USAGE has 1-year retention and up to 3-hour latency; INFORMATION_SCHEMA is near-real-time with short retention (7–14 days)',
    exp: 'ACCOUNT_USAGE: 365-day retention, 45 min–3 hr latency (some views up to 2 days), includes dropped objects, account-wide scope. INFORMATION_SCHEMA: near-real-time, 7–14 day retention (varies by view), current DB scope only, no dropped objects.',
  },

  // ── DOMAIN 3: Data Loading, Unloading & Connectivity (11 questions) ────────

  {
    id: 'd3_d3_01',
    domain: 3,
    topic: 'Stages',
    difficulty: 'easy',
    q: 'Which command lists the files currently stored in a Snowflake stage?',
    options: ['SHOW FILES IN @mystage', 'LIST @mystage', 'SELECT * FROM @mystage', 'DESCRIBE STAGE @mystage'],
    answer: 'LIST @mystage',
    exp: 'LIST @<stage_name> returns the files in a stage with their size, last-modified date, and MD5 hash. Works for all stage types. LS @mystage is a valid alias for LIST.',
  },
  {
    id: 'd3_d3_02',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'medium',
    q: 'A COPY INTO command is run with VALIDATION_MODE = \'RETURN_ERRORS\'. What does this do?',
    options: [
      'Loads all valid rows and returns a list of errored rows',
      'Validates the files and returns any errors WITHOUT loading any data',
      'Aborts the load and returns the first 10 errors',
      'Validates only the header row of each CSV file',
    ],
    answer: 'Validates the files and returns any errors WITHOUT loading any data',
    exp: 'VALIDATION_MODE is a dry-run option — it parses the files and reports errors without performing any actual data load. RETURN_ERRORS returns all rows that would fail. RETURN_N_ROWS returns the first N valid rows. No data is written.',
  },
  {
    id: 'd3_d3_03',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'medium',
    q: 'A CSV file has columns in a different order than the target table. Which COPY INTO clause maps source columns to target table columns?',
    options: [
      'COLUMN_REORDER = TRUE',
      'MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE',
      'A column list in the COPY INTO syntax: COPY INTO t (col_b, col_a) FROM @stage',
      'FILE_FORMAT = (COLUMN_ORDER = SOURCE_SCHEMA)',
    ],
    answer: 'A column list in the COPY INTO syntax: COPY INTO t (col_b, col_a) FROM @stage',
    exp: 'You can explicitly specify a target column list in the COPY INTO statement to map source file columns to table columns in a specific order: COPY INTO table (col2, col1) FROM @stage. This handles mismatched column ordering.',
  },
  {
    id: 'd3_d3_04',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'hard',
    q: 'A file was previously loaded successfully into a table. You want to reload it to fix a transformation issue. Which COPY INTO option forces the re-load even though load history says it was already processed?',
    options: [
      'ON_ERROR = CONTINUE',
      'PURGE = FALSE',
      'FORCE = TRUE',
      'RELOAD = TRUE',
    ],
    answer: 'FORCE = TRUE',
    exp: 'FORCE = TRUE bypasses the 64-day load history deduplication — the file is loaded again regardless of previous history. Use with caution as it can create duplicate rows if the target table already has the data.',
  },
  {
    id: 'd3_d3_05',
    domain: 3,
    topic: 'Snowpipe',
    difficulty: 'medium',
    q: 'Snowpipe Streaming differs from classic Snowpipe in what key way?',
    options: [
      'Snowpipe Streaming uses virtual warehouses; classic Snowpipe uses serverless compute',
      'Snowpipe Streaming ingests rows via an SDK with very low latency (seconds); classic Snowpipe ingests files via event notifications',
      'Snowpipe Streaming is only available on AWS; classic Snowpipe works on all clouds',
      'Snowpipe Streaming can only ingest JSON; classic Snowpipe supports all file formats',
    ],
    answer: 'Snowpipe Streaming ingests rows via an SDK with very low latency (seconds); classic Snowpipe ingests files via event notifications',
    exp: 'Snowpipe Streaming uses the Snowflake Ingest SDK to push individual rows (or small batches) into Snowflake with latency in the seconds. Classic Snowpipe is file-based — it triggers on cloud event notifications when files land in cloud storage.',
  },
  {
    id: 'd3_d3_06',
    domain: 3,
    topic: 'Streams',
    difficulty: 'hard',
    q: 'What happens to a Snowflake stream if it is not consumed before its STALE_AFTER timestamp?',
    options: [
      'The stream is automatically dropped',
      'The stream becomes STALE — the change tracking data is no longer available and the stream must be recreated',
      'The stream pauses and resumes when next consumed',
      'Snowflake extends the retention window automatically',
    ],
    answer: 'The stream becomes STALE — the change tracking data is no longer available and the stream must be recreated',
    exp: 'A stream\'s retention is tied to the source table\'s DATA_RETENTION_TIME_IN_DAYS (minimum 14 days for stream staleness). If not consumed within that window, STALE = TRUE. The stream must be recreated from scratch — historical changes are lost.',
  },
  {
    id: 'd3_d3_07',
    domain: 3,
    topic: 'Tasks',
    difficulty: 'medium',
    q: 'A serverless task in Snowflake does NOT require specifying a WAREHOUSE parameter. How is its compute billed?',
    options: [
      'It uses the account\'s default warehouse credits',
      'It is billed as serverless compute-seconds, separately from virtual warehouse credits',
      'It runs on Cloud Services compute — no additional billing',
      'It is billed against a Snowflake-managed shared warehouse at a discounted rate',
    ],
    answer: 'It is billed as serverless compute-seconds, separately from virtual warehouse credits',
    exp: 'Serverless tasks use Snowflake-managed compute (no warehouse required). They are billed as compute-seconds. This can be more cost-efficient for infrequent, short tasks where warming up a full VW would be wasteful.',
  },
  {
    id: 'd3_d3_08',
    domain: 3,
    topic: 'File Formats',
    difficulty: 'medium',
    q: 'When loading a JSON array file like [{"id":1},{"id":2}] into a Snowflake table, which FILE FORMAT option prevents the outer array brackets from being stored in the VARIANT column?',
    options: [
      'ARRAY_FLATTEN = TRUE',
      'STRIP_OUTER_ARRAY = TRUE',
      'PARSE_ARRAY = TRUE',
      'OUTER_BRACKET_REMOVE = TRUE',
    ],
    answer: 'STRIP_OUTER_ARRAY = TRUE',
    exp: 'STRIP_OUTER_ARRAY = TRUE in the JSON file format removes the top-level array brackets and loads each array element as a separate row. Without it, the entire array is stored as a single VARIANT value.',
  },
  {
    id: 'd3_d3_09',
    domain: 3,
    topic: 'Connectivity',
    difficulty: 'medium',
    q: 'Which Snowflake integration type allows stored procedures and tasks to read source code files directly from a linked GitHub or GitLab repository?',
    options: [
      'Storage Integration',
      'Notification Integration',
      'API Integration',
      'Git Integration',
    ],
    answer: 'Git Integration',
    exp: 'Git Integration (CREATE GIT REPOSITORY) links a remote Git repo to Snowflake. You can FETCH the latest commits and reference files using a special @repo_name/branches/main/path syntax in EXECUTE IMMEDIATE FROM or CALL statements.',
  },
  {
    id: 'd3_d3_10',
    domain: 3,
    topic: 'Streams',
    difficulty: 'medium',
    q: 'A developer creates a stream ON VIEW. What type of change data can this stream capture?',
    options: [
      'All DML on the underlying base tables visible through the view',
      'Only changes to the view definition (DDL)',
      'Only INSERT operations on the underlying tables',
      'Streams on views are not supported in Snowflake',
    ],
    answer: 'Only INSERT operations on the underlying tables',
    exp: 'Streams on views are insert-only streams — they capture only new rows inserted into the underlying tables (visible through the view). Standard (delta) streams with UPDATE/DELETE are not supported on views.',
  },
  {
    id: 'd3_d3_11',
    domain: 3,
    topic: 'COPY INTO',
    difficulty: 'easy',
    q: 'Which COPY INTO ON_ERROR option loads all valid rows from a file and skips only the errored rows (continuing to the next row)?',
    options: [
      'ABORT_STATEMENT (default)',
      'SKIP_FILE',
      'CONTINUE',
      'SKIP_ROW',
    ],
    answer: 'CONTINUE',
    exp: 'ON_ERROR = CONTINUE processes every row in the file — valid rows are loaded, errored rows are skipped and recorded in load history. SKIP_FILE skips the entire file when any error is found. ABORT_STATEMENT (default) rolls back on first error.',
  },

  // ── DOMAIN 4: Performance, Querying & Transformation (13 questions) ────────

  {
    id: 'd4_d3_01',
    domain: 4,
    topic: 'Caching',
    difficulty: 'medium',
    q: 'A user runs SHOW TABLES IN SCHEMA mydb.myschema. This command does NOT spin up a virtual warehouse. Why?',
    options: [
      'SHOW commands use the local SSD cache instead of the warehouse',
      'SHOW commands are served by the metadata cache in Cloud Services — no virtual warehouse needed',
      'SHOW commands use the result cache from the last execution',
      'SHOW commands always require a warehouse, but it is auto-provisioned silently',
    ],
    answer: 'SHOW commands are served by the metadata cache in Cloud Services — no virtual warehouse needed',
    exp: 'SHOW commands (SHOW TABLES, SHOW DATABASES, SHOW WAREHOUSES, etc.) are metadata operations served directly from the Cloud Services metadata layer. No virtual warehouse is required and no warehouse credits are consumed.',
  },
  {
    id: 'd4_d3_02',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'In Snowflake Query Profile, what is the significance of the "Partitions scanned" vs "Partitions total" ratio?',
    options: [
      'It indicates how many partitions needed compaction vs total',
      'It measures how effective partition pruning was — lower scanned/total ratio means better pruning',
      'It shows how many partitions were spilled to disk vs processed in memory',
      'It indicates the number of micro-partitions created during the query',
    ],
    answer: 'It measures how effective partition pruning was — lower scanned/total ratio means better pruning',
    exp: 'The ratio partitions_scanned / partitions_total shows pruning efficiency. A ratio close to 1.0 means nearly all micro-partitions were scanned (poor pruning). A ratio near 0.1 means 90% were pruned — highly efficient.',
  },
  {
    id: 'd4_d3_03',
    domain: 4,
    topic: 'Caching',
    difficulty: 'hard',
    q: 'A user changes their active role with USE ROLE analyst;, then reruns a SELECT query that previously used the result cache. Does the result cache serve the result?',
    options: [
      'Yes — result cache is independent of the active role',
      'No — changing roles always invalidates the result cache for all queries',
      'Yes — but only if the new role has the same privileges as the previous role',
      'It depends on whether the query accesses tables protected by Row Access Policies',
    ],
    answer: 'It depends on whether the query accesses tables protected by Row Access Policies',
    exp: 'For most queries, role changes do NOT invalidate the result cache. However, if the table has row-level security (Row Access Policy or Dynamic Data Masking), Snowflake re-evaluates the query since different roles may see different data.',
  },
  {
    id: 'd4_d3_04',
    domain: 4,
    topic: 'Clustering',
    difficulty: 'medium',
    q: 'How do you DISABLE automatic clustering on a table that has a clustering key defined?',
    options: [
      'ALTER TABLE orders DROP CLUSTERING KEY;',
      'ALTER TABLE orders SUSPEND RECLUSTER;',
      'ALTER TABLE orders SET ENABLE_SCHEMA_EVOLUTION = FALSE;',
      'DROP CLUSTERING KEY ON TABLE orders;',
    ],
    answer: 'ALTER TABLE orders SUSPEND RECLUSTER;',
    exp: 'ALTER TABLE … SUSPEND RECLUSTER pauses automatic re-clustering (stops background compute from re-clustering). The clustering key definition remains — you can resume with ALTER TABLE … RESUME RECLUSTER. To remove the key entirely: ALTER TABLE … DROP CLUSTERING KEY.',
  },
  {
    id: 'd4_d3_05',
    domain: 4,
    topic: 'Materialized Views',
    difficulty: 'medium',
    q: 'A developer wants to share a Materialized View to a consumer account via Data Sharing. What is the requirement?',
    options: [
      'The MV must be a secure materialized view',
      'The base tables must be in the same share as the MV',
      'MVs cannot be shared — only standard views can be shared',
      'The consumer must be on Enterprise edition',
    ],
    answer: 'The MV must be a secure materialized view',
    exp: 'Like standard views, a Materialized View must be created as a SECURE MATERIALIZED VIEW to be included in a Data Share. This prevents the consumer from inspecting the underlying query definition.',
  },
  {
    id: 'd4_d3_06',
    domain: 4,
    topic: 'Search Optimization',
    difficulty: 'medium',
    q: 'What is the correct DDL to enable Search Optimization Service on a specific column of a table?',
    options: [
      'CREATE SEARCH INDEX ON orders (customer_id);',
      'ALTER TABLE orders ADD SEARCH OPTIMIZATION ON EQUALITY(customer_id);',
      'ALTER TABLE orders SET SEARCH_OPTIMIZATION = TRUE FOR COLUMN customer_id;',
      'ENABLE SEARCH OPTIMIZATION ON TABLE orders COLUMN customer_id;',
    ],
    answer: 'ALTER TABLE orders ADD SEARCH OPTIMIZATION ON EQUALITY(customer_id);',
    exp: 'ALTER TABLE … ADD SEARCH OPTIMIZATION enables Search Optimization. You can target specific columns and predicate types: ON EQUALITY(col), ON SUBSTRING(col), ON GEO(col), etc. Without column specification, it applies to all supported columns.',
  },
  {
    id: 'd4_d3_07',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'medium',
    q: 'Which Snowflake function constructs a VARIANT object from key-value pairs at query time?',
    options: [
      'PARSE_JSON(\'{"k":"v"}\')',
      'TO_VARIANT()',
      'OBJECT_CONSTRUCT(\'key\', value, \'key2\', value2)',
      'BUILD_OBJECT(\'key\', value)',
    ],
    answer: 'OBJECT_CONSTRUCT(\'key\', value, \'key2\', value2)',
    exp: 'OBJECT_CONSTRUCT builds a VARIANT JSON object from key-value argument pairs at query time — useful for creating JSON payloads from relational columns. PARSE_JSON parses an existing JSON string; they serve different purposes.',
  },
  {
    id: 'd4_d3_08',
    domain: 4,
    topic: 'Semi-Structured Data',
    difficulty: 'hard',
    q: 'Which SQL clause in Snowflake filters rows AFTER a window function has been computed — similar to HAVING but for window functions?',
    options: ['HAVING', 'FILTER', 'QUALIFY', 'WHERE'],
    answer: 'QUALIFY',
    exp: 'QUALIFY filters rows based on the result of a window function, applied after the window computation. Example: SELECT *, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) AS rn FROM emp QUALIFY rn = 1;',
  },
  {
    id: 'd4_d3_09',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'In a MERGE statement in Snowflake, what happens when a source row matches multiple target rows?',
    options: [
      'The first matched target row is updated; the rest are ignored',
      'All matched target rows are updated',
      'Snowflake raises an error: non-deterministic MERGE is not allowed',
      'The MERGE aborts and rolls back all changes',
    ],
    answer: 'Snowflake raises an error: non-deterministic MERGE is not allowed',
    exp: 'Snowflake enforces deterministic MERGE semantics — a source row may match at most one target row. If a source row matches multiple target rows, an error is raised. Use a deduplicated source CTE to avoid this.',
  },
  {
    id: 'd4_d3_10',
    domain: 4,
    topic: 'Query Optimization',
    difficulty: 'medium',
    q: 'Which technique can help reduce data spilling in a query that sorts a very large result set?',
    options: [
      'Add a clustering key on the sorted column',
      'Increase warehouse size to provide more memory per node',
      'Use LIMIT to reduce result set size',
      'Enable the Search Optimization Service on the sorted column',
    ],
    answer: 'Increase warehouse size to provide more memory per node',
    exp: 'Spilling occurs when the warehouse runs out of memory for intermediate results (sorts, joins, aggregates). Upsizing the warehouse provides more memory per node, reducing or eliminating spilling. Clustering helps pruning but not in-memory sort operations.',
  },
  {
    id: 'd4_d3_11',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'medium',
    q: 'What does COPY GRANTS do when used in a CREATE OR REPLACE TABLE statement?',
    options: [
      'Copies the table structure (DDL) without copying the data',
      'Preserves the existing privilege grants on the table when it is replaced',
      'Creates a zero-copy clone of the original table',
      'Copies column-level grants but not table-level grants',
    ],
    answer: 'Preserves the existing privilege grants on the table when it is replaced',
    exp: 'By default, CREATE OR REPLACE drops and recreates the object — losing all grants. COPY GRANTS transfers the existing privilege grants from the old object to the new one, avoiding permission disruption for dependent users.',
  },
  {
    id: 'd4_d3_12',
    domain: 4,
    topic: 'Query Profile',
    difficulty: 'easy',
    q: 'In Snowflake Query Profile, a node labeled "Aggregate" with a very high percentage of total execution time suggests which issue?',
    options: [
      'The table has too many micro-partitions',
      'A GROUP BY or aggregation is processing a very large number of rows or groups, possibly due to data skew or missing pruning',
      'The warehouse is undersized for the number of concurrent users',
      'The query is reading from a cold (uncached) warehouse',
    ],
    answer: 'A GROUP BY or aggregation is processing a very large number of rows or groups, possibly due to data skew or missing pruning',
    exp: 'A dominant Aggregate node means the grouping/aggregation step is the bottleneck. Causes: high-cardinality GROUP BY on unfiltered data, data skew (one group contains most rows), or a missing WHERE clause that allows too many rows into the aggregate.',
  },
  {
    id: 'd4_d3_13',
    domain: 4,
    topic: 'Transformations',
    difficulty: 'hard',
    q: 'A Snowpark DataFrame operation like df.filter(col("amount") > 100).select("id", "amount") — when does Snowflake actually execute the SQL against the data?',
    options: [
      'Immediately when each method is called (eager evaluation)',
      'When the DataFrame is defined with schema()',
      'Only when an action is triggered (e.g., .collect(), .show(), .write.saveAsTable())',
      'When the Snowpark session is closed',
    ],
    answer: 'Only when an action is triggered (e.g., .collect(), .show(), .write.saveAsTable())',
    exp: 'Snowpark DataFrames use lazy evaluation — transformation methods (filter, select, join, etc.) build a logical plan but do not execute SQL. Execution only happens when an action (collect, show, write, count) is called. This mirrors Apache Spark\'s model.',
  },

  // ── DOMAIN 5: Data Collaboration (5 questions) ───────────────────────────

  {
    id: 'd5_d3_01',
    domain: 5,
    topic: 'Time Travel',
    difficulty: 'medium',
    q: 'A table was dropped 3 days ago. The account uses Enterprise edition with the default DATA_RETENTION_TIME_IN_DAYS = 1 day. Can you recover the table with UNDROP?',
    options: [
      'Yes — UNDROP works within the 7-day Fail-safe window',
      'No — the 1-day Time Travel window has already expired; the table is unrecoverable via SQL',
      'Yes — UNDROP works within the 90-day maximum Enterprise retention window',
      'No — UNDROP only works within 24 hours on any edition',
    ],
    answer: 'No — the 1-day Time Travel window has already expired; the table is unrecoverable via SQL',
    exp: 'UNDROP uses Time Travel, not Fail-safe. With DATA_RETENTION_TIME_IN_DAYS = 1, the table is only recoverable for 1 day after being dropped. After that, only Snowflake Support can attempt Fail-safe recovery (7-day window, no guarantee).',
  },
  {
    id: 'd5_d3_02',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'Which DDL creates a Snowflake share and grants a consumer account access to a table?',
    options: [
      'CREATE DATA SHARE myshare; GRANT SELECT ON TABLE orders TO SHARE myshare; ADD ACCOUNT consumer_account TO SHARE myshare;',
      'CREATE SHARE myshare; GRANT SELECT ON TABLE orders TO SHARE myshare; ALTER SHARE myshare ADD ACCOUNTS = consumer_account;',
      'PUBLISH SHARE myshare TO ACCOUNT consumer_account WITH TABLE orders;',
      'CREATE SHARE myshare AS SELECT * FROM orders FOR ACCOUNT consumer_account;',
    ],
    answer: 'CREATE SHARE myshare; GRANT SELECT ON TABLE orders TO SHARE myshare; ALTER SHARE myshare ADD ACCOUNTS = consumer_account;',
    exp: 'The correct 3-step DDL: (1) CREATE SHARE, (2) GRANT privilege (USAGE on DB, USAGE on schema, SELECT on table) TO SHARE, (3) ALTER SHARE … ADD ACCOUNTS. All three steps are required for a consumer to access shared data.',
  },
  {
    id: 'd5_d3_03',
    domain: 5,
    topic: 'Data Sharing',
    difficulty: 'medium',
    q: 'What is a Snowflake Reader Account, and when is it used?',
    options: [
      'A Snowflake account with read-only access to all objects in the provider account',
      'A Snowflake-managed account that lets non-Snowflake customers consume shared data without their own Snowflake account',
      'A secondary account used for disaster recovery reads only',
      'An account with access to the Snowflake Marketplace as a consumer',
    ],
    answer: 'A Snowflake-managed account that lets non-Snowflake customers consume shared data without their own Snowflake account',
    exp: 'Reader Accounts (managed accounts) are created and billed to the data provider. They allow consumers who don\'t have a Snowflake account to query shared data using Snowsight. Compute runs on the reader account\'s virtual warehouse (provider-paid).',
  },
  {
    id: 'd5_d3_04',
    domain: 5,
    topic: 'Cloning',
    difficulty: 'hard',
    q: 'Can you clone a table AT a specific point in Time Travel — for example, to restore yesterday\'s state into a new table?',
    options: [
      'No — cloning always reflects the current table state',
      'Yes — CREATE TABLE restored CLONE orders AT (TIMESTAMP => \'2026-03-17 12:00:00\'::TIMESTAMP)',
      'Yes — but only using UNDROP, not CREATE … CLONE',
      'No — Time Travel clones require ACCOUNTADMIN privileges',
    ],
    answer: 'Yes — CREATE TABLE restored CLONE orders AT (TIMESTAMP => \'2026-03-17 12:00:00\'::TIMESTAMP)',
    exp: 'You can combine Time Travel and zero-copy cloning: CREATE TABLE t CLONE source AT (TIMESTAMP => …). This creates an instant clone of the table as it existed at that point in time — a powerful recovery technique.',
  },
  {
    id: 'd5_d3_05',
    domain: 5,
    topic: 'Marketplace',
    difficulty: 'medium',
    q: 'A data provider publishes a listing on the Snowflake Marketplace. A consumer discovers and installs the listing. Which statement about the data transfer is TRUE?',
    options: [
      'Snowflake copies the data nightly to the consumer\'s account storage',
      'The consumer queries the provider\'s live data directly — no data is copied to the consumer',
      'The data is replicated to a Snowflake-managed intermediate account first',
      'Data is encrypted and delivered as a download package to the consumer',
    ],
    answer: 'The consumer queries the provider\'s live data directly — no data is copied to the consumer',
    exp: 'Snowflake Marketplace listings are powered by Secure Data Sharing — zero-copy. The consumer\'s queries read the provider\'s data in real time (or from a regional replica). No data transfer costs, no copying, no staleness.',
  },
];
